objects/Activity.object
<CustomObject>
    <fields>
        <fullName>LCRM_Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Inbound</fullName>
                </value>
                <value>
                    <fullName>Call Outbound</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>Email Outbound</fullName>
                </value>
                <value>
                    <fullName>Email Inbound</fullName>
                </value>
                <value>
                    <fullName>Request to Professional Services</fullName>
                </value>
                <value>
                    <fullName>Social Media/Online Chat</fullName>
                </value>
                <value>
                    <fullName>Notes to Account</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Call Back</fullName>
                </value>
                <value>
                    <fullName>Click To Dial</fullName>
                </value>
                <value>
                    <fullName>Cold call</fullName>
                </value>
                <value>
                    <fullName>Dialer Call</fullName>
                </value>
                <value>
                    <fullName>Drop-Off</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Email Clickthroughs</fullName>
                </value>
                <value>
                    <fullName>Email Opens</fullName>
                </value>
                <value>
                    <fullName>Email Sends</fullName>
                </value>
                <value>
                    <fullName>Event-Campaign</fullName>
                </value>
                <value>
                    <fullName>External Activity</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Form Submits</fullName>
                </value>
                <value>
                    <fullName>Inbound Email</fullName>
                </value>
                <value>
                    <fullName>Info to Account</fullName>
                </value>
                <value>
                    <fullName>Office Visit</fullName>
                </value>
                <value>
                    <fullName>Outbound Mail</fullName>
                </value>
                <value>
                    <fullName>To Do</fullName>
                </value>
                <value>
                    <fullName>Web Visits</fullName>
                </value>
                <value>
                    <fullName>Follow Up</fullName>
                </value>
                <value>
                    <fullName>S2E</fullName>
                    <default>true</default>
                    <label>S2E</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LCRM_Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>LCRM_Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LCRM_Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Record_Ids__c</fullName>
        <label>Record Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>LCRM Exception Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>LCRM Exception Logs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCRM Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LCRMTaskActivityCategoryUpdate.cls
/**
* Description   : Batch class for updating the existing Task with Activity Type as S2E
*                 
* Author        : TCS 
* Change History: 16-May-2017 Initial Version
* 
* 
* 
*/
global class LCRMTaskActivityCategoryUpdate implements Database.Batchable<sObject>{
    public String query;
    
    global LCRMTaskActivityCategoryUpdate(){
        query = 'SELECT Id, LCRM_Activity_Type__c from Task';
        query += ' WHERE LCRM_Activity_Type__c = null AND IsRecurrence = false AND LastModifiedDate > LAST_YEAR';
        query += ' limit 50000' ;
    }
    
    global Database.QueryLocator Start(Database.BatchableContext BC){
     return database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope){
        System.debug(scope);
        List<Task> taskList = new List<Task>();
        List<LCRM_Exception_Log__c> exceptionList = new List<LCRM_Exception_Log__c>();
        
        for(sObject sobj: scope){
        Task t = new Task(Id = sobj.Id, LCRM_Activity_Type__c = 'S2E');
        taskList.add(t);
        }
        //Database.update(taskList, false);
        Database.SaveResult[] results = Database.update(taskList, false);
        for(Integer i=0;i<results.size();i++){
            if(!results.get(i).isSuccess()){
                exceptionList.add(createExceptionLog(results.get(i).getErrors().get(0).getMessage(),taskList.get(i).Id));
            }
        }
        
        if(exceptionList != null && exceptionList.size() > 0)
            insert exceptionList ;
    }
    
    global void finish(Database.BatchableContext bc){
        
    }
    
    @TestVisible
    private LCRM_Exception_Log__c createExceptionLog(String errorMessage, String recordId){
        LCRM_Exception_Log__c excepObj = new LCRM_Exception_Log__c();
        excepObj.LCRM_Exception_Message__c= errorMessage;
        excepObj.LCRM_Record_Ids__c= recordId;
        excepObj.LCRM_Exception_Type__c = 'Activity Type changing batch job for Task';
        return excepObj;
    }
}