objects/APTS_Group__c.object
<CustomObject>
    <description>This is proposal group which will be created dynamically on cart</description>
    <fields>
        <fullName>APTS_Decentralized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Decentralized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_MLA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MLA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_ProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group</label>
    <nameField>
        <displayFormat>G-{000000}</displayFormat>
        <label>Group Nnumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>APTS_Decentralized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APTS_Decentralized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Existing_Subscriptions_Total__c</fullName>
        <label>Existing Subscriptions Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Group_Primary_Material_Name__c</fullName>
        <label>Group Primary Material Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Group_Primary_Material__c</fullName>
        <label>Group Primary Material</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bundle A</fullName>
                </value>
                <value>
                    <fullName>Bundle B</fullName>
                </value>
                <value>
                    <fullName>Bundle C</fullName>
                </value>
                <value>
                    <fullName>Bundle D</fullName>
                </value>
                <value>
                    <fullName>Bundle E</fullName>
                </value>
                <value>
                    <fullName>Bundle F</fullName>
                </value>
                <value>
                    <fullName>Bundle G</fullName>
                </value>
                <value>
                    <fullName>Bundle H</fullName>
                </value>
                <value>
                    <fullName>Bundle I</fullName>
                </value>
                <value>
                    <fullName>Bundle J</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Keep_Terms__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Keep Terms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_MLA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APTS_MLA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_New_Subscriptions_Total__c</fullName>
        <label>New Subscriptions Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Code__c</fullName>
        <formula>Apttus_Config2__ProductId__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_is_Primary_in_Bundle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Primary in Bundle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BasePrice__c</fullName>
        <description>The base price is List price + Automatic Adjustments for individual products and options</description>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ChargeType__c</fullName>
        <description>The charge type  associated with the product or service</description>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Price</fullName>
                </value>
                <value>
                    <fullName>License Fee</fullName>
                </value>
                <value>
                    <fullName>Subscription Fee</fullName>
                </value>
                <value>
                    <fullName>Implementation Fee</fullName>
                </value>
                <value>
                    <fullName>Installation Fee</fullName>
                </value>
                <value>
                    <fullName>Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Shipping &amp; Handling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsCustomPricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether custom pricing is in effect for the line item</description>
        <label>Is Custom Pricing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ItemSequence__c</fullName>
        <description>The sequence of items belonging to a line</description>
        <label>Item Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineNumber__c</fullName>
        <description>The line number</description>
        <label>Line Number</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineSequence__c</fullName>
        <description>Sequence a logical line using this sequence.</description>
        <inlineHelpText>Sequence a logical line using this sequence.</inlineHelpText>
        <label>Line Sequence</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ListPrice__c</fullName>
        <description>The list price for the product or service with no adjustments</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceUom__c</fullName>
        <description>The pricing unit of measure for the product</description>
        <label>Pricing Uom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                </value>
                <value>
                    <fullName>Hour</fullName>
                </value>
                <value>
                    <fullName>Day</fullName>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Gallon</fullName>
                </value>
                <value>
                    <fullName>Seats</fullName>
                </value>
                <value>
                    <fullName>Holds</fullName>
                </value>
                <value>
                    <fullName>Users</fullName>
                </value>
                <value>
                    <fullName>Alerts</fullName>
                </value>
                <value>
                    <fullName>Concurrent</fullName>
                </value>
                <value>
                    <fullName>Concurrent Users</fullName>
                </value>
                <value>
                    <fullName>Price Tier</fullName>
                </value>
                <value>
                    <fullName>Price Tiered</fullName>
                </value>
                <value>
                    <fullName>INPUTS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Uom__c</fullName>
        <description>The product or service unit of measure</description>
        <label>Product Uom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>Hour</fullName>
                </value>
                <value>
                    <fullName>Day</fullName>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Gallon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <fields>
        <fullName>Apttus_Config2__ListPrice__c</fullName>
        <description>The list price for the product</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceUom__c</fullName>
        <description>The pricing unit of measure for the product</description>
        <label>Price Uom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>Hour</fullName>
                </value>
                <value>
                    <fullName>Day</fullName>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Gallon</fullName>
                </value>
                <value>
                    <fullName>Seats</fullName>
                </value>
                <value>
                    <fullName>Holds</fullName>
                </value>
                <value>
                    <fullName>Alerts</fullName>
                </value>
                <value>
                    <fullName>Users</fullName>
                </value>
                <value>
                    <fullName>Concurrent</fullName>
                </value>
                <value>
                    <fullName>Price Tier</fullName>
                </value>
                <value>
                    <fullName>Price Tiered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DCPDynamicBundling.cls
/********************************************************************************
Class Name : DCPDynamicBundling
@description : This class is for dynamic bundling.
***************************************************************************************

Modification Details
    Date             Description                                            Owner
10/06/2021           Class Created                                          By Herin Acharya

*********************************************************************************/
public without sharing class DCPDynamicBundling{ 

    public static Apttus_Config2__ProductConfiguration__c objectCart;
    public static APTS_ConfigBundlePageSettings__c configBundleCS;
    public static DCPDBInitializeData.BundleWrapper bundleWrapper;
    public static Map<Id,DCPDBWrapper.BundleData> cartToBundleData = new Map<Id,DCPDBWrapper.BundleData>();
    public static boolean hasBundleProduct = false;
    
    //private static Map<Id, List<Apttus_Config2__LineItem__c>> cartIdLineItemMap= new Map<Id, List<Apttus_Config2__LineItem__c>>();
    private static Id cartId;   
    private static list<string> groupNameList;
    private static set<String> setOfTabNames = new Set<String>{'Print','Online/Software'};     
    private static Map<Id,decimal> bundleProdIdToLineNumber = new Map<id,decimal>();    
    private static String bundleName{get; set;}
    

    /** 
    @description call the execute bundling method
    @param requestBody will contain "cartId" as a parameter.
    @return Returns string in case of success OR thows execption in case of failure
    */
    public static string executeDynamicBundling(Map<string,string> requestBody){
        try{
            if(requestBody.containskey('cartId') && !String.isBlank(requestBody.get('cartId'))){
                cartId = requestBody.get('cartId');
                
                bundleName = 'Bundle A';
                
                //get group name list
                groupNameList = new list<string>();
                groupNameList.addAll(DCPDynamicBundlingHelper.getGroupPicklistValues(bundleName));
                   
                //get Cart details/field
                objectCart = DCPDBCartQuery.getCartDetails(cartId);
                            
                //To Populate Custom SettingS detail                
                configBundleCS = APTS_ConfigBundlePageSettings__c.getValues('Bundle Page Properties');                               
                
                // Call Initialize
                bundleWrapper = new DCPDBInitializeData.BundleWrapper(); 
                bundleWrapper = DCPDBInitializeData.initializeData();
                
                // Call Main Save method
                parseAndSaveData();
                
                return 'Success';
              
            }else{
                 return('ImproperRequestFormat');   
            }
        }catch(Exception ex){
             throw new DCCustomException(ex.getStackTraceString());
        }               
    }
    
     private static void parseAndSaveData(){

        Map<String,APTS_Group__c> groupNameUpdated=new Map<String,APTS_Group__c>();

        for(APTS_Group__c grps : bundlewrapper.groupListTobeInsert){
            bundlewrapper.grpMap.put(grps.APTS_ProductConfiguration__c, grps);
        }
        
        System.debug(LoggingLevel.DEBUG,'bundlewrapper.grpMap ------------------'+ bundlewrapper.grpMap);
        
        bundlewrapper.grpList = DCPDBInitializeData.getGrouplnItems(objectCart.Apttus_QPConfig__Proposald__c);  
        DCPDBPopulateLineItemsDetails.populateLineItemDetails(groupNameUpdated);

        System.debug(LoggingLevel.DEBUG,'CARTTOBUNDLEDATA:::::'+cartToBundleData);

        Map<id,List<Apttus_Config2__LineItem__c>> cartIDToLineItemsMap = new Map<id,List<Apttus_Config2__LineItem__c>>();
        Map<String,Apttus_Config2__PriceListItem__c> plimap = new Map<String,Apttus_Config2__PriceListItem__c>();
        plimap = DCPDBCreateBundleLineItem.getPrceListItem();

        cartIDToLineItemsMap = DCPDBCartQuery.getCartLineItems(cartId);
        DCPDBCreateBundleLineItem.createDynamicBundleLineItem(cartIDToLineItemsMap,plimap);

        cartIDToLineItemsMap = DCPDBCartQuery.getCartLineItems(cartId);
        updateDynamicBundleLineItem(cartIDToLineItemsMap,groupNameUpdated,plimap);

        cartIDToLineItemsMap = DCPDBCartQuery.getCartLineItems2(cartId);
        DCPDBUpdateBundleLineItem.updateDynamicBundleLineItem(cartIDToLineItemsMap);

        System.debug(LoggingLevel.DEBUG,'bundlewrapper.grpMap-----------'+ bundlewrapper.grpMap);
        DCPDBGroupHelper.deleteGroupList();
        String actionType = 'backToCart';
        
        if(!bundlewrapper.isMLA && actionType == 'backToCart'){
            DCPDBLocation.deleteExistingRecords();
            DCPDBLocation.insertNewLocation();
            
        } else if(bundlewrapper.isMLA && actionType == 'backToCart' && bundlewrapper.isKeepTerms && bundlewrapper.mlaAgreementNumber != null){
            DCPDBLocation.updateExistingLocation();
        }


        //Call reprice for dynamic bundle line item
        //repriceCart();
        
        //If Bundle Product exists, call second reprice to fix pricing issue.
        if(hasBundleProduct){
            repriceCart();
        }
        
        DCPDBSummaryGroup.createSummaryGroup(bundlewrapper.grpMap,cartId);
        
        DCPDynamicBundlingHelper.updateCartToNewStatus(cartId);
    }
    
    private static void repriceCart(){
        if(!Test.isRunningTest()){
            DCPDynamicBundlingHelper.callApttusPriceUpdateAPI(cartId);
        }      
    }
                 
      private static void updateDynamicBundleLineItem(Map<id,List<Apttus_Config2__LineItem__c>> cartIDToLineItemsMap,Map<String,APTS_Group__c> groupNameUpdated,Map<String,Apttus_Config2__PriceListItem__c> plimap){
        
        List<Apttus_Config2__LineItem__c> lineitemlist = new List<Apttus_Config2__LineItem__c>();

        //This logic is for populating the dynamic bundle line item details
        Decimal count1 = 1;
        Map<String,Apttus_Config2__LineItem__c> fieldmap = new Map<String,Apttus_Config2__LineItem__c>();
        DCPDBUpdateBundleLineItem.populateFieldMap(fieldmap,cartId,cartIDToLineItemsMap.get(cartId));

        for(Apttus_Config2__LineItem__c li: cartIDToLineItemsMap.get(cartId)){
            System.debug(LoggingLevel.DEBUG,li.Apttus_Config2__ConfigurationId__c + ''+  li);
            if(cartToBundleData.get(cartId).prdcode != null && cartToBundleData.get(cartId).prdcode.contains(li.APTS_Product_Code__c)){
                for(String str : cartToBundleData.get(cartId).bundles.keyset()){
                    String temp = str.substringAfter(':');
                    if(li.APTS_Product_Code__c == temp){
                        li.APTS_Group__c = str.substringBetween(';',':');
                        li.APTS_Group_Primary_Material_Name__c = str.substringBefore(';');
                        setLineItemPrice(li,cartId,str);
                        li.Apttus_Config2__LineSequence__c  = count1;
                        li.Apttus_Config2__LineNumber__c = count1;
                        li.Apttus_Config2__ItemSequence__c = count1;
                        li.Apttus_Config2__PriceUom__c='Each';
                        li.Apttus_Config2__Uom__c='Each';
                        li.APTS_Group_Primary_Material__c = cartToBundleData.get(cartId).groupPrimaryMaterial;
                        setLineItemPriceListItemDetail(li,plimap,temp);
                        setLineItemProposalGroup(li,groupNameUpdated,str);
                        li.APTS_Decentralized__c= bundlewrapper.decentralized;
                        li.APTS_MLA__c = bundlewrapper.existOnlineSoftwareProduct;
                        li.APTS_is_Primary_in_Bundle__c=true;                       
                        li.APTS_Existing_Subscriptions_Total__c = DCPDynamicBundlingHelper.getExistingSubscriptionTotal(cartIDToLineItemsMap.get(cartId));
                        li.APTS_New_Subscriptions_Total__c = DCPDynamicBundlingHelper.getNewSubscriptionTotal(cartIDToLineItemsMap.get(cartId)); 
                        li.apts_keep_terms__c =bundlewrapper.isKeepTerms ;
                        count1 = count1 + 1 + cartToBundleData.get(cartId).bundlecount.get(str);
                        setLineItemPriceAdjustment(li,fieldmap);
                        lineitemlist.add(li);
                        cartToBundleData.get(cartId).bundles.remove(str);
                        break;
                    }
                }
            }
        }
        //end of logic for populating dynamic bundle line item details
        

        System.debug(LoggingLevel.DEBUG,lineitemlist);
        if(!lineitemlist.isEmpty() && !Test.isRunningTest() 
           && Schema.sObjectType.Apttus_Config2__LineItem__c.isUpdateable()){
            update lineitemlist;
        }
    }
    
    private static void setLineItemPrice(Apttus_Config2__LineItem__c li,Id configId,String str ){
        if(cartToBundleData.get(configId).bundles.get(str) != null){
            li.Apttus_Config2__ListPrice__c = Decimal.valueOf(cartToBundleData.get(configId).bundles.get(str).substringBefore('list'));
            li.Apttus_Config2__BasePrice__c= Decimal.valueOf(cartToBundleData.get(configId).bundles.get(str).substringBetween('list','base'));
            li.Apttus_Config2__IsCustomPricing__c = true;
        }
    }
    
    private static void setLineItemPriceListItemDetail(Apttus_Config2__LineItem__c li,Map<String,Apttus_Config2__PriceListItem__c> plimap,String temp){

        if(!plimap.isEmpty() && plimap.get(temp)!=null){
            li.Apttus_Config2__ChargeType__c= plimap.get(temp).Apttus_Config2__ChargeType__c; 
            li.Apttus_Config2__SellingFrequency__c=plimap.get(temp).Apttus_Config2__Frequency__c;
            li.Apttus_Config2__PriceType__c=plimap.get(temp).Apttus_Config2__PriceType__c;
            li.Apttus_Config2__Frequency__c=plimap.get(temp).Apttus_Config2__Frequency__c;
            li.Apttus_Config2__Term__c=1;
            li.Apttus_Config2__BasePriceMethod__c=plimap.get(temp).Apttus_Config2__PriceMethod__c;
            li.Apttus_Config2__PriceMethod__c=plimap.get(temp).Apttus_Config2__PriceMethod__c; 
            if(!(li.Apttus_Config2__LineStatus__c=='Amended')){ 
                li.Apttus_Config2__LineStatus__c='New'; 
            }
        }
    }
    
    private static void setLineItemProposalGroup(Apttus_Config2__LineItem__c li,Map<String,APTS_Group__c> groupNameUpdated,String str){

        if(groupNameUpdated!=null && groupNameUpdated.get(str)!=null){  
            System.debug(LoggingLevel.DEBUG,'bundle'+groupNameUpdated.get(str));                          
            li.APTS_Existing_Agreement_Total__c = groupNameUpdated.get(str).APTS_Existing_Agreement_Total__c;
            li.APTS_Online_Incremental__c = groupNameUpdated.get(str).APTS_Online_Incremental__c;
            li.APTS_Proposal_Group__c = groupNameUpdated.get(str).id; 
        }
    }
    
    private static void setLineItemPriceAdjustment(Apttus_Config2__LineItem__c li,Map<String,Apttus_Config2__LineItem__c> fieldmap){

        if(fieldmap != null && fieldmap.get(li.APTS_Totaling_Summary_Group__c) != null){
            li.APTS_Bridge__c = fieldmap.get(li.APTS_Totaling_Summary_Group__c).APTS_Bridge__c;
            li.APTS_New_Bridge_Discount__c = fieldmap.get(li.APTS_Totaling_Summary_Group__c).APTS_New_Bridge_Discount__c;
            li.APTS_Contract_Term__c = fieldmap.get(li.APTS_Totaling_Summary_Group__c).APTS_Contract_Term__c;
            li.APTS_Years_2_Plus_Adjustment__c = fieldmap.get(li.APTS_Totaling_Summary_Group__c).APTS_Years_2_Plus_Adjustment__c;
            li.Apttus_Config2__BillingFrequency__c = fieldmap.get(li.APTS_Totaling_Summary_Group__c).Apttus_Config2__BillingFrequency__c;
            li.Apttus_Config2__AdjustmentType__c = fieldmap.get(li.APTS_Totaling_Summary_Group__c).Apttus_Config2__AdjustmentType__c;
            li.Apttus_Config2__AdjustmentAmount__c = fieldmap.get(li.APTS_Totaling_Summary_Group__c).Apttus_Config2__AdjustmentAmount__c;
        }
    }

}