objects/APTS_Product_Variant__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Auto_Renew_Price_Basis__c</fullName>
        <description>DOC-6390</description>
        <label>Auto Renew Price Basis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Auto_Renew_Price_Percentage__c</fullName>
        <description>DOC-6390</description>
        <label>Auto Renew Price Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Bridge_Eligibility__c</fullName>
        <label>Bridge_Eligibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_CUAS1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CUAS+1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Partial_Year_Charge_Eligible__c</fullName>
        <label>Partial_Year_Charge_Eligible</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Delivery__c</fullName>
        <label>Product Delivery</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product_ID__c</fullName>
        <label>Product ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Variant_ID__c</fullName>
        <label>Product Variant ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Renewal_Type__c</fullName>
        <description>Renewal Type Indicator</description>
        <label>Renewal_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Variant</label>
    <nameField>
        <label>Product Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Variant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>APTS_Auto_Renew_Price_Basis__c</fullName>
        <label>Auto Renew Price Basis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Auto_Renew_Price_Percentage__c</fullName>
        <label>Auto Renew Price Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Bridge_Eligibility__c</fullName>
        <label>Bridge Eligibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_CUAS1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CUAS+1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_PPC_Mgmt_Fee_Override__c</fullName>
        <formula>Apttus_Config2__AttributeValueId__r.APTS_PPC_Mgmt_Fee_Override__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PPC Management Fee Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Partial_Year_Charge_Eligible__c</fullName>
        <label>Partial Year Charge Eligible</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Delivery__c</fullName>
        <label>Product Delivery</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Variant_ID__c</fullName>
        <label>Product Variant ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Proposal_Business_Unit__c</fullName>
        <formula>TEXT(Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.APTS_Proposal_Business_Unit__c )</formula>
        <label>Proposal Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Renewal_Type__c</fullName>
        <label>Renewal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Renew</fullName>
                </value>
                <value>
                    <fullName>Evergreen</fullName>
                </value>
                <value>
                    <fullName>Term Commitment</fullName>
                </value>
                <value>
                    <fullName>Non-Renewable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__ProductAttributeValue__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineType__c</fullName>
        <description>The line type</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Service</fullName>
                    <default>true</default>
                    <label>Product/Service</label>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductOptionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product option</description>
        <label>Product Option</label>
        <referenceTo>Apttus_Config2__ProductOptionComponent__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_product_variant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Variant</label>
        <referenceTo>APTS_Product_Variant__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Apttus_Config2__ProductAttributeValue__c.object
<CustomObject>
    <description>Represents the attribute values for a product class</description>
    <fields>
        <fullName>APTS_PPC_Mgmt_Fee_Override__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This will change the standard Management Fee % and will require an approval.</inlineHelpText>
        <label>PPC Management Fee Override %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Delivery__c</fullName>
        <label>Product Delivery</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Download</fullName>
                </value>
                <value>
                    <fullName>eBook</fullName>
                </value>
                <value>
                    <fullName>Online/Web</fullName>
                </value>
                <value>
                    <fullName>Media CD</fullName>
                </value>
                <value>
                    <fullName>Live/In Person/Virtual</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
                <value>
                    <fullName>Media DVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Product_Variant_ID__c</fullName>
        <label>Product Variant ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Proposal_Business_Unit_PAV__c</fullName>
        <formula>Apttus_Config2__LineItemId__r.APTS_Proposal_Business_Unit__c</formula>
        <label>Proposal Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsTransient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates a transient record created by the application with default values. A new product attribute value is in transient state until the record is explicitly saved by the user. Workflow rules should check this field to test for false before executing so that rules are not incorrectly executed when transient product attribute values are created .</description>
        <inlineHelpText>Indicates a transient record created by the application with default values. A new product attribute value is in transient state until the record is explicitly saved by the user.</inlineHelpText>
        <label>Is Transient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineItemId__c</fullName>
        <description>ID of the associated line item</description>
        <label>Line Item</label>
        <referenceTo>Apttus_Config2__LineItem__c</referenceTo>
        <relationshipLabel>Product Attribute Values</relationshipLabel>
        <relationshipName>ProductAttributeValues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Product Attribute Value</label>
    <nameField>
        <displayFormat>AV-{0000000000}</displayFormat>
        <label>Attribute Value Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Apttus_Config2__ProductOptionComponent__c.object
<CustomObject>
    <description>Represents a product option component which is a member of the list of options associated with a product.option group</description>
    <fields>
        <fullName>Apttus_Config2__ComponentProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the component product</description>
        <label>Component Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Parent Products</relationshipLabel>
        <relationshipName>ParentProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Option Component</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Option Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Option Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/APTS_ProductAttributeValueTriggerHelper.cls
public with sharing class APTS_ProductAttributeValueTriggerHelper { 
    public static void setLineItemFieldsPA(List<Apttus_Config2__ProductAttributeValue__c> PANewObjects)
    {
        List<Apttus_Config2__ProductAttributeValue__c> getPAValues=new List<Apttus_Config2__ProductAttributeValue__c>();
        List<Apttus_Config2__LineItem__c> getLines= new List<Apttus_Config2__LineItem__c>();
        List<APTS_Product_Variant__c> detailsVariant= new List<APTS_Product_Variant__c>();
        Set<String> productDelivery=new Set<String>();
        List<Id> parentIds=new List<Id>();
        String AttrValueRecord;
        
        /*Populate fields on line items Code starts here*/
        
        for(Apttus_Config2__ProductAttributeValue__c PAValues:PANewObjects)            
        {   
            System.debug('PBU Value = '+PAValues.APTS_Proposal_Business_Unit_PAV__c);
            
            if(PAValues.APTS_Proposal_Business_Unit_PAV__c == 'Tax Professional')
            {
                Map<String, Object> fieldToValue = PAValues.getPopulatedFieldsAsMap();
             for (String str : fieldToValue.keyset()) 
             { 
                 System.debug('Value of the field = ' + str);
                 if((str!= 'lastmodifieddate') && (str!= 'id') && (str != 'systemmodstamp') && (str!= 'CreatedDate') && (str!= 'CreatedById') && (str!= 'CurrencyIsoCode') && (str!= 'IsDeleted') && (str!= 'LastModifiedById') && (str!= 'Apttus_Config2__LineItemId__c') && (str!= 'Name') && (str!= 'LastReferencedDate') && (str!= 'LastViewedDate') && (str!= 'LastActivityDate') && (str!= 'Name') && (str!='Apttus_Config2__IsTransient__c') && (str!='APTS_PPC_Mgmt_Fee_Override__c') && (str!='APTS_Proposal_Business_Unit_PAV__c') )
                 { 
                     if((fieldToValue.get(str)) != null)
                     {
                         AttrValueRecord = (String)fieldToValue.get(str);  
                        productDelivery.add(AttrValueRecord);
                         System.debug(str + '->' + fieldToValue.get(str)+'AttrValueRecord VAlue = '+AttrValueRecord);                                                                           
                     }
                     
                 } 
             }
             parentIds.add(PAValues.id);
         }
        }
        system.debug('*parentIds ='+ parentIds);
        system.debug('*Product Delivery = '+ productDelivery);
        try
        {
            if(Schema.sObjectType.Apttus_Config2__LineItem__c.isAccessible()&&Schema.sObjectType.Apttus_Config2__LineItem__c.isQueryable()&& parentIds != null && parentIds.size()>0){
                getLines=[select id,Apttus_Config2__LineType__c, Apttus_Config2__ProductOptionId__r.Apttus_Config2__ComponentProductId__r.ProductCode, APTS_Proposal_Business_Unit__c,Apttus_Config2__ProductId__r.ProductCode, Apttus_Config2__AttributeValueId__r.APTS_Product_Delivery__c,APTS_Auto_Renew_Price_Basis__c,APTS_Renewal_Type__c,APTS_Product_Variant_ID__c,APTS_Product_Delivery__c,APTS_CUAS1__c from Apttus_Config2__LineItem__c where Apttus_Config2__AttributeValueId__c IN :parentIds AND APTS_Proposal_Business_Unit__c = 'Tax Professional' ];
            }
            system.debug('*Line Items = '+ getLines);
            
            
            List<String> productCode=new List<String>();
            
            if(getLines!=null && getLines.size()>0){ 
                for(Apttus_Config2__LineItem__c lines:getLines)
                {
                    if(lines.Apttus_Config2__LineType__c == 'Product/Service')
                    {
                        productCode.add(lines.Apttus_Config2__ProductId__r.ProductCode);
                    }
                    else if(lines.Apttus_Config2__LineType__c == 'Option')
                    {
                        productCode.add(lines.Apttus_Config2__ProductOptionId__r.Apttus_Config2__ComponentProductId__r.ProductCode);
                    }
                    
                    
                }
                
            }
            
            system.debug('*Product Code ='+ productCode);
            if(Schema.sObjectType.APTS_Product_Variant__c.isAccessible()&&Schema.sObjectType.APTS_Product_Variant__c.isQueryable() && productDelivery != null && productDelivery.size()> 0 ){    
                detailsVariant=[select id,APTS_Product_ID__c,APTS_Product_Delivery__c,APTS_Auto_Renew_Price_Basis__c,APTS_Auto_Renew_Price_Percentage__c, APTS_Bridge_Eligibility__c,APTS_Partial_Year_Charge_Eligible__c,APTS_Renewal_Type__c,APTS_Product_Variant_ID__c,APTS_CUAS1__c from APTS_Product_Variant__c where APTS_Product_ID__c IN :productCode and APTS_Product_Delivery__c IN :productDelivery ];
            }
            system.debug('*Product Variants = '+ detailsVariant);
            
            
            List<Apttus_Config2__LineItem__c> updateLines=new List<Apttus_Config2__LineItem__c>();
            
            if(detailsVariant!=null && detailsVariant.size()>0 && getLines!=null && getLines.size()>0)
            {    
                system.debug('*Inside IF block for updating LIne Items');
                for(Apttus_Config2__LineItem__c line:getLines) //L1B, L2O1, L3O2
                {
                    system.debug('*Inside for Line items line == '+line);
                    for(APTS_Product_Variant__c items:detailsVariant) //P1B, P2O1, P3O2
                    {
                        for(String pavValue: productDelivery)//PD1B, PD2O
                        {
                        system.debug('*pavValue =='+pavValue);
                        system.debug('*LineItem Option Product Code '+line.Apttus_Config2__ProductOptionId__r.Apttus_Config2__ComponentProductId__r.ProductCode);
                        system.debug('*LineItem Bundle Product Code '+line.Apttus_Config2__ProductId__r.ProductCode);
                        system.debug('*Inside for Line items items.APTS_Product_ID__c =='+items.APTS_Product_ID__c);
                        system.debug('*Inside Product Variant Items =='+items);
                        if(((line.APTS_Proposal_Business_Unit__c=='Tax Professional' && line.Apttus_Config2__LineType__c == 'Product/Service' && line.Apttus_Config2__ProductId__r.ProductCode == items.APTS_Product_ID__c) || (line.Apttus_Config2__LineType__c == 'Option' && line.Apttus_Config2__ProductOptionId__r.Apttus_Config2__ComponentProductId__r.ProductCode == items.APTS_Product_ID__c)) && /*line.testAttr1__c*/ pavValue == items.APTS_Product_Delivery__c)
                        {
                            system.debug('*Inside if main check before'+line);
                            
                            line.APTS_Auto_Renew_Price_Basis__c=items.APTS_Auto_Renew_Price_Basis__c;
                            line.APTS_Auto_Renew_Price_Percentage__c=items.APTS_Auto_Renew_Price_Percentage__c;
                            line.APTS_Bridge_Eligibility__c=items.APTS_Bridge_Eligibility__c;
                            line.APTS_Partial_Year_Charge_Eligible__c=items.APTS_Partial_Year_Charge_Eligible__c;
                            line.APTS_Renewal_Type__c=items.APTS_Renewal_Type__c;
                            line.Apttus_product_variant__c=items.id;
                            line.APTS_Product_Variant_ID__c = items.APTS_Product_Variant_ID__c;
                            line.APTS_Product_Delivery__c = items.APTS_Product_Delivery__c;
                            line.APTS_CUAS1__c = items.APTS_CUAS1__c;
                            
                            updateLines.add(line);
                            system.debug('*Inside if main check after update'+line);
                            
                        }
                    }
                    }
                }
            }
            system.debug('Line Item Information'+getLines);
            
            if(updateLines!= null && updateLines.size() > 0) 
            {
                update updateLines;
            } 
        }
        catch(Exception e) 
        {
            System.debug('setLineItemFieldsPA error ' + e.getMessage() );
        }
        /*Populate fields on line items Code ends here*/
    }
}