objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>Apttus_QPConfig__ProposalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated quote/proposal</description>
        <inlineHelpText>ID of the associated quote/proposal</inlineHelpText>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>APTS_AccountMirror_Picklist__c</fullName>
        <label>Account Mirror Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation National Accounts</fullName>
                </value>
                <value>
                    <fullName>Corporation Strategic</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Law School Library</fullName>
                </value>
                <value>
                    <fullName>Legal Education Group</fullName>
                </value>
                <value>
                    <fullName>LLF Enterprise</fullName>
                </value>
                <value>
                    <fullName>LLF Strategic</fullName>
                </value>
                <value>
                    <fullName>MLF 30-79</fullName>
                </value>
                <value>
                    <fullName>MLF 80+</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SLF 11-20</fullName>
                </value>
                <value>
                    <fullName>SLF 21-29</fullName>
                </value>
                <value>
                    <fullName>SLF 2-3</fullName>
                </value>
                <value>
                    <fullName>SLF 4-6</fullName>
                </value>
                <value>
                    <fullName>SLF 7-10</fullName>
                </value>
                <value>
                    <fullName>Solo Law Firm</fullName>
                </value>
                <value>
                    <fullName>State Government</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
                <value>
                    <fullName>CORPORAT</fullName>
                </value>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>Law Firm</fullName>
                </value>
                <value>
                    <fullName>Corp Counsel</fullName>
                </value>
                <value>
                    <fullName>Corp Counsel Existing</fullName>
                </value>
                <value>
                    <fullName>Corp Investigative</fullName>
                </value>
                <value>
                    <fullName>Corp Investigative Financial</fullName>
                </value>
                <value>
                    <fullName>Corp National Investigative</fullName>
                </value>
                <value>
                    <fullName>MLF 30-179</fullName>
                </value>
                <value>
                    <fullName>AmLaw100</fullName>
                </value>
                <value>
                    <fullName>LLF 180+</fullName>
                </value>
                <value>
                    <fullName>State Gov Investigative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Order_Confirmation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Confirmation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Apttus_Proposal__Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposals (Order Confirmation Contact)</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_PaymentGateway_URL__c</fullName>
        <label>APTS_PaymentGateway_URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Option__c</fullName>
        <label>Payment Option</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>APTS_Proposal_Business_Unit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Bill to Account</fullName>
                    <default>true</default>
                    <label>Bill to Account</label>
                </value>
                <value>
                    <fullName>Auto EFT/Auto Charge</fullName>
                </value>
                <value>
                    <fullName>Payment Express Auto EFT/Auto Charge</fullName>
                </value>
                <value>
                    <fullName>Autopay</fullName>
                </value>
                <value>
                    <fullName>Auto Charge</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Payment Express Auto ETF/Auto Charge</fullName>
                </value>
                <value>
                    <fullName>One Time EFT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Proposal_Name__c</fullName>
        <label>Proposal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/KeyValueListStore__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueListStore</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+ AccountId,  Account.Name,&apos;_self&apos;)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Acct SSD</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Source_System_Detail__c.Account_Name__r.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Source_System_Detail__c.Account_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RecordtypeIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will store the record type IDs which will be used in apex classes.</description>
    <fields>
        <fullName>recTypeId__c</fullName>
        <label>recTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Record type Ids</label>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Frozen_Market_Segment__c</fullName>
        <description>Created for R4</description>
        <label>Frozen Market Segment</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_Name__c</fullName>
        <label>Source System Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Buttonerrormsgtest.cls
@isTest
private class Buttonerrormsgtest
{
  
  
  static testMethod void Buttonerrormsg()
  {   Account oAccount = new Account(Name='Pathra Test', SAPAccountNumber__c ='11334455', BillingCountry ='US', BillingState='IL', BillingPostalCode = '60603-3801', Tax_Number__c= '12345');
        insert oAccount; 
        
        Schema.DescribeFieldResult fieldResultMarket = Apttus_Config2__ProductConfiguration__c.APTS_AccountMirror_Picklist__c.getDescribe();
        String valueMarket = fieldResultMarket.getPicklistValues().get(0).getValue();

        
        KeyValueListStore__c keyvaluestore=new  KeyValueListStore__c();
        keyvaluestore.Name='ANZUsersProfileId';
        keyvaluestore.TextValue__c='00e30000001ZUki';
        insert keyvaluestore;
        KeyValueListStore__c keyvaluestore1=new  KeyValueListStore__c();
        keyvaluestore1.Name='ReasonWithCompetitor';
        keyvaluestore1.TextValue__c='Content';
        insert keyvaluestore1;
        
        List<RecordtypeIds__c> recordlist=new List<RecordtypeIds__c>();
        RecordtypeIds__c recordtype=new RecordtypeIds__c();
        recordtype.Name='Pre-Pipeline Opportunities';
        recordtype.recTypeId__c='01230000001MA4c';
        recordlist.add(recordtype);
        
        RecordtypeIds__c recordtype1=new RecordtypeIds__c();
        recordtype1.Name='Pipeline Opportunities';
        recordtype1.recTypeId__c='01230000001MA4c';
        recordlist.add(recordtype1);
        
       
        insert recordlist;

         Id ssdRecorType=Schema.SObjectType.Source_System_Detail__c.getRecordTypeInfosByName().get(label.SourcesystemdetailUSLRecordtype).getRecordTypeId();
        Source_System_Detail__c accountSSD= new Source_System_Detail__c();
        accountSSD.RecordtypeId=ssdRecorType;
        accountSSD.Name='ABC';
        accountSSD.Source_System_Name__c='ABC';
        accountSSD.Account_Name__c=oAccount.ID;
        accountSSD.LCRM_Frozen_Market_Segment__c = valueMarket;
        accountSSD.Account_Inactive__c=false;
        accountSSD.LCRM_Sales_Org__c='WEST';
        insert accountSSD;
        
        Id opptyRecorType=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('GLI Pipeline Opportunity').getRecordTypeId();
        Opportunity oppty=APTS_TestDataFactory.createOpportunity('abc',oAccount.id,'Needs Analysis',Date.Today());
        oppty.RecordtypeId=opptyRecorType;
        oppty.Source_System_Detail__c=accountSSD.id;
        oppty.Account=oAccount;
        insert oppty;

        Apttus_Proposal__Proposal__c p = APTS_TestDataFactory.createProposal(oppty.id, accountSSD.Id);
        insert p;
      
        Contact oContact = new Contact(FirstName='S',LastName='Pathra',Account=oAccount);
        insert oContact;
        Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c(Name = 'Thomson Reuters Master - US Legal');
        insert priceList;
        //Apttus_Proposal__Proposal__c oProposal = New Apttus_Proposal__Proposal__c(Apttus_Proposal__Proposal_Name__c ='Pathra Proposal Test', APTS_PaymentGateway_URL__c='',Apttus_Proposal__Account__c = oAccount.Id,APTS_Payment_Option__c = 'Credit Card',APTS_Order_Confirmation_Contact__r=oContact);
        //insert oProposal; 
        Apttus_Config2__Order__c order = new Apttus_Config2__Order__c(Apttus_QPConfig__ProposalId__c=p.Id);
        insert order;
      Buttonerrormsg buttId = new Buttonerrormsg();
      Buttonerrormsg.PermissiontoButton(p.Id);
  }
}