objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Order_Confirmation_Contact_Email__c</fullName>
        <label>Order Confirmation Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>APTS_Order_Confirmation_Contact_Name__c</fullName>
        <formula>UPPER(LEFT(APTS_Order_Confirmation_Contact__r.FirstName,1)) + LOWER(RIGHT(APTS_Order_Confirmation_Contact__r.FirstName,LEN(APTS_Order_Confirmation_Contact__r.FirstName)-1))+
&quot; &quot;+UPPER(LEFT(APTS_Order_Confirmation_Contact__r.LastName,1)) + LOWER(RIGHT(APTS_Order_Confirmation_Contact__r.LastName,LEN(APTS_Order_Confirmation_Contact__r.LastName)-1))</formula>
        <label>Order Confirmation Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Order_Confirmation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Confirmation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Apttus_Proposal__Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposals (Order Confirmation Contact)</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
        <description>The proposal approval stage</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Primary__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the quote/proposal is the primary quote to update the related opportunity</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Batch_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Digital Batch Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Envelope_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to only generate the Digital DocuSign Envelope one time.  This is only used for the Digital Automation process.</description>
        <label>Digital Envelope Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Quote_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Helps to identify the Digital quote automation records</description>
        <label>Digital Quote Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Quote_Type__c</fullName>
        <description>Holds the value of the type of Digital quote</description>
        <label>Digital Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Straight Renewal</fullName>
                </value>
                <value>
                    <fullName>Best Value</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Best Value+Config</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Digital_New_Sales__c</fullName>
        <formula>Apttus_Proposal__Opportunity__r.Is_Digital_New_Sales__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital New Sales</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SAP_Account_Number__c</fullName>
        <description>TW SAP Account Number,Formulae(account.SAPAccountNumber)</description>
        <formula>Account.SAPAccountNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <description>Campaign code. Manually entered by Sales Reps. For Telemarketing in Argentina. Used for commission purposes. Data is loaded to LATAM db and then to commissions system (SICO) to be used in commission calculations. OV will not be dependent on any SFDC info for commissions once LATAM is live on OV.</description>
        <label>Campaign Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Digital_Firm__c</fullName>
        <label>Digital Firm</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Digital_PreviousStageName__c</fullName>
        <description>DLT-10048  Update opportunity stage back to Original values for DSR  used Opportunity.</description>
        <inlineHelpText>Help Previous stage name for Digital Automation</inlineHelpText>
        <label>Digital Previous StageName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Digital_New_Sales__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Digital New Sales</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Date of subscription renewal.</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Number__c</fullName>
        <formula>IF( RecordType.Name == &apos;GLI Pipeline Opportunity&apos; ,  Source_System_Detail__r.Source_System_Account_Number__c , Account.SAPAccountNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Acct SSD</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Source_System_Detail__c.Account_Name__r.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Source_System_Detail__c.Account_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sub_Campaign_Code__c</fullName>
        <description>DLT-8281</description>
        <label>sub-Campaign Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product_Account_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Bypass_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this Digital Subscription record will not get picked up and processed through the Digital Automation Process.</description>
        <label>Bypass Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <label>Campaign Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Subscription__c</fullName>
        <label>Current Subscription</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Digital_Firm__c</fullName>
        <description>For &apos;SLF&apos;, Small Law 
For &apos;Corp&apos;, Corporate 
For &apos;Govt&apos;, Government 
For &apos;Findlaw&apos;, Findlaw</description>
        <label>Digital Firm</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sub_Campaign_Code__c</fullName>
        <description>DLT-8281</description>
        <label>sub-Campaign Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Digital Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Product Account  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Firm__c</fullName>
        <formula>CASE(BU_Segment_Level_2__c, &apos;Corp Emerging Existing&apos;,&apos;Corporate&apos;,&apos;Corp Large Existing&apos;,&apos;Corporate&apos;,&apos;Corp Counsel&apos;, &apos;Corporate&apos;, &apos;Corp Counsel Existing&apos;, &apos;Corporate&apos;, &apos;Corp Investigative&apos;, &apos;Corporate&apos;, &apos;Corp Investigative Financial&apos;, &apos;Corporate&apos;, &apos;Corp Major Accounts&apos;,&apos;Corporate&apos;, &apos;Corp National Investigative&apos;, &apos;Corporate&apos;, &apos;Corporation Enterprise&apos;, &apos;Corporate&apos;, &apos;Corporation National Accounts&apos;, &apos;Corporate&apos;, &apos;Corporation Strategic&apos;, &apos;Corporate&apos;, &apos;Corporation Strategic Existing&apos;, &apos;Corporate&apos;, &apos;SLF 11-20&apos;, &apos;Small Law&apos;, &apos;SLF 21-29&apos;, &apos;Small Law&apos;, &apos;SLF 2-3&apos;, &apos;Small Law&apos;, &apos;SLF 4-6&apos;, &apos;Small Law&apos;, &apos;SLF 7-10&apos;, &apos;Small Law&apos;, &apos;Solo Law Firm&apos;, &apos;Small Law&apos;,&apos;State Government&apos;, &apos;Government&apos;,&apos;Corp-Emerging&apos;,&apos;Corporate&apos;,
&apos;Corp-Large&apos;,&apos;Corporate&apos;,
&apos;Corp Large&apos;,&apos;Corporate&apos;,
&apos;Corp-SMB&apos;,&apos;Corporate&apos;,
&apos;Corp Strategic&apos;, &apos;Corporate&apos;,
&apos;Global 7&apos;,&apos;Corporate&apos;,
&apos;Federal&apos;,&apos;Government&apos;,
&apos;Federal courts&apos;,&apos;Government&apos;,
&apos;State/Local Courts&apos;,&apos;Government&apos;,
&apos;Tribal&apos;,&apos;Government&apos;,
&apos;Academia&apos;,&apos;Government&apos;,
&apos;Academic&apos;,&apos;Government&apos;,
&apos;State/Local&apos;,&apos;Government&apos;,
&apos;Other - Government&apos;,&apos;&apos;,
&apos;Medium Law&apos;,&apos;Medium Law&apos;,
&apos;Small Law&apos;,&apos;Small Law&apos;,
&apos;Large Law&apos;,&apos;Large Law&apos;,
&apos;Other - Legal Professionals&apos;,&apos;&apos;,
&apos;Other - Corporate&apos;,&apos;&apos;,&apos;None&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Digital Firm</label>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WebServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for external web service endpoints and credentials.</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The web service url as defined by the service provider</description>
        <inlineHelpText>The web service url as defined by the service provider</inlineHelpText>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Service_Unavailable_Message__c</fullName>
        <description>The message displayed to the user in the event the service is inactive or unavailable for use</description>
        <inlineHelpText>The message displayed to the user in the event the service is inactive or unavailable for use</inlineHelpText>
        <label>Service Unavailable Message</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Web Service Settings</label>
</CustomObject>

classes/DigitalDocuSignEnvelopeCreation_Test.cls
/**
 * Test class for testing the DigitalDocuSignEnvelopeCreation class.  The DigitalDocuSignEnvelopeCreationclass is a schedulable job that
 * creates DocuSign Envelope ID for Proposal Quote that meet specific criteria.  
 */
/**
 * CHANGE HISTORY
 * =============================================================================
 * Date         Name                    Description
 * 2017-04-01   Brenda Shields          Created
 * 2017-07-11   Dinesh Kumar            Updated the class 
 * 2017-09-12   Brenda Shields          Updated for new Jiras DLT-2301, DLT-2689 and DLT-495
 * 2017-12-29   Brenda Shields          Updated for new quote selection logic  DLT-6929
 * 2018-01-11   Benjamin Her            Updated to ensure 85% code coverage as of date.
 * 2018-02-28   Brenda Shields          Updated for DLT-7917 - Create Opportunity Pricing record for Straight Renewal Quotes
 * 2018-06-11   Brenda Shields          DLT-9762 - GLI Updates
 * 2020-03-07   Brenda Shields          DLT-21480 - [ALL] Update the Envelope Creation class to look for the order form pdf as a file and not an attachment
 *                                                  Fix PMD violations
 * =============================================================================
 */
/** 
* @description : test class for DDigitalDocuSignEnvelopeCreation class
*/ 
@isTest
private class DigitalDocuSignEnvelopeCreation_Test {
    public static String accountId;
    public static String oppId;
    public static String quoteId;
    public static string attachmentId;

    
    // Create Quote data for DocuSign Envelope Creation
    @testSetup
    static void setup(){
        // create account, ssd, opp, contact and quote
        DCTestData.createData();
        Test.startTest();   
        DCTestData.createQuote();      
        
        list<WebServiceSettings__c> webServiceList = new list<WebServiceSettings__c>{new WebServiceSettings__c(Name='EnterpriseWSDL',Endpoint__c='https://api.thomsonreuters.com/ebs/entitlement/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available'),
           new WebServiceSettings__c(Name='StatusPostbackLocation',Endpoint__c='https://api.thomsonreuters.com/ebs/entitlement/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available'),
           new WebServiceSettings__c(Name='PostbackLocation',Endpoint__c='https://api.thomsonreuters.com/ebs/entitlement/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available'),
           new WebServiceSettings__c(Name='Payment AutoCharge',Endpoint__c='https://api.thomsonreuters.com/ebs/entitlement/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available'),
           new WebServiceSettings__c(Name='PaymentCreditIncrease',Endpoint__c='https://api.thomsonreuters.com/ebs/entitlement/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available')};
        insert webServiceList;
        
        // update renewal date on Opp
        Opportunity oOpp = new Opportunity();
        oOpp.id = DCTestData.oppId;
        oOpp.StageName = 'Contacting';
        oOpp.Renewal_Date__c = system.today().addDays(180);
        update oOpp;  
        oppId = oOpp.id;  

        // update Proposal
        Apttus_Proposal__Proposal__c oQuote = new Apttus_Proposal__Proposal__c();
        oQuote.id = DCTestData.bQuoteId;
        oQuote.Apttus_Proposal__Approval_Stage__c = 'Generated';
        oQuote.Apttus_Proposal__Primary__c = true;
        oQuote.Digital_Batch_Processed__c = true;
        oQuote.Digital_Quote_Automation__c = true;
        oQuote.Digital_Quote_Type__c = 'Straight Renewal';
        oQuote.Digital_Envelope_Created__c = false;          
        update oQuote;
        quoteId = oQuote.id;

        // create a matching Digital Subscription record
        Product_Account_Detail__c prodAcctDetail = DCTestData.createDigitalSubscriptions('42072689','42072690', 'Plus', '1004284494', System.Today()+30, 'testCampaign');
        prodAcctDetail.Current_Subscription__c = '41010973';
        prodAcctDetail.sub_Campaign_Code__c = 'subtestcampaign';
        update prodAcctDetail;
                
        // create data for DocuSign connection
        DCTestData.createDocuSignUser();
        
        // delete extra quote
        Apttus_Proposal__Proposal__c oQuote2 = new Apttus_Proposal__Proposal__c();
        oQuote2.Id = DCTestData.cQuoteId;
        //delete oQuote2;
        
        // create web services
        DCTestData.createDocuSignWebService();
        DCTestData.createMarketAutomationWebsvc();
        DCTestData.createPaymentCreditWebService();
        
        // create attachment for the quote
        DCTestData.createAttachment(oQuote.id);
        //DCTestData.createFileAttachment(oQuote.id);      
        Test.stopTest();      
        
    }

    // Test for normal Envelope creation - Test should end successfully
    static testmethod void testEnvelopeCreation() {
        
        Test.startTest();   
        
        // Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock());
        
        DigitalDocuSignEnvelopeCreation dc = new DigitalDocuSignEnvelopeCreation();
        dc.execute(null,dc.QuoteList);
        
        // Check to see if the envelope was created
        Apttus_Proposal__Proposal__c oQuotes = [Select id, Digital_Envelope_Created__c from Apttus_Proposal__Proposal__c where Digital_Envelope_Created__c =: TRUE LIMIT 1];
        system.AssertEquals(True, oQuotes.Digital_Envelope_Created__c, 'Envelope should have been created');
        
        Test.stopTest();
    }
    
     
    static testmethod void testEnvelopeCreationWithUpdates() {
        // Create Envelope with different values causing different updates - Test should end successfully
        
        Opportunity oOpp = [SELECT id, Renewal_Date__c, StageName, Digital_PreviousStageName__c
                            FROM Opportunity 
                            WHERE StageName = 'Contacting'];
        oOpp.Renewal_Date__c = system.today().addDays(-180);
        oOpp.StageName = 'Appointment Scheduled';
        oOpp.Digital_PreviousStageName__c = 'Generate Contract';
        update oOpp;
    
        
        Test.startTest();   
        
        // Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock());
        
        DigitalDocuSignEnvelopeCreation dc = new DigitalDocuSignEnvelopeCreation();
        dc.execute(null,dc.QuoteList);
        
        // Check to see if the envelope was created and stage set to correct value
        Opportunity oOppty = [Select id, StageName from Opportunity where id =: oOpp.id];
        system.AssertEquals('Appointment Scheduled', oOppty.StageName, 'Opportunity should be the correct stage');
        
        Test.stopTest();
    }
    
    // don't create an attachment so the envelope generation will not complete
    static testmethod void testEnvelopeCreationError() {
            
        // create quote with no attachment so it will get an error    
        List<Attachment> oAttachment = [SELECT id FROM Attachment];
        delete oAttachment;
                   
        Test.startTest(); 
        
        // Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock());
        
        DigitalDocuSignEnvelopeCreation dc = new DigitalDocuSignEnvelopeCreation();
        dc.execute(null,dc.QuoteList);
        
        // Check to see if the envelope was not created due to no attachment        
        Apttus_Proposal__Proposal__c oQuotes = [Select id, Digital_Envelope_Created__c from Apttus_Proposal__Proposal__c where Digital_Envelope_Created__c = false LIMIT 1];
        system.AssertEquals(False, oQuotes.Digital_Envelope_Created__c, 'Envelope Creation Flag');
        
        Test.stopTest();
    }    
    
    //test where call to create DocuSign envelope failed
    static testmethod void testEnvelopeCreationCalloutError() {
         
        Test.startTest(); 
        // Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock.failToCreatEnvelope());
        
        DigitalDocuSignEnvelopeCreation dc = new DigitalDocuSignEnvelopeCreation();
        dc.execute(null,dc.QuoteList);
        
        // check to see the envelope was not created
        Apttus_Proposal__Proposal__c oQuotes = [Select id, Digital_Envelope_Created__c from Apttus_Proposal__Proposal__c where Digital_Envelope_Created__c = false LIMIT 1];
        system.AssertEquals(False, oQuotes.Digital_Envelope_Created__c, 'Envelope creation flag');  
        
        Test.stopTest();
    }    
    
    // test where call to DocSign to validate users failed
    static testmethod void testDocusignStartMethod() {

        Test.startTest(); 
        
        // Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock.failToCreatEnvelope());
        
        DigitalDocuSignEnvelopeCreation dc = new DigitalDocuSignEnvelopeCreation();
        Iterable<Apttus_Proposal__Proposal__c> proposalList = dc.start(null);
        
        System.Assert(proposalList != null, 'proposalList is null');
        
        Test.stopTest();

    } 

    static testmethod void testDocusignFinishMethod(){

        Test.startTest(); 
        
        // Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock.failToCreatEnvelope());
        
        DigitalDocuSignEnvelopeCreation dc = new DigitalDocuSignEnvelopeCreation();
        dc.finish(null);

        List<Product_Account_Detail__c> digitalSubscriptionsList = [
            SELECT id
            FROM Product_Account_Detail__c 
            WHERE Campaign_Code__c != null AND Renewal_Date__c > Today AND Bypass_Automation__c = true
        ];

        System.Assert(digitalSubscriptionsList != null, 'DS Bypass not updated');
        
        Test.stopTest();

    }
    
    static testmethod void testEnvelopeCreationNewSales() {
        // Test New Sales specific code
        // update Opp for New Sales
        Opportunity oOpp = [SELECT id, Renewal_Date__c, StageName, Digital_PreviousStageName__c
                            FROM Opportunity 
                            WHERE StageName = 'Contacting'];
        oOpp.Is_Digital_New_Sales__c = true;
        update oOpp;
    
        // update Proposal for New Sales
        Apttus_Proposal__Proposal__c oQuote = [select id, Digital_Quote_TYpe__c 
        					from Apttus_Proposal__Proposal__c 
        					where Apttus_Proposal__Opportunity__c = : oOpp.Id];
        oQuote.Digital_Quote_Type__c = 'Manual';         
        update oQuote;

        Test.startTest();   
        
        // Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock());
        
        list<Apttus_Proposal__Proposal__c> quoteList = [Select id, name, Apttus_Proposal__Opportunity__c,
          Apttus_Proposal__Opportunity__r.Source_System_Detail__r.Digital_Firm__c,
          Apttus_Proposal__Opportunity__r.SAP_Account_Number__c,
          Apttus_Proposal__Opportunity__r.Owner.Email, Apttus_Proposal__Opportunity__r.Owner.Name,
          Apttus_Proposal__Opportunity__r.Digital_PreviousStageName__c,
          APTS_Order_Confirmation_Contact__c, APTS_Order_Confirmation_Contact_Name__c,
          APTS_Order_Confirmation_Contact_Email__c, APTS_Renewal__c,
          Apttus_Proposal__Primary__c, Digital_Quote_Type__c,
          APTS_Sold_To_SAP_Account_Number__c, APTS_Approval_Segment__c,APTS_Proposal_Business_Unit__c,
          Apttus_Proposal__Opportunity__r.Renewal_Date__c, CreatedDate, Is_Digital_New_Sales__c
          FROM Apttus_Proposal__Proposal__c WHERE id =: oQuote.Id];

      	DigitalDocuSignEnvelopeCreation.CreateEnvelopes(quoteList);
        
        // Check to see if the envelope was created and stage set to correct value
        Opportunity oOppty = [Select id, StageName from Opportunity where id =: oOpp.id];
        system.AssertEquals('Contacting', oOppty.StageName, 'Opportunity should be the correct stage');
        
        Test.stopTest();
    }
    
/*
    static testmethod void testContentVersionCreation(){
        
        DigitalDocuSignEnvelopeCreation dc = new DigitalDocuSignEnvelopeCreation(); 
            
		// LatAm User  
		// work-around for error inserting content version records in ContentDocuDelRestrictionHandler
		User u = [select Id from User where profile.Name = 'LatAm User' and IsActive = true limit 1];
        system.runAs(u) {          
        	ContentVersion contentVer = new ContentVersion();
        	contentVer.ContentLocation = 'S';
        	contentVer.Title = String.valueOf('Order Form Test Content Version');
        	contentVer.PathOnClient = String.valueOf('Test PathOnClient');
        	contentVer.versiondata = EncodingUtil.base64Decode('Test versionData');
        	contentVer.Legacy_ParentId__c = dc.QuoteList[0].id; // use this field to tie the content version to the proposal
        	insert contentVer;
        	contentVer = [SELECT id, ContentDocumentId FROM ContentVersion WHERE Title = 'Order Form Test Content Version' LIMIT 1];

        	ContentDocumentLink contentDocLink = new ContentDocumentLink();
        	contentDocLink.ContentDocumentId = contentVer.ContentDocumentId;
       	 	contentDocLink.LinkedEntityId  = dc.QuoteList[0].id;
        	insert contentDocLink;
        }
        Test.startTest();

        // Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock());
        
        dc.execute(null,dc.QuoteList);
        
        // Check to see if the envelope was created
        Apttus_Proposal__Proposal__c oQuotes = [Select id, Digital_Envelope_Created__c from Apttus_Proposal__Proposal__c where Digital_Envelope_Created__c =: TRUE LIMIT 1];
        system.AssertEquals(True, oQuotes.Digital_Envelope_Created__c, 'Envelope should have been creaed');

        Test.stopTest();
    }
*/
    
}