objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_Proposal__Primary__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the quote/proposal is the primary quote to update the related opportunity</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactGUID__c</fullName>
        <label>ContactGUID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ContactPrimaryUserFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ContactPrimaryUserFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContactTrialEligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ContactTrialEligibility</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LCRM_Contact_SSD__c.object
<CustomObject>
    <fields>
        <fullName>LCRM_Account_SSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account SSD</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipName>Contact_SSDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Source System Detail</relationshipLabel>
        <relationshipName>Contact_SSDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Contact Source System</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Source Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+ AccountId,  Account.Name,&apos;_self&apos;)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Digital_Firm__c</fullName>
        <label>Digital Firm</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Digital_Review_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, business has completed review of the offer and can now be presented to the customer.</description>
        <label>Digital Review Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ImpartnerPRM__PartnerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.ImpartnerPRM__PartnerAccount__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.ImpartnerPRM__PartnerAccount__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[BRS_MS9.1.01]The related Master or Parent Opportunity only required if this is a child opportunity.</description>
        <inlineHelpText>Master Opportunity name related to this child opportunity</inlineHelpText>
        <label>Master Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Child Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field is used in Renewals</description>
        <label>Primary Quote ID</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as part of DPS-16054</description>
        <label>Ship To Contact</label>
        <referenceTo>LCRM_Contact_SSD__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Acct SSD</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Source_System_Detail__c.Account_Name__r.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Source_System_Detail__c.Account_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isDigitalSpearHead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Digital Channel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Child Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Segment_Level_2__c</fullName>
        <description>Created as per Tax Prof ECM feed, DPS-9495</description>
        <label>Frozen Market Current Year Segment L2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Digital_Firm__c</fullName>
        <formula>CASE(BU_Segment_Level_2__c, &apos;Corp Emerging Existing&apos;,&apos;Corporate&apos;,&apos;Corp Large Existing&apos;,&apos;Corporate&apos;,&apos;Corp Counsel&apos;, &apos;Corporate&apos;, &apos;Corp Counsel Existing&apos;, &apos;Corporate&apos;, &apos;Corp Investigative&apos;, &apos;Corporate&apos;, &apos;Corp Investigative Financial&apos;, &apos;Corporate&apos;, &apos;Corp Major Accounts&apos;,&apos;Corporate&apos;, &apos;Corp National Investigative&apos;, &apos;Corporate&apos;, &apos;Corporation Enterprise&apos;, &apos;Corporate&apos;, &apos;Corporation National Accounts&apos;, &apos;Corporate&apos;, &apos;Corporation Strategic&apos;, &apos;Corporate&apos;, &apos;Corporation Strategic Existing&apos;, &apos;Corporate&apos;, &apos;SLF 11-20&apos;, &apos;Small Law&apos;, &apos;SLF 21-29&apos;, &apos;Small Law&apos;, &apos;SLF 2-3&apos;, &apos;Small Law&apos;, &apos;SLF 4-6&apos;, &apos;Small Law&apos;, &apos;SLF 7-10&apos;, &apos;Small Law&apos;, &apos;Solo Law Firm&apos;, &apos;Small Law&apos;,&apos;State Government&apos;, &apos;Government&apos;,&apos;Corp-Emerging&apos;,&apos;Corporate&apos;,
&apos;Corp-Large&apos;,&apos;Corporate&apos;,
&apos;Corp Large&apos;,&apos;Corporate&apos;,
&apos;Corp-SMB&apos;,&apos;Corporate&apos;,
&apos;Corp Strategic&apos;, &apos;Corporate&apos;,
&apos;Global 7&apos;,&apos;Corporate&apos;,
&apos;Federal&apos;,&apos;Government&apos;,
&apos;Federal courts&apos;,&apos;Government&apos;,
&apos;State/Local Courts&apos;,&apos;Government&apos;,
&apos;Tribal&apos;,&apos;Government&apos;,
&apos;Academia&apos;,&apos;Government&apos;,
&apos;Academic&apos;,&apos;Government&apos;,
&apos;State/Local&apos;,&apos;Government&apos;,
&apos;Other - Government&apos;,&apos;&apos;,
&apos;Medium Law&apos;,&apos;Medium Law&apos;,
&apos;Small Law&apos;,&apos;Small Law&apos;,
&apos;Large Law&apos;,&apos;Large Law&apos;,
&apos;Other - Legal Professionals&apos;,&apos;&apos;,
&apos;Other - Corporate&apos;,&apos;&apos;,&apos;None&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Digital Firm</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>LCRM_Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>OLC_Account_Number__c</fullName>
        <label>OLC Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Timed-out</fullName>
                </value>
                <value>
                    <fullName>Bounceback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trial__c.object
<CustomObject>
    <description>As per DLT-5979 - This object is created to capture details of Trial.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_ssd__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact ssd</label>
        <referenceTo>LCRM_Contact_SSD__c</referenceTo>
        <relationshipLabel>Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ssd</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>On-Demand Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <label>Trial Id(s)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Bounceback</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Timed-out</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Entitlement Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trial</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Trial Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WestLawOpptyDetails.cls
/*
* This class has westlaw service related to SAP Account Number and returns corresponding OppID, Acc ID and Trial Data
* 
* CHANGE HISTORY
* ==================================================================================================================================
* Date         Name                    Description
* 2018-07-12   Rajan Tatuskar          DLT-10853 - Ensure In-Product WESTLAW notifications do not appear based on certain Proposal types
* 2018-08-16   Rajan Tatuskar          DLT-11707 - Utilizing Digitally reviewed flag for suppressing in-product notification when Renewal offer not reviewed and approved
* 2018-09-10   Rajan Tatuskar          DLT-10215 - Enable/Disable In Product Notifications
* 2019-03-20   Navleen Kaur            DLT-15672  [Tech Story] [SLF] Automation Changes for New Mid Contract Flag
* 2019-04-22   Srikanth Kota           DLT-16179  [SLF] - Prevent new contract proposal displayed in In product notification 
* 2019-04-22   Srikanth Kota           DLT-16178  [SLF] Only Primary proposal Need to be consider for WestLawOpptyDetails service
* 2019-05-12   Srikanth kota           DLT-18594  [FL] Fix In-product notification for FindLaw.
* 2020-08-05   Rahul Natarajan         DLT-20503   [PL] [REN][SFDC] Add Subcampagn Code Field and Made Few PMD fixes
* 2021-02-23   Ameeta Antonio		   DLT-21440 - [SFDC][REN][ML] In product Renewal Prompt and fixed PMD errors.
* 2021-05-10   Ameeta Antonio		   DLT-21743   Enable MLF SSD query for ODT Practical Law Trials
=================================================================================================================================
*/
/** 
* @description : Webservice to return related details based on SAP AccountNum
*/
@RestResource(urlMapping = '/westLawOpportunity/*')
global with sharing class WestLawOpptyDetails {
    
    private static Final String OLDMIDCONTRACT = 'Old Mid Contract';
    private static Final Set < String > MIDCONTRACT = new Set < String > {
        'Old Mid Contract',
            '    New Mid Contract'
            }; // DLT-16179
                
                private static Set < Id > optyIds = new Set < Id > ();
    /** 
* @description : GET method of the webservice
* @return AccOptyWrapper
*/
    @HttpGet
    global static AccOptyWrapper doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        //DLT-20503 Gave If Else braces
        if (!test.isRunningTest()){
            res.addHeader('Cache-Control', 'public,max-age=43200');
        }
        
        
        //String accountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);        
        String sapAccountNum = req.params.get('sapAccountNum');
        //String TrialId= req.params.get('TrialId');
        
        List < Opportunity > optyList = new List < Opportunity > ();
        //Set < Id > optyIds = new Set < Id > ();
        Set < Id > optyIdFiltered = new Set < Id > ();
        //Contact con;
        //Account acc;
        AccOptyWrapper wrapperObj;
        Source_System_Detail__c acc = new Source_System_Detail__c();
        Source_System_Detail__c ssd = new Source_System_Detail__c();
        //AccTrialWrappercls wrapperObj2;
        
        try {
            
            ssd = [Select Id,Source_System_Account_Number__c,BU_Segment_Level_2__c from Source_System_Detail__c where Source_System_Account_Number__c =: sapAccountNum WITH SECURITY_ENFORCED];
                        
            if(ssd.BU_Segment_Level_2__c == 'Medium Law'){
               acc = [Select id, name, Source_System_Account_Number__c, OLC_Account_Number__c, LCRM_Phone__c, LCRM_Website__c, Trial_Status__c,Digital_Firm__c,(SELECT Id, Trial_Status__c, Trial_Id__c, Trial_End_Date__c from Trials__r ORDER BY Trial_End_Date__c DESC) from Source_System_Detail__c where(Source_System_Account_Number__c =: sapAccountNum OR OLC_Account_Number__c =: sapAccountNum) WITH SECURITY_ENFORCED]; 
            }else{
            //*** START :: Added by Rajan :: DLT-11707 - Utilizing Digitally reviewed flag for suppressing in-product notification when Renewal offer not reviewed and approved
            // DLT-11707 - added "Digital_Review_Complete__c = true" criteria in SQOL Query for Opportunity
            //*** START :: Added by Rajan :: DLT-10215 - Enable/Disable In Product Notifications
            // DLT-10215 - added "Account_Name__r.Disable_In_Product_Notifications__c = false" criteria in SQOL Query for Source_System_Detail__c
            acc = [Select id, name, Source_System_Account_Number__c, OLC_Account_Number__c, LCRM_Phone__c, LCRM_Website__c, Trial_Status__c,Digital_Firm__c, (SELECT Id FROM Opportunities__r WHERE isDigitalSpearHead__c = true AND Digital_Review_Complete__c = true), (SELECT Id, LCRM_Account_SSD__r.Trial_Status__c, LCRM_Contact__r.ContactGUID__c, LCRM_Contact__r.ContactTrialEligibility__c, LCRM_Contact__r.ContactPrimaryUserFlag__c from Contact_SSDs__r), (SELECT Id, Trial_Status__c, Trial_Id__c, Trial_End_Date__c from Trials__r ORDER BY Trial_End_Date__c DESC) from Source_System_Detail__c where(Source_System_Account_Number__c =: sapAccountNum OR OLC_Account_Number__c =: sapAccountNum) AND Account_Name__r.Disable_In_Product_Notifications__c = false AND BU_Segment_Level_2__c <> 'Medium Law' WITH SECURITY_ENFORCED];
            //*** END :: Added by Rajan :: DLT-10215 - Enable/Disable In Product Notifications
            //*** END :: Added by Rajan :: DLT-11707 - Utilizing Digitally reviewed flag for suppressing in-product notification when Renewal offer not reviewed and approved
            // acc= [SELECT Id, Name, Phone, Website,Trial_Status__c,SAPAccountNumber__c,(SELECT Id FROM Opportunities WHERE isDigitalSpearHead__c=true),(SELECT Id,account.Trial_Status__c, ContactGUID__c,ContactTrialEligibility__c,ContactPrimaryUserFlag__c from Contacts),(SELECT Id, Trial_Status__c,Trial_Id__c,Trial_End_Date__c from Trials__r ORDER BY Trial_End_Date__c DESC ) FROM Account WHERE SAPAccountNumber__c= :sapAccountNum];
        	}
        } catch (System.QueryException e) {
            System.debug(LoggingLevel.INFO,'Could not find any Account for the SAP account number provided');
        }
        
        //Checking if there's any oppty record and pulling the Ids into a Set
        wrapperObj = retrieveSetOfOppty(acc);
        
        
        //Checking if there's any oppty Id record and pulling the opty id into a Set based on proposal stage 
        if (optyIds != null && optyIds.size() >= 1) {
            system.debug(LoggingLevel.INFO,'optyIds=========>' + optyIds);
            //*** START :: Added by Rajan :: DLT-10853 - Ensure In-Product WESTLAW notifications do not appear based on certain Proposal types //DLT-16178 update Apttus_Proposal__Primary__c and Contract_Type__c
            //for(Apttus_Proposal__Proposal__c ap :[SELECT id,Apttus_Proposal__Opportunity__c,Apttus_Proposal__Approval_Stage__c FROM Apttus_Proposal__Proposal__c WHERE Digital_Quote_Type__c != 'Manual' AND Contract_Type__c != :OLDMIDCONTRACT AND Apttus_Proposal__Approval_Stage__c IN ('Presented') AND Apttus_Proposal__Primary__c = TRUE  AND Apttus_Proposal__Opportunity__c IN :optyIds]){                                              
            // DLT-18594
            for (Apttus_Proposal__Proposal__c ap: [SELECT id, Apttus_Proposal__Opportunity__c, Apttus_Proposal__Approval_Stage__c FROM Apttus_Proposal__Proposal__c WHERE Digital_Quote_Type__c != 'Manual'
                                                   AND Contract_Type__c NOT IN: MIDCONTRACT AND Apttus_Proposal__Approval_Stage__c IN('Presented') AND Apttus_Proposal__Primary__c = TRUE AND APTS_Proposal_Business_Unit__c != 'FindLaw'
                                                   AND Apttus_Proposal__Opportunity__c IN: optyIds
                                                  ]) {
                                                      system.debug(LoggingLevel.INFO,'================>' + ap.Apttus_Proposal__Opportunity__c);
                                                      optyIdFiltered.add(ap.Apttus_Proposal__Opportunity__c);
                                                  }
            //*** END :: Added by Rajan :: DLT-10853 - Ensure In-Product WESTLAW notifications do not appear based on certain Proposal types
            System.debug(LoggingLevel.INFO,'@@@@@@@@@@54filterde' + optyIdFiltered);
        } else {
            System.debug(LoggingLevel.INFO,'@@@@@@@@@@54' + acc);
            wrapperObj = new AccOptyWrapper(acc, null, 'Could not find any opportunity for the SAP account number provided');
        }
        
        //Checking if there's any filtered oppty record and pulling the opty records into a List 
        if (optyIdFiltered != null && optyIdFiltered.size() >= 1) {
            try {
                //*** START :: Added by Rajan :: DLT-10853 - Ensure In-Product WESTLAW notifications do not appear based on certain Proposal types  //DLT-16178 update Apttus_Proposal__Primary__c  and Contract_Type__c
                //optyList = [SELECT Id,accountId,Name,Renewal_Date__c,(SELECT Id, Name, Apttus_Proposal__Approval_Stage__c FROM Apttus_Proposal__R00N70000001yUfDEAU__r WHERE Digital_Quote_Type__c != 'Manual' AND Contract_Type__c != :OLDMIDCONTRACT AND Apttus_Proposal__Approval_Stage__c IN ('Presented') AND Apttus_Proposal__Primary__c = TRUE) FROM Opportunity WHERE Id IN :optyIdFiltered];
                //DLT-18594
                optyList = [SELECT Id, accountId, Name,sub_Campaign_Code__c,Renewal_Date__c, (SELECT Id, Name, Apttus_Proposal__Approval_Stage__c FROM Apttus_Proposal__R00N70000001yUfDEAU__r WHERE Digital_Quote_Type__c != 'Manual'
                                                                                              AND Contract_Type__c NOT IN: MIDCONTRACT AND Apttus_Proposal__Approval_Stage__c IN('Presented') AND Apttus_Proposal__Primary__c = TRUE AND APTS_Proposal_Business_Unit__c != 'FindLaw') FROM Opportunity WHERE Id IN: optyIdFiltered WITH SECURITY_ENFORCED];
                // DLT-20503 - Added sub_Campaign_Code__c field in above query
                //*** END :: Added by Rajan :: DLT-10853 - Ensure In-Product WESTLAW notifications do not appear based on certain Proposal types 
                wrapperObj = new AccOptyWrapper(acc, optyList, 'No Error');
            } catch (System.QueryException e) {
                System.debug(LoggingLevel.INFO,'Could not find any filtered opty for the SAP account number provided');
            }
        } else {
            System.debug(LoggingLevel.INFO,'@@@@@@@@@@67' + acc);
            wrapperObj = new AccOptyWrapper(acc, null, 'Could not find any opportunity for the SAP account number provided');
        }
        
        
        return wrapperObj;
    }
    
    /** 
* @description : method to retrieve set of oppty id's
* @param acc : SSD query
* @return AccOptyWrapper
*/    
    private static AccOptyWrapper retrieveSetOfOppty(Source_System_Detail__c acc){
        AccOptyWrapper wrapperObj;
        if (acc != null) {
            if (acc.Opportunities__r != null && acc.Opportunities__r.size() >= 1) {
                for (Opportunity op: acc.Opportunities__r) {
                    optyIds.add(op.Id);
                }
                System.debug(LoggingLevel.INFO,'@@@@@afterloop' + optyIds);
            } else {
                System.debug(LoggingLevel.INFO,'@@@@@@@@@@39' + acc);
                wrapperObj = new AccOptyWrapper(acc, null, 'Could not find any opportunity for the SAP account number provided');
            }
        } else {
            wrapperObj = new AccOptyWrapper(null, null, 'Could not find any account for the SAP account number provided');
        }
        return wrapperObj;
    }
    
    /** 
* @description : Creating this wrapper class in case service wants more unrelated Obj data in future
*/ 
    global class AccOptyWrapper {
        //Account acc;
        // Contact ContactTrialPreference;
        //DLT-20503 Changed to LowerCase Variable - Opty & AccTrialWrapper
        List < Opportunity > opty;
        AccTrialWrappercls accTrialWrapper;
        String message;
        
        AccOptyWrapper(Source_System_Detail__c acc, List < Opportunity > op, String msg) {
            //this.acc=ac;
            //*** START :: Added by Rajan :: DLT-10853 - Ensure In-Product WESTLAW notifications do not appear based on certain Proposal types
            if (op != null) {
                for (Opportunity tempOpp: op) {
                    tempOpp.accountId = acc.id;
                }
            }
            //*** END :: Added by Rajan :: DLT-10853 - Ensure In-Product WESTLAW notifications do not appear based on certain Proposal types 
            this.opty = op;
            //this.ContactTrialPreference=con;
            this.message = msg;
            
            if (acc != null){
                //DLT-20503 Gave If Else braces
                accTrialWrapper = new AccTrialWrappercls(acc, 'msg');
            }
            else {
                accTrialWrapper = new AccTrialWrappercls(null, 'msg');
            }
        }
    }
    
    /** 
* @description : wrapper class for trials
*/ 
    global class AccTrialWrappercls {
        //DLT-20503 Changed to LowerCase Variable - Status & TrialEligibility
        String status;
        String trialEligibility;
        String mssg;
        String accountID;
        String accountName;
        
        AccTrialWrappercls(Source_System_Detail__c acc, String m) {
            if (acc != null) {
                status = acc.Trial_Status__c;
                accountID = acc.Id;
                accountName = acc.Name;
                
                if (acc.Trial_Status__c == null){
                    //DLT-20503 Gave If Else braces
                    trialEligibility = 'true';
                }
                else {
                    String s = Label.ODT_Trial_Difference;
                    //DLT-20503 Changed to LowerCase Variable
                    Integer odtDifference = 180;
                    //DLT-20503 Gave If Else braces
                    if (s.isNumeric()){
                        odtDifference = integer.valueOf(s);
                    }
                    
                    trialEligibility = checkTrialEligibility(acc,odtDifference);
                    
                }
                mssg = m;
            } else {
                trialEligibility = null;
            }
        }
 
    /** 
* @description : method to check trial eligibility
* @param acc : Source_System_Detail__c
* @param odtDifference : Integer
* @return String
*/        
        public String checkTrialEligibility(Source_System_Detail__c acc, Integer odtDifference){
        String trialEligibility;
        for (Trial__c tr: acc.Trials__r) {
            switch on tr.Trial_Status__c{
                when 'Invited','Rep Initiated','Timed-out'{
                	trialEligibility = 'true';
                }
                when 'Accepted'{
                	trialEligibility = 'false';
                    break;
                }
                when 'Expired'{
                    //DLT-20503 Changed to LowerCase Variable
                    Integer trialDifference = tr.Trial_End_Date__c.DaysBetween(System.today());
                    system.debug(LoggingLevel.INFO,'Dates..........' + trialDifference);
                    if (trialDifference > odtDifference) {
                        trialEligibility = 'true';
                    } else {
                        trialEligibility = 'false';
                        break;
                    }
                }
            }
        }
        return trialEligibility;
    }
        
    }
 
   
}