objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>APTS_Info_PlanType__c</fullName>
        <label>Plan Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Info_RenewalDate__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Material_Number__c</fullName>
        <formula>Apttus_Config2__ProductId__r.ProductCode</formula>
        <label>Material Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset Line Items (Sold To)</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetCode__c</fullName>
        <description>The asset code</description>
        <label>Asset Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetStatus__c</fullName>
        <description>The asset status</description>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Pending Re-activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Change</fullName>
                </value>
                <value>
                    <fullName>Pending Suspension</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Incremented</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BundleAssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated bundle line item.</description>
        <inlineHelpText>ID of the associated bundle line item.</inlineHelpText>
        <label>Bundle Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Option Asset Line Items</relationshipLabel>
        <relationshipName>OptionAssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ChargeType__c</fullName>
        <description>The charge type  associated with the product or service</description>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Price</fullName>
                </value>
                <value>
                    <fullName>License Fee</fullName>
                </value>
                <value>
                    <fullName>Subscription Fee</fullName>
                </value>
                <value>
                    <fullName>Implementation Fee</fullName>
                </value>
                <value>
                    <fullName>Installation Fee</fullName>
                </value>
                <value>
                    <fullName>Maintenance Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__HasOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product has options.</description>
        <label>Has Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsInactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the asset is inactive.</description>
        <inlineHelpText>Indicates whether the asset is inactive.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__NetPrice__c</fullName>
        <description>The net price for the product or service is the Adjusted Price after applying the Group Adjustment %</description>
        <label>Net Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__SellingTerm__c</fullName>
        <description>The selling term associated with the product or service</description>
        <label>Selling Term</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ShipToAccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the ship to account</description>
        <inlineHelpText>ID of the ship to account</inlineHelpText>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset Line Items (Ship To)</relationshipLabel>
        <relationshipName>AssetLineItemsShipTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__HasOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product has options.</description>
        <label>Has Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Media_Lower_Level__c</fullName>
        <description>Represents a more detailed media of the individual material. (Bound Volume, Pamphlet, etc.)</description>
        <inlineHelpText>Represents a more detailed media of the individual material.  (Bound Volume, Pamphlet, etc.)</inlineHelpText>
        <label>Media Lower Level</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/APTS_AccInstalledProductsController.cls
/*
    Class : APTS_AccInstalledProductsController
*/
public without Sharing class APTS_AccInstalledProductsController {
    
    public List<Apttus_Config2__AssetLineItem__c> shipToAssetLines { get;private set; }
    public ApexPages.StandardController stdController;
    private Account acc; 
    public Boolean hasActiveAssets { get;private set; }
    //constructor
    public APTS_AccInstalledProductsController(ApexPages.StandardController controller) {
        hasActiveAssets = false;
        this.stdController = controller;
        acc = (Account)controller.getRecord();
        if(acc == null){
             return;
        }
        //Replaced  Apttus_Config2__ShipToAccountId__c field with Apttus_Config2__AccountId__c in query filter condition as part of CRM-14603
           //SOC-9796 PMD Fix
        if(Apttus_Config2__AssetLineItem__c.sObjectType.getDescribe().isAccessible()){
            shipToAssetLines = [Select Id, Name,Apttus_Config2__AccountId__c,Apttus_Config2__ShipToAccountId__c, Apttus_Config2__ProductId__c, Apttus_Config2__ProductId__r.Name , Apttus_Config2__AssetCode__c, 
            Apttus_Config2__ChargeType__c, Apttus_Config2__Quantity__c, Apttus_Config2__NetPrice__c,Apttus_Config2__AssetStatus__c,
            APTS_Material_Number__c, Apttus_Config2__BundleAssetId__c, Apttus_Config2__HasOptions__c,
            APTS_Info_PlanType__c, APTS_Info_RenewalDate__c, Apttus_Config2__ProductId__r.Media_Lower_Level__c   
            from Apttus_Config2__AssetLineItem__c
           // where Apttus_Config2__ShipToAccountId__c = :acc.Id
            where Apttus_Config2__AccountId__c = :acc.Id
            AND Apttus_Config2__IsInactive__c = False AND Apttus_Config2__AssetStatus__c != 'Cancelled'];
        }  
       //example[x].round(System.RoundingMode.FLOOR)
       for (integer j=0; j < shipToAssetLines.size(); j++)
       {
          if (shipToAssetLines.get(j).Apttus_Config2__Quantity__c != null){
              shipToAssetLines.get(j).Apttus_Config2__Quantity__c = shipToAssetLines.get(j).Apttus_Config2__Quantity__c.round(System.RoundingMode.FLOOR);
          }
          if (shipToAssetLines.get(j).Apttus_Config2__SellingTerm__c != null){
              shipToAssetLines.get(j).Apttus_Config2__SellingTerm__c = shipToAssetLines.get(j).Apttus_Config2__SellingTerm__c.round(System.RoundingMode.FLOOR);
          }
       }
        
        if(shipToAssetLines != null && !shipToAssetLines.isEmpty()) {
            hasActiveAssets = true;
        }
    }
}