objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready For Approvals</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Ready For Finalization</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Microsite__c</fullName>
        <label>Lead Microsite</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deloitte</fullName>
                </value>
                <value>
                    <fullName>PWC</fullName>
                </value>
                <value>
                    <fullName>TR Store</fullName>
                </value>
                <value>
                    <fullName>Triform</fullName>
                </value>
                <value>
                    <fullName>Deskcopy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TRStoreDeleteOrphancartsUtilityTest.cls
@istest(seealldata=false)
public class TRStoreDeleteOrphancartsUtilityTest{
/*
    @description test class for TRStoreDeleteOrphancartsUtility
*/


        //@description Started test coverage for TRStoreDeleteOrphancartsUtility
        public static testmethod void batchexecute(){
    
            TRStore_OrderTest.createStaticValues();
            
            LIST<Apttus_Config2__ProductConfiguration__c> cartLists = new LIST<Apttus_Config2__ProductConfiguration__c>(); 
            Apttus_Config2__ProductConfiguration__c cartRec = TRStore_OrderTest.createProductConfigurations();
            Apttus_Config2__ProductConfiguration__c cart1 =  insertDummyCart();
            Apttus_Config2__ProductConfiguration__c cart2 =  insertDummyCart();
            Apttus_Config2__ProductConfiguration__c cart3 =  insertDummyCart();
            
            cartLists.add(cartRec);
            cartLists.add(cart1);
            cartLists.add(cart2);
            cartLists.add(cart3);
             
             Database.insert(cartLists, false);
            System.assert(cartLists != null, 'Inserted cart List');
             
             system.debug(loggingLevel.INFO,'Hello...........      '+cart2.lastModifiedByID);
             
             
            integer noofDaysCount = 90 ;
            string cartName = 'Auto Generated';
            string cartStatus = 'New';
            string cartModifieduserId = userinfo.getuserId() ;
            
             date tobeConsiderDate = system.today().addDays(noofDaysCount*(1));
       
       
            LIST<Apttus_Config2__ProductConfiguration__c> cartListsQuery =  [Select id from Apttus_Config2__ProductConfiguration__c WHERE Apttus_QPConfig__Proposald__c = null AND Name =: cartName AND Apttus_Config2__Status__c =: cartStatus AND LastModifiedBy.id=: cartModifieduserId  AND LastModifiedDate <=: tobeConsiderDate ];
            
             system.debug(loggingLevel.INFO,'cartListsQuery ..........    '+cartListsQuery );
           
            
             
            lead ld = new lead();
            ld.FirstName='TestFirstname';
            ld.LastName='TestLastName';
            ld.Email='testfirst.testlast@test.com';
            ld.IsConverted=false;
            ld.Company='TestCompany';
            ld.Lead_Microsite__c = 'PWC';
            ld.Product_Configuration__c = cart1.id;
            
            insert ld;
            
             TRStoreDeleteOrphancartsUtilitySchedule myClass = new TRStoreDeleteOrphancartsUtilitySchedule();   
             myClass.execute(null);
            
            
        }
        
        //@description get user cart record
        public static Apttus_Config2__ProductConfiguration__c  insertDummyCart(){
              
            Apttus_Config2__ProductConfiguration__c prodConfigObj = new Apttus_Config2__ProductConfiguration__c();
            prodConfigObj.Name = 'Auto Generated';
            prodConfigObj.Apttus_Config2__Status__c ='New';
             
             
             return prodConfigObj ;
        }
        
        
}