objects/Apttus_DocuApi__DocuSignEnvelope__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Order_Confirmation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Confirmation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Apttus_Proposal__Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposals (Order Confirmation Contact)</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
        <description>The proposal approval stage</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Primary__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the quote/proposal is the primary quote to update the related opportunity</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Acct SSD</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Source_System_Detail__c.Account_Name__r.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Source_System_Detail__c.Account_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unmarked_Digital_Channel__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag that is set when a Digital Proposal gets an automation error and all Proposals for that Opportunity are set to Expired. This flag is used by Informatica so it can exclude these Opportunities/Proposals from further processing.</description>
        <label>Unmarked Digital Channel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isDigitalSpearHead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Digital Channel</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Digital_BulkExpireAllProposalsCntl_Test.cls
/**
 * Test class for testing the Digital_BulkExpireAllProposalsController class.  That class is a button on the 
 * Opportunity list view which 'expires' all Quote/Proposals from the selected opportunities
 */
/**
 * CHANGE HISTORY
 * =============================================================================
 * Date         Name                    Description
 * 2018-02-06   Brenda Shields          Created
 * 2018-06-21   Poonam Garg             modified to increase coverage and create TestData using
                                        DCTestData Class.  
 * =============================================================================
 */
@isTest
private class Digital_BulkExpireAllProposalsCntl_Test {

    @testSetup static void init(){
        User u3 = [SELECT Id FROM User WHERE Name='Molly Bentz']; 
        System.runas(u3){
            DCTestData.createData();
            Test.startTest();
            DCTestData.createQuote();
            Test.StopTest();
        	Apttus_Proposal__Proposal__c prop=[Select id from Apttus_Proposal__Proposal__c LIMIT 1];
         	// create envelope record
        	Apttus_DocuApi__DocuSignEnvelope__c newEnv = DCTestdata.createDocuSignEnvelope('sent',prop.Id);
        	insert newEnv;  
        }  
    }
    
/*  
There is a continue response needed to complete the process - the complete test is already done below  
     @isTest static void testExpireQuote() {
        User u3 = [SELECT Id FROM User WHERE Name='Molly Bentz'];
        System.runAs(u3) {
                Test.startTest();
                List<Opportunity> oppList=[Select id,name,AccountId,stagename,CloseDate,isDigitalSpearHead__c from opportunity ];
                System.debug('*******opplist'+oppList);
            
                PageReference pageRef = Page.DigitalBulkExpireAllProposals;
                Test.setCurrentPage(pageRef);
                ApexPages.StandardSetController con = new ApexPages.StandardSetController(oppList);
                con.setSelected(oppList);
                Digital_BulkExpireAllProposalsController conBulk = new Digital_BulkExpireAllProposalsController(con);
                
                
                PageReference pg = conBulk.BulkExpireProposals();
                //PageReference pg1 = conBulk.BulkExpireProposals();        
                
                Opportunity oppRec=[Select id,Unmarked_Digital_Channel__c,isDigitalSpearHead__c from Opportunity where id =:oppList];
                System.debug('&&&opp'+oppRec);
                System.AssertEquals(True,oppRec.Unmarked_Digital_Channel__c,'Unmarked');
                System.AssertEquals(False,oppRec.isDigitalSpearHead__c,'Digital Channel');
                PageReference pg3 = conBulk.ReturnToOpp();
                Test.stopTest();
        }
    }
*/
    
	@isTest static void testNoDigitalProposal() {
        User u3 = [SELECT Id FROM User WHERE Name='Molly Bentz'];
        System.runAs(u3) {
            Test.startTest();
            List<Opportunity> oppList=[Select id,name,AccountId,stagename,CloseDate,isDigitalSpearHead__c from opportunity LIMIT 1];
            Apttus_Proposal__Proposal__c newQuote =[Select Apttus_Proposal__Opportunity__c,Apttus_Proposal__Approval_Stage__c,Apttus_Proposal__Primary__c,Apttus_Proposal__Account__c,APTS_Order_Confirmation_Contact__c from Apttus_Proposal__Proposal__c where Apttus_Proposal__Opportunity__c in :oppList][0];
            
            newQuote.Apttus_Proposal__Approval_Stage__c = 'Accepted';
            update newQuote;
            PageReference pageRef = Page.DigitalBulkExpireAllProposals;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetController con = new ApexPages.StandardSetController(oppList);
            con.setSelected(oppList);
            Digital_BulkExpireAllProposalsController conBulk = new Digital_BulkExpireAllProposalsController(con);           
            
            PageReference pg = conBulk.BulkExpireProposals();
            PageReference pg1 = conBulk.BulkExpireProposals();
            Opportunity oppRec=[Select id,Unmarked_Digital_Channel__c,isDigitalSpearHead__c from Opportunity where id =:opplist];
            System.AssertEquals(false,oppRec.Unmarked_Digital_Channel__c,'Unmarked');
            System.AssertEquals(true,oppRec.isDigitalSpearHead__c,'Digital Channel');
            Test.stopTest();
        }
    }   
       
    @isTest static void testInvalidUser() {
        Profile p1 = [SELECT Id FROM Profile WHERE Name='ANZ Users']; 
        DCTestData.createUser();
        User newUser=[Select id from User where username='Test.User@testorg.com' LIMIT 1];
        // Opportunity Owner
    	Test.startTest();        
        List<Opportunity> oppList=[Select id,name,AccountId,stagename,CloseDate,isDigitalSpearHead__c from opportunity where name ='Test Class Opp' LIMIT 1];       
        System.runAs(newUser) {
            PageReference pageRef = Page.DigitalBulkExpireAllProposals;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetController con = new ApexPages.StandardSetController(oppList);
            con.setSelected(oppList);
            Digital_BulkExpireAllProposalsController conBulk = new Digital_BulkExpireAllProposalsController(con);
            try {
            	PageReference pg = conBulk.BulkExpireProposals();
            } catch(Exception e) {
                System.assertEquals(e.getmessage(),'You are not authorized to Expire Proposals in bulk using this function. Please contact an authorized user to Expire Digital Quote/Proposals via the Opportunity List View.');
            }
            Test.stopTest();
        }
    }
    
    @isTest static void testContinueQuotes() {
        User u3 = [SELECT Id FROM User WHERE Name='Molly Bentz'];
        System.runAs(u3) {        
            Test.startTest();       
            List<Opportunity> oppList=[Select id,name,AccountId,stagename,CloseDate,isDigitalSpearHead__c from opportunity LIMIT 1]; 
            // Set mock callout class for Envelope response
            Test.setMock(HttpCalloutMock.class, new HttpResponseMock());
            PageReference pageRef = Page.DigitalBulkExpireAllProposals;
            Test.setCurrentPage(pageRef);        
            ApexPages.StandardSetController con = new ApexPages.StandardSetController(oppList);
            con.setSelected(oppList);
            Digital_BulkExpireAllProposalsController conBulk = new Digital_BulkExpireAllProposalsController(con); 
            System.assertEquals(1, conBulk.getMySelectedSize()); 
            conBulk.isContinue = true;
            PageReference pg = conBulk.ContinueExpire();
            Opportunity oppRec=[Select id,Unmarked_Digital_Channel__c,isDigitalSpearHead__c from Opportunity where id =:opplist];
            System.AssertEquals(True,oppRec.Unmarked_Digital_Channel__c,'Unmarked');
            System.AssertEquals(False,oppRec.isDigitalSpearHead__c,'Digital Channel');
            Test.stopTest();
        } 
    }
           
    @isTest static void testNonDigitalOpportunity() {
        //create required custom setting
        User u3 = [SELECT Id FROM User WHERE Name='Molly Bentz'];
        System.runAs(u3) {
            Test.startTest();       
            List<Opportunity> oppList = [Select id,name,AccountId,stagename,CloseDate,isDigitalSpearHead__c from opportunity LIMIT 1];
            List<Account> accList=[Select id from Account LIMIT 1];
            Source_System_Detail__c accountSSD=[Select id from Source_System_Detail__c LIMIT 1][0];
            Contact newContact=[Select id from Contact][0];
            Account newAcc=[Select id from Account][0];
            Opportunity newOpp1 = DCTestData.createOpportunityRec('Test Class Opp', accList[0].Id, 'Contacting', system.today(),accountSSD.id);
            newOpp1.Name = 'Test Class Opp';
            newOpp1.isDigitalSpearHead__c = false;          
            insert newOpp1;
            oppList.add(newOpp1);        
            // create Proposal for Non Digital Opportunity
            Apttus_Proposal__Proposal__c newQuote1 = DCTestdata.createProposalRec(newOpp1.Id,accountSSD.id,newAcc.id,newContact.Id,'test0987@tr.com');
            //newQuote.name = 'Test Class Quote';
            newQuote1.Apttus_Proposal__Approval_Stage__c = 'Accepted';
            newQuote1.Apttus_Proposal__Primary__c = true;
            insert newQuote1;
            PageReference pageRef = Page.DigitalBulkExpireAllProposals;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetController con = new ApexPages.StandardSetController(oppList);
            con.setSelected(oppList);
            Digital_BulkExpireAllProposalsController conBulk = new Digital_BulkExpireAllProposalsController(con); 
            List<Apttus_Proposal__Proposal__c> newQuoteList =[Select Apttus_Proposal__Opportunity__c,Apttus_Proposal__Approval_Stage__c,Apttus_Proposal__Primary__c,Apttus_Proposal__Account__c,APTS_Order_Confirmation_Contact__c from Apttus_Proposal__Proposal__c where Apttus_Proposal__Approval_Stage__c ='Expired'];
            System.assertEquals(newQuoteList.size(),0);           
            PageReference pg = conBulk.BulkExpireProposals();
            Test.stopTest();
        }      
    }
    
    @isTest static void noOpportunitySelected() {   
        //Test.setMock(HttpCalloutMock.class, new HttpResponseMock());
        User u3 = [SELECT Id FROM User WHERE Name='Molly Bentz'];
        System.runAs(u3) {
            Test.startTest();       
            List<Opportunity> oppList=[Select id,name,AccountId,stagename,CloseDate,isDigitalSpearHead__c from opportunity  LIMIT 1];
        
            System.debug('*******opplist'+oppList);
            PageReference pageRef = Page.DigitalBulkExpireAllProposals;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetController con = new ApexPages.StandardSetController(oppList);
            //con.setSelected(oppList);
            Digital_BulkExpireAllProposalsController conBulk = new Digital_BulkExpireAllProposalsController(con);  
            try {
            	PageReference pg = conBulk.BulkExpireProposals();
            } catch(Exception e) {
                System.assertEquals(e.getMessage(),'Please select at least one Opportunity.');          
            }
            Test.stopTest();
        }
    }   
}