objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_SAP_Status__c</fullName>
        <label>SAP Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Order Completed</fullName>
                </value>
                <value>
                    <fullName>Order Cancelled</fullName>
                </value>
                <value>
                    <fullName>Order Credit Block</fullName>
                </value>
                <value>
                    <fullName>Order on Hold</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Sap Validation Error</fullName>
                </value>
                <value>
                    <fullName>COB Complete</fullName>
                </value>
                <value>
                    <fullName>No Inventory Available</fullName>
                </value>
                <value>
                    <fullName>Ready for COB</fullName>
                </value>
                <value>
                    <fullName>Waiting for COB</fullName>
                </value>
                <value>
                    <fullName>Order Created</fullName>
                </value>
                <value>
                    <fullName>Rejected by Credit</fullName>
                </value>
                <value>
                    <fullName>Order Other Block</fullName>
                </value>
                <value>
                    <fullName>Order Shipped</fullName>
                </value>
                <value>
                    <fullName>FindLaw Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partially Completed</fullName>
                </value>
                <value>
                    <fullName>Credit Pass</fullName>
                </value>
                <value>
                    <fullName>Order Failed</fullName>
                </value>
                <value>
                    <fullName>Case Created</fullName>
                </value>
                <value>
                    <fullName>SAP Technical Review</fullName>
                </value>
                <value>
                    <fullName>In Credentialing</fullName>
                </value>
                <value>
                    <fullName>Held for Response</fullName>
                </value>
                <value>
                    <fullName>In Processing Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_SSD_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Acct SSD</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Orders (Sold To SSD)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__ProposalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated quote/proposal</description>
        <inlineHelpText>ID of the associated quote/proposal</inlineHelpText>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Quote_Value__c</fullName>
        <description>summary of the line items.</description>
        <label>APTS_Quote_Value</label>
        <summarizedField>Apttus_Proposal__Proposal_Line_Item__c.Apttus_QPConfig__NetPrice__c</summarizedField>
        <summaryFilterItems>
            <field>Apttus_Proposal__Proposal_Line_Item__c.Apttus_QPConfig__LineType__c</field>
            <operation>equals</operation>
            <value>Product/Service</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Apttus_Proposal__Proposal_Line_Item__c.APTS_is_Primary_in_Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Apttus_Proposal__Proposal_Line_Item__c.Apttus_Proposal__Proposal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>APTS_SSD_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Acct SSD</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Send_NACI_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Credit Increase Form</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
        <description>The proposal approval stage</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Check_Description__c</fullName>
        <label>Pending Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Credit_Check_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Check Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAP_Credit_Check_Status__c</fullName>
        <label>SAP Credit Check Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Logger__c.object
<CustomObject>
    <description>This object will store the real time transactions to and from Salesforce to MiddleTier(SAP). It captures the key data request elements and any success/error codes. Created as part of BigRule#1.

Note** Records need to be purged at regular intervals to free up storage</description>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Apttus_Config2__Order__c</referenceTo>
        <relationshipLabel>Integration Logger</relationshipLabel>
        <relationshipName>Integration_Logger</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Message__c</fullName>
        <description>Incoming or outgoing request element</description>
        <inlineHelpText>Incoming or outgoing request element</inlineHelpText>
        <label>Request Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <description>Name of the service or functionality</description>
        <inlineHelpText>Name of the service or functionality</inlineHelpText>
        <label>Service Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LCRM_GetOrderDetail</fullName>
                </value>
                <value>
                    <fullName>LCRM_GetOrder</fullName>
                </value>
                <value>
                    <fullName>LCRMSubscriptionServices</fullName>
                </value>
                <value>
                    <fullName>LCRM_CredentialInfoServices</fullName>
                </value>
                <value>
                    <fullName>LCRM_IPRestrictionServices</fullName>
                </value>
                <value>
                    <fullName>LCRM_DocumentService</fullName>
                </value>
                <value>
                    <fullName>OrderSubmission</fullName>
                </value>
                <value>
                    <fullName>OC Tax On Quote</fullName>
                </value>
                <value>
                    <fullName>Order Submission Status Postback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source System Detail</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Integration Logger</relationshipLabel>
        <relationshipName>Integration_Logger</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Logger</label>
    <nameField>
        <displayFormat>LOG-{000}</displayFormat>
        <label>Integration Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/KeyValueListStore__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueListStore</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <description>This object will hold the Order details which will be posted back from SAP. Created as part of Big Rule#1 project.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>LCRM_Credit_Exposure__c</fullName>
        <label>Credit Exposure</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LCRM_Credit_Limit_Amount__c</fullName>
        <label>Credit Limit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LCRM_SAP_Account_Number__c</fullName>
        <description>Created for R4</description>
        <label>SAP Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Segment__c</fullName>
        <description>Created for USL R4</description>
        <formula>LCRM_Market_Segment__c &amp;&apos;-&apos;&amp; LCRM_Sub_Segment__c &amp;&apos;-&apos;&amp; LCRM_Industry__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WebServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for external web service endpoints and credentials.</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The web service url as defined by the service provider</description>
        <inlineHelpText>The web service url as defined by the service provider</inlineHelpText>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Web Service Settings</label>
</CustomObject>

classes/CreditCheckCallout1.cls
/**
* @description Interface to send Credit Check to Dell Boomi
* @author  TCS
*/

public without sharing class CreditCheckCallout1{

 // @description This method sends the request and get the response from Dell Boomi for Credit Check

    public static String creditchekcallout(Id orderId){
        String serviceName = 'Order Credit Check';
        String ObjName = 'Order';
        String prevRequestMsg = '';
        String prevExcepMsg = '';
        String requestMsg = Datetime.now().format()+'\n';
        String responseMsg = Datetime.now().format()+'\n';
        Boolean isSuccess = true;
        String sapstatus;
        List<Apttus_Config2__Order__c> listOfProposals = new List<Apttus_Config2__Order__c>();
        List<Integration_Logger__c> intLogList;
        try{
            if(Schema.sObjectType.Integration_Logger__c.isAccessible()){
                intLogList=[Select Id,Request_Message__c, Exception_Message__c, Source_System_Detail__c, Order__c from Integration_Logger__c where Order__c =: orderId and Service_Name__c = :serviceName];
                if(intLogList!=null && intLogList.size()>0){
                    prevRequestMsg = intLogList[0].Request_Message__c + '\n\n';
                    prevExcepMsg = intLogList[0].Exception_Message__c + '\n\n';
                }
            }
            if(Schema.sObjectType.Apttus_Config2__Order__c.isAccessible()){ 
                listOfProposals = [select Apttus_QPConfig__ProposalId__r.id from Apttus_Config2__Order__c where Id  =: orderId];
            }
            List<Id> listOfProposalIds = new List<Id>();
            List<Id> listOfcasecreationIds = new List<Id>();
            Map<Id,String> failurereason = new Map<Id,String>();
            String amt;
            for(Apttus_Config2__Order__c o : listOfProposals){
                listOfProposalIds.add(o.Apttus_QPConfig__ProposalId__r.id);
            }
            system.debug(listOfProposalIds);
            List<id> accounts = new List<id>();
            for(Apttus_Proposal__Proposal__c p : [select id,APTS_SSD_Sold_To__c,Apttus_Proposal__Approval_Stage__c,APTS_Quote_Value__c,APTS_Send_NACI_Form__c,Credit_Check_Flag__c from Apttus_Proposal__Proposal__c where id in: listOfProposalIds]){
                 accounts.add(p.APTS_SSD_Sold_To__c);
                 amt = String.valueOf(p.APTS_Quote_Value__c);
                 system.debug('accountstest'+accounts);
            }
            List<Source_System_Detail__c> accountsDetails = new List<Source_System_Detail__c>();
            if(Schema.sObjectType.Source_System_Detail__c.isAccessible()){ 
                accountsDetails = [select id,currencyIsoCode,LCRM_Credit_Exposure__c,LCRM_Credit_Limit_Amount__c,Source_System_Account_Number__c,LCRM_SAP_Account_Number__c,LCRM_Segment__c from Source_System_Detail__c where id in : accounts ];
            }
            WebServiceSettings__c oWebServiceSettings = AppUtil.getWebServiceSettings('CreditCheck');  
            system.debug('oWebServiceSettings...'+oWebServiceSettings);
            CreditCheckSerializeandDeserializeReq smpReq = new CreditCheckSerializeandDeserializeReq(); 
            List<CreditCheckSerializeandDeserializeReq.CreditCheckRequest> smpReq2 = new List <CreditCheckSerializeandDeserializeReq.CreditCheckRequest>(); 
            CreditCheckSerializeandDeserializeReq.CreditCheckRequest creditcheck = new CreditCheckSerializeandDeserializeReq.CreditCheckRequest();
            creditcheck.account = new List<CreditCheckSerializeandDeserializeReq.Account>();
            List<CreditCheckSerializeandDeserializeReq.account> accList = new List<CreditCheckSerializeandDeserializeReq.account>();
            CreditCheckSerializeandDeserializeReq.CreditCheckInfo checkinfo= new CreditCheckSerializeandDeserializeReq.CreditCheckInfo();
            KeyValueListStore__c appId = KeyValueListStore__c.getValues('BOOMIProductId');
            checkinfo.currencyCode ='USD';
            checkinfo.amount = amt;
            smpReq.BOOMIHeader.applicationId  = appId.TextValue__c;
            smpReq.BOOMIHeader.timeStamp = String.valueof(System.now());
            checkinfo.retrievalPermission = 'true';
            for(Source_System_Detail__c ssd : accountsDetails){
                 CreditCheckSerializeandDeserializeReq.account acc1= new CreditCheckSerializeandDeserializeReq.account();
                 acc1.accountNumber = ssd.Source_System_Account_Number__c;
                 acc1.customerSegment='2000';
                 accList.add(acc1);
            }
            System.debug('accList!!!!!!!!!!'+ accList);
            creditcheck.account =accList;
            creditcheck.CreditCheckInfo =checkinfo;
            smpReq2.add(creditcheck);
            smpReq.CreditCheckRequest=smpReq2;
            string strBody = JSON.serialize(smpReq);
            system.debug('strBody...'+strBody);
            requestMsg = requestMsg + 'Request : ' + strBody;
            if(checkinfo.currencyCode == null || checkinfo.amount == null || checkinfo.retrievalPermission == null || smpReq.BOOMIHeader.applicationId == null || smpReq.BOOMIHeader.timeStamp == null || creditcheck.account[0].accountNumber == null || creditcheck.account[0].customerSegment == null){
                //IntegrationLogger.OCAddMessage('','', 'Order', 'Required Information missing', '','CreditCheck',false,orderId);  
                responseMsg = responseMsg  + 'Required Information missing : ';
                responseMsg = responseMsg  + '\ncheckinfo.currencyCode : ' + checkinfo.currencyCode;
                responseMsg = responseMsg  + '\ncheckinfo.amount : ' + checkinfo.amount;
                responseMsg = responseMsg  + '\ncheckinfo.retrievalPermission : ' + checkinfo.retrievalPermission;
                responseMsg = responseMsg  + '\nsmpReq.BOOMIHeader.applicationId : ' + smpReq.BOOMIHeader.applicationId;
                responseMsg = responseMsg  + '\nsmpReq.BOOMIHeader.timeStamp : ' + smpReq.BOOMIHeader.timeStamp;
                responseMsg = responseMsg  + '\ncreditcheck.account[0].accountNumber : ' + creditcheck.account[0].accountNumber;
                responseMsg = responseMsg  + '\ncreditcheck.account[0].customerSegment : ' + creditcheck.account[0].customerSegment;
                sapstatus = 'fail';
                isSuccess = false;
            }else{
                String requestBodyStringSafe = strBody.replaceAll('\"currency_x\":', '\"currency\":');
                requestBodyStringSafe = requestBodyStringSafe.replaceAll('\"address_x\":', '\"address\":');
                Http http;
                HttpRequest request;
                String grantType = 'client_credentials';
                String contentType= 'application/x-www-form-urlencoded';
                String accessToken;
                if(!Test.isRunningTest()){   
                    accessToken=DellBoomiTokenGeneration.getAuthToken();
                }
                else{
                    accessToken= 'DtOdJzb5sjdWBpqcvWyGTmGdRYTR';
                }
                if(accessToken!=null){
                    http = new Http();
                    request = new HttpRequest();
                }
                HttpResponse resp = new HttpResponse();
                request.setEndpoint(oWebServiceSettings.Endpoint__c);
                request.setMethod('POST');
                request.setTimeout(120000);    
                request.setHeader('Authorization','Bearer '+accessToken);
                request.setHeader('Content-Type', contentType);
                request.setHeader('grant_type', grantType);
                request.setBody(requestBodyStringSafe );
                if(!Test.isRunningTest()) {
                    resp = http.send(request);
                }
                else{
                    resp = CreditCheckMockHttpResponseGenerator.respond(request);
                }
                string strRes = resp.getBody();
                responseMsg = responseMsg + 'Reponse : ' + JSON.serialize(resp.getBody());
                system.debug('strRes..'+strRes);    
                system.debug('strRes..'+resp.getStatusCode());   
                CreditCheckSerializeandDeserializeRes.SetCCBySAPAccountResponse oCreditChk = (CreditCheckSerializeandDeserializeRes.SetCCBySAPAccountResponse) JSON.deserialize(strRes, CreditCheckSerializeandDeserializeRes.SetCCBySAPAccountResponse.class);
                system.debug('oCreditChk...'+oCreditChk);
                List<Source_System_Detail__c> updateSSDs = new List<Source_System_Detail__c>();
                List<Apttus_Proposal__Proposal__c> updateProposals = new List<Apttus_Proposal__Proposal__c>();
                List<id> propIds = new List<id>();
                List<Apttus_Config2__Order__c> updateOrder = new list<Apttus_Config2__Order__c>();
                for(Apttus_Proposal__Proposal__c p1 : [select id,SAP_Credit_Check_Status__c,Credit_Check_Description__c ,APTS_SSD_Sold_To__c,Apttus_Proposal__Approval_Stage__c,APTS_Send_NACI_Form__c,Credit_Check_Flag__c,APTS_SSD_Sold_To__r.LCRM_SAP_Account_Number__c from Apttus_Proposal__Proposal__c where id in: listOfProposalIds ]){
                    if(oCreditChk.CreditCheckResponse.creditStatus == 'Pass' || oCreditChk.CreditCheckResponse.creditStatus == 'Pending'){
                        p1.SAP_Credit_Check_Status__c = oCreditChk.CreditCheckResponse.creditStatus;
                    }
                    p1.Credit_Check_Description__c = oCreditChk.CreditCheckResponse.checkingDescription;
                    if(p1.SAP_Credit_Check_Status__c != null){  
                        if(p1.SAP_Credit_Check_Status__c.containsIgnoreCase('Credit limit')){
                            failurereason.put(p1.Id,'Insufficient Credit');
                        }else{
                            failurereason.put(p1.Id,'Credit Check');
                        }
                    }
                    updateProposals.add(p1);
                    propIds.add(p1.id);
                }
                if(updateProposals.size()>0 && Schema.sObjectType.Apttus_Proposal__Proposal__c.isUpdateable()){
                    system.debug('######@@@@@@!!!!!'); 
                    update updateProposals;
                }
                for(Apttus_Config2__Order__c o : [select id,Apttus_QPConfig__ProposalId__r.SAP_Credit_Check_Status__c,APTS_SAP_Status__c,Apttus_QPConfig__ProposalId__r.Id from Apttus_Config2__Order__c  where Apttus_QPConfig__ProposalId__c in : propIds AND Id  =: orderId]){
                    if(o.Apttus_QPConfig__ProposalId__r.SAP_Credit_Check_Status__c=='Pass'){
                        o.APTS_SAP_Status__c = 'Credit Pass';
                    }
                    else if(o.Apttus_QPConfig__ProposalId__r.SAP_Credit_Check_Status__c=='Pending'){
                        o.APTS_SAP_Status__c = 'Order Credit Block';
                        listOfcasecreationIds.add(o.Apttus_QPConfig__ProposalId__r.Id);
                    } 
                    updateOrder.add(o);
                    sapstatus = o.APTS_SAP_Status__c; 
                    system.debug('updateOrder.size()'+updateOrder.size());
                }
                if(updateOrder.size()>0 && Schema.sObjectType.Apttus_Config2__Order__c.isUpdateable()){
                    system.debug('######@@@@@@!!!!!updateOrder'+updateOrder); 
                    update updateOrder;
                    if(listOfcasecreationIds.size() > 0 && failurereason.size() > 0){
                        GenericCaseMgmtService casecall = new GenericCaseMgmtService();
                        List<Id> createdcases = casecall.createCreditCheckCase(listOfcasecreationIds,failurereason); 
                    }
                }    
            }
        }catch(Exception ex){
            isSuccess = false;
            responseMsg = responseMsg + 'Exception Message : '+ex.getMessage()+' \nException Trace : '+ex.getStackTraceString();
        }
        if(intLogList!=null && intLogList.size()>=1){
            IntegrationLogger.TaxupdateMessage(intLogList[0].Id, isSuccess, prevExcepMsg + responseMsg, prevRequestMsg + requestMsg); 
        }else{
            IntegrationLogger.OCAddMessage(responseMsg, orderId, ObjName, requestMsg, 'Outound', serviceName , isSuccess, orderId);    
        }
        return sapstatus;
    }           
}