objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsPrimaryLine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the line is the primary line for the product or option</description>
        <label>Is Primary Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ItemSequence__c</fullName>
        <description>The sequence of items belonging to a line</description>
        <label>Item Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineNumber__c</fullName>
        <description>The line number</description>
        <label>Line Number</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the price list  associated with the product or service</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PricingStatus__c</fullName>
        <description>The pricing status</description>
        <label>Pricing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PrimaryLineNumber__c</fullName>
        <description>Represents the unique number for each primary line item</description>
        <label>Primary Line Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mark_Removed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UE Mark Removed</label>
        <type>Checkbox</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_Config2__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the price list associated with the configuration</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_QPConfig__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated price list</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Quotes/Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UE_Proposal__c.object
<CustomObject>
    <fields>
        <fullName>AppId__c</fullName>
        <externalId>true</externalId>
        <label>AppId</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>InActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LineItemId__c</fullName>
        <label>LineItemId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteId__c</fullName>
        <label>QuoteId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cartId__c</fullName>
        <label>cartId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>UE Proposal</label>
    <nameField>
        <displayFormat>OP-{0000000}</displayFormat>
        <label>Orphan Proposal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UE Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DCPCreateProposalAPIHandler.cls
/* Class: DCPCreateProposalAPIHandler
* Purpose: Handler to handle the Rest API Service to create proposal records for three different sites like USL, Tax Professional, Canada
* Created: 05/24/2021
* Author: Avudaiappan A
*
* CHANGE HISTORY
* =============================================================================
* Date         Name             JIRA        Description
* 2021-05-24   Avudaiappan A     DCP-1982   Refactoring for PMD
*/
/********************************************************************************************************
*  @description  DCPCreateProposalAPIHandler - Handler class to perform business logic for CreateProposalAPI
********************************************************************************************************/
public with sharing class DCPCreateProposalAPIHandler{

 /********************************************************************************************************
*  @description  createLines - Method to create line item
*  @param staticVal - Bring all static values
*  @return String - jsonData 
*********************************************************************************************************/ 
public static string createLines(Map<String,String> staticVal){
        String jsonData;
        DCPCreateProposalAPI.statusCls sts = new DCPCreateProposalAPI.statusCls();
        List<Apttus_Config2__LineItem__c> lineItemList = new List<Apttus_Config2__LineItem__c>();
      Map<String,String> errorHandlerMap = new Map<String,String>{'objectName'=>'Product Configuration','webServiceName'=>'CreateProposalAPI','requestType'=>'Line Item Record Creation','reqMsg'=>'Exception Class Name: TRStoreCreateProposalAPI','module'=>'UEStore','recId'=>staticVal.get('cartId'),'supportEmail'=>staticVal.get('supportEmail'),'toSupport'=>'true'};
        List<Id> lineIds = new List<Id>();
        string cartId = staticVal.get('cartId');
        String query = 'Select id,Apttus_Config2__ProductId__c from Apttus_Config2__LineItem__c where (Apttus_Config2__ConfigurationId__c =:cartId and Mark_Removed__c = true)';
        lineItemList = Database.Query(query);
        if(!lineItemList.isEmpty()){
            for(Apttus_Config2__LineItem__c li: lineItemList){
                if(String.isBlank(li.Apttus_Config2__ProductId__c)){
                    lineIds.add(li.Id);
                }
            }
        }
        if(!lineIds.isEmpty()){
            jsonData = (String.isNotBlank(String.ValueOf(lineIds[0])))?NULL+','+staticVal.get('cartId')+','+String.ValueOf(lineIds[0])+','+NULL+','+NULL+','+NULL:NULL;
        }else{
            
        Apttus_Config2__LineItem__c lineSO = new Apttus_Config2__LineItem__c();
                lineSO.Apttus_Config2__ConfigurationId__c = cartId;
                lineSO.Apttus_Config2__PricingStatus__c = 'Pending';
                lineSO.Mark_Removed__c = true;
                lineSO.Apttus_Config2__LineNumber__c = Decimal.valueOf(staticVal.get('lineItemNumber'));
                lineSO.Apttus_Config2__PrimaryLineNumber__c=  lineSO.Apttus_Config2__LineNumber__c;
                lineSO.Apttus_Config2__ItemSequence__c =  lineSO.Apttus_Config2__LineNumber__c;
                lineSO.Apttus_Config2__IsPrimaryLine__c = true;
                try{
                    Database.insert(lineSO,true);
                    jsonData = (String.isNotBlank(lineSO.Id))?null+','+staticVal.get('cartId')+','+lineSO.Id+','+NULL+','+NULL+','+NULL:NULL;
                }catch(Exception e){
                   sts.status = TRStoreConstants.FAILURESTATUS;
                   sts.statusCode = TRStoreConstants.ERROR_CODE;
                   errorhandlerMap.put('expMsg',e.getMessage()+':'+e.getLineNumber()+':'+e.getStackTraceString());
                   TRStore_ErrorHandler.logException(errorHandlerMap);
                }
            }
                return jsonData;
    }
  
     /********************************************************************************************************
*  @description  checkForData - Method to check the data.
*  @param staticVal - Bring all static values
*  @param halfPointLimit - halfPointLimit for getting the custom data limit
*  @return String - jsonData 
*********************************************************************************************************/ 
    public Static String checkForData(Map<String,String> staticVal,Integer halfPointLimit){
        String jsonData;
        List<UE_Proposal__c> oQList = new List<UE_Proposal__c>([Select lineitemId__c,quoteId__c,cartId__c,InActive__c from UE_Proposal__c where appId__c =:staticVal.get('site') and InActive__c=false]);
        if(OQList!=null && OQList.size()>0){ 
            List<Apttus_Config2__ProductConfiguration__c> pcList = [Select Id, Apttus_QPConfig__Proposald__r.Apttus_QPConfig__PriceListId__c, name from Apttus_Config2__ProductConfiguration__c where Id =:OQList[0].CartId__c WITH SECURITY_ENFORCED];
            jsonData = OQList[0].QuoteId__c+','+OQList[0].CartId__c+','+OQList[0].lineItemId__c+','+pcList[0].Apttus_QPConfig__Proposald__r.Apttus_QPConfig__PriceListId__c+','+pcList[0].name;
            OQList[0].inactive__c = true;
            Update OQList[0];
        }else{
            jsonData = DCPCreateProposalAPIHandler.getJSONData(staticVal);
        }
        
       if((oQlist.size() <= halfPointLimit)&&((staticVal.get('site')).contains('UECAPR') || (staticVal.get('site')).contains('UEUSPR'))){
            String[] status = new String[]{'Holding','Preparing','Processing','Queued'};
            List<AsyncApexJob> asyncJobList = new  List<AsyncApexJob>([select Id,ApexClass.Name,Status from AsyncApexJob where CreatedDate = TODAY and ApexClass.Name = 'TRStore_CreateProposalApexQueue' and (status IN:Status) WITH SECURITY_ENFORCED]);
           if(asyncJobList.size()==0){
             System.enqueueJob(new TRStore_CreateProposalApexQueue(staticVal.get('site')));
            }
        }
        return jsonData;
    }

  private static string getJSONData(Map<String,String> staticVal){
        String jsonData;
        if((staticVal.get('site')).contains('UECAPR') || (staticVal.get('site')).contains('UEUSPR')){
            DCPCreateProposalAPI.createProposal(staticVal.get('priceListName'),1,staticVal.get('site'));
            jsonData = String.isNotBlank(DCPCreateProposalAPI.proposalIds)?DCPCreateProposalAPI.proposalIds:NULL;
        }else{
            jsonData = null;
        }
        return jsonData;
    }


   /********************************************************************************************************
*  @description  createLineItems - Method to create Lines
*  @param thresholdLimit - thresholdLimit for getting the custom data limit
*  @param cartSaveResultList - cartSaveResultList is the list of cart
*  @return DCPCreateProposalAPI.ProductConfigWrapper - Wrapper class 
*********************************************************************************************************/ 
    
    public static DCPCreateProposalAPI.ProductConfigWrapper createLineItems(Integer thresholdLimit, Database.SaveResult[] cartSaveResultList){
        List<Apttus_Config2__LineItem__c> lineItemList = new List<Apttus_Config2__LineItem__c>();
        DCPCreateProposalAPI.ProductConfigWrapper lineMap = new DCPCreateProposalAPI.ProductConfigWrapper();
        Set<Id> prodConfigIds = new Set<Id>();
        for(integer i=0; i<thresholdLimit;i++){
            Apttus_Config2__LineItem__c lineSO = new Apttus_Config2__LineItem__c();
            lineSO.Apttus_Config2__ConfigurationId__c = cartSaveResultList[i].getId();
            lineSO.Apttus_Config2__PricingStatus__c = 'Pending';
            lineSO.Mark_Removed__c = true;
            lineSO.Apttus_Config2__LineNumber__c = 1000;
            lineSO.Apttus_Config2__PrimaryLineNumber__c=  lineSO.Apttus_Config2__LineNumber__c;
            lineSO.Apttus_Config2__ItemSequence__c =  lineSO.Apttus_Config2__LineNumber__c;
            lineSO.Apttus_Config2__IsPrimaryLine__c = true;
            //lineSO.Apttus_Config2__PriceListId__c = (pli!=null)?pli.id:null;
            prodConfigIds.add(cartSaveResultList[i].getId());
            lineItemList.add(lineSO);
        }
        lineMap.lineItemList = lineItemList;
        lineMap.prodConfigIds = prodConfigIds;
        return lineMap;
    }
/********************************************************************************************************
*  @description  insertCart - Method to create Lines
*  @param prodConfigIds - prodConfigIds for getting the cartIds
*  @param thresholdLimit - thresholdLimit is the integer limit
*  @param params - list of params
*********************************************************************************************************/ 
 
    public static void insertCart(Set<Id> prodConfigIds,Integer thresholdLimit,Map<String,String> params){
        List<UE_Proposal__c> oQList = new List<UE_Proposal__c>();
        if(!prodConfigIds.isEmpty()){
            for (Apttus_Config2__lineItem__c li : [Select Id,Apttus_Config2__ConfigurationId__c,Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__c, Apttus_Config2__ConfigurationId__r.name, Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Apttus_QPConfig__PriceListId__c from Apttus_Config2__lineItem__c where Apttus_Config2__ConfigurationId__c IN:prodConfigIds ]) {
                if(thresholdLimit>=1){ 
                    OQlist.add(new UE_Proposal__c(LineItemId__c = li.id,CartId__c = li.Apttus_Config2__ConfigurationId__c,QuoteId__c=li.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__c,appId__c = params.get('site')));
                }else{
                    DCPCreateProposalAPI.proposalIds = li.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__c+','+li.Apttus_Config2__ConfigurationId__c+','+li.id+', '+li.Apttus_Config2__ConfigurationId__r.name+', '+li.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Apttus_QPConfig__PriceListId__c;
                }
            }
                system.debug(loggingLevel.INFO, 'Orphan Records:'+OQlist);
        }
        if(OQlist!=null && OQlist.size()>0){
             Map<String,String> errorHandlerMap = new Map<String,String>{'objectName'=>'Quote/Proposal','webServiceName'=>'CreateProposalAPI','requestType'=>'UEProposal Creation','reqMsg'=>'Exception Class Name: TRStoreCreateProposalAPI','module'=>'UEStore','recId'=>OQlist[0].id,'supportEmail'=>params.get('supportEmail'),'toSupport'=>'true'};

            try{
                Database.insert(OQlist,true);
                
            }catch(Exception e){
                 errorhandlerMap.put('expMsg',e.getMessage()+':'+e.getLineNumber()+':'+e.getStackTraceString());
        TRStore_ErrorHandler.logException(errorHandlerMap);
            }
        }
    }
/********************************************************************************************************
*  @description  deleteCart - Method to delete Lines
*  @param thresholdLimit - thresholdLimit for getting the cartIds
*  @param site - site represents current site
*  @param supportEmail - Email to be dropped for any issues
*********************************************************************************************************/ 
 
    public static void deleteCart(Integer thresholdLimit,String site,String supportEmail){
        //Delete the inactive records
        Map<String,String> errorHandlerMap = new Map<String,String>{'objectName'=>'Quote/Proposal','webServiceName'=>'CreateProposalAPI','requestType'=>'UEProposalRecord deletion','reqMsg'=>'Exception Class Name: TRStoreCreateProposalAPI','module'=>'UEStore','recId'=>'','supportEmail'=>supportEmail,'toSupport'=>'true'};
        if(thresholdLimit>=1){
            List<UE_Proposal__c> uEList = [Select id from UE_Proposal__c where InActive__c = true and appId__c =:site WITH SECURITY_ENFORCED Limit 200];
            system.debug(loggingLevel.INFO, 'Orphan Records:'+uElist);
            if(uEList!=null && uEList.size()>0){
                try{
                    Database.delete(uEList,true);
                }catch(Exception e){
                    errorhandlerMap.put('expMsg',e.getMessage()+':'+e.getLineNumber()+':'+e.getStackTraceString());
                    TRStore_ErrorHandler.logException(errorHandlerMap);
                }
            }
        }
    }
}