objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>APTS_AccountMirror_Picklist__c</fullName>
        <label>Account Mirror Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation National Accounts</fullName>
                </value>
                <value>
                    <fullName>Corporation Strategic</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Law School Library</fullName>
                </value>
                <value>
                    <fullName>Legal Education Group</fullName>
                </value>
                <value>
                    <fullName>LLF Enterprise</fullName>
                </value>
                <value>
                    <fullName>LLF Strategic</fullName>
                </value>
                <value>
                    <fullName>MLF 30-79</fullName>
                </value>
                <value>
                    <fullName>MLF 80+</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SLF 11-20</fullName>
                </value>
                <value>
                    <fullName>SLF 21-29</fullName>
                </value>
                <value>
                    <fullName>SLF 2-3</fullName>
                </value>
                <value>
                    <fullName>SLF 4-6</fullName>
                </value>
                <value>
                    <fullName>SLF 7-10</fullName>
                </value>
                <value>
                    <fullName>Solo Law Firm</fullName>
                </value>
                <value>
                    <fullName>State Government</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
                <value>
                    <fullName>CORPORAT</fullName>
                </value>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>Law Firm</fullName>
                </value>
                <value>
                    <fullName>Corp Counsel</fullName>
                </value>
                <value>
                    <fullName>Corp Counsel Existing</fullName>
                </value>
                <value>
                    <fullName>Corp Investigative</fullName>
                </value>
                <value>
                    <fullName>Corp Investigative Financial</fullName>
                </value>
                <value>
                    <fullName>Corp National Investigative</fullName>
                </value>
                <value>
                    <fullName>MLF 30-179</fullName>
                </value>
                <value>
                    <fullName>AmLaw100</fullName>
                </value>
                <value>
                    <fullName>LLF 180+</fullName>
                </value>
                <value>
                    <fullName>State Gov Investigative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Clauses_Selected__c</fullName>
        <label>Clauses Selected</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>APTS_AccountMirror_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Auto-Renew for All</fullName>
                </value>
                <value>
                    <fullName>Auto-Renew for Named Products</fullName>
                </value>
                <value>
                    <fullName>Auto-Renew for All and Split Venue</fullName>
                </value>
                <value>
                    <fullName>Auto-Renew for Named Products and Split Venue</fullName>
                </value>
                <value>
                    <fullName>Non Availability of Funds - Online</fullName>
                </value>
                <value>
                    <fullName>NY Choice of Law and Venue</fullName>
                </value>
                <value>
                    <fullName>SLF-Dissolution Pay 12 Month Charges</fullName>
                </value>
                <value>
                    <fullName>SLF-Material Change up or down and reorg</fullName>
                </value>
                <value>
                    <fullName>SLF-Merger with Another West Subscriber</fullName>
                </value>
                <value>
                    <fullName>Solo Becomes a Judge</fullName>
                </value>
                <value>
                    <fullName>Solo Joins Another West Subscriber</fullName>
                </value>
                <value>
                    <fullName>Solo Medical</fullName>
                </value>
                <value>
                    <fullName>Solo Public Office</fullName>
                </value>
                <value>
                    <fullName>Solo Retirement</fullName>
                </value>
                <value>
                    <fullName>Split Venue</fullName>
                </value>
                <value>
                    <fullName>Variable One-Time Out</fullName>
                </value>
                <value>
                    <fullName>Variable One-Time Out - Product specific</fullName>
                </value>
                <value>
                    <fullName>48 or 60 Month Min Term Addendum - RENEWAL Sales</fullName>
                </value>
                <value>
                    <fullName>90 Day Chargeable Software POC</fullName>
                </value>
                <value>
                    <fullName>90 Day Chgble Software POC 1 Time Out after 12 Months</fullName>
                </value>
                <value>
                    <fullName>90 Day Non-Chargeable Software POC</fullName>
                </value>
                <value>
                    <fullName>Auto Renew to Lapse</fullName>
                </value>
                <value>
                    <fullName>Auto Renew to MTM WCMP/APP/LSP</fullName>
                </value>
                <value>
                    <fullName>Auto-Renewal for all and split venue</fullName>
                </value>
                <value>
                    <fullName>Corp Acquisition by another entity</fullName>
                </value>
                <value>
                    <fullName>Corp WL Monitored Usage</fullName>
                </value>
                <value>
                    <fullName>Correctional Facility Certifications</fullName>
                </value>
                <value>
                    <fullName>Government Tribal Choice of Law and Venue</fullName>
                </value>
                <value>
                    <fullName>Non Availabiltiy of Funds WCMP/APP/LSP</fullName>
                </value>
                <value>
                    <fullName>Proflex Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Selected_Clauses__c</fullName>
        <label>Selected Clauses</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>APTS_Proposal_Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add&apos;l Addendum #301 - Solo Retirement</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #303 - Solo Military Service</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #305 - Solo Becomes a Judge</fullName>
                </value>
                <value>
                    <fullName>Non Avail Funds - Online</fullName>
                </value>
                <value>
                    <fullName>Non Avail Funds - Print</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #711 - Split Venue</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #402 - SLF Material Change Up or Down Re-org</fullName>
                </value>
                <value>
                    <fullName>Autorenew to MTM - Print</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #503 NY Choice of Law and Venue Corp Only</fullName>
                </value>
                <value>
                    <fullName>Autorenew Out and Split Ven</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #501 - Corp Acquisition by another entity</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #401 - SLF - Dissolution Law Firm 12 month charges</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #601- Government Tribal Choice of Law and Venue</fullName>
                </value>
                <value>
                    <fullName>SLF – Merger with Another West Subscriber</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement – No inmate access</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement – Indirect Inmate access</fullName>
                </value>
                <value>
                    <fullName>Law Enforcement – Direct Inmate access</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #302 - Solo Medical</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Addendum #306 - Solo Public Office</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-Return-30</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-AcctMSA</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-Autolapse-out</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-SoloRetire</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-LimitLiab-Gen</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-LimitLiabDataSec</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-Pymt-Term-45</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-Pymt-Term-60</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-PH1</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-PH2</fullName>
                </value>
                <value>
                    <fullName>Tax-LL-PH3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/APTS_SegmentSelectorController.cls
public with sharing class APTS_SegmentSelectorController {
    
    public Apttus_Proposal__Proposal__c proposal {get;set;}
    public List<String> selectedValues {get;set;}
    public String applicableClauses;
    List<String> clausesList = new List<String>();
    //public Apttus_Config2__ProductConfiguration__c cart {get;set;}
    //public static String test = 'Test';
    
    public APTS_SegmentSelectorController() {
        //Id cartId = ApexPages.currentPage().getParameters().get('id');
        //cart = [SELECT APTS_AccountMirror_Picklist__c, APTS_Clauses_Selected__c, Apttus_QPConfig__Proposald__r.APTS_Selected_Clauses__c, 
                //Apttus_QPConfig__Proposald__r.Apttus_Proposal__Account__r.FrozenMarketSegment__c 
                //FROM Apttus_Config2__ProductConfiguration__c WHERE Id =: cartId];
                
        proposal = [SELECT Id, APTS_Selected_Clauses__c, APTS_Approval_Segment__c,Customer_Group__c,APTS_Proposal_Business_Unit__c
                    FROM Apttus_Proposal__Proposal__c 
                    WHERE Id =: ApexPages.currentPage().getParameters().get('retId')];
        
        List<APTS_Clause_Mapping_Per_Segment__c> clauseMappingList = new List<APTS_Clause_Mapping_Per_Segment__c>([SELECT APTS_Approval_Segment__c, 
                                                                                                                    APTS_Applicable_Clauses__c 
                                                                                                                    FROM APTS_Clause_Mapping_Per_Segment__c]);
        System.debug('clauseMappingList ++' + clauseMappingList);
        
        for(APTS_Clause_Mapping_Per_Segment__c mapping : clauseMappingList){
            System.debug('proposal.APTS_Approval_Segment__c ++' + proposal.APTS_Approval_Segment__c);
            if(mapping.APTS_Approval_Segment__c == proposal.APTS_Approval_Segment__c  && proposal.APTS_Proposal_Business_Unit__c != 'Canada'  && proposal.APTS_Proposal_Business_Unit__c != 'Tax Professional'){
                applicableClauses = mapping.APTS_Applicable_Clauses__c;
            }
            //DOC-3980- Added by Nandha : Starts here
            if(proposal.APTS_Proposal_Business_Unit__c == 'Canada'){
                applicableClauses = System.Label.CANSELCTEDCLAUSE1;
                //Start:Jinal Bhatt: DOC-7415 - Added one more value which should be availabel for sales rep.
                applicableClauses += System.Label.CANSELCTEDCLAUSE3 +';';
                //End DOC-7415
            }
            if(proposal.APTS_Proposal_Business_Unit__c == 'Canada' && (proposal.Customer_Group__c == 'ACADEMIC' || proposal.Customer_Group__c == 'GOVERNMENT')){
                applicableClauses = applicableClauses + System.Label.CANSELCTEDCLAUSE2;
            }
            //DOC-3980- Added by Nandha : Ends here
            //DOC-9810- Added by Nandha : Starts here
            if(proposal.APTS_Proposal_Business_Unit__c == 'Tax Professional'){
                applicableClauses = System.Label.TAXSELCTEDCLAUSE;
            }
            //DOC-9810- Added by Nandha : Ends here
        }
        System.debug('applicableClauses ++' + applicableClauses);
        
        if(applicableClauses != NULL) clausesList = applicableClauses.split(';');
        
    }
    
    public List<SelectOption> getItems() {
        List<selectOption> options = new List<selectOption>();
        
        for (String clause :  clausesList) { 
            options.add(new selectOption(clause, clause)); //for all records found - add them to the picklist options
        }
        return options;
    }

    public void doSave(){
        String finalValues = String.join(selectedValues, ';');
        proposal.APTS_Selected_Clauses__c = finalValues;
        update proposal;
        
    }
    public void doCancel(){

    }

    
}