objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU_Segment__c</fullName>
        <description>Created as part of DPS-2200, should hold Account&apos;s BU Segment value</description>
        <formula>TEXT(Account.Bu_Segment__c)</formula>
        <label>Frozen Market Current Year Segment L1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for Contact</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LJUU</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>WEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/KeyValueListStore__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueListStore</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BU_Segment__c</fullName>
        <description>Created as part of data segmentation for LOTUS, should hold different Business Segments. DPS-1711</description>
        <inlineHelpText>Customer information is frozen once a year - a Sales User can set this upon Account Creation, but otherwise this is a view-only field</inlineHelpText>
        <label>Frozen Market Current Year Segment L1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_GLI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field created for LCRM project</description>
        <label>Is GLI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org of Lead</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>WEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>GLI</fullName>
        <active>true</active>
        <businessProcess>Legal</businessProcess>
        <description>Record type used for US legal</description>
        <label>GLI</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LTS_Disable_Application_Automation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to disable the triggers, validation, workflows etc.</description>
    <fields>
        <fullName>LTS_Disable_Process_Builders__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the process builders</description>
        <inlineHelpText>If checked, will disable all process builder wherever this flag is used.</inlineHelpText>
        <label>Disable Process Builders</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTS_Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the triggers</description>
        <inlineHelpText>If checked, will disable all triggers wherever this flag is used.</inlineHelpText>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTS_Disable_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the validation Rules</description>
        <inlineHelpText>If checked, will disable all validation rules wherever this flag is used.</inlineHelpText>
        <label>Disable Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTS_Disable_Workflow_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the Workflow Rules</description>
        <inlineHelpText>If checked, will disable all workflow rule wherever this flag is used.</inlineHelpText>
        <label>Disable Workflow Rules</label>
        <type>Checkbox</type>
    </fields>
    <label>Disable Application Automation</label>
</CustomObject>

objects/Static_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>We will store key pair static values under this custom settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Static Values</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for User</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/BU_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Professional Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <masterLabel>BU Segment</masterLabel>
</GlobalValueSet>

classes/DCPConverLead_Test.cls
/* Class: DCPCovertLead_Test
* Purpose: Test coverage for DCPConvertLead.cls, DCPConvertLeadUtility.cls,
*            DCPConvertLeadHandler.cls,
*           DCPConstants.cls
* Created: 06/14/2021
* Author: Kavya Ganagaraju
* 
* CHANGE HISTORY
* =============================================================================
* Date         Name             JIRA        Description
* 06/14/2021   Kavya G          DCP-1693    Created
* =============================================================================
*/

@isTest(seeAllData=false)
public class DCPConverLead_Test {
    
    @TestSetup
    static void convertLeadTestDataSetup(){
        
        // Create New Lead
        Lead newLead = new Lead();

        newLead.FirstName          ='Lead';
        newLead.LastName           ='Test';
        newLead.Email              ='LeadTest123@test.com';        
        newLead.IsConverted        =false;
        newLead.Company            ='CL Test LLC';
        newLead.Billing_Street__c  = 'Test Lead St';
        newLead.Billing_City__c    = 'Eagan';
        newLead.Billing_State__c   = 'MN';
        newLead.Billing_Country__c = 'US';
        newLead.PostalCode         = '55123';
        //newLead.Is_GLI__c          =true;

        insert newLead;

        //Create Cart
        Apttus_Config2__ProductConfiguration__c cart =
                    new Apttus_Config2__ProductConfiguration__c();
         cart = DCPTestDataFactory.createCart();
         insert cart;

         //Create lineItem
         Apttus_Config2__LineItem__c lineItem =
                    new Apttus_Config2__LineItem__c();
        lineItem = DCPTestDataFactory.createLineItem();
        lineItem.Apttus_Config2__ConfigurationId__c = cart.id;
        insert lineItem;

        //update lead with Cart Id
        newLead.Product_Configuration__c = cart.id;
        update newLead;
        
        //Insert Static values Custom settings
        LIST<Static_Values__c> staticCSList = new LIST<Static_Values__c>();
       
        Static_Values__c sv1 = new Static_Values__c(name='LeadSupportEmail', 
                            value__c= 'testLeadsupport@test.com');
        Static_Values__c sv2 = new Static_Values__c(name='SSDRecordType', 
                            value__c= 'LOTUS Source Systems');
        Static_Values__c sv3 = new Static_Values__c(name='PriceBookName', 
                            value__c= 'GLI Price Book - US Legal/LMS');
        Static_Values__c sv4 = new Static_Values__c(name='OrderProcessSupportEmail', 
                                                value__c= 'orderProcesssupport@test.com');
        
        staticCSList.add(sv1);
        staticCSList.add(sv2);
        staticCSList.add(sv3);
        staticCSList.add(sv4);
        insert staticCSList;

        LTS_Disable_Application_Automation__c ltstemp = new LTS_Disable_Application_Automation__c();
        ltstemp.LTS_Disable_Process_Builders__c = true;
        ltstemp.LTS_Disable_Triggers__c = true;
        ltstemp.LTS_Disable_Validation_Rules__c = true;
        ltstemp.LTS_Disable_Workflow_Rules__c = true; 
        ltstemp.Name = 'temp';
        ltstemp.SetupOwnerId = userinfo.getuserid();
        insert ltstemp;
    
         Profile p = [SELECT Id FROM Profile WHERE Name = 'ANZ Users' LIMIT 1];
        User u;
        u  = [Select ID, Sales_Org__c FROM User where Sales_Org__c = 'LRA'AND Profile.id =:p.id limit 1];
        LIST<KeyValueListStore__c> keyValueList = new LIST<KeyValueListStore__c>();
        KeyValueListStore__c kv = new KeyValueListStore__c(TextValue__c=p.id, name='ANZUsersProfileId' );
         KeyValueListStore__c kv1 = new KeyValueListStore__c(TextValue__c='Content,Functionality', name='ReasonWithCompetitor');
        keyValueList.add(kv);
        keyValueList.add(kv1);
        insert keyValueList;

       /* KeyValueListStore__c keyvaluestore=new  KeyValueListStore__c();
        keyvaluestore.Name='ANZUsersProfileId';
        keyvaluestore.TextValue__c='00e30000001ZUki';
        insert keyvaluestore;
     */
        
    } 
    
    @istest static void convertLeadTest1() {

        Lead l = [SELECT Id, email, firstname,lastName, company, isconverted,Billing_Street__c, Billing_City__c,
        Billing_State__c,Billing_Country__c, postalcode FROM Lead Limit 1];
        
        Apttus_Config2__ProductConfiguration__c cart = [SELECT Id  
                            FROM  Apttus_Config2__ProductConfiguration__c
                            LIMIT 1];
        DmlException dmlEx;
    
        Test.startTest();

        try{
            DCPConvertLeadHelperTwo.ConvertLeadWrapperDetails clwdt = new DCPConvertLeadHelperTwo.ConvertLeadWrapperDetails();

            clwdt.leadId = l.id;
            clwdt.cartId = cart.id;

            DCPConvertLead cLead = new DCPConvertLead();
            cLead.convertLeadInitiation(clwdt);  

        }
        catch(dmlException d){
            dmlEx = d;
        }
        
        Test.stopTest();

        system.assertEquals(null, dmlEx, 'Lead Conversion is Unsuccessful');

        
    }

    @istest static void convertLeadTest2() {

        Lead l = [SELECT Id, email, firstname,lastName, company, isconverted,Billing_Street__c, Billing_City__c,
        Billing_State__c,Billing_Country__c, postalcode FROM Lead Limit 1];

        Apttus_Config2__ProductConfiguration__c cart = [SELECT Id  
                            FROM  Apttus_Config2__ProductConfiguration__c
                            LIMIT 1];

        Account a = new Account();

        a.Name = l.company;
        a.Bu_Segment__C = 'Professional Legal';
        a.BillingStreet = l.Billing_Street__c;
        a.BillingCountry = l.Billing_Country__c;
        a.BillingCity = l.Billing_city__c;
        a.BillingState = l.Billing_State__C;
        a.Customer_Group__c = 'CORPORATION';
        a.Customer_class_c__c = 'LARGE';

        insert a;

        contact c = new contact();

        c.FirstName = l.firstname;
        c.lastname = l.LastName;
        c.email = l.email;
        c.AccountId = a.id;

        insert c;

        DmlException dmlEx;

        test.startTest();
       try{
            DCPConvertLeadHelperTwo.ConvertLeadWrapperDetails clwdt = new DCPConvertLeadHelperTwo.ConvertLeadWrapperDetails();

            clwdt.leadId = l.id;
            clwdt.cartId = cart.id;

            DCPConvertLead cLead = new DCPConvertLead();
            cLead.convertLeadInitiation(clwdt);  

        }
        catch(dmlException d){
            dmlEx = d;
        }
        
        Test.stopTest();

        system.assertEquals(null, dmlEx, 'Lead Conversion is Unsuccessful');

        
    }

    @istest static void convertLeadTest3() {


        test.startTest();
       try{
        DCPConvertLeadHelperTwo.ConvertLeadWrapperDetails clwdt = new DCPConvertLeadHelperTwo.ConvertLeadWrapperDetails();

            DCPConvertLead cLead = new DCPConvertLead();
            cLead.convertLeadInitiation(clwdt);  

        }
        catch(Exception e){
            system.assert(e.getMessage().contains('Errors While Conversion of Lead convertion failed cartId or leadId is null'),true);
        }
        
        Test.stopTest();
        
    }

    @istest static void  beforeconvertLeadTest(){
        //checks to see if an exception is thrown if there is no Contact and account created.

        Lead l = [SELECT Id, email, firstname,lastName, company, isconverted,Billing_Street__c, Billing_City__c,
        Billing_State__c,Billing_Country__c, postalcode FROM Lead Limit 1];

        Apttus_Config2__ProductConfiguration__c cart;
        cart = [SELECT Id  
                            FROM  Apttus_Config2__ProductConfiguration__c
                            LIMIT 1];

        Account a = new Account();

        a.Name = l.company;
        a.Bu_Segment__C = 'Professional Legal';
        a.BillingStreet = l.Billing_Street__c;
        a.BillingCountry = l.Billing_Country__c;
        a.BillingCity = l.Billing_city__c;
        a.BillingState = l.Billing_State__C;
        a.Customer_Group__c = 'CORPORATION';
        a.Customer_class_c__c = 'LARGE';

        insert a;

        contact c = new contact();

        c.FirstName = l.firstname;
        c.lastname = l.LastName;
        c.email = l.email;
        c.AccountId = a.id;

        insert c;
        try{
            list<Lead> unConvertedLeads = new List<Lead>();
            unConvertedLeads.add(l);

            DCPConvertLead.convertLeadWrapper cwl = new DCPConvertLead.ConvertLeadWrapper();

            cwl.conIdw = c.Id;
            cwl.leadsw = unConvertedLeads;

            DCPConvertLead cLead = new DCPConvertLead();

            cLead.convertLeadDataCheck(cwl);
        }catch(Exception e){
            system.assert(e.getMessage().contains('convertion failed as your email or account is incorrect'),true);
        }

        

    }

    @istest static void  createNewAccountTest(){
        //checks to see if an exception is thrown if there is no Contact and account created.

        Lead l = [SELECT Id, email, firstname,lastName, company, isconverted,Billing_Street__c, Billing_City__c,
        Billing_State__c,Billing_Country__c, postalcode FROM Lead Limit 1];

        Map<String,String> existingContToAccMap = 
                            new Map<String,String>();
        DCPConvertLeadHelper cLeadHelper = new DCPConvertLeadHelper();
        try{
            cLeadHelper.createNewAccount(l, existingContToAccMap);
        }catch(Exception e){
            system.assert(e.getMessage().contains('Errors While Creation of Account / SSD'),true);
        }

    }


}