objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>APTS_Contract_Term_Default__c</fullName>
        <formula>IF(
(
(APTS_Media_High_Level_Code__c ==&apos;13&apos; &amp;&amp; APTS_Media_Lower_Level_Code__c == NULL)
|| (APTS_Media_High_Level_Code__c ==&apos;13&apos; &amp;&amp; APTS_Media_Lower_Level_Code__c == &quot;SS&quot;)
|| (APTS_Media_High_Level_Code__c ==&apos;26&apos; &amp;&amp; APTS_Media_Lower_Level_Code__c == NULL)
) &amp;&amp; TEXT( Apttus_Config2__ChargeType__c ) == &quot;Subscription Fee&quot;
,
&apos;&apos;,
IF(APTS_Media_High_Level_Code__c ==&apos;13&apos; &amp;&amp; NOT(TEXT(Apttus_Config2__ProductId__r.Family) == &apos;CASELINE&apos;) &amp;&amp;
(APTS_Media_Lower_Level_Code__c == &apos;PS&apos; ||APTS_Media_Lower_Level_Code__c == &apos;ST&apos; || APTS_Media_Lower_Level_Code__c == &apos;Q6&apos;)
,
&apos;1 Year&apos;,
IF(APTS_Proposal_Business_Unit__c == &apos;Canada&apos; &amp;&amp; NOT(TEXT(Apttus_Config2__ProductId__r.Family) == &apos;ACRITAS&apos;) &amp;&amp; NOT(TEXT(Apttus_Config2__ProductId__r.Family) == &apos;CASELINE&apos;),&apos;1 Year&apos;,
IF(APTS_Proposal_Business_Unit__c == &apos;SCS&apos; ,&apos;3 Years&apos;,
IF(APTS_Proposal_Business_Unit__c == &apos;FindLaw&apos;,&apos;1 Year&apos;,
IF(
(Apttus_Config2__ProductId__r.APTS_Cat_L5__c== &apos;L5_T736510_FP&apos; ||
Apttus_Config2__ProductId__r.APTS_Cat_L5__c== &apos;L5_T770021_FP&apos; ||
Apttus_Config2__ProductId__r.APTS_Cat_L5__c== &apos;L5_T736500_FP&apos; || Apttus_Config2__ProductId__r.APTS_Cat_L4__c== &apos;L4_T77135_FP&apos; )
,&apos;1 Year&apos;,&apos;3 Years&apos;)))
)))</formula>
        <label>Contract Term Default</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Contract_Term__c</fullName>
        <label>Contract Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 Year</fullName>
                </value>
                <value>
                    <fullName>2 Years</fullName>
                </value>
                <value>
                    <fullName>3 Years</fullName>
                </value>
                <value>
                    <fullName>4 Years</fullName>
                </value>
                <value>
                    <fullName>5 Years</fullName>
                </value>
                <value>
                    <fullName>1 Month</fullName>
                </value>
                <value>
                    <fullName>2 Months</fullName>
                </value>
                <value>
                    <fullName>3 Months</fullName>
                </value>
                <value>
                    <fullName>4 Months</fullName>
                </value>
                <value>
                    <fullName>5 Months</fullName>
                </value>
                <value>
                    <fullName>6 Months</fullName>
                </value>
                <value>
                    <fullName>7 Months</fullName>
                </value>
                <value>
                    <fullName>8 Months</fullName>
                </value>
                <value>
                    <fullName>9 Months</fullName>
                </value>
                <value>
                    <fullName>10 Months</fullName>
                </value>
                <value>
                    <fullName>11 Months</fullName>
                </value>
                <value>
                    <fullName>Short Term Trial</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>n/a</fullName>
                </value>
                <value>
                    <fullName>10 Years</fullName>
                    <isActive>false</isActive>
                    <label>10 Years</label>
                </value>
                <value>
                    <fullName>Short Term</fullName>
                    <isActive>false</isActive>
                    <label>Short Term</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Proposal_Business_Unit__c</fullName>
        <formula>TEXT(Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.APTS_Proposal_Business_Unit__c )</formula>
        <label>Proposal Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Years_2_Plus_Adjustment__c</fullName>
        <label>YoY 2+ %</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Years_2_Plus_Default__c</fullName>
        <formula>IF(OR(APTS_Cat_L2__c== $Label.APTS_HighQ_Product_Family,
AND(OR(APTS_Proposal_Business_Unit__c == &apos;SCS&apos; || APTS_Proposal_Business_Unit__c == &apos;Canada&apos;),
OR(TEXT(Apttus_Config2__ProductId__r.Family) == &apos;ACRITAS&apos; || (TEXT(Apttus_Config2__ProductId__r.Family) == &apos;CASELINE&apos; &amp;&amp; APTS_Media_High_Level_Code__c ==&apos;13&apos;)))), 3,
IF(APTS_Proposal_Business_Unit__c  == &apos;Corp OneOTC US&apos; || APTS_Proposal_Business_Unit__c  == &apos;Corp OneOTC UK&apos;,4,
IF(APTS_Proposal_Business_Unit__c == &apos;Tax Professional&apos;,5,
IF((APTS_Proposal_Business_Unit__c == $Label.SALESORGCAN &amp;&amp; (APTS_Product_Pricing_Model__c== $Label.BGBPRICINGMODEL || APTS_Product_Pricing_Model__c== $Label.BANDED || APTS_Product_Pricing_Model__c== $Label.PERSEAT  || APTS_Product_Code__c ==&apos;41972767&apos; )),2,
IF(APTS_Proposal_Business_Unit__c == &apos;SCS&apos; &amp;&amp; contains($Label.APTS_SCS_Proflex,APTS_Product_Code__c),5,
IF((APTS_Media_High_Level_Code__c !=&apos;13&apos; &amp;&amp; APTS_Media_Lower_Level_Code__c != NULL) || (APTS_Media_High_Level_Code__c !=&apos;13&apos; &amp;&amp; APTS_Media_Lower_Level_Code__c != &quot;SS&quot;) || (APTS_Media_High_Level_Code__c !=&apos;26&apos; &amp;&amp; APTS_Media_Lower_Level_Code__c != NULL), 
IF((APTS_Media_High_Level_Code__c ==&apos;13&apos; &amp;&amp; (APTS_Media_Lower_Level_Code__c == &apos;PS&apos; || APTS_Media_Lower_Level_Code__c == &apos;ST&apos; || APTS_Media_Lower_Level_Code__c == &apos;Q6&apos;)) || 
(APTS_Media_High_Level_Code__c ==&apos;06&apos; &amp;&amp; (APTS_Media_Lower_Level_Code__c == &apos;51&apos; || APTS_Media_Lower_Level_Code__c == &apos;AR&apos;)),0,
IF(((APTS_Proposal_Business_Unit__c  == &apos;SCS&apos; || APTS_Proposal_Business_Unit__c  == $Label.SALESORGCAN)&amp;&amp; 
((APTS_Media_High_Level_Code__c ==&apos;13&apos;) &amp;&amp; (APTS_Media_Lower_Level_Code__c == &apos;NT&apos; || APTS_Media_Lower_Level_Code__c == &apos;NW&apos; || APTS_Media_Lower_Level_Code__c == &apos;NX&apos;))&amp;&amp; APTS_Item_Category_Group__c == &apos;ZWG3&apos;),4,5)),
5))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YoY 2+ Default</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Yr_1_Renewal_Adjustment__c</fullName>
        <label>YoY 1 Renewal %</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Yr_1_Renewal_Default__c</fullName>
        <formula>IF(OR(APTS_Cat_L2__c== $Label.APTS_HighQ_Product_Family,AND(OR(APTS_Proposal_Business_Unit__c == &apos;SCS&apos; || APTS_Proposal_Business_Unit__c == &apos;Canada&apos;),OR(TEXT(Apttus_Config2__ProductId__r.Family) == &apos;ACRITAS&apos;,TEXT(Apttus_Config2__ProductId__r.Family) == &apos;CASELINE&apos;,TEXT(Apttus_Config2__ProductId__r.Family) == &apos;PONDERA&apos;),ISPICKVAL( Apttus_Config2__LineStatus__c , &apos;Renewed&apos;))),3,IF(AND(OR(APTS_Proposal_Business_Unit__c = &apos;Canada&apos;,APTS_Approval_Segment__c = &apos;AEM Risk&apos;), ISPICKVAL( Apttus_Config2__LineStatus__c , &apos;Renewed&apos;)), 5, IF( AND(OR(APTS_Proposal_Business_Unit__c = &apos;Corp OneOTC US&apos;,APTS_Proposal_Business_Unit__c = &apos;Corp OneOTC UK&apos;), ISPICKVAL( Apttus_Config2__LineStatus__c , &apos;Renewed&apos;)) , 4, IF( AND(OR(APTS_Proposal_Business_Unit__c = &apos;Corp OneOTC US&apos;,APTS_Proposal_Business_Unit__c = &apos;Corp OneOTC UK&apos;), ISPICKVAL( Apttus_Config2__LineStatus__c , &apos;New&apos;)),null,CASE(APTS_Media_Lower_Level_Code__c,
&quot;51&quot;,0,
&quot;AR&quot;,0,
&quot;ST&quot;,0,
&quot;PS&quot;,IF(APTS_Media_High_Level_Code__c=&quot;13&quot;,0,7),
&quot;Q6&quot;,IF(APTS_Media_High_Level_Code__c=&quot;13&quot;,0,7),
7)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YoY 1 Renewal Default</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceType__c</fullName>
        <description>The price type</description>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
                <value>
                    <fullName>Included Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/APTS_CORP_PricingCallbackMethods.cls
/**
* Pricing callback used for Corporate Business Unit to get price from SAP 
* @author Keerthana Thallam
* @version 7/2/2019 as part of DOC-1043
*/

/**
* CHANGE HISTORY
* =============================================================================
* Date         Name                    Description
*/
public with sharing class APTS_CORP_PricingCallbackMethods{
    //Start: Added by Kruti Shah (DOC-2007-2008,1577)
    public static void defaultContractTermYOYRenewalType(List<Apttus_Config2__LineItem__c> bundleItems, Map<Decimal, List<Apttus_Config2__LineItem__c>> lineNumberToOptionsMap){
        System.debug('Artem bundleItems' + lineNumberToOptionsMap.size());
        //For all the bundle level ones
           for(Apttus_Config2__LineItem__c lineItem : bundleItems){
            if(lineItem.APTS_Proposal_Business_Unit__c == 'Corp OneOTC US' || lineItem.APTS_Proposal_Business_Unit__c == 'Corp OneOTC UK'){
                if(lineItem.APTS_Contract_Term__c == null && lineItem.Apttus_Config2__PriceType__c != 'One Time')
                    lineItem.APTS_Contract_Term__c = lineItem.APTS_Contract_Term_Default__c;
                if(lineItem.APTS_Years_2_Plus_Adjustment__c == null && lineItem.Apttus_Config2__PriceType__c != 'One Time')
                    lineItem.APTS_Years_2_Plus_Adjustment__c = String.valueOf(lineItem.APTS_Years_2_Plus_Default__c);
                //DOC-4350 starts
                if(lineItem.APTS_Yr_1_Renewal_Adjustment__c == null && lineItem.Apttus_Config2__PriceType__c != 'One Time' && lineItem.APTS_Yr_1_Renewal_Default__c!=null)
                    lineItem.APTS_Yr_1_Renewal_Adjustment__c = String.valueOf(lineItem.APTS_Yr_1_Renewal_Default__c);
                //DOC-4350 ends
                if(lineItem.APTS_Renewal_Type__c == null)
                    lineItem.APTS_Renewal_Type__c = lineItem.APTS_Renewal_Type_Default__c;         
                if(lineItem.APTS_WLEC_Product_Category__c != null && lineItem.APTS_WLEC_Product_Category__c =='PS'){
                    if(lineItem.Apttus_Config2__BillingFrequency__c == null && (lineItem.APTS_Item_Category_Group__c != null && lineItem.APTS_Item_Category_Group__c != 'ZRRB'))
                    lineItem.Apttus_Config2__BillingFrequency__c = lineItem.APTS_Billing_Frequency_Default__c;
                    
                }
            }
			 //Added as part of DOC-12660 for Risk Sep Release
            if(lineItem.APTS_Proposal_Business_Unit__c !=null && System.Label.Risk_PBUs.contains(lineItem.APTS_Proposal_Business_Unit__c))
            {
                system.debug('RK --> YOY1Renew'+lineItem.APTS_Yr_1_Renewal_Default__c);
                if(lineItem.APTS_Yr_1_Renewal_Adjustment__c == null && lineItem.Apttus_Config2__PriceType__c != 'One Time' && lineItem.Apttus_Config2__LineStatus__c=='Renewed')
                    lineItem.APTS_Yr_1_Renewal_Adjustment__c = String.valueOf(lineItem.APTS_Yr_1_Renewal_Default__c);

            }
        }
    }
    //End: added by Kruti Shah (DOC-2007-2008,1577)
}