objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>APTS_AccountMirror_Picklist__c</fullName>
        <label>Account Mirror Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation National Accounts</fullName>
                </value>
                <value>
                    <fullName>Corporation Strategic</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Law School Library</fullName>
                </value>
                <value>
                    <fullName>Legal Education Group</fullName>
                </value>
                <value>
                    <fullName>LLF Enterprise</fullName>
                </value>
                <value>
                    <fullName>LLF Strategic</fullName>
                </value>
                <value>
                    <fullName>MLF 30-79</fullName>
                </value>
                <value>
                    <fullName>MLF 80+</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SLF 11-20</fullName>
                </value>
                <value>
                    <fullName>SLF 21-29</fullName>
                </value>
                <value>
                    <fullName>SLF 2-3</fullName>
                </value>
                <value>
                    <fullName>SLF 4-6</fullName>
                </value>
                <value>
                    <fullName>SLF 7-10</fullName>
                </value>
                <value>
                    <fullName>Solo Law Firm</fullName>
                </value>
                <value>
                    <fullName>State Government</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
                <value>
                    <fullName>CORPORAT</fullName>
                </value>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>Law Firm</fullName>
                </value>
                <value>
                    <fullName>Corp Counsel</fullName>
                </value>
                <value>
                    <fullName>Corp Counsel Existing</fullName>
                </value>
                <value>
                    <fullName>Corp Investigative</fullName>
                </value>
                <value>
                    <fullName>Corp Investigative Financial</fullName>
                </value>
                <value>
                    <fullName>Corp National Investigative</fullName>
                </value>
                <value>
                    <fullName>MLF 30-179</fullName>
                </value>
                <value>
                    <fullName>AmLaw100</fullName>
                </value>
                <value>
                    <fullName>LLF 180+</fullName>
                </value>
                <value>
                    <fullName>State Gov Investigative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Customer_Category__c</fullName>
        <description>Formula Field that projects Quote/Proposal&apos;s Account &quot;Customer Category&quot; picklist value as TEXT into Product Configuration; primarily for use in Approvals/DealMaximizer</description>
        <formula>TEXT(Apttus_QPConfig__Proposald__r.APTS_SSD_Sold_To__r.APTS_Customer_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Category</label>
        <type>Text</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Business_Partner_Function__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>IF(ISBLANK(Related_Account_GLI__c) ,Related_Account__r.BillingCity, Related_Account_GLI__r.City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bill-To</fullName>
                </value>
                <value>
                    <fullName>Ship-To</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Sold To</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Customer Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>IF(ISBLANK(Related_Account_GLI__c) ,Related_Account__r.BillingState, Related_Account_GLI__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <formula>IF(ISBLANK(Related_Account_GLI__c) ,Related_Account__r.BillingCountry, Related_Account_GLI__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>country</label>
        <type>Text</type>
    </fields>
    <label>Business Partner Function</label>
    <nameField>
        <displayFormat>BPF-{0000}</displayFormat>
        <label>Business Partner Function Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Partner Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Customer_Category__c</fullName>
        <description>Created as part of OC GLI implementation</description>
        <label>APTS_Customer_Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Segment_Level_2__c</fullName>
        <description>Created as per Tax Prof ECM feed, DPS-9495</description>
        <label>Frozen Market Current Year Segment L2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Customer_Group__c</fullName>
        <description>Created for US Legal Sales Users as part of LegalCRM-R4 project(CRM-6422)</description>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>LCRM_Frozen_Market_Segment__c</fullName>
        <description>Created for R4</description>
        <label>Frozen Market Segment</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Name_2__c</fullName>
        <description>Created for R4</description>
        <label>Name 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Name_3__c</fullName>
        <description>Created for R4</description>
        <label>Name 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_PO_Box__c</fullName>
        <description>Created for R4</description>
        <label>PO Box</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>LCRM_SAP_Account_Number__c</fullName>
        <description>Created for R4</description>
        <label>SAP Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_Street3__c</fullName>
        <label>Street3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Street4__c</fullName>
        <label>Street4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Street_2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Name__c</fullName>
        <label>Source System Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WebServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for external web service endpoints and credentials.</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The web service url as defined by the service provider</description>
        <inlineHelpText>The web service url as defined by the service provider</inlineHelpText>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Service_Unavailable_Message__c</fullName>
        <description>The message displayed to the user in the event the service is inactive or unavailable for use</description>
        <inlineHelpText>The message displayed to the user in the event the service is inactive or unavailable for use</inlineHelpText>
        <label>Service Unavailable Message</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Web Service Settings</label>
</CustomObject>

classes/TRStoreBill_ShippingDetailsServiceTest.cls
@isTest(seeAllData=false)
public class TRStoreBill_ShippingDetailsServiceTest{
    
    public static testMethod  void TRStoreBill_ShippingDetailsServiceMet1(){
        
        
         Schema.DescribeFieldResult fieldResultMarket = Apttus_Config2__ProductConfiguration__c.APTS_AccountMirror_Picklist__c.getDescribe();
        String valueMarket = fieldResultMarket.getPicklistValues().get(0).getValue();
        
        Account a = APTS_TestDataFactory.createAccount('Test Account');
        //a.BU_Segment_Level_2__c= valueMarket;
        insert a;
      
        Id ssdRecorType=Schema.SObjectType.Source_System_Detail__c.getRecordTypeInfosByName().get('LOTUS Source Systems').getRecordTypeId();
       /* Source_System_Detail__c accountSSD=APTS_TestDataFactory.createSourceSystem(a);
        accountSSD.RecordtypeId=ssdRecorType;
        accountSSD.Name='ABC';
        accountSSD.Source_System_Name__c='ABC';
       // accountSSD.Account_Name__c=a.ID;
        accountSSD.LCRM_Frozen_Market_Segment__c = valueMarket;
        accountSSD.Account_Inactive__c=false;
        accountSSD.LCRM_Customer_Group__c='Academic';
        accountSSD.Source_System_Account_Number__c='11111112';
        accountSSD.LCRM_SAP_Account_Number__c ='11111112'; 
        accountSSD.LCRM_Sales_Org__c='WEST';
        accountSSD.Postal_Code__c ='12345-6789';
        insert accountSSD;
        */
         List<WebServiceSettings__c> WebserviceList = new List<WebServiceSettings__c>{new WebServiceSettings__c(Name='EnterpriseWSDL',Endpoint__c='https://api.apigarden-qa.thomsonreuters.com/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available'),
            new WebServiceSettings__c(Name='StatusPostbackLocation',Endpoint__c='https://api.apigarden-qa.thomsonreuters.com/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available'),
            new WebServiceSettings__c(Name='PostbackLocation',Endpoint__c='https://api.apigarden-qa.thomsonreuters.com/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available'),
            new WebServiceSettings__c(Name='Payment AutoCharge',Endpoint__c='https://api.apigarden-qa.thomsonreuters.com/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available'),
            new WebServiceSettings__c(Name='PaymentCreditIncrease',Endpoint__c='https://api.apigarden-qa.thomsonreuters.com/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/entitlement/uat/getEntitlements/ebs/account/qa/createAccount',Service_Unavailable_Message__c='Service not Available')};
                
                insert WebserviceList;
       
        
         Source_System_Detail__c accountSSD= new Source_System_Detail__c(RecordtypeId=ssdRecorType,Name='ABC',Source_System_Name__c='ABC'/*,Account_Name__c=acc.ID*/,APTS_Customer_Category__c='1',
                                                                        LCRM_Customer_Group__c='Academic',Account_Inactive__c=false,LCRM_Sales_Org__c='WEST',Source_System_Account_Number__c='123456',
                                                                        LCRM_Name_2__c='DEF',LCRM_Name_3__c='XYZ',Number_Street__c='Street5',LCRM_Street_2__c='Street2',LCRM_Street3__c='Street3',LCRM_Street4__c='Street4',
                                                                        City__c='TestCity',State__c='TestState',Country__c='testCountry',Postal_Code__c='12345',LCRM_Phone__c='9876547777',LCRM_Fax__c='8765432109',LCRM_PO_Box__c='PO-156');  
        insert accountSSD;
        
        
        
        List<Business_Partner_Function__c> bpfList=new List<Business_Partner_Function__c>();
                Business_Partner_Function__c bpf1 = new Business_Partner_Function__c();
                bpf1.Relationship_Type__c ='Bill-to party';
                bpf1.Related_Account_GLI__c=accountSSD.id;
                bpf1.Sold_To_Account_GLI__c=accountSSD.id;
            bpf1.Related_Account__c=a.id;
            bpf1.Sold_To_Account__c=a.id;
            bpfList.add(bpf1);
            
             Business_Partner_Function__c bpf2 = new Business_Partner_Function__c();
        bpf2.Relationship_Type__c ='Ship-to party';
        bpf2.Related_Account_GLI__c=accountSSD.id;
        bpf2.Sold_To_Account_GLI__c=accountSSD.id;
    bpf2.Related_Account__c=a.id;
    bpf2.Sold_To_Account__c=a.id;
        bpfList.add(bpf2);
        
         
        
        insert bpfList;
        
        
         LIST<Static_Values__c> staticCSList = new LIST<Static_Values__c>{
                                                                         new Static_Values__c(name='BusinessPartnerBillPay', value__c='Bill-to party'),
                                                                         new Static_Values__c(name='BusinessPartnerShipPay', value__c='Ship-to party'),
                                                                         new Static_Values__c(name='CanadaSalesOrg', value__c='CARS'),
                                                                         new Static_Values__c(name='UsSalesOrg', value__c='WEST'),
                                                                         new Static_Values__c(name='pwcBusinessAcc1', value__c='10000254'),
                                                                         new Static_Values__c(name='pwcBusinessAcc2', value__c='10058985'),
                                                                         new Static_Values__c(name='pwcBusinessAcc3', value__c='10058985'),
                                                                         new Static_Values__c(name='detBusinessAcc1', value__c='10058985'),
                                                                         new Static_Values__c(name='detBusinessAcc2', value__c='10058985'),
                                                                         new Static_Values__c(name='detBusinessAcc3', value__c='10058985')
                                                                         };
        
        insert staticCSList ;
        
         
        
         RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/BillingShippingDetails';  //Request URL
        req.httpMethod = 'GET';//HTTP Request Type
         
        req.addHeader('Content-Type', 'application/json');
        
        req.params.put('billToAccountNum', accountSSD.Source_System_Account_Number__c);
        req.params.put('zipCode', '12345');
        req.params.put('country', 'US');
        req.params.put('site', 'pwc');
        
        RestContext.request = req;
    
        TRStoreBill_ShippingDetailsService.fetchBillingAndShippingAddress();
        
        req.params.put('site', 'det');
        RestContext.request = req;
        TRStoreBill_ShippingDetailsService.fetchBillingAndShippingAddress();
        
        
        
    }
    
}