objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_SSD_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Acct SSD</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACADEMIC</fullName>
                </value>
                <value>
                    <fullName>CORPORATION</fullName>
                </value>
                <value>
                    <fullName>FEDERAL GOVERNMENT</fullName>
                </value>
                <value>
                    <fullName>FIRM</fullName>
                </value>
                <value>
                    <fullName>GOVERNMENT</fullName>
                </value>
                <value>
                    <fullName>RESELLER</fullName>
                </value>
                <value>
                    <fullName>Private (Individual No Bus)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/KeyValueListStore__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueListStore</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+ AccountId,  Account.Name,&apos;_self&apos;)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <description>Customer Group from the Account object.</description>
        <formula>TEXT( Account.Customer_Group__c )</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Customer_Group__c</fullName>
        <description>Created as a part of CRM -11131</description>
        <label>Customer Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>To be populated at the time of opportunity creation but changeable.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Acct SSD</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Source_System_Detail__c.Account_Name__r.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Source_System_Detail__c.Account_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Product_Pricing_Model__c</fullName>
        <label>Product Pricing Model</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for Product</description>
        <label>xx-Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SCSI</fullName>
                </value>
                <value>
                    <fullName>SFWS</fullName>
                </value>
                <value>
                    <fullName>SMG</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>TSCE</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>West Group:WEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WLEC_Product_Category__c</fullName>
        <label>WPD Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attorney Jobs</fullName>
                </value>
                <value>
                    <fullName>ReqWired</fullName>
                </value>
                <value>
                    <fullName>WLEC Subscription</fullName>
                </value>
                <value>
                    <fullName>WLEC Live</fullName>
                </value>
                <value>
                    <fullName>WLEC OnDemand</fullName>
                </value>
                <value>
                    <fullName>WPD Publications</fullName>
                </value>
                <value>
                    <fullName>Fed Pubs – Live Events</fullName>
                </value>
                <value>
                    <fullName>Fed Pubs – In-house</fullName>
                </value>
                <value>
                    <fullName>WLEC Live Events</fullName>
                </value>
                <value>
                    <fullName>Beyond the Bar</fullName>
                </value>
                <value>
                    <fullName>SOTW</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RecordtypeIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will store the record type IDs which will be used in apex classes.</description>
    <fields>
        <fullName>recTypeId__c</fullName>
        <label>recTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Record type Ids</label>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Customer_Group__c</fullName>
        <description>Created for US Legal Sales Users as part of LegalCRM-R4 project(CRM-6422)</description>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_Name__c</fullName>
        <label>Source System Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/APTS_DocuSignEnvelRecpStatTriggerTest.cls
@isTest
private class APTS_DocuSignEnvelRecpStatTriggerTest {
 
  @isTest
  static void setup(){ 
       
    Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Account a = new Account(RecordTypeId=accRecordTypeId,name='test',sales_org__c='ABEP',customer_group__c='Academic',customer_type__c='Organization',customer_class_c__c='Academic Lecturer');
        insert a;
        System.assertequals('test',a.Name,'Success');
        
        List<KeyValueListStore__c> keyvaluestoreList=new List<KeyValueListStore__c>();
        
        KeyValueListStore__c keyval1 = new KeyValueListStore__c(Name='ANZUsersProfileId',TextValue__c=System.Label.APTS_OC_Test_Id);
        keyvaluestoreList.add(keyval1);
        
        KeyValueListStore__c keyval = new KeyValueListStore__c();
        keyval.Name='ReasonWithCompetitor';
        keyval.TextValue__c='Price';
        keyvaluestoreList.add(keyval);
        insert keyvaluestoreList;
        
         List<RecordtypeIds__c> recordlist=new List<RecordtypeIds__c>();
        RecordtypeIds__c recordtype=new RecordtypeIds__c();
        recordtype.Name='Pre-Pipeline Opportunities';
        recordtype.recTypeId__c=System.Label.APTS_OC_Test_Id;
        recordlist.add(recordtype);
        
        RecordtypeIds__c recordtype1=new RecordtypeIds__c();
        recordtype1.Name='Pipeline Opportunities';
        recordtype1.recTypeId__c=System.Label.APTS_OC_Test_Id;
        recordlist.add(recordtype1);
        insert recordlist;
       // Id accRecordTypeIdSSD = Schema.SObjectType.Source_System_Detail__c.getRecordTypeInfosByName().get('LOTUS Source Systems').getRecordTypeId();
        Source_System_Detail__c accountSSD= new Source_System_Detail__c();
        accountSSD.Name='ABC';
        accountSSD.Source_System_Name__c='ABC';
        accountSSD.Account_Name__c=a.ID;
        accountSSD.LCRM_Customer_Group__c='Academic';
        accountSSD.LCRM_Sales_Org__c='TA78';
        insert accountSSD;
         
        Id opptyRecorType=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('GLI Pipeline Opportunity').getRecordTypeId();
        Opportunity opp=APTS_TestDataFactory.createOpportunity('abc',a.id,'New',Date.Today());
        opp.RecordtypeId=opptyRecorType;
        opp.Source_System_Detail__c=accountSSD.id;
        opp.Account=a;
        insert opp; 
        Product2 oProduct=new Product2(Name ='1SRC NRA Banner Interface',
                                  ProductCode = '41318361',
                                  WLEC_Product_Category__c='SS',
                                  APTS_Product_Pricing_Model__c = 'INCOME TAX');     
       insert oProduct;
       Apttus_Proposal__Proposal__c proposal= new Apttus_Proposal__Proposal__c();
       proposal.Apttus_Proposal__Account__c=a.id;
       proposal.APTS_SSD_Sold_To__c=accountSSD.id;
       proposal.Apttus_Proposal__Opportunity__c = opp.id;
       proposal.APTS_Proposal_Business_Unit__c = 'Corp OneOTC US';
       proposal.APTS_Existing_Database__c=true;
       proposal.APTS_Client_Database_Code__c='12345';
       proposal.Apttus_Proposal__Approval_Stage__c='Presented';
       proposal.Apttus_Proposal__Primary__c=false;

    Apttus_DocuApi__DocuSignEnvelope__c oEnvelope = DCTestData.createDocuSignEnvelope('voided', proposal.id);
    oEnvelope.Apttus_DocuApi__RecallReason__c = '';
    oEnvelope.Apttus_DocuApi__EnvelopeId__c = 'ce12dc3d-ffff-4444-aaaa-3b0494af30b9';
    insert proposal;
      insert oEnvelope; 
    
  }


  @isTest   
    static void test1()
    {   setup();
      //  Account account =  [SELECT id FROM Account WHERE Name='Test'];
    //    Apttus_Proposal__Proposal__c proposal =[SELECT id,Apttus_Proposal__Approval_Stage__c,APTS_Existing_Database__c,Apttus_Proposal__Account__c,APTS_SSD_Sold_To__c,Apttus_Proposal__Opportunity__c,APTS_Proposal_Business_Unit__c  FROM  Apttus_Proposal__Proposal__c WHERE Apttus_Proposal__Account__c =: account.id ];
        

        Apttus_DocuApi__DocuSignEnvelope__c docSignEnv = [SELECT Apttus_DocuApi__EnvelopeId__c,Apttus_DocuApi__Status__c 
                                                            FROM Apttus_DocuApi__DocuSignEnvelope__c 
                                                            WHERE Apttus_DocuApi__EnvelopeId__c  = 'ce12dc3d-ffff-4444-aaaa-3b0494af30b9'];
    
       List <Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c> docuSignEnvelopeRS = new List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>(); 
        //Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c doc = [SELECT id,Apttus_DocuApi__Status__c FROM Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c WHERE Apttus_DocuApi__DocuSignEnvelopeId__c =: docSignEnv.Apttus_DocuApi__EnvelopeId__c];
        //doc.Apttus_DocuApi__Status__c ='Completed';
       Test.startTest();  
          Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c doc = new Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c();
          doc.Apttus_DocuApi__DocuSignEnvelopeId__c=docSignEnv.id;
          doc.Apttus_DocuApi__Email__c = 'random@random.com';
          doc.Apttus_DocuApi__Status__c ='Completed';
      // insert doc;
       docuSignEnvelopeRS.add(doc);   
     
        insert docuSignEnvelopeRS;     
       // APTS_DocuSignEnvelopeStatTriggerHandler.adminAcceptprocess(docuSignEnvelopeRS);
      //  APTS_DocuSignEnvelopeStatTriggerHandler.exclusionframework(docuSignEnvelopeRS);
      System.assertEquals('Completed',doc.Apttus_DocuApi__Status__c,'status does not match');
        Test.stopTest();                                           
    }



}