objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>APTS_Approval_Segment__c</fullName>
        <description>Formula Field that projects Quote/Proposal&apos;s &quot;Approval Segment&quot; picklist value as TEXT into Product Configuration; primarily for use in Approvals/DealMaximizer</description>
        <formula>TEXT(Apttus_QPConfig__Proposald__r.APTS_Approval_Segment__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Current_Holdings__c</fullName>
        <label>Value of Current Holdings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_SSD_bill_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created as part of OC-GLI implementation, a look up to Account SSD</description>
        <label>Bill To Acct SSD</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready For Approvals</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Ready For Finalization</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Approval_Segment__c</fullName>
        <label>Approval Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small Law</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>Medium Law</fullName>
                </value>
                <value>
                    <fullName>Large Law</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Government - CLEAR</fullName>
                </value>
                <value>
                    <fullName>LMS Channel</fullName>
                </value>
                <value>
                    <fullName>Corporate Investigative</fullName>
                </value>
                <value>
                    <fullName>Corporate Strategic</fullName>
                </value>
                <value>
                    <fullName>Corporate SMB</fullName>
                </value>
                <value>
                    <fullName>Corporate Large</fullName>
                </value>
                <value>
                    <fullName>Corporate Global7</fullName>
                </value>
                <value>
                    <fullName>Corporate Legal Software Risk &amp; Compliance</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>AEM Risk</fullName>
                </value>
                <value>
                    <fullName>Tax Prof – Small – Mid Tax</fullName>
                </value>
                <value>
                    <fullName>Tax Prof – Emerging Tax</fullName>
                </value>
                <value>
                    <fullName>Tax Prof – Large Tax</fullName>
                </value>
                <value>
                    <fullName>Tax Prof – Other – Tax Professionals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Payment_Option__c</fullName>
        <label>Payment Option</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>APTS_Proposal_Business_Unit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Bill to Account</fullName>
                    <default>true</default>
                    <label>Bill to Account</label>
                </value>
                <value>
                    <fullName>Auto EFT/Auto Charge</fullName>
                </value>
                <value>
                    <fullName>Payment Express Auto EFT/Auto Charge</fullName>
                </value>
                <value>
                    <fullName>Autopay</fullName>
                </value>
                <value>
                    <fullName>Auto Charge</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Payment Express Auto ETF/Auto Charge</fullName>
                </value>
                <value>
                    <fullName>One Time EFT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_SSD_bill_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Acct SSD</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Proposals (Bill to SSD)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
        <description>The proposal approval stage</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Primary__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the quote/proposal is the primary quote to update the related opportunity</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Quote_Type__c</fullName>
        <description>Holds the value of the type of Digital quote</description>
        <label>Digital Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Straight Renewal</fullName>
                </value>
                <value>
                    <fullName>Best Value</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Best Value+Config</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_in_CXD_Renewals__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enabling this checkbox will push the checked Digital &quot;Manual&quot; quote to the Digital Offer Landing Page.</description>
        <inlineHelpText>Check this box to show this manually created proposal on the Digital Offer Landing Page. Only one manually created proposal can be checked per opportunity.</inlineHelpText>
        <label>Display in CXD Renewals</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocuSign_Envelope_ID__c</fullName>
        <description>Holds the DocuSign Envelope ID created for Digital renewals.</description>
        <label>DocuSign Envelope ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal_Line_Item__c.object
<CustomObject>
    <description>Represents a product or service line item associated with a quote/proposal</description>
    <fields>
        <fullName>APTS_Product_Pricing_Model__c</fullName>
        <label>Product Pricing Model</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_SSD_Bill_To__c</fullName>
        <formula>Apttus_Proposal__Proposal__r.APTS_SSD_bill_to__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bill To Acct SSD</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Proposal Line Items</relationshipLabel>
        <relationshipName>R00N70000001yUfPEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Proposal__c</fullName>
        <description>ID of the associated quote/proposal</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>R00N70000001yUfBEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__LineStatus__c</fullName>
        <description>The line status</description>
        <label>Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Incremented</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Upgraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Proposal Line Item</label>
    <nameField>
        <displayFormat>QL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Product_Pricing_Model__c</fullName>
        <label>Product Pricing Model</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DCPProposal.cls
/**
    @description Proposal data layer class for DCP projects.
    CHANGE HISTORY
    ================================================
    Date            Developer           Description
    2021-04-14      Benjamin Her        DCP-1414 Initial Creation
    2021-07-19      Vishnu Santhosh     DCP-2144 Added 'getProposalLineItems' method
 */
public without sharing class DCPProposal{
    public static final string STAGE_PRESENTED = 'Presented';
    public static final string LINESTATUS_NEW = 'New';
    
    /**
        @description Stores the queried proposal
     */
    public static List<Apttus_Proposal__Proposal__c> propList;

    /**
        @description Stores the queried proposal
     */
    public static List<Apttus_Proposal__Proposal_Line_Item__c> lineItemsList;
    
    /**
        @description Run queries on Proposal object
        @param propIds List of proposal ids to query
        @return Returns the queried proposal
     */
    public static List<Apttus_Proposal__Proposal__c> getProposal(List<id> propIds){
        propList=   
                [SELECT id, Apttus_Proposal__Primary__c,APTS_Approval_Segment__c,APTS_Payment_Option__c,DocuSign_Envelope_ID__c, 
                (SELECT id, APTS_Current_Holdings__c FROM Apttus_QPConfig__Configurations__r WHERE Apttus_Config2__Status__c = 'Finalized')
                FROM Apttus_Proposal__Proposal__c
                WHERE id IN : propIds
                WITH SECURITY_ENFORCED];
                
        return propList;
    }    
    /**
        @description Run queries on Proposal object
        @param oppId Opportunity Id used to filter
        @param ssdId SSD Id used to filter
        @return Returns the presented proposal from Opp and SSD
     */
    public static List<Apttus_Proposal__Proposal__c> getPresentedProposal(Id oppId, Id ssdId){
        propList=   
                [SELECT id, Apttus_Proposal__Primary__c, APTS_Approval_Segment__c,Display_in_CXD_Renewals__c,DocuSign_Envelope_ID__c,Digital_Quote_Type__c, APTS_Payment_Option__c, CurrencyIsoCode
                FROM Apttus_Proposal__Proposal__c
                WHERE Apttus_Proposal__Opportunity__c =: oppId
                AND APTS_SSD_bill_to__c =: ssdId
                AND Apttus_Proposal__Approval_Stage__c =: STAGE_PRESENTED
                WITH SECURITY_ENFORCED];
                
        return propList;
    }    
    /**
        @description Run queries on Proposal object
        @param oppId Opportunity Id used to filter
        @param ssdId SSD Id used to filter
        @return Returns the presented proposal from Opp and SSD
     */
    public static List<Apttus_Proposal__Proposal__c> getPresentedProposalWithCart(Id oppId, Id ssdId){
        propList=   
                [SELECT id, Apttus_Proposal__Primary__c,APTS_Approval_Segment__c,APTS_Payment_Option__c, 
                (SELECT id, APTS_Current_Holdings__c FROM Apttus_QPConfig__Configurations__r WHERE Apttus_Config2__Status__c = 'Finalized')
                FROM Apttus_Proposal__Proposal__c
                WHERE Apttus_Proposal__Opportunity__c =: oppId
                AND APTS_SSD_bill_to__c =: ssdId
                AND Apttus_Proposal__Approval_Stage__c =: STAGE_PRESENTED
                WITH SECURITY_ENFORCED];
                
        return propList;
    }
    
    /**
    @description To retrieve proposal line items using proposal id.
    @param proposalId Id to query
    @return List of proposal line items
    */
    public static List<Apttus_Proposal__Proposal_Line_Item__c> getProposalLineItems(Id proposalId){
    lineItemsList = [   SELECT  Id, 
                                Name, 
                                Apttus_Proposal__Product__r.Name,
                                Apttus_Proposal__Product__r.APTS_Product_Pricing_Model__c,
                                Apttus_Proposal__Product__r.Id

                        FROM Apttus_Proposal__Proposal_Line_Item__c
                        WHERE Apttus_Proposal__Proposal__c=:proposalId
                        AND Apttus_QPConfig__LineStatus__c=:LINESTATUS_NEW
                        WITH SECURITY_ENFORCED];
    return lineItemsList;
    }

                        
    /**
        @description Updates Proposal object
        @param propUpdateList List of proposal ids to update
    
    public static void updateProposal(List<Apttus_Proposal__Proposal__c> propUpdateList){
        Database.SaveResult[] results = Database.update(propUpdateList,false);
    }
     */
    
}