objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Digital_Quote_Type__c</fullName>
        <description>Holds the value of the type of Digital quote</description>
        <label>Digital Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Straight Renewal</fullName>
                </value>
                <value>
                    <fullName>Best Value</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Best Value+Config</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_in_CXD_Renewals__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enabling this checkbox will push the checked Digital &quot;Manual&quot; quote to the Digital Offer Landing Page.</description>
        <inlineHelpText>Check this box to show this manually created proposal on the Digital Offer Landing Page. Only one manually created proposal can be checked per opportunity.</inlineHelpText>
        <label>Display in CXD Renewals</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+ AccountId,  Account.Name,&apos;_self&apos;)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Acct SSD</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Source_System_Detail__c.Account_Name__r.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Source_System_Detail__c.Account_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DCPGetRenewal.cls
/**
@description Main GET logic for DCP Renewal Service
CHANGE HISTORY
================================================
Date            Developer           Description
2021-04-14      Benjamin Her        DCP-1414 Initial Creation
2021-04-29      Vishnu Santhosh     DCP-1118 acc Instance added
2021-06-25      Vishnu Santhosh     DCP-2212 | Added 'ssd' parameter to opp. data response
2021-06-29      Dinesh              DCP-2214 | Added  populate wrapper data

*/
//@suppresswarnings({})
//@SuppressWarnings({'pmd.CyclomaticComplexity','pmd.CognitiveComplexity'})
public without sharing class DCPGetRenewal{
private static final string STR_OPPID = 'oppId';
private static final string STR_SSDID = 'ssdId';
private static Opportunity opp;
private static Contact con;
private static List<Apttus_Proposal__Proposal__c> propList;
private static List<Apttus_Config2__ProductConfiguration__c> cartList;
private static Map<String,Apttus_Config2__ProductConfiguration__c> proposalIDToCartMap = new Map<String,Apttus_Config2__ProductConfiguration__c>();
private static Source_System_Detail__c ssd;
private static Account acc;  
// US 2681
// Added By: Sudhanshu Upadhayay
// Date Added: 26-07-2021
private static final String DIGITAL_QUOTE_TYPE_PLUS = 'Best Value';
private static final String DIGITAL_QUOTE_TYPE_MANUAL = 'Manual';
private static final String DIGITAL_QUOTE_TYPE_STRAIGHT = 'Straight Renewal'; 
private static final String DIGITAL_QUOTE_TYPE_PREMIUM = 'Premium'; 
//Commented out Sprint 13 Changes for deployment - Vishnu
//private static List<DCPRenewalDBCatWrapper> dbCatWrapperList;//Add by Dinesh

/**
    @description Pulls DCPRenewalResponse data
    @param reqParameter Request parameter pull from URL
    @return Returns DCPRenewalResponse data
    */
public static DCPRenewalResponse getDCPRenewalResponse(Map<String, String> reqParameter){

    if(reqParameter == null || reqParameter.isEmpty()){
        throw new DCCustomException('Request Parameters do not exist');
    }

    queryData(reqParameter);

    return populateDCPRenewalResponse();
}

private static void queryData(Map<String, String> reqParameter){
    string oppId;
    string ssdId;

    if(reqParameter.containsKey(STR_OPPID) && String.isNotBlank(reqParameter.get(STR_OPPID))
        && reqParameter.containsKey(STR_SSDID) && String.isNotBlank(reqParameter.get(STR_SSDID))){

        oppId = reqParameter.get(STR_OPPID);
        ssdId = reqParameter.get(STR_SSDID);
        opp = DCPOpportunity.getOpportunity(new List<Id>{oppId})[0];
        con = DCPContact.getContact(new List<Id>{opp.Key_Contact__c})[0];
        propList = DCPProposal.getPresentedProposal(oppId,ssdId);
        propList =manualOfferReplacement(propList);// for manual proposal logic and fixing cart size to 3
        cartList = DCPCart.getFinalizeCartFromProposal(propList);
        for(Apttus_Config2__ProductConfiguration__c cart : cartList){
            proposalIDToCartMap.put(cart.Apttus_QPConfig__Proposald__c, cart);
        }
        DCPRenewalSetting.getRenewalSetting();
        ssd = DCPSSD.getSSD(new List<Id>{ssdId})[0];
        acc = DCPAccount.getAccounts(new List<id>{ssd.Account_Name__c})[0];
        
        //Commented out Sprint 13 Changes for deployment - Vishnu    
        //dbCatWrapperList = DCPDBCategory.getCBCats(oppId,ssdId);//Add by Dinesh
    

        }
    else{
        throw new DCCustomException('Error with request parameter. Parameter is missing or blank');
    }
}

private static DCPRenewalResponse populateDCPRenewalResponse(){
    
    DCPRenewalResponse response = new DCPRenewalResponse();
    response.data.opportunityData = DCPRenewalOpportunity.populateOpportunityDetails(opp,ssd);       
    response.data.contactData = DCPRenewalContact.populateContactDetails(con);
    response.data.proposalData = DCPRenewalProposal.getProposalDetails(propList,proposalIDToCartMap, opp);
    response.data.accountData = DCPRenewalAccount.populateAccountDetails(acc, ssd);
    
    
    //Commented out Sprint 13 Changes for deployment - Vishnu
    //response.data.dbData = dbCatWrapperList;//Add by Dinesh


    return response;
}

/**
    @description manualOfferReplacement() method.Updated DCP-2691 - Replaces automated offers with up to 3 manual offers
    @param carts
    @return List <Apttus_Proposal__Proposal__c>
    */
public static List <Apttus_Proposal__Proposal__c> manualOfferReplacement(List < Apttus_Proposal__Proposal__c> carts) {
    //List < Apttus_Proposal__Proposal__c > configlist = new List < Apttus_Proposal__Proposal__c> ();
    List < Apttus_Proposal__Proposal__c > manualProposalList = new List < Apttus_Proposal__Proposal__c > ();
        Apttus_Proposal__Proposal__c bestProposal;
        Apttus_Proposal__Proposal__c straightProposal;
    Apttus_Proposal__Proposal__c plusProposal;
    Apttus_Proposal__Proposal__c premiumProposal;


    //Data validation check. Return passed in cart.
    if (carts == null || carts.isEmpty()) {
        return carts;
    }

    //Iterates over passed in cart list and stores any 'Manual' proposals
    //Stores Straight and Best proposals for easier access
    DigitalProposalWrapper dpw = new DigitalProposalWrapper();
    dpw = getProposalsFromCart(carts);
    manualProposalList = dpw.manualProposals;
    straightProposal=dpw.straightProposal;
    plusProposal=dpw.bestProposal;
    premiumProposal=dpw.premiumProposal;



    //If zero manual offers exists, return original cart
    if (manualProposalList.isEmpty() && carts.size()<=3 ) {
        return carts;
    } 
    // If existing carts contains more than 3 items and no rep generated proposals
    else if(manualProposalList.isEmpty()&& carts.size() > 3 ){
            List < Apttus_Proposal__Proposal__c > configList = new List < Apttus_Proposal__Proposal__c > ();
        for(Integer i=0; i<3; i++){
            if(carts[i].Digital_Quote_Type__c != DIGITAL_QUOTE_TYPE_MANUAL){
                configlist.add(carts[i]);  
            }
            }
        return configlist;
    } 
    else {
        //Build/Return new list since manual proposals are present
        DigitalProposalWrapper digitalProposals = new DigitalProposalWrapper();
        digitalProposals.straightProposal = straightProposal;
        digitalProposals.bestProposal = plusProposal;
        digitalProposals.premiumProposal = premiumProposal;
        return DCPManualOffferReplacementProposals.manualOfferReplacementHelper(manualProposalList,digitalProposals);
        //return manualProposalList;

    }
} //end of manualOfferReplacement() method
    

private static DigitalProposalWrapper getProposalsFromCart(List<Apttus_Proposal__Proposal__c> carts){
            //Iterates over passed in cart list and stores any 'Manual' proposals
    //Stores Straight and Best proposals for easier access
    DigitalProposalWrapper dpr = new DigitalProposalWrapper();
    for (Apttus_Proposal__Proposal__c pconfig: carts) {
        if (pconfig.Digital_Quote_Type__c == DIGITAL_QUOTE_TYPE_MANUAL && pconfig.Display_in_CXD_Renewals__c==true ) { //add manual proposals to list.
            dpr.manualProposals.add(pconfig);
        }  if (pconfig.Digital_Quote_Type__c == DIGITAL_QUOTE_TYPE_STRAIGHT) { //assign straight proposal
            dpr.straightProposal = pconfig;
        }  if (pconfig.Digital_Quote_Type__c == DIGITAL_QUOTE_TYPE_PLUS) { //assign plus proposal.
            dpr.bestProposal = pconfig;
        }
            if (pconfig.Digital_Quote_Type__c == DIGITAL_QUOTE_TYPE_PREMIUM) { //assign premium proposal.
            dpr.premiumProposal = pconfig;
        }
    }
return dpr;
}  

}