objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
        <description>The proposal approval stage</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Primary__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the quote/proposal is the primary quote to update the related opportunity</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Batch_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Digital Batch Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Envelope_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to only generate the Digital DocuSign Envelope one time.  This is only used for the Digital Automation process.</description>
        <label>Digital Envelope Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Quote_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Helps to identify the Digital quote automation records</description>
        <label>Digital Quote Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digital_Quote_Type__c</fullName>
        <description>Holds the value of the type of Digital quote</description>
        <label>Digital Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Straight Renewal</fullName>
                </value>
                <value>
                    <fullName>Best Value</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Best Value+Config</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Date of subscription renewal.</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sub_Campaign_Code__c</fullName>
        <description>DLT-8281</description>
        <label>sub-Campaign Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product_Account_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Current_Subscription__c</fullName>
        <label>Current Subscription</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sub_Campaign_Code__c</fullName>
        <description>DLT-8281</description>
        <label>sub-Campaign Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Digital Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Product Account  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Digital_DocusignSchedulable_Test.cls
@isTest
public class Digital_DocusignSchedulable_Test {
	public static String accountId;
    public static String oppId;
    public static String quoteId;
    public static string attachmentId;
    
    // Create Quote data for DocuSign Envelope Creation
    @testSetup
    static void setup(){
        // create account, ssd, opp, contact and quote
        DCTestData.createData();
        Test.startTest();   
        DCTestData.createQuote();      
        Test.stopTest();
        
        // update renewal date on Opp
        Opportunity oOpp = new Opportunity();
        oOpp.id = DCTestData.oppId;
        oOpp.StageName = 'Contacting';
        oOpp.Renewal_Date__c = system.today().addDays(180);
        update oOpp;  
        oppId = oOpp.id;  

        // update Proposal
        Apttus_Proposal__Proposal__c oQuote = new Apttus_Proposal__Proposal__c();
        oQuote.id = DCTestData.bQuoteId;
        oQuote.Apttus_Proposal__Approval_Stage__c = 'Generated';
        oQuote.Apttus_Proposal__Primary__c = true;
        oQuote.Digital_Batch_Processed__c = true;
        oQuote.Digital_Quote_Automation__c = true;
        oQuote.Digital_Quote_Type__c = 'Straight Renewal';
        oQuote.Digital_Envelope_Created__c = true;          
        update oQuote;
        quoteId = oQuote.id;

        // create a matching Digital Subscription record
        Product_Account_Detail__c prodAcctDetail = DCTestData.createDigitalSubscriptions('42072689','42072690', 'Plus', '1004284494', System.Today()+30, 'testCampaign');
        prodAcctDetail.Current_Subscription__c = '41010973';
        prodAcctDetail.sub_Campaign_Code__c = 'subtestcampaign';
        update prodAcctDetail;
                
        // create data for DocuSign connection
        DCTestData.createDocuSignUser();
        
        // delete extra quote
        Apttus_Proposal__Proposal__c oQuote2 = new Apttus_Proposal__Proposal__c();
        oQuote2.Id = DCTestData.cQuoteId;
        //delete oQuote2;
        
        // create web services
        DCTestData.createDocuSignWebService();
        DCTestData.createMarketAutomationWebsvc();
        DCTestData.createPaymentCreditWebService();
        
        // create attachment for the quote
        DCTestData.createAttachment(oQuote.id);
		//DCTestData.createFileAttachment(oQuote.id);            
    }
    
    public static testmethod void testSched() {
    	
    	Test.startTest();
    	// Set mock callout class for Envelope response
        Test.setMock(HttpCalloutMock.class, new HttpResponseMock());

        DateTime now  = DateTime.now();
        DateTime nextRunTime = now.addHours(2);
        String cronString = '' + nextRunTime.second() + ' ' + nextRunTime.minute() + ' ' + nextRunTime.hour() + ' ' + nextRunTime.day() + ' ' + nextRunTime.month() + ' ? ' + nextRunTime.year(); 
        Digital_DocusignSchedulable ddc = new Digital_DocusignSchedulable();
        system.schedule('Testexecution', cronString, ddc);
        Test.stopTest();
        
        // Check to see if the envelope was created
        Apttus_Proposal__Proposal__c oQuotes = [Select id, Digital_Envelope_Created__c from Apttus_Proposal__Proposal__c where Digital_Envelope_Created__c =: false LIMIT 1];
        System.AssertEquals(false, oQuotes.Digital_Envelope_Created__c);

    } 
}