objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Amount__c</fullName>
        <label>Credit Card Approved Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Authorization_Number__c</fullName>
        <label>Authorization Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Authorization_Transaction__c</fullName>
        <label>Authorization Transaction</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Card_Expiration_Date__c</fullName>
        <description>The expiration date of the credit card.</description>
        <label>Card Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>DISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Credit_Card_Token__c</fullName>
        <label>Credit Card Token</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Quote_Value__c</fullName>
        <description>summary of the line items.</description>
        <label>APTS_Quote_Value</label>
        <summarizedField>Apttus_Proposal__Proposal_Line_Item__c.Apttus_QPConfig__NetPrice__c</summarizedField>
        <summaryFilterItems>
            <field>Apttus_Proposal__Proposal_Line_Item__c.Apttus_QPConfig__LineType__c</field>
            <operation>equals</operation>
            <value>Product/Service</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Apttus_Proposal__Proposal_Line_Item__c.APTS_is_Primary_in_Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Apttus_Proposal__Proposal_Line_Item__c.Apttus_Proposal__Proposal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>APTS_VisaMessageType__c</fullName>
        <label>VisaMessageType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_VisaTransNumber__c</fullName>
        <description>Field created for Payment Gateway requirement.</description>
        <label>VisaTransNumber</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESC_Case_Form_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Bank_Routing_Number__c</fullName>
        <label>Bank Routing Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Form Extension</relationshipLabel>
        <relationshipName>Case_Form_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ESC_CreditCard_Details__c</fullName>
        <label>Credit Card Type/Number/Amount</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Credit_Card_Number__c</fullName>
        <description>Credit Card Number</description>
        <label>Credit Card Number (Last 4 digits)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ESC_Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>amex</fullName>
                </value>
                <value>
                    <fullName>discover</fullName>
                </value>
                <value>
                    <fullName>American Express</fullName>
                    <isActive>false</isActive>
                    <label>American Express</label>
                </value>
                <value>
                    <fullName>Discover Card</fullName>
                    <isActive>false</isActive>
                    <label>Discover Card</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ESC Form</label>
        <referenceTo>GenerateForm__c</referenceTo>
        <relationshipLabel>Case Form Extensions</relationshipLabel>
        <relationshipName>ESC_GenerateForm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESC_Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USL_Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>USL_Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>USL_Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>TextArea</type>
    </fields>
    <label>Case Form Extension</label>
    <nameField>
        <label>Case Form Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Form Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ESC_Case_Form_Extension_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ESC_Case_Form_Extension__c</fullName>
        <label>Case Form Extension</label>
        <referenceTo>ESC_Case_Form_Extension__c</referenceTo>
        <relationshipLabel>Case Form Extension Line Items</relationshipLabel>
        <relationshipName>Case_Form_Extension_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <description>Modify Invoice Form</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Case Form Extension Line Item</label>
    <nameField>
        <label>Case Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Form Extension Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GenerateForm__c.object
<CustomObject>
    <label>CSS Form</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProposalCCTokenPostBack.cls
/**
 * Post Back class for Proposal CC Token details
 *
 * @author  TCS
 * @version 2016-12-08
 */

/**
 * CHANGE HISTORY
 * =============================================================================
 * Date         Name                    Description
 * 2016-12-08   Pathra/Sreenu D                     Created                                                                   
 * =============================================================================
 */
/**
    * @description
    *  
    */
global class ProposalCCTokenPostBack 
{
   //Define an object in apex that is exposed in apex web service
   /**
    * @description
    *  
    */
   global class CreditCardInfo
   {
      webservice String AuthorizationNumber;
      webservice String TokenizationNumber;
      webservice String ExpirationDate;
      webservice String TransactionId;
      webservice String CardType;
      webservice String Amount;
      webservice Id proposalID;    
      webservice String VisaMessageType;
      webservice String VisaTransNumber;      
      webservice String caseNumber;
      webservice String paymentDate;
      webservice String status;
      webservice String bankrouting;
      webservice String bankaccount;
      webservice String applicationid;     
      webservice invlist[] invoicelist;
   }
   global class invlist
   { 
       webservice String invoice;
   }
   /**
        * @description
    * @param vToken
    *  @return 
    */
   webservice static string fetchTokenInfo(CreditCardInfo vToken) 
   {   
       try
       {    system.debug(LoggingLevel.WARN,'vtoken'+vToken);
       if(vToken.caseNumber != null){
             ESC_Case_Form_Extension__c cfe = new ESC_Case_Form_Extension__c();
             List<ESC_Case_Form_Extension_Line_Item__c> cfli = new List<ESC_Case_Form_Extension_Line_Item__c>();
             if(Schema.sObjectType.ESC_Case_Form_Extension__c.isQueryable()){
                cfe = [Select id,name,USL_Payment_Date__c,USL_Transaction_Date__c,ESC_Credit_Card_Type__c,ESC_Credit_Card_Number__c,USL_Total_Amount__c,ESC_Bank_Routing_Number__c,Bank_Account_Number__c,ESC_CreditCard_Details__c,ESC_Invoice_Number__c,ESC_Payment_Type__c from ESC_Case_Form_Extension__c WHERE ESC_Case__r.caseNumber=:vToken.caseNumber and ESC_Form__r.name =: 'CreditCard/Debit Payment' LIMIT 1];
             }
             
             //if(Schema.sObjectType.ESC_Case_Form_Extension_Line_Item__c.isQueryable()){
             //cfli = [ Select id,name,Invoice_Number__c from ESC_Case_Form_Extension_Line_Item__c where ESC_Case_Form_Extension__c =: cfe.id];
             //}
             if(cfe != null && vToken.status != 'Error'){
                system.debug(LoggingLevel.WARN,'vtoken'+vToken);
                string temp1;
                
                String fmTransDate = vToken.ExpirationDate;
                List<String> fmDate = fmTransDate.split(' ');
                cfe.USL_Transaction_Date__c = (cfe.USL_Transaction_Date__c == null || cfe.USL_Transaction_Date__c == '') ? fmDate[0] : cfe.USL_Transaction_Date__c+', '+ fmDate[0];
                if(vToken.CardType != '' && vToken.CardType !=null){
                    temp1 = vToken.CardType + '/'+ vToken.VisaTransNumber+'/ $'+ decimal.valueof(vToken.Amount);
                    //cfe.ESC_Credit_Card_Type__c = vToken.CardType ;
                    
                    /*
                    if(cfe.ESC_Payment_Type__c != null && cfe.ESC_Payment_Type__c == 'Credit')
                    {
                        cfe.ESC_Payment_Type__c = 'Credit';
                    }
                    else
                    {
                        cfe.ESC_Payment_Type__c = 'Both';
                    }
					*/
                    if(cfe.ESC_Payment_Type__c == null || cfe.ESC_Payment_Type__c == '')
                    {
                        cfe.ESC_Payment_Type__c = 'Credit';
                    }
                    else
                    {
                    if(cfe.ESC_Payment_Type__c != 'Credit'){
                        cfe.ESC_Payment_Type__c = 'Both';
                        }
                    }
                }
                else{
                    temp1 = vToken.bankrouting +'/'+vToken.bankaccount +'/ $'+decimal.valueof(vToken.Amount);
                    //cfe.ESC_Bank_Routing_Number__c = vToken.bankrouting;
                    /*
                    if(cfe.ESC_Payment_Type__c != null && cfe.ESC_Payment_Type__c == 'Debit')
                    {
                        cfe.ESC_Payment_Type__c = 'Debit';
                    }
                    else
                    {
                        cfe.ESC_Payment_Type__c = 'Both';
                    }
					*/
                    if(cfe.ESC_Payment_Type__c == null || cfe.ESC_Payment_Type__c == '')
                    {
                        cfe.ESC_Payment_Type__c = 'Debit';
                    }
                    else
                    {
                    if(cfe.ESC_Payment_Type__c != 'Debit'){
                        cfe.ESC_Payment_Type__c = 'Both';
                        }
                    }
                }
                
                cfe.ESC_CreditCard_Details__c = (cfe.ESC_CreditCard_Details__c == null || cfe.ESC_CreditCard_Details__c == '') ? temp1 : cfe.ESC_CreditCard_Details__c + ', '+temp1;
                
                for(invlist inv : vToken.invoicelist){
                        if(cfe.ESC_Invoice_Number__c == null || cfe.ESC_Invoice_Number__c == '')
                        {
                            cfe.ESC_Invoice_Number__c = inv.invoice;
                        }
                        else if(!cfe.ESC_Invoice_Number__c.contains(inv.invoice)){
                            cfe.ESC_Invoice_Number__c = cfe.ESC_Invoice_Number__c + ',' + inv.invoice;
                        }
                 }
                
                
                if(Schema.sObjectType.ESC_Case_Form_Extension__c.isUpdateable()){
                update cfe;}
                return 'Success'; 
                }          
                else
                {
                    return 'Matched record not found';
                }
            }
            else{
              Apttus_Proposal__Proposal__c quote = new Apttus_Proposal__Proposal__c();
              if(Schema.sObjectType.Apttus_Proposal__Proposal__c.isQueryable()){
              
            //            Apttus_Proposal__Proposal__c quote = [SELECT Id,Name,APTS_Amount__c,APTS_Quote_Value__c,APTS_Card_Type__c,APTS_Authorization_Transaction__c,APTS_Card_Expiration_Date__c,APTS_Authorization_Number__c,APTS_TokenizationNumber__c FROM Apttus_Proposal__Proposal__c WHERE id=:vToken.proposalID LIMIT 1];
              quote = [SELECT Id,Name,APTS_Amount__c,APTS_Quote_Value__c,APTS_Card_Type__c,APTS_Authorization_Transaction__c,APTS_Card_Expiration_Date__c,APTS_Authorization_Number__c,APTS_Credit_Card_Token__c,APTS_VisaMessageType__c,APTS_VisaTransNumber__c FROM Apttus_Proposal__Proposal__c WHERE id=:vToken.proposalID LIMIT 1];      
            }
            if(quote != Null)
            {  
                system.debug(LoggingLevel.WARN,'vtoken'+vToken);
                List <String> dateParts = vToken.ExpirationDate.split('/');
                Date tempDate = date.parse(dateParts[0]+'/'+dateParts[1]+'/'+dateParts[2]);
                quote.APTS_Card_Expiration_Date__c = tempDate;
                quote.APTS_Credit_Card_Token__c = vToken.TokenizationNumber; 
                quote.APTS_Authorization_Number__c = vToken.AuthorizationNumber;
                //quote.APTS_Credit_Card_Token__c  = vToken.AuthorizationNumber;
                quote.APTS_Card_Type__c = vToken.CardType;
                quote.APTS_Authorization_Transaction__c = vToken.TransactionId;
                quote.APTS_Amount__c = decimal.valueof(vToken.Amount);
                quote.APTS_VisaMessageType__c = vToken.VisaMessageType;
                quote.APTS_VisaTransNumber__c = vToken.VisaTransNumber;
                
                if(Schema.sObjectType.Apttus_Proposal__Proposal__c.isUpdateable()){
                update quote;}
                return 'Success';           
            }
            else
            {
                return 'Matched record not found';
            }
            }
       }
       catch (Exception ex)
       {
           system.debug(LoggingLevel.WARN,'exception...'+ex.getMessage()+ex.getLineNumber());
           return 'Exception while updating the Proposal'; 
       }        
  }
}