objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Config2__OrderLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an order</description>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__OrderProductAttributeValue__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__OrderId__c</fullName>
        <description>ID of the associated order</description>
        <inlineHelpText>ID of the associated order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Apttus_Config2__Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/APTS_OrderLineItemTriggerHandler.cls
/**
 * @description handler class for orderlineitem trigger
 */
@SuppressWarnings('PMD.AvoidGlobalModifier,PMD.ApexSharingViolations,PMD.ApexCRUDViolation')
public class APTS_OrderLineItemTriggerHandler{
    public static boolean afterUpdateRun = FALSE;
    /**
     * @description hanlder method for after update of orderlineitem trigger
     * @param newList
     * @param oldMap
     */
    public static void doAfterUpdate(List<Apttus_Config2__OrderLineItem__c> newList, Map<Id,Apttus_Config2__OrderLineItem__c> oldMap){
        if(!afterUpdateRun){
            List<Apttus_Config2__Order__c> oList = new List<Apttus_Config2__Order__c>();
            Set<ID> oIDSet = new Set<ID>();
            for(Apttus_Config2__OrderLineItem__c oli : newList){
                System.debug(LoggingLevel.DEBUG, 'Apttus_Config2__AttributeValueId__c new : '+oli.Apttus_Config2__AttributeValueId__c);
                System.debug(LoggingLevel.DEBUG, 'Apttus_Config2__AttributeValueId__c old : '+oldMap.get(oli.Id).Apttus_Config2__AttributeValueId__c);
                if(oli.Apttus_Config2__AttributeValueId__c != 
                    oldMap.get(oli.Id).Apttus_Config2__AttributeValueId__c){oIDSet.add(oli.Apttus_Config2__OrderId__c);}
            }
            System.debug(LoggingLevel.DEBUG, 'oIDSet : '+oIDSet);
            for(Id oID : oIDSet){
                Apttus_Config2__Order__c oRec = new Apttus_Config2__Order__c(ID=oID); oList.add(oRec);
            }
            System.debug(LoggingLevel.DEBUG, 'oList : '+oList);
            if(oList.size()>0){
                update oList;
                afterUpdateRun = TRUE;
            }
            
        }
    }


}