objects/Apttus__APTS_Template__c.object
<CustomObject>
    <description>Contract language templates available in the system. These templates specify guidance, language, local setitngs, and include Word attachment templates representing the bulk of actual contracts that can be used when creating a first draft . Templates can include standard and non-standard language.</description>
    <fields>
        <fullName>Apttus__Agreement_Types__c</fullName>
        <description>Note: If you add a new agreement record type, the type must also be manually added to this set of picklist values to keep record types in sync between agreements and templates.</description>
        <label>Agreement Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__FrameworkFormat__c</fullName>
        <description>Template framework format</description>
        <inlineHelpText>Template framework format</inlineHelpText>
        <label>Framework Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre FX2</fullName>
                </value>
                <value>
                    <fullName>FX2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes whether the contract template is active or not</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus__ReferenceId__c</fullName>
        <description>A unique external reference identifier</description>
        <externalId>true</externalId>
        <inlineHelpText>A unique external reference identifier</inlineHelpText>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus__Type__c</fullName>
        <description>Specifies the contract template type which can be either a template or clause type.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                    <default>true</default>
                    <label>Agreement</label>
                </value>
                <value>
                    <fullName>Clause</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Supporting Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>APTS_Proposal_Business_Unit__c</fullName>
        <formula>TEXT( Apttus_QPConfig__Proposald__r.APTS_Proposal_Business_Unit__c )</formula>
        <label>Proposal Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready For Approvals</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Ready For Finalization</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Order_Confirmation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Confirmation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Apttus_Proposal__Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposals (Order Confirmation Contact)</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Proposal_Business_Unit__c</fullName>
        <label>Proposal Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SCS</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>Corp OneOTC US</fullName>
                </value>
                <value>
                    <fullName>Corp OneOTC UK</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Tax Professional</fullName>
                </value>
                <value>
                    <fullName>Argentina-LLEY</fullName>
                </value>
                <value>
                    <fullName>Brazil-TSL</fullName>
                </value>
                <value>
                    <fullName>Hong Kong-SMHK</fullName>
                </value>
                <value>
                    <fullName>India-INWL</fullName>
                </value>
                <value>
                    <fullName>Australia-PNG-LRA</fullName>
                </value>
                <value>
                    <fullName>NZ-Fiji-BKRS</fullName>
                </value>
                <value>
                    <fullName>FACT-TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>Russia-1S</fullName>
                </value>
                <value>
                    <fullName>SouthKorea-DUZON</fullName>
                </value>
                <value>
                    <fullName>Dofiscal</fullName>
                </value>
                <value>
                    <fullName>LatAm</fullName>
                    <isActive>false</isActive>
                    <label>LatAm</label>
                </value>
                <value>
                    <fullName>TRIE</fullName>
                    <isActive>false</isActive>
                    <label>TRIE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
        <description>The proposal approval stage</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Primary__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the quote/proposal is the primary quote to update the related opportunity</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Proposal_Name__c</fullName>
        <label>Proposal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__ReadyToGenerate__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the proposal is ready for generation</description>
        <label>Ready To Generate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__BillToAccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the bill to account associated with the quote/proposal</description>
        <inlineHelpText>ID of the bill to account associated with the quote/proposal</inlineHelpText>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Bill To)</relationshipLabel>
        <relationshipName>QuotesBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__ShipToAccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the ship to account associated with the quote/proposal</description>
        <inlineHelpText>ID of the ship to account associated with the quote/proposal</inlineHelpText>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Ship To)</relationshipLabel>
        <relationshipName>QuotesShipTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>APTS_Proposal_Business_Unit__c</fullName>
        <label>Proposal Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>SCS</fullName>
                </value>
                <value>
                    <fullName>Russia-1S</fullName>
                </value>
                <value>
                    <fullName>SouthKorea-DUZON</fullName>
                </value>
                <value>
                    <fullName>Dofiscal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Digital_WS_GenerateDocumentTest.cls
/*
 * CHANGE HISTORY
 * ==================================================================================================================================
 * Date         Name                  Description
 * 2019-05-10   Navleen Kaur          DLT-16389 - Find Law- AEM call to set Correct template for Findlaw to SFDC during Generate Document
 * 17-12-2020   Rahul Natarajan       DLT-21120 - [TECH][SFDC][REN][NSE] Update New OrderForm template for all Renewal and New Sales proposals
 * ==================================================================================================================================   
 */
@istest
public class Digital_WS_GenerateDocumentTest {
	@testsetup
	public static void testdata() {
		Test.startTest();
		DCTestData.createData();
		Test.stopTest();

		Opportunity opp = [select id from Opportunity Limit 1];
		Account acc = [select id from Account Limit 1];
		Contact con = [select id from Contact Limit 1];
		List<Apttus_Proposal__Proposal__c > quoteList = new list<Apttus_Proposal__Proposal__c > ();

		Apttus_Proposal__Proposal__c q1 = new Apttus_Proposal__Proposal__c();
		q1.Apttus_Proposal__Proposal_Name__c = 'Quote 1';
		q1.Apttus_Proposal__Opportunity__c = opp.id;
		q1.Apttus_Proposal__Account__c = acc.id;
		q1.Apttus_QPConfig__BillToAccountId__c = acc.id;
		q1.Apttus_QPConfig__ShipToAccountId__c = acc.id;
		q1.Apttus_Proposal__Approval_Stage__c = 'Draft';
		q1.APTS_Order_Confirmation_Contact__c = con.id;
		q1.Apttus_Proposal__ReadyToGenerate__c = TRUE;
		q1.APTS_Proposal_Business_Unit__c = 'FindLaw';
		q1.Apttus_Proposal__Primary__c = true;
		quoteList.add(q1);

		Apttus_Proposal__Proposal__c q2 = new Apttus_Proposal__Proposal__c();
		q2.Apttus_Proposal__Proposal_Name__c = 'Quote 2';
		q2.Apttus_Proposal__Opportunity__c = opp.id;
		q2.Apttus_Proposal__Account__c = acc.id;
		q2.Apttus_QPConfig__BillToAccountId__c = acc.id;
		q2.Apttus_QPConfig__ShipToAccountId__c = acc.id;
		q2.Apttus_Proposal__Approval_Stage__c = 'Draft';
		q2.APTS_Order_Confirmation_Contact__c = con.id;
		q2.Apttus_Proposal__ReadyToGenerate__c = TRUE;
		q2.APTS_Proposal_Business_Unit__c = 'SCS';
		q2.Apttus_Proposal__Primary__c = true;
		quoteList.add(q2);
		insert quoteList;

		// create new cart
		list<Apttus_Config2__ProductConfiguration__c > cartList = new list<Apttus_Config2__ProductConfiguration__c > ();
		Apttus_Config2__ProductConfiguration__c newCart1 = new Apttus_Config2__ProductConfiguration__c();
		newCart1.Apttus_QPConfig__Proposald__c = quoteList[0].Id;
		newCart1.Apttus_Config2__Status__c = 'Finalized';
		cartList.add(newCart1);
		insert cartList;

		// create template - need more data than this
		List<Apttus__APTS_Template__c > listOfTemp = new List<Apttus__APTS_Template__c > ();
		Apttus__APTS_Template__c newTemplate = new Apttus__APTS_Template__c();
		newTemplate.Name = System.Label.Digital_OF;
		newTemplate.Apttus__IsActive__c = TRUE;
		newTemplate.Apttus__Type__c = 'Proposal';
		newTemplate.Apttus__ReferenceId__c = '0db18264-424c-a7fa-5058-680a594f5189';
		newTemplate.Apttus__Agreement_Types__c = 'Default;Proposal;RFP';
		newTemplate.Apttus__FrameworkFormat__c = 'FX2';
		listOfTemp.add(newTemplate);

		Apttus__APTS_Template__c newTemplate1 = new Apttus__APTS_Template__c();
		newTemplate1.Name = System.Label.Digital_FOF;
		newTemplate1.Apttus__IsActive__c = TRUE;
		newTemplate1.Apttus__Type__c = 'Proposal';
		newTemplate1.Apttus__ReferenceId__c = '0db18264-424c-a7fa-5058-680a594f5189';
		newTemplate1.Apttus__Agreement_Types__c = 'Default;Proposal;RFP';
		newTemplate1.Apttus__FrameworkFormat__c = 'FX2';
		listOfTemp.add(newTemplate1);
		Insert listOfTemp;
	}
	private static testmethod void testEnvelopeCreation() {
		Apttus_Proposal__Proposal__c quote = [SELECT id, APTS_Proposal_Business_Unit__c FROM Apttus_Proposal__Proposal__c WHERE APTS_Proposal_Business_Unit__c = 'SCS'
			LIMIT 1
		];
		Test.startTest();
		Digital_WS_GenerateDocument.DigitalResponse dr = new Digital_WS_GenerateDocument.DigitalResponse();
		dr = Digital_WS_GenerateDocument.doPost(quote.id);
		System.AssertEquals(dr.Status, 'Failure', 'Expected Value');
		Test.stopTest();
	}
	private static testmethod void testEnvelopeCreation1() {
		Apttus_Proposal__Proposal__c quote = [SELECT id, APTS_Proposal_Business_Unit__c FROM Apttus_Proposal__Proposal__c WHERE APTS_Proposal_Business_Unit__c = 'FindLaw'
			LIMIT 1
		];
		Test.startTest();
		Digital_WS_GenerateDocument.DigitalResponse dr = new Digital_WS_GenerateDocument.DigitalResponse();
		dr = Digital_WS_GenerateDocument.doPost(quote.id);
		System.AssertEquals(dr.Status, 'Failure', 'Expected Value');
		Test.stopTest();
	}
	private static testmethod void testNegative() {
		List<Apttus__APTS_Template__c > listOfTemp = [select id from Apttus__APTS_Template__c where Name =:System.Label.Digital_FOF];
		delete listOfTemp;
		Apttus_Proposal__Proposal__c quote = [SELECT id, APTS_Proposal_Business_Unit__c FROM Apttus_Proposal__Proposal__c WHERE APTS_Proposal_Business_Unit__c = 'FindLaw'
			LIMIT 1
		];
		Test.startTest();
		Digital_WS_GenerateDocument.DigitalResponse dr = new Digital_WS_GenerateDocument.DigitalResponse();
		dr = Digital_WS_GenerateDocument.doPost(quote.id);
		System.AssertEquals(dr.Status, null, 'Expected Value');
		Test.stopTest();
	}
}