objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>APTS_Availability_Date__c</fullName>
        <formula>Apttus_Config2__ProductId__r.APTS_Availability_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Availability Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Contract_Term_Number__c</fullName>
        <formula>CASE( 
TEXT( APTS_Contract_Term__c ), 
&quot;1 Month&quot;, 1, 
&quot;2 Months&quot;, 2, 
&quot;3 Months&quot;, 3, 
&quot;4 Months&quot;, 4, 
&quot;5 Months&quot;, 5, 
&quot;6 Months&quot;, 6, 
&quot;7 Months&quot;, 7, 
&quot;8 Months&quot;, 8, 
&quot;9 Months&quot;, 9, 
&quot;10 Months&quot;, 10, 
&quot;11 Months&quot;, 11, 
&quot;1 Year&quot;,12, 
&quot;2 Years&quot;,24, 
&quot;3 Years&quot;,36,
&quot;4 Years&quot;,48, 
&quot;5 Years&quot;,60, 
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Term Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Contract_Term__c</fullName>
        <label>Contract Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 Year</fullName>
                </value>
                <value>
                    <fullName>2 Years</fullName>
                </value>
                <value>
                    <fullName>3 Years</fullName>
                </value>
                <value>
                    <fullName>4 Years</fullName>
                </value>
                <value>
                    <fullName>5 Years</fullName>
                </value>
                <value>
                    <fullName>1 Month</fullName>
                </value>
                <value>
                    <fullName>2 Months</fullName>
                </value>
                <value>
                    <fullName>3 Months</fullName>
                </value>
                <value>
                    <fullName>4 Months</fullName>
                </value>
                <value>
                    <fullName>5 Months</fullName>
                </value>
                <value>
                    <fullName>6 Months</fullName>
                </value>
                <value>
                    <fullName>7 Months</fullName>
                </value>
                <value>
                    <fullName>8 Months</fullName>
                </value>
                <value>
                    <fullName>9 Months</fullName>
                </value>
                <value>
                    <fullName>10 Months</fullName>
                </value>
                <value>
                    <fullName>11 Months</fullName>
                </value>
                <value>
                    <fullName>Short Term Trial</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>n/a</fullName>
                </value>
                <value>
                    <fullName>10 Years</fullName>
                    <isActive>false</isActive>
                    <label>10 Years</label>
                </value>
                <value>
                    <fullName>Short Term</fullName>
                    <isActive>false</isActive>
                    <label>Short Term</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_FL_Renewal_Only_Clone__c</fullName>
        <description>Formula is modified as per Corporate requirement for template for old and new versioned product (DOC-8034): When contract term is None or 1 year, value of this field is Apttus_Config2__ProductId__r.APTS_FL_Renewal_Only_Clone__c.For all other contract term values it is blank.</description>
        <formula>IF(OR(APTS_Proposal_Business_Unit__c==&apos;Corp OneOTC US&apos;,APTS_Proposal_Business_Unit__c==&apos;Corp OneOTC UK&apos;),IF(OR(APTS_Contract_Term_Number__c==0,APTS_Contract_Term_Number__c==12),TEXT( Apttus_Config2__ProductId__r.APTS_FL_Renewal_Only_Clone__c ),&apos;&apos;),(TEXT( Apttus_Config2__ProductId__r.APTS_FL_Renewal_Only_Clone__c )))</formula>
        <label>Renewal Only/Old Versions</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Name__c</fullName>
        <formula>IF( Apttus_Config2__OptionId__c &lt;&gt;&apos;&apos;, Apttus_Config2__OptionId__r.Name , Apttus_Config2__ProductId__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Proposal_Business_Unit__c</fullName>
        <formula>TEXT(Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.APTS_Proposal_Business_Unit__c )</formula>
        <label>Proposal Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Renewal_Type__c</fullName>
        <label>Renewal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Renew</fullName>
                </value>
                <value>
                    <fullName>Evergreen</fullName>
                </value>
                <value>
                    <fullName>Term Commitment</fullName>
                </value>
                <value>
                    <fullName>Non-Renewable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Yr_2_Amount__c</fullName>
        <description>Created as part of DOC-3563</description>
        <label>Yr 2 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BasePrice__c</fullName>
        <description>The base price is List price + Automatic Adjustments for individual products and options</description>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ChargeType__c</fullName>
        <description>The charge type  associated with the product or service</description>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Price</fullName>
                </value>
                <value>
                    <fullName>License Fee</fullName>
                </value>
                <value>
                    <fullName>Subscription Fee</fullName>
                </value>
                <value>
                    <fullName>Implementation Fee</fullName>
                </value>
                <value>
                    <fullName>Installation Fee</fullName>
                </value>
                <value>
                    <fullName>Maintenance Fee</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Shipping &amp; Handling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EndDate__c</fullName>
        <description>The end date for products and services</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineStatus__c</fullName>
        <description>The line status</description>
        <label>Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Incremented</fullName>
                </value>
                <value>
                    <fullName>Upgraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceType__c</fullName>
        <description>The price type</description>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
                <value>
                    <fullName>Included Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>APTS_Proposal_Business_Unit__c</fullName>
        <formula>TEXT( Apttus_QPConfig__Proposald__r.APTS_Proposal_Business_Unit__c )</formula>
        <label>Proposal Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_QPConfig__Proposald__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the quote/proposal associated with the configuration</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>APTS_Proposal_Business_Unit__c</fullName>
        <label>Proposal Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SCS</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>Corp OneOTC US</fullName>
                </value>
                <value>
                    <fullName>Corp OneOTC UK</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Tax Professional</fullName>
                </value>
                <value>
                    <fullName>Argentina-LLEY</fullName>
                </value>
                <value>
                    <fullName>Brazil-TSL</fullName>
                </value>
                <value>
                    <fullName>Hong Kong-SMHK</fullName>
                </value>
                <value>
                    <fullName>India-INWL</fullName>
                </value>
                <value>
                    <fullName>Australia-PNG-LRA</fullName>
                </value>
                <value>
                    <fullName>NZ-Fiji-BKRS</fullName>
                </value>
                <value>
                    <fullName>FACT-TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>Russia-1S</fullName>
                </value>
                <value>
                    <fullName>SouthKorea-DUZON</fullName>
                </value>
                <value>
                    <fullName>Dofiscal</fullName>
                </value>
                <value>
                    <fullName>LatAm</fullName>
                    <isActive>false</isActive>
                    <label>LatAm</label>
                </value>
                <value>
                    <fullName>TRIE</fullName>
                    <isActive>false</isActive>
                    <label>TRIE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Renewal_Type__c</fullName>
        <label>Renewal Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Availability_Date__c</fullName>
        <label>Availability Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_FL_Renewal_Only_Clone__c</fullName>
        <description>The Values are set for Renewal Only Bundle Clone</description>
        <label>Renewal Only/Old Versions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Price_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <description>WS call for CORP non-simplified Products</description>
        <label>Price Call</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/APTS_CORP_Validation_CallbackHelper.cls
/**
* Extended Validation Callback class for Corporate 
*
* @author  TCS
* @version 2019-04-08
*/
/**
* CHANGE HISTORY
* =============================================================================
* Date         Name                    Description
* 2019-04-08  Kruti Shah               Created
* =============================================================================
*/
global with sharing class APTS_CORP_Validation_CallbackHelper {
    
    public Apttus_Config2.CustomClass.ValidationResult validateCart(Apttus_Config2.ProductConfiguration cart) {
        Apttus_Config2.CustomClass.ValidationResult result= new Apttus_Config2.CustomClass.ValidationResult(true); 
        Apttus_Config2__ProductConfiguration__c Productconfig = New Apttus_Config2__ProductConfiguration__c();
        List<Apttus_Config2__LineItem__c> lineItems = new List<Apttus_Config2__LineItem__c>();
        String priceCallProductNames;
        Integer bridgemonths;         
        Boolean dollarAmountsIncomplete;   
        String bridgeDaysProductNames;
        //Start: Added by Kruti Shah (DOC-10107)
        set<String> restrictedBridgeValues = new set<String>();
        restrictedBridgeValues.add('7 Days');
        restrictedBridgeValues.add('14 Days');
        restrictedBridgeValues.add('28 Days');
        restrictedBridgeValues.add('N/a');
        //End: Added by Kruti Shah (DOC-10107)
        if(!Schema.sObjectType.Apttus_Config2__ProductConfiguration__c.isAccessible() && !Schema.sObjectType.Apttus_Config2__ProductConfiguration__c.isQueryable()){
            return null;}        
        Productconfig = [Select ID,Apttus_QPConfig__Proposald__r.APTS_Proposal_Business_Unit__c 
                         from Apttus_Config2__ProductConfiguration__c 
                         where ID =:cart.getConfigSO().Id];
                         
        if(!Schema.sObjectType.Apttus_Config2__LineItem__c.isAccessible() && !Schema.sObjectType.Apttus_Config2__LineItem__c.isQueryable()){
            return null;}
        
                                           lineItems = [SELECT Apttus_Config2__EndDate__c,APTS_Product_Name__c,APTS_Proposal_Business_Unit__c,APTS_Availability_Date__c,
                                                       Apttus_Config2__ProductId__c,Apttus_Config2__LineStatus__c,APTS_Contract_Term__c,                                                                
                                                       Apttus_Config2__ChargeType__c, Apttus_Config2__PriceType__c,Apttus_Config2__ProductId__r.APTS_Availability_Date__c,
                                                       Apttus_Config2__ProductId__r.APTS_FL_Renewal_Only_Clone__c,APTS_Contract_Term_Number__c,
                                                       Apttus_Config2__ProductId__r.Name,APTS_Renewal_Type__c,Apttus_Config2__ProductId__r.APTS_Price_Call__c,Apttus_Config2__BasePrice__c,
                                                       APTS_Yr_2_Amount__c,APTS_Yr_3_Amount__c,APTS_Yr_4_Amount__c,APTS_Yr_5_Amount__c,APTS_Term_Type__c,APTS_Bridge__c,Apttus_Config2__StartDate__c
                                                       ,APTS_Bridge_Eligibility__c,APTS_Start_Date__c,APTS_Years_2_Plus_Adjustment__c
                                                       FROM Apttus_Config2__LineItem__c 
                                                       WHERE Apttus_Config2__ConfigurationId__c = :cart.getConfigSO().Id];
        
         for(Apttus_Config2__LineItem__c lineItem : lineItems){          
            dollarAmountsIncomplete=false;
          if(lineItem.APTS_Proposal_Business_Unit__c != 'Tax Professional'&& lineItem.APTS_Proposal_Business_Unit__c != 'Canada' && lineItem.APTS_Proposal_Business_Unit__c != 'SCS'){
              System.debug('Inside Term Number Block');
                if(lineItem.APTS_Contract_Term_Number__c !=null 
                    &&( lineItem.Apttus_Config2__ProductId__r.APTS_FL_Renewal_Only_Clone__c != null
                    && lineItem.Apttus_Config2__ProductId__r.APTS_FL_Renewal_Only_Clone__c == 'Yes'))
              {                       
                system.debug('KS-->APTS_Contract_Term_Number__c '+lineItem.APTS_Contract_Term_Number__c);          
                if(lineItem.APTS_Contract_Term_Number__c > 12){
                    //result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error, 'Contract Term must be 1 year for past version products.'));                
                    //result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error, 'Contract Term must be 1 year for past version products : \''+lineItem.Apttus_Config2__ProductId__r.Name  +'\' '));
                     result.Messages.add(new ApexPages.Message(ApexPages.Severity.INFO, 'Do not create a multi year contract for expired version except for fiscal filers : \''+lineItem.Apttus_Config2__ProductId__r.Name  +'\' '));
                    //result.isSuccess = false;                  
                    //return result; 
                }
              }
              
                if(lineItem.APTS_Contract_Term_Number__c !=null 
                && lineItem.APTS_Renewal_Type__c !=null && lineItem.APTS_Renewal_Type__c=='Evergreen')                  
              {                       
                system.debug('KS-->APTS_Contract_Term_Number__c '+lineItem.APTS_Contract_Term_Number__c);          
                if(lineItem.APTS_Contract_Term_Number__c > 12){             
                    result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error, Label.APTS_ValidationCallbackMessage + '\''+lineItem.Apttus_Config2__ProductId__r.Name  +'\' '));
                    result.isSuccess = false;                  
                    return result; 
                }
              }
              if(lineItem.APTS_Contract_Term_Number__c !=null && (lineItem.Apttus_Config2__LineStatus__c == 'New' || lineItem.Apttus_Config2__LineStatus__c == 'Renewed')){
                 if(lineItem.APTS_Contract_Term_Number__c==36){
                     if((lineItem.APTS_Yr_2_Amount__c!=null && lineItem.APTS_Yr_3_Amount__c==null) || (lineItem.APTS_Yr_2_Amount__c==null && lineItem.APTS_Yr_3_Amount__c!=null))
                        dollarAmountsIncomplete=true;
                 }else if(lineItem.APTS_Contract_Term_Number__c==48){
                      if((lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null) && (lineItem.APTS_Yr_2_Amount__c==null || lineItem.APTS_Yr_3_Amount__c==null || lineItem.APTS_Yr_4_Amount__c==null)){
                          dollarAmountsIncomplete=true;
                      }
                 }else if(lineItem.APTS_Contract_Term_Number__c==60){
                      if((lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null) && (lineItem.APTS_Yr_2_Amount__c==null || lineItem.APTS_Yr_3_Amount__c==null || lineItem.APTS_Yr_4_Amount__c==null || lineItem.APTS_Yr_5_Amount__c==null)){
                           dollarAmountsIncomplete=true;
                      }
                 }
              }
            }
            //DOC-7883 Roma Starts
              if(lineItem.APTS_Proposal_Business_Unit__c == 'Tax Professional'){ 
                    
                    if((lineItem.APTS_Contract_Term_Number__c ==null || String.valueOf(lineItem.APTS_Contract_Term_Number__c) =='' ||lineItem.Apttus_Config2__ChargeType__c !='Subscription Fee' ) && (lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null)){
                        dollarAmountsIncomplete=true;
                    }
                    else{  
                        if(lineItem.APTS_Contract_Term_Number__c !=null && lineItem.Apttus_Config2__LineStatus__c != null && (lineItem.Apttus_Config2__LineStatus__c == 'New' || lineItem.Apttus_Config2__LineStatus__c == 'Renewed')){
                            if(lineItem.APTS_Contract_Term_Number__c==12){
                                if(lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null)
                                    dollarAmountsIncomplete=true;                                
                            }                            
                            else if(lineItem.APTS_Contract_Term_Number__c==24){
                                if(lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null)
                                    dollarAmountsIncomplete=true;                                
                            }                            
                            else if(lineItem.APTS_Contract_Term_Number__c==36){
                                if((lineItem.APTS_Yr_2_Amount__c!=null && lineItem.APTS_Yr_3_Amount__c==null) || (lineItem.APTS_Yr_2_Amount__c==null && lineItem.APTS_Yr_3_Amount__c!=null) || (lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null))
                                    dollarAmountsIncomplete=true;
                            }
                            else if(lineItem.APTS_Contract_Term_Number__c==48){
                                system.debug('APTS_Contract_Term_Number__c--'+lineItem.APTS_Contract_Term_Number__c);
                                if(((lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null) && (lineItem.APTS_Yr_2_Amount__c==null || lineItem.APTS_Yr_3_Amount__c==null || lineItem.APTS_Yr_4_Amount__c==null)) || lineItem.APTS_Yr_5_Amount__c!=null ){
                                    dollarAmountsIncomplete=true;
                                    system.debug('APTS_Contract_Term_Number__c--'+lineItem.APTS_Contract_Term_Number__c);
                                }
                            }else if(lineItem.APTS_Contract_Term_Number__c==60){
                                if((lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null) && (lineItem.APTS_Yr_2_Amount__c==null || lineItem.APTS_Yr_3_Amount__c==null || lineItem.APTS_Yr_4_Amount__c==null || lineItem.APTS_Yr_5_Amount__c==null)){
                                    dollarAmountsIncomplete=true;
                                }
                            }
                        } 
                    }  
                    //DOC-9921,DOC-9923 : Added by Nandha : Starts Here
                    if(lineItem.APTS_Term_Type__c != NULL){ 
                        if(lineItem.APTS_Bridge__c == '1 Month' || lineItem.APTS_Bridge__c == '2 Months' || lineItem.APTS_Bridge__c == '3 Months' || lineItem.APTS_Bridge__c == '4 Months' || lineItem.APTS_Bridge__c == '5 Months' || lineItem.APTS_Bridge__c == '6 Months' || lineItem.APTS_Bridge__c == '7 Months' || lineItem.APTS_Bridge__c == '8 Months' || lineItem.APTS_Bridge__c == '9 Months'){
                            bridgemonths = integer.valueof(lineItem.APTS_Bridge__c.left(1));
                        }else if(lineItem.APTS_Bridge__c == '10 Months' || lineItem.APTS_Bridge__c == '11 Months'){
                            bridgemonths = integer.valueof(lineItem.APTS_Bridge__c.left(2));
                        }
                        if((lineItem.APTS_Term_Type__c == 'Co-Term' || lineItem.APTS_Term_Type__c == 'Future Start Date and Co-Term') && lineItem.Apttus_Config2__StartDate__c != NULL && lineItem.Apttus_Config2__EndDate__c != NULL && bridgemonths == NULL && (((lineItem.Apttus_Config2__StartDate__c.monthsBetween(lineItem.Apttus_Config2__EndDate__c)) + 1) > 11)){
                            result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error,'End Date for a Co-term must be less than a year. Please adjust End Date.'));
                            result.isSuccess = false;  
                            return result;
                        }
                        else if(lineItem.APTS_Term_Type__c == 'Co-Term' && lineItem.APTS_Bridge__c != NULL && (lineItem.APTS_Bridge__c == '1 Month' || lineItem.APTS_Bridge__c == '2 Months' || lineItem.APTS_Bridge__c == '3 Months' || lineItem.APTS_Bridge__c == '4 Months' || lineItem.APTS_Bridge__c == '5 Months' || lineItem.APTS_Bridge__c == '6 Months' || lineItem.APTS_Bridge__c == '7 Months' || lineItem.APTS_Bridge__c == '8 Months' || lineItem.APTS_Bridge__c == '9 Months' || lineItem.APTS_Bridge__c == '10 Months' || lineItem.APTS_Bridge__c == '11 Months')){ 
                            result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error,'Bridge is not applicable with Co-term. Please select Term Type= Future Start Date and Co-Term'));
                            result.isSuccess = false;  
                            return result;
                        }
                        else if(lineItem.APTS_Term_Type__c == 'Future Start Date and Co-Term' && lineItem.Apttus_Config2__StartDate__c != NULL && lineItem.APTS_Bridge__c != NULL){ 
                            if(lineItem.Apttus_Config2__StartDate__c != NULL && bridgemonths != NULL && lineItem.Apttus_Config2__StartDate__c != System.Date.today().addMonths(1).addMonths(bridgemonths).toStartOfMonth()){
                                result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error,'Please select Start Date which is 1st of the Month after Bridge Period Ends'));
                                result.isSuccess = false;  
                                return result;
                            }
                            else if(lineItem.Apttus_Config2__StartDate__c != NULL && lineItem.Apttus_Config2__EndDate__c != NULL && bridgemonths != NULL && ((lineItem.Apttus_Config2__StartDate__c.monthsBetween(lineItem.Apttus_Config2__EndDate__c) + 1 + bridgemonths) > 11)){
                                result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error,'Please select End Date which do not exceed more than 11 Months from the Bridge Start Date'));
                                result.isSuccess = false;  
                                return result;
                            }
                        }
                    }
                    //DOC-9921,DOC-9923 : Added by Nandha : Ends Here
                    
                    //Start: Added by Kruti Shah (DOC-10107)
                    System.debug('KS-->lineItem.APTS_Bridge__c '+lineItem.APTS_Bridge__c);
                    System.debug('KS-->lineItem.APTS_Bridge_Eligibility__c '+lineItem.APTS_Bridge_Eligibility__c);
                    
                    if(lineItem.APTS_Bridge__c != null && lineItem.APTS_Bridge_Eligibility__c != null 
                       && lineItem.APTS_Bridge_Eligibility__c == 'Yes' && restrictedBridgeValues.contains(lineItem.APTS_Bridge__c) ){
                           if(bridgeDaysProductNames==null)
                               bridgeDaysProductNames=lineItem.Apttus_Config2__ProductId__r.Name;
                           else if(!bridgeDaysProductNames.contains(lineItem.Apttus_Config2__ProductId__r.Name))
                               bridgeDaysProductNames=bridgeDaysProductNames+','+lineItem.Apttus_Config2__ProductId__r.Name;
                       }
                    
                    if(bridgeDaysProductNames != null){
                        System.debug('KS--> Inside Bridge Validation for TAx Professional');
                        result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error, 'Bridge for 7/14/28 days not applicable for \''+bridgeDaysProductNames  +'\' '+'. Please reselect Bridge in Months or select "None" and Reprice."'));
                        result.isSuccess = false;                  
                        return result;
                    }
                    //End: Added by Kruti Shah (DOC-10107)                 
          }
          //Added as part of DOC-12660 for Risk Spree Wave2
          if(lineItem.APTS_Proposal_Business_Unit__c != null && System.Label.Risk_PBUs.contains(lineItem.APTS_Proposal_Business_Unit__c)){
              System.debug('Inside Risk Block');
              if((lineItem.APTS_Term_Type__c != NULL && lineItem.APTS_Term_Type__c == 'Delivery Date') && lineItem.APTS_Start_Date__c == NULL){
                  result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error,'Please ensure Start Date is populated as Term Type selected is Delivery Date'));
                  result.isSuccess = false;  
                  return result;
              }
          }          
          if(lineItem.APTS_Proposal_Business_Unit__c == 'Canada' || lineItem.APTS_Proposal_Business_Unit__c == 'SCS'){ 
          System.debug('Inside Canada or SCS validation');
          //Added as part of DOC-13241
              if(lineItem.APTS_Years_2_Plus_Adjustment__c != NULL && lineItem.APTS_Yr_2_Amount__c != NULL){
                  result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error,'You must use either YOY 2+% or the Ramped Pricing fields. Please update your line items accordingly.'));
                  result.isSuccess = false;  
                  return result;
              }
              if((lineItem.APTS_Contract_Term_Number__c ==null || String.valueOf(lineItem.APTS_Contract_Term_Number__c) =='') && (lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null)){
                        dollarAmountsIncomplete=true;
                    }
                    else{  
                        if(lineItem.APTS_Contract_Term_Number__c !=null && lineItem.Apttus_Config2__LineStatus__c != null && (lineItem.Apttus_Config2__LineStatus__c == 'New' || lineItem.Apttus_Config2__LineStatus__c == 'Renewed')){
                            if(lineItem.APTS_Contract_Term_Number__c==12){
                                if(lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null)
                                    dollarAmountsIncomplete=true;                                
                            }                            
                            else if(lineItem.APTS_Contract_Term_Number__c==24){
                                if(lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null)
                                    dollarAmountsIncomplete=true;                                
                            }                            
                            else if(lineItem.APTS_Contract_Term_Number__c==36){
                                if((lineItem.APTS_Yr_2_Amount__c!=null && lineItem.APTS_Yr_3_Amount__c==null) || (lineItem.APTS_Yr_2_Amount__c==null && lineItem.APTS_Yr_3_Amount__c!=null) || (lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null))
                                    dollarAmountsIncomplete=true;
                            }
                            else if(lineItem.APTS_Contract_Term_Number__c==48){
                                system.debug('APTS_Contract_Term_Number__c--'+lineItem.APTS_Contract_Term_Number__c);
                                if(((lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null) && (lineItem.APTS_Yr_2_Amount__c==null || lineItem.APTS_Yr_3_Amount__c==null || lineItem.APTS_Yr_4_Amount__c==null)) || lineItem.APTS_Yr_5_Amount__c!=null ){
                                    dollarAmountsIncomplete=true;
                                    system.debug('APTS_Contract_Term_Number__c--'+lineItem.APTS_Contract_Term_Number__c);
                                }
                            }else if(lineItem.APTS_Contract_Term_Number__c==60){
                                if((lineItem.APTS_Yr_2_Amount__c!=null || lineItem.APTS_Yr_3_Amount__c!=null || lineItem.APTS_Yr_4_Amount__c!=null || lineItem.APTS_Yr_5_Amount__c!=null) && (lineItem.APTS_Yr_2_Amount__c==null || lineItem.APTS_Yr_3_Amount__c==null || lineItem.APTS_Yr_4_Amount__c==null || lineItem.APTS_Yr_5_Amount__c==null)){
                                    dollarAmountsIncomplete=true;
                                }
                            }
                        } 
                    }
          
          }
          if(dollarAmountsIncomplete){
                result.Messages.add(new ApexPages.Message(ApexPages.Severity.Error, Label.APTS_MultiTieredPricingIncomplete));
                result.isSuccess = false;                  
                return result;
             }
        }
        return result;
    }
    
}