objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_ID__c</fullName>
        <description>TW SAP Account Number</description>
        <externalId>true</externalId>
        <label>SAP Contact ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRMOD URL</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product_Trial__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Trials</relationshipLabel>
        <relationshipName>Product_Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product Trials</relationshipLabel>
        <relationshipName>Product_Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Trial</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Trial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trial_User__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Trial Users</relationshipLabel>
        <relationshipName>Trial_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Trial__c</fullName>
        <label>Product Trial</label>
        <referenceTo>Product_Trial__c</referenceTo>
        <relationshipLabel>Trial Users</relationshipLabel>
        <relationshipName>Trial_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_ID__c</fullName>
        <label>SAP Contact ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Trial User</label>
    <nameField>
        <label>Trial User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProductTrialTriggerHandler.cls
Public class ProductTrialTriggerHandler{
    public static Boolean flag = true;
    public static Boolean recflag = true;
    public static void UpdateAccountOnTrial(List<Product_Trial__c> listProductTrials){
        Map<Id,Opportunity> MapOpportunity = new Map<Id,Opportunity>();
        Set<Id> ProductTrialOptyIds = new Set<Id>();
        
        for(Product_Trial__c oProductTrial : listProductTrials){
            ProductTrialOptyIds.add(oProductTrial.Opportunity__c);
        }
        
        MapOpportunity = new Map<Id,Opportunity>([Select Id,AccountId,OwnerId from Opportunity where Id IN : ProductTrialOptyIds]);

       for(Product_Trial__c oProductTrial : listProductTrials){
          if(MapOpportunity.containskey(oProductTrial.Opportunity__c)){
                    oProductTrial.Account__c = MapOpportunity.get(oProductTrial.Opportunity__c).AccountId;
                    oProductTrial.OwnerId = MapOpportunity.get(oProductTrial.Opportunity__c).OwnerId;
          }else{
              oProductTrial.Account__c = null;
          }
      }
    }
    
    public static void InsertTrialUsers(List<Product_Trial__c> listProductTrials){
        Map<Id,List<OpportunityContactRole>> MapOppContacts = new Map<Id,List<OpportunityContactRole>>();
        Set<Id> ProductTrialOptyIds = new Set<Id>();
        List<Trial_User__c> listTrialUsersInsert = new List<Trial_User__c>();
        List<Trial_User__c> ListTrialUsers = new List<Trial_User__c>();
        Map<Id,Set<String>> mapTrialUsers = new Map<Id,Set<String>>(); 
        ListTrialUsers = [Select Product_Trial__c,Contact__c from Trial_User__c where Product_Trial__c IN :listProductTrials];
        
        for(Trial_User__c oTrialUser : ListTrialUsers){
                if(!mapTrialUsers.containskey(oTrialUser.Product_Trial__c)){
                    mapTrialUsers.put(oTrialUser.Product_Trial__c,new Set<String>{oTrialUser.Contact__c});
                }else{
                    mapTrialUsers.get(oTrialUser.Product_Trial__c).add(oTrialUser.Contact__c);
                }
        }
        
        for(Product_Trial__c oProductTrial : listProductTrials){
            ProductTrialOptyIds.add(oProductTrial.Opportunity__c);
        }
        
        for(OpportunityContactRole oOpportunityContact : [Select ContactId,Contact.FirstName,Contact.LastName,Contact.Email,OpportunityId,Role,Contact.SAP_Contact_ID__c from OpportunityContactRole where OpportunityId IN : ProductTrialOptyIds and Role='Trial User']){
            if(!MapOppContacts.containskey(oOpportunityContact.OpportunityId)){
               MapOppContacts.put(oOpportunityContact.OpportunityId,new OpportunityContactRole[]{oOpportunityContact});
             }else{
                 MapOppContacts.get(oOpportunityContact.OpportunityId).add(oOpportunityContact);
             }
        
        }
        
        if(!MapOppContacts.IsEmpty()){
            for(Product_Trial__c oProductTrial : listProductTrials){
                for(OpportunityContactRole oOpportunityContact : MapOppContacts.get(oProductTrial.Opportunity__c)){
                if(MapTrialUsers.IsEmpty() || !MapTrialUsers.get(oProductTrial.Id).contains(oOpportunityContact.Contact.Id)){
                        Trial_User__c oTrialUser = new Trial_User__c(Name = oOpportunityContact.Contact.FirstName+' '+oOpportunityContact.Contact.LastName );
                        oTrialUser.Product_Trial__c = oProductTrial.Id;
                        oTrialUser.First_Name__c = oOpportunityContact.Contact.FirstName;
                        oTrialUser.Last_Name__c = oOpportunityContact.Contact.LastName;
                        oTrialUser.Email__c = oOpportunityContact.Contact.Email;
                        oTrialUser.Contact__c = oOpportunityContact.ContactId;
                        listTrialUsersInsert.add(oTrialUser);
                    }
                }
                insert listTrialUsersInsert;
            }
      }
    }
}