objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU_Region__c</fullName>
        <description>Created as part of DPS-2200, should hold Account&apos;s BU Region value</description>
        <formula>Account.BU_Region__c</formula>
        <label>BU Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU_Segment__c</fullName>
        <description>Created as part of DPS-2200, should hold Account&apos;s BU Segment value</description>
        <formula>TEXT(Account.Bu_Segment__c)</formula>
        <label>Frozen Market Current Year Segment L1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Account_Is_Archived__c</fullName>
        <description>This checkbox denotes whether the account associated with this contact is archived.
Gurvinder Virdi(27APR2016): Changes done for SFD-506, should satisfy only for LaTam Sales Org.</description>
        <formula>IF( 
AND(
Account.RecordType.Name == &apos;Archive&apos;,
OR(
ISPICKVAL(Account.Sales_Org__c, &apos;LLEY&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;BEJE&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;ABEP&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;RV01&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;TSL&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;LPCL&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;LPTC&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;LLUR&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;LLPA&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;SSRL&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;TGPS&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;TSCE&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;SCSI&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;SFWS&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;EDIC&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;WEST&apos;),
ISPICKVAL(Account.Sales_Org__c, &apos;GSI&apos;)
)), 
TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Identifies that this Contacts Account is Archived.</inlineHelpText>
        <label>Contact Account Is Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is for capturing if a contact is Active/Inactive as per GLI</description>
        <label>Contact Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ESC_tocContactStatus__c</fullName>
        <inlineHelpText>Shows if user is Active or Inactive.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current user</fullName>
                </value>
                <value>
                    <fullName>GSLA Qualified User</fullName>
                </value>
                <value>
                    <fullName>Left Account</fullName>
                </value>
                <value>
                    <fullName>Non user</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Ex-user</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_Is_GLI__c</fullName>
        <formula>Account.Is_GLI__c</formula>
        <label>Is GLI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for Contact</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LJUU</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>WEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ESC_segment_Region_Lotus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>RegionUSLegal__c</fullName>
        <label>RegionUSLegal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ESC Segment Region Lotus</label>
</CustomObject>

classes/ESC_CaseContactAssociation.cls
/**
* CHANGE HISTORY
* =============================================================================
* Date         Name                    Description
* 2017-08-07   AjayG                   Added GGO related lists and soql queries
* =============================================================================
*/
/**
 * @description ESC_CaseContactAssociation class
 */
public without sharing class ESC_CaseContactAssociation{
    
    /*
This method will be invoked by Case process builder for Case association to Account/Contact
based on the status of the contact(Cases created by Web2case,Email2Case)
*/
 /**
 * @description getContacttoCaseonCreation method
 * @param cases
 */   
    @InvocableMethod(label='Update Contact on Case' description='Update case')
    public static void getContacttoCaseonCreation(List<Case> cases){
        //Dss-6256 hardcoding removal
        //
        ESC_segment_Region_Lotus__c srl = ESC_segment_Region_Lotus__c.getOrgDefaults();
        //if list is empty lets keep it nothing
        if(cases == null || cases.isEmpty()){
            return;
        }
        List<String> lstemail = new List<String>();
        List<String> gliEmail = new List<String>();
        //  List<String> Lotusemail = new List<String>();
        List<String> buSegment = new List<String>();
        List<String> buRegion = new List<String>();
        List<String> ggoEmail = new List<String>();       
        map<string,List<contact>> mapcon=new Map<string,List<contact>>();
        List<Contact> lstcon=new List<Contact>();
        List<String> lstActTaxType= new List<String>();
        List<String> lstActTaxNum= new List<String>();
        List<Case> lstupdatecase = new List<case>();
        string taxNumbertype='';
        string taxNumber='';
        Boolean nonGLI = false;
        Boolean ggoContact= False;
        
        map<string,List<contact>> preMapcon=new Map<string,List<contact>>();
        List<Contact> lstcon1=new List<Contact>();
        List<Contact> lstcon2=new List<Contact>();
        
        for(Case si:cases){
            system.debug(logginglevel.warn,'supplied email'+si.SuppliedEmail+'@@@'+'is gli is'+si.Is_GLI__c);
            if(si.SuppliedEmail!=null && si.Is_GLI__c){
                gliEmail.add(si.SuppliedEmail);
                if(si.BU_Segment__c!=null && si.LCRM_Sub_Bu__c!=null){
                    buSegment.add(si.BU_Segment__c);
                    buRegion.add(si.LCRM_Sub_Bu__c);
                }
            }
            else if(si.ContactId==null && si.SuppliedEmail!=null && si.LCRM_Sub_BU__c!= null && (si.LCRM_Sub_BU__c!= 'USL'||si.LCRM_Sub_BU__c!= srl.RegionUSLegal__c )&& si.LCRM_Sub_BU__c!='GGO'){
                lstemail.add(si.SuppliedEmail);
                
            }
            
            else if(si.ContactId==null && si.SuppliedEmail!=null && si.LCRM_Sub_BU__c=='GGO' && si.Origin=='Email'){
                lstemail.add(si.SuppliedEmail);
                ggoContact=True;
            }
            else if(si.ContactId==null && si.SuppliedEmail!=null && si.LCRM_Sub_BU__c=='GGO' && si.Origin=='Web'){
                ggoEmail.add(si.SuppliedEmail);
                taxNumbertype=si.Description.substringBetween(Schema.case.fields.GGO_Tax_Number_Type__c.getDescribe().getLabel()+': ','; '+Schema.case.fields.GGO_Tax_Number__c.getDescribe().getLabel());
                taxNumber=si.Description.substringBetween(Schema.case.fields.GGO_Tax_Number__c.getDescribe().getLabel()+': ','; '+Schema.case.fields.SuppliedEmail.getDescribe().getLabel());    
                lstActTaxType.add(taxNumbertype);   
                lstActTaxNum.add(taxNumber);  
                ggoContact=True;
            }
            
        }
        
        if(gliEmail.size()>0 && (buSegment.isEmpty() || buRegion.isEmpty())){
            lstCon = [select Contact_Account_Is_Archived__c,id,ESC_tocContactStatus__c,Contact_Inactive__c,phone,Email,AccountId,LCRM_Is_GLI__c,Account.Sales_Org__c from contact where email IN :gliEmail and LCRM_Is_GLI__c=true and Account.Sales_Org__c='GLI'];
            if(lstcon.size()==0){
                nonGLI=true;
            }
        }
        else if(gliEmail.size()>0 && !buSegment.isEmpty() && !buRegion.isEmpty()){
            system.debug(logginglevel.warn,'buSegment is'+buSegment +'@@@@@'+'buRegion is'+buRegion);

            lstCon2 = [select Contact_Account_Is_Archived__c,id,ESC_tocContactStatus__c,Contact_Inactive__c,phone,Email,AccountId,LCRM_Is_GLI__c,Account.Sales_Org__c from contact where email IN :gliEmail and LCRM_Is_GLI__c=true and Account.Sales_Org__c='GLI'];

            //Start
            for(contact c : lstCon2)
            {
                if(c.email!=null){
                    if(preMapcon.containsKey(c.email)){
                        preMapcon.get(c.email).add(c);
                    }else{
                        preMapcon.put(c.email,new List<Contact>{c});
                    }
                }
            }
            
            List<id> conids = new List<id>();
            
            for(String conEmailId : preMapcon.keySet())
            {
                List<Contact> conEmails = preMapcon.get(conEmailId);
                
                if(conEmails.size() > 1)
                {
                 for(contact con : conEmails){
                    conids.add(con.id);
                    }
                }
                else
                {
                    lstCon.addAll(conEmails);
                }
            }
            
            if(conids.size() > 0 && Schema.sObjectType.contact.isQueryable())
            {
                lstCon1 = [select Contact_Account_Is_Archived__c,id,ESC_tocContactStatus__c,Contact_Inactive__c,phone,Email,AccountId,LCRM_Is_GLI__c,Account.Sales_Org__c from contact where id IN : conids and Account.Bu_Segment__c IN :buSegment and Account.BU_Region__c IN :buRegion];
                lstCon.addAll(lstCon1);
            }
            //End
            
            /*
            if(lstcon.size()>1){
            lstCon = [select Contact_Account_Is_Archived__c,id,ESC_tocContactStatus__c,Contact_Inactive__c,phone,Email,AccountId,LCRM_Is_GLI__c,Account.Sales_Org__c from contact where email IN :gliEmail and Account.Bu_Segment__c IN :buSegment and Account.BU_Region__c IN :buRegion];
            } 
            */
            if(lstcon.size()==0){
                nonGLI=true;
            }
        }
        else if(lstemail.size()>0){
            lstCon2 = [select id,ESC_tocContactStatus__c,Contact_Account_Is_Archived__c,Contact_Inactive__c,phone,Email,AccountId,LCRM_Is_GLI__c from contact where email IN :lstemail];
            lstCon.addAll(lstCon2);  
            system.debug(logginglevel.warn,'ist list'+ lstCon2);         
        }else if(ggoEmail.size()>0){  
            lstCon2 = [select id,ESC_tocContactStatus__c,Contact_Account_Is_Archived__c,Contact_Inactive__c,phone,Email,AccountId,LCRM_Is_GLI__c from contact 
                       where email IN :ggoEmail and Account.Tax_Number_Type__c IN :lstActTaxType and Account.Tax_Number__c IN :lstActTaxNum];
            lstCon.addAll(lstCon2);
        }
        for(Contact c:lstcon){
            if(c.email!=null){
                if(Mapcon.containsKey(c.email)){
                    Mapcon.get(c.email).add(c);
                }else{
                    Mapcon.put(c.email,new List<Contact>{c});
                }
            }
        }
        for(Case c:cases){
            if(mapcon.get(c.SuppliedEmail)!=null){
                //If only 1 contact exists with the email associated to a case,associate to it
                if(mapcon.get(c.SuppliedEmail).size()==1){
                    for(Contact con:mapcon.get(c.SuppliedEmail)){
                        Case cs=new Case();
                        cs.id=c.id; 
                        cs.contactid =con.id;
                        cs.accountid =con.AccountId;
                        lstupdatecase.add(cs);
                    }
                }
                //If more than1 contact exists with the email associated to a case
                else if(mapcon.get(c.SuppliedEmail).size()>1){
                    integer act=0;
                    integer inact=0;
                    // Contact contacts=new Contact();
                    for(Contact con:mapcon.get(c.SuppliedEmail)){
                        If(ggoContact=True)
                        {    if(!con.Contact_Inactive__c && !con.Contact_Account_Is_Archived__c){
                            act++;
                        }else if(con.Contact_Inactive__c || con.Contact_Account_Is_Archived__c){
                            inact++;
                        }
                        }
                        else
                        {
                            if(!con.Contact_Inactive__c){
                                act++;
                            }else if(con.Contact_Inactive__c){
                                inact++;
                            }
                        }
                    }
                    system.debug(logginglevel.warn,'InactveContacts :'+ inact);
                    //If 1 active contact exists with multi inactive, associate active contact to a case
                    if(act==1 && inact>0){
                        for(Contact con:mapcon.get(c.SuppliedEmail)){
                            If(ggoContact=True)
                            {    if(!con.Contact_Inactive__c && !con.Contact_Account_Is_Archived__c){
                                Case cs=new Case();
                                cs.id=c.id; 
                                cs.contactid =con.id;
                                cs.accountid =con.AccountId;
                                lstupdatecase.add(cs);
                            }
                            }
                            else if(!con.Contact_Inactive__c){
                                Case cs=new Case();
                                cs.id=c.id;
                                cs.contactid =con.id;
                                cs.accountid =con.AccountId;
                                lstupdatecase.add(cs);
                            }
                        }
                    }
                    
                    else if(act>1 || inact>1 || nonGLI){
                        //If multi contacts exist with many active contacts then don't associate any contact with a case
                        Case cs=new Case();
                        cs.id=c.id; 
                        cs.contactid = null;
                        cs.accountid = null;    
                        lstupdatecase.add(cs);
                    }
                }
            }
            // Added as part of UKI
            else if(mapcon.get(c.SuppliedEmail)==null && nonGLI){
                Case cs=new Case();
                cs.id=c.id; 
                cs.contactid = null;
                cs.accountid = null;
                lstupdatecase.add(cs);
            }
        }
        if(lstupdatecase.size()>0 && Schema.sObjectType.case.isQueryable()){
            update lstupdatecase;
        }
    }
}