objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SAP_Contact_ID__c</fullName>
        <description>TW SAP Account Number</description>
        <externalId>true</externalId>
        <label>SAP Contact ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Role__c</fullName>
        <description>S_CONTACT.X_SAP_ROLE_CD The role this contact has as noted in SAP.</description>
        <inlineHelpText>The role this contact has as noted in SAP.</inlineHelpText>
        <label>SAP Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACCT NAMED PARTNER</fullName>
                </value>
                <value>
                    <fullName>ACQUISITION LIBRARIAN</fullName>
                </value>
                <value>
                    <fullName>AUTO PAYMENT PROCESS</fullName>
                </value>
                <value>
                    <fullName>Acad-ACQUISITION LIBRARIAN</fullName>
                </value>
                <value>
                    <fullName>Acad-ATTORNEY - ACADEMIC</fullName>
                </value>
                <value>
                    <fullName>Acad-INTERNATIONAL PROFESSOR</fullName>
                </value>
                <value>
                    <fullName>Acad-INTERNATIONAL STUDENT</fullName>
                </value>
                <value>
                    <fullName>Acad-LAW REVIEW EDITOR</fullName>
                </value>
                <value>
                    <fullName>Acad-LAW SCHOOL LIBRARIAN</fullName>
                </value>
                <value>
                    <fullName>Acad-LAW SCHOOL PROFESSOR</fullName>
                </value>
                <value>
                    <fullName>Acad-LAW SCHOOL STUDENT</fullName>
                </value>
                <value>
                    <fullName>Acad-NONATTORNEY - ACADEMIC</fullName>
                </value>
                <value>
                    <fullName>Acad-NOT SPECIFIED</fullName>
                </value>
                <value>
                    <fullName>Acad-PARALEGAL STUDENT</fullName>
                </value>
                <value>
                    <fullName>Acad-PROMOTION ADMINISTRATOR</fullName>
                </value>
                <value>
                    <fullName>Acad-UNDERGRADUATE PROFESSOR</fullName>
                </value>
                <value>
                    <fullName>Acad-UNDERGRADUATE STUDENT</fullName>
                </value>
                <value>
                    <fullName>COMMUNICATIONS DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>CORP - CEO/PRESIDENT</fullName>
                </value>
                <value>
                    <fullName>CORP - CFO</fullName>
                </value>
                <value>
                    <fullName>CORP - CHRO</fullName>
                </value>
                <value>
                    <fullName>CORP - COO/CAO</fullName>
                </value>
                <value>
                    <fullName>CORP - CTO/CIO/CKO</fullName>
                </value>
                <value>
                    <fullName>CORP - GENERAL COUNSEL</fullName>
                </value>
                <value>
                    <fullName>CORP -CMO</fullName>
                </value>
                <value>
                    <fullName>CORP-CHIEF COMPLIANCE OFFICER</fullName>
                </value>
                <value>
                    <fullName>Corp-ACCOUNT EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>Corp-ACCOUNTING PROFESSIONAL</fullName>
                </value>
                <value>
                    <fullName>Corp-CLAIMS SPECIALIST</fullName>
                </value>
                <value>
                    <fullName>Corp-COMMUNICATIONS DIRECTOR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LCRM_Contact_SSD__c.object
<CustomObject>
    <fields>
        <fullName>LCRM_Account_SSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account SSD</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipName>Contact_SSDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Source System Detail</relationshipLabel>
        <relationshipName>Contact_SSDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Email__c</fullName>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_SAP_Account_Number__c</fullName>
        <label>SAP Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_SAP_Role__c</fullName>
        <label>SAP Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Source_Contact_Id__c</fullName>
        <label>Source Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Contact Source System</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Source Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Customer_Category__c</fullName>
        <description>Created as part of OC GLI implementation</description>
        <label>APTS_Customer_Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_APTS_Band_Number__c</fullName>
        <label>APTS_Band_Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LCRM_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LCRM_Frozen_Market_Segment__c</fullName>
        <description>Created for R4</description>
        <label>Frozen Market Segment</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_SAP_Account_Number__c</fullName>
        <description>Created for R4</description>
        <label>SAP Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_eOutput_Eligibility__c</fullName>
        <label>eOutput Eligibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Name__c</fullName>
        <label>Source System Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DC_ContactSSDFieldCapitalisation_Test.cls
/*
 * CHANGE HISTORY
 * ==================================================================================================================================
 * Date         Name                    Description
 * 2018-07-17   Navleen Kaur            Created for GLI to format fields of Contact SSD
 * 2018-08-07   Bharat Bhushan          DLT-11509- [TECH STORY] SAP Contact ID field to modify as per GLI to be replace with Source Contact ID
 * 2018-04-25   Benjamin Her            Changed SSD RecordType Label from USL to Lotus
 * 2019-06-06   Navleen Kaur            DLT-16786 : [Tech Story] [Code Scan] - Fix code scan MAJOR issues in this DC_ContactSSDFieldCapitalisation_Test.cls
 * ==================================================================================================================================   
 */
@IsTest
public class DC_ContactSSDFieldCapitalisation_Test {
   private Static testmethod void getSSD_Test(){
      Account acc= new Account();
      acc = UnitTest.getAccountInstance();
      insert acc;
       
      test.starttest();
      Id ssdRecorType=Schema.SObjectType.Source_System_Detail__c.getRecordTypeInfosByName().get('LOTUS Source Systems').getRecordTypeId();
      Source_System_Detail__c accountSSD= new Source_System_Detail__c();
      accountSSD.RecordtypeId=ssdRecorType;
      accountSSD.Name='ABC';
      accountSSD.Source_System_Name__c='ABC';
      accountSSD.Account_Name__c=acc.ID; 
      accountSSD.City__c = 'BANGALORE';
      accountSSD.Account_Inactive__c = false;  
      //accountSSD.Source_System_Account_Number__c = acc.SAPAccountNumber__c;    
      accountSSD.LCRM_Frozen_Market_Segment__c = 'Solo Law Firm';
      accountSSD.LCRM_SAP_Account_Number__c = '1004284494';        
      accountSSD.LCRM_APTS_Band_Number__c= 1;
      accountSSD.APTS_Customer_Category__c = '3';
      accountSSD.LCRM_eOutput_Eligibility__c= ''; 
      accountSSD.LCRM_Sales_Org__c= 'WEST';
      accountSSD.State__c = 'California';
      insert accountSSD;
       
      Contact con = new contact();
      con = UnitTest.getContactInstance(acc.id);
      insert con;
       
      LCRM_Contact_SSD__c conSSD = new LCRM_Contact_SSD__c();
      conSSD.LCRM_Contact__c=con.Id;
      conSSD.LCRM_SAP_Role__c=con.SAP_Role__c;
      conSSD.LCRM_Source_Contact_Id__c=con.SAP_Contact_ID__c;
      conSSD.LCRM_Account_SSD__c = accountSSD.Id;
      conSSD.LCRM_Email__c= con.Email;
      insert conSSD;
      List<LCRM_Contact_SSD__c> listOfSSD = new List<LCRM_Contact_SSD__c>();
      listOfSSD.add(conSSD);
      DC_ContactSSDFieldValueCapitalisation.getFormattedContactSSD(listOfSSD);
      system.assert(listOfSSD!=null);
   }
}