objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MDB_Contact_ID__c</fullName>
        <description>S_CONTACT.X_MDB_CONTACT_ID</description>
        <label>MDB Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ESC_Special_Instruction__c.object
<CustomObject>
    <fields>
        <fullName>ESC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Special Instructions</relationshipLabel>
        <relationshipName>Special_Instructions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESC_Category_Account__c</fullName>
        <label>Account Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Instructions</fullName>
                </value>
                <value>
                    <fullName>No Remote Support</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Remote Support</fullName>
                </value>
                <value>
                    <fullName>TLC</fullName>
                </value>
                <value>
                    <fullName>Premium Support Account</fullName>
                </value>
                <value>
                    <fullName>Customer Defense Process</fullName>
                </value>
                <value>
                    <fullName>Customer Defense Hypercare</fullName>
                </value>
                <value>
                    <fullName>Bejerman Customized Customer</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Detailed_Instructions__c</fullName>
        <label>Detailed Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Special Instruction</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ESC_FetchAccountController_test1.cls
@istest(seeAllData=false)
public class ESC_FetchAccountController_test1{

 @IsTest(SeeAllData= false) 
    public static void setaccdata(){
        //insert account data
        Account acc = new Account();
        Acc.name = 'Test account';
        Acc.Phone = '91 80 23456789';
        Acc.BillingCountry = 'KP';
        Acc.BillingState='IL';
        Acc.BillingPostalCode = '60603-3801';
        Acc.SAPAccountNumber__c = 'UTSAP002';      
        insert acc;
        
        Contact Cont=new Contact();
        Cont.firstname = 'Steve';
        Cont.lastname = 'Smith';
        Cont.Email = 'Fred@Smith.com';
        Cont.MDB_Contact_ID__c = '1234567890';
        insert Cont;
        
       List<ESC_Special_Instruction__c> splinstlist = new List<ESC_Special_Instruction__c>();
        ESC_Special_Instruction__c splinst = new ESC_Special_Instruction__c();
        splinst.ESC_Account__c = acc.Id;
        splinst.ESC_Category_Account__c = 'No Remote Support';
        splinst.ESC_Detailed_Instructions__c = 'Special Instruction detail';
        splinst.ESC_Status__c = 'Active';
        splinstlist.add(splinst);
           insert splinstlist;
        
        ESC_FetchAccountController.getSObjDetails(acc.id,'Account');
        ESC_FetchAccountController.getSObjDetails(Cont.id,'Contact');
        ESC_FetchAccountController.getAccList(acc.id);
        ESC_FetchAccountController.getRecTypeId(acc.id);
        ESC_FetchAccountController.getRecordTypeId();
        ESC_FetchAccountController.getCaseRecordTypeID();
    }
}