objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRMOD URL</label>
</CustomObject>

objects/Entitlement__c.object
<CustomObject>
    <label>Entitlement</label>
    <nameField>
        <label>Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EntitlementProduct__c.object
<CustomObject>
    <description>Junction object for many- to- many relationship b/w product and entitlements</description>
    <fields>
        <fullName>Entitlement__c</fullName>
        <label>Entitlement</label>
        <referenceTo>Entitlement__c</referenceTo>
        <relationshipLabel>EntitlementProducts</relationshipLabel>
        <relationshipName>EntitlementProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>EntitlementProducts</relationshipLabel>
        <relationshipName>EntitlementProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EntitlementProduct</label>
    <nameField>
        <displayFormat>EP{0000}</displayFormat>
        <label>EntitlementProduct Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EntitlementProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <description>Customer Group from the Account object.</description>
        <formula>TEXT( Account.Customer_Group__c )</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Win_Loss__c</fullName>
        <inlineHelpText>Set to “Won” for closed sales, “Lost” for sales lost, “Abandoned” or “Duplicate Opportunity” as appropriate.</inlineHelpText>
        <label>Win/Loss</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Won – Downgrade</fullName>
                </value>
                <value>
                    <fullName>Won – Competitor</fullName>
                </value>
                <value>
                    <fullName>Won – New Sale</fullName>
                </value>
                <value>
                    <fullName>Won – Upgrade</fullName>
                </value>
                <value>
                    <fullName>Won – Renewed</fullName>
                </value>
                <value>
                    <fullName>Won – Other</fullName>
                </value>
                <value>
                    <fullName>Lost – Price</fullName>
                </value>
                <value>
                    <fullName>Lost – Other</fullName>
                </value>
                <value>
                    <fullName>Lost – MTM Renewal</fullName>
                </value>
                <value>
                    <fullName>Lost – Competitor</fullName>
                </value>
                <value>
                    <fullName>Lost – Performance</fullName>
                </value>
                <value>
                    <fullName>Lost – Service</fullName>
                </value>
                <value>
                    <fullName>Abandoned – Duplicate Opportunity</fullName>
                </value>
                <value>
                    <fullName>Abandoned - Customer Not Proceeding</fullName>
                </value>
                <value>
                    <fullName>No Change – Client Satisfied</fullName>
                </value>
                <value>
                    <fullName>Won - No change-Client Satisfied</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Duplicate Opportunity</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Change of Research Focus</fullName>
                </value>
                <value>
                    <fullName>Company/Site Shut down</fullName>
                </value>
                <value>
                    <fullName>Competitor Replacement</fullName>
                </value>
                <value>
                    <fullName>Currency Fluctuation</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>Merger/Acquisition</fullName>
                </value>
                <value>
                    <fullName>Non Payment/Collections Issue</fullName>
                </value>
                <value>
                    <fullName>Poor/Low Usage</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Product_Detail_Contact__c.object
<CustomObject>
    <description>Allows users to associate multiple contacts to an opportunity product detail record.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product Detail Contacts</relationshipLabel>
        <relationshipName>Opportunity_Product_Detail_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Existing contacts will show associated email address. User will be able to update the contact email address from this field.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <label>Product Detail</label>
        <referenceTo>OpportunityProductDetail__c</referenceTo>
        <relationshipLabel>Opportunity Product Detail Contacts</relationshipLabel>
        <relationshipName>Opportunity_Product_Detail_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Product Detail Contact</label>
    <nameField>
        <displayFormat>PDC-{00000}</displayFormat>
        <label>Opportunity Product Detail Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Detail Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityProductDetail__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunitiy Product Details</relationshipLabel>
        <relationshipName>Opportunitiy_Product_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product Details</relationshipLabel>
        <relationshipName>Opportunitiy_Product_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunitiy Product Details</relationshipLabel>
        <relationshipName>Opportunitiy_Product_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Product Detail</label>
    <nameField>
        <displayFormat>DP-{0000000000}</displayFormat>
        <label>Opportunity Product Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiy Product Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product Classification used for GLI Products</description>
        <label>Product Level 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Detail__c.object
<CustomObject>
    <description>Stores the product data in JSON format and data for all the related objects for that product</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product record for which &apos;Product Detail&apos; field holds the value</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Details</relationshipLabel>
        <relationshipName>Product_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <displayFormat>PDN-{00000000}</displayFormat>
        <label>Product Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestEReaderLoadProductController.cls
/**
 * test class for load product details controllers
 *
 * @author  Anshita Sharma
 * @version 2013-07-14
 */

/**
 * CHANGE HISTORY
 * =============================================================================
 * Date         Name                    Description
 * 2013-07-14   Anshita Sharma          Created                                                                
 * =============================================================================
 */

@istest(seeAllData=true)
private class TestEReaderLoadProductController  {
    
    public static testmethod void test() {
        
        Date dt = system.today();
        
        Account acc1= UnitTest.getAccountInstance();
        acc1.Name = 'testAccount';
        acc1.Customer_Type__c = 'Induvidual';
        acc1.Customer_Group__c = 'ACADEMIC';
        acc1.Industry = 'Energy';
        acc1.SAPAccountNumber__c = '1111111111';       
        insert acc1;
       
        Opportunity oppty1 = new Opportunity(CloseDate= dt, Win_Loss__c='Kickout',AccountId =acc1.Id,name='testClass_Oppty1',StageName = '10%');
        insert oppty1;
       
        Contact contact = UnitTest.getContactInstance(acc1.Id);
        contact.LastName = 'testContact';
        contact.FirstName = 'testContact';
        contact.AccountId = acc1.Id;
        contact.email = 'test.test@test.com';
        
        Contact contact1 = UnitTest.getContactInstance(acc1.Id);
        contact1.LastName = 'testContact';
        contact1.FirstName = 'testContact';
        contact1.AccountId = acc1.Id;
        contact1.email = '';
        
        List<Contact> conList = new List<Contact>{contact,contact1};
        insert conList;
        
        Product2 prod = new Product2();
        prod.Name = 'TEST';
        insert prod;
       
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
       
        
        List<Pricebook2> testPricebook =[select id from Pricebook2 where isActive = true];    
             
        PricebookEntry entry= new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert entry;
       
               
        OpportunityLineItem item = new OpportunityLineItem();
        item.PricebookEntryId = entry.id;
        item.Quantity = 1;
        item.OpportunityId = oppty1.id;       
        item.UnitPrice = 100;
        insert item;
      
        OpportunityProductDetail__c d = new OpportunityProductDetail__c();
        d.Opportunity_Line_Item_Id__c = (((String)item.ID).substring(0,15));
        d.Opportunity__c = oppty1.id;
        d.Contact__c = contact.id;
        d.Product__c = prod.Id;
        insert d;
      
        
        Opportunity_Product_Detail_Contact__c opdc = new Opportunity_Product_Detail_Contact__c();
        opdc.Product_Detail__c = d.Id;
        opdc.Contact__c = contact.Id;
        opdc.Email__c = 'jivuv@ghvh.com';
       
        Opportunity_Product_Detail_Contact__c opdc1 = new Opportunity_Product_Detail_Contact__c();
        opdc1.Product_Detail__c = d.Id;
        opdc1.Contact__c = contact1.Id;
        opdc1.Email__c = 'jivuv123@ghvh.com';
        List<Opportunity_Product_Detail_Contact__c> opdcList = new List<Opportunity_Product_Detail_Contact__c>{opdc,opdc1};
        insert opdcList;
        
        
        System.currentPageReference().getParameters().put('oppId', oppty1.id);
        
        //test loadOppProductController
        
        loadOppProductDetailController controller = new loadOppProductDetailController(new ApexPages.StandardController(new OpportunityProductDetail__c()));
        
        controller.quickSave();
        controller.cancel(); 
        controller.getContactSelectOptions();
        controller.selectedProd = 0;
        controller.addContact();
        controller.selectedCon = 1;
        controller.handleContactChange();
        
      
        opdc.Email__c = '';
        controller.Save();
        
        Entitlement__c e = new Entitlement__c(Name = '123456');
        try{
            insert e;
        }
        catch(exception ex){
        } 
        
        EntitlementProduct__c ep = new EntitlementProduct__c(Product__c = prod.id, Entitlement__c = e.id);
        try{
        insert ep;
        }
        catch(exception ex){
        } 
        //test loadOppProductBJController
        loadOppProductDetailBJController controllerBJ = new loadOppProductDetailBJController (new ApexPages.StandardController(new OpportunityProductDetail__c()));
        
        controllerBJ.quickSave();
        controllerBJ.cancel(); 
        controllerBJ.getContactSelectOptions();
        
        //test triggerOpportunityProductDetail/opportunityProductDetailTriggerHandler
        
        OpportunityProductDetail__c d1 = new OpportunityProductDetail__c();
        d1.Opportunity_Line_Item_Id__c = (((String)item.ID).substring(0,15));
        d1.Opportunity__c = oppty1.id;
        d1.Contact__c = contact.id;
        try{
            insert d1;
        }
        catch(exception ex){
        } 
        
        
    }
}