objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ESC_IsAllowRepDB__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For VSTS staging</description>
        <label>IsAllowRepDB</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ESC_Case_Collaborator__c.object
<CustomObject>
    <description>ESC_ Custom object to enable the Accountable Resolver, Case Collaborator, and Escalation processes in Enterprise Service Cloud program</description>
    <fields>
        <fullName>ESC_Case_Description__c</fullName>
        <description>ESC_ This field Copies the description from the related case</description>
        <label>Case Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESC_ The related case to the referral</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals/Escalations</relationshipLabel>
        <relationshipName>Case_Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESC_Product__c</fullName>
        <formula>TEXT(ESC_Case__r.ESC_Product_Title__c)</formula>
        <label>Product Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Referral_Status__c</fullName>
        <description>ESC_ The current status of the referral. Rejected and Closed are the equivalent of the ISCLOSED statuses on referrals</description>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ESC_Role__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Customer Hold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Change</fullName>
                </value>
                <value>
                    <fullName>Pending Customer</fullName>
                </value>
                <value>
                    <fullName>Pending Other</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Role__c</fullName>
        <description>ESC_ Maintains the role of the referral function - Accountable Resolver, Collaborator, manager Escalation</description>
        <label>Referral Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accountable Resolver</fullName>
                    <default>true</default>
                    <label>Accountable Resolver</label>
                </value>
                <value>
                    <fullName>Collaborator</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Severity__c</fullName>
        <description>ESC_ The Severity field from the related case</description>
        <formula>TEXT( ESC_Case__r.ESC_Severity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Severity</label>
        <type>Text</type>
    </fields>
    <label>Referral/Escalation</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals/Escalations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESC_Case_Product__c.object
<CustomObject>
    <description>ESC_ Custom Object to relate multiple products to a case.</description>
    <label>Case Product Line Item</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Product Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ESC_Product_Version__c.object
<CustomObject>
    <description>ESC_ Custom Object to relate product versionsto Case products and Products</description>
    <fields>
        <fullName>ESC_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Versions</relationshipLabel>
        <relationshipName>Product_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Version</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESC_VSTS_Staging__c.object
<CustomObject>
    <description>ESC_VSTS_Staging to hold the records to be sent to TFS</description>
    <fields>
        <fullName>ESC_Account_Name__c</fullName>
        <description>Used in ESC_VSTS_Staging</description>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Created_Date__c</fullName>
        <label>Case Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Description__c</fullName>
        <description>Used in ESC_VSTS_Staging</description>
        <label>Case Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Diagnosis__c</fullName>
        <description>Used in ESC_VSTS_Staging</description>
        <label>Case Diagnosis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Number__c</fullName>
        <description>Used in ESC_VSTS_Staging</description>
        <label>Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Owner__c</fullName>
        <label>Case Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Priority__c</fullName>
        <description>Used in ESC_VSTS_Staging</description>
        <label>Case Priority</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Product_Version__c</fullName>
        <label>Case Product Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Product__c</fullName>
        <label>Case Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Severity__c</fullName>
        <description>Used in ESC_VSTS_Staging</description>
        <label>Case  Severity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Subject__c</fullName>
        <description>Captures the case subject on VSTS records</description>
        <label>Case Subject</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Error_Log__c</fullName>
        <label>Error Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Feed_Comment__c</fullName>
        <description>place holder of Feed comment from Salesforce to VSTS</description>
        <label>Feed Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_IsAllowRepDB__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value will be true or false</description>
        <label>IsAllowRepDB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ESC_Last_Statusfrom_VSTS__c</fullName>
        <description>VSTS status in salesforce</description>
        <label>Last Statusfrom VSTS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_RequestType__c</fullName>
        <label>RequestType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_SAP_Account_Num__c</fullName>
        <description>Used in ESC_VSTS_Staging</description>
        <label>SAP Account Num</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Staging_Status__c</fullName>
        <label>Staging Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>VSTS Staging</label>
    <nameField>
        <displayFormat>VSTS-{00000000}</displayFormat>
        <label>VSTS Stagging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VSTS Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ESC_VSTS_StatusfromVSTS_Test.cls
@isTest(SeeAllData=false)
public class ESC_VSTS_StatusfromVSTS_Test{
    
    static testmethod void VSTSStatusMethod(){
 
        
        Group grp = [Select id,Name from Group where Type='Queue' and DeveloperName='BR_LE_Development_Legal_One'];
        Profile profile = [SELECT Id FROM Profile where Name='LatAM Helpdesk Agent'];
        
        User testUser = new User(Alias = 'Tuvsts13', Email='Tuvsts13@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Tuvsts13', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = profile.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='Tuvsts13@ss.com');
            insert testUser;
            
        Account acc= new Account();
        	acc.Name='Test';
        	acc.SAPAccountNumber__c='Test123';
        	insert acc;
        	
        	//insert contact
        Contact con1 = new Contact();
            con1.LastName = '2Name';
            con1.Email = 'mail2g@mail.com';
            con1.Phone = '9889384214';
            con1.MobilePhone = '9889384214';
            con1.salutation = 'Ms.';
            con1.firstName = '2name';
            con1.AccountId = acc.Id;
            con1.Department = 'TR';
            con1.ESC_IsAllowRepDB__c=true;
            insert con1;
            
        Product2 product = new Product2();
            product.Name='Test';
            insert product;
        
        ESC_Product_Version__c prodVersion = new ESC_Product_Version__c();
            prodVersion.name='Test';
            prodVersion.ESC_Product__c=product.Id;
            insert prodVersion;
        
            //insert case
        List <Case> listCase= new List<Case>();
        Case cs1=new Case();
            cs1.ESC_Impact__c = '1-Whole Site';
            cs1.AccountId=acc.Id;
            cs1.OwnerId=testUser.Id;
            cs1.Description='testDescription';
            cs1.subject='test';
            cs1.ESC_Customer_Symptom__c='Content Addition';
            cs1.ESC_Diagnosis_Summary__c='Content Explanation';
            cs1.ESC_Severity__c='1 - High';
            cs1.Priority='2 - Medium';
            cs1.ContactId= con1.Id;
            cs1.ProductId=product.Id;
            cs1.GGO_Product_Complement__c='Test';
            cs1.ESC_Product_Version__c=prodVersion.Id;
            cs1.status ='Work in progress';
            cs1.ESC_Proactive_Type__c='Internal Origin';
            cs1.RecordtypeID=Schema.SObjectType.case.getRecordTypeInfosByName().get('Incident').getRecordTypeId();
            listcase.add(cs1);
        insert listcase;
        
         List<case> caselist1 = [select id, CaseNumber from Case where id =: cs1.id];
         
        
        List<FeedItem> feedList= new List<FeedItem>();
        FeedItem feed = new FeedItem();
            feed.Type= 'TextPost';
            feed.body='@BR_LE_Development_Legal_One test';
            feed.parentId=cs1.Id;
            insert feed;
            feedList.add(feed);
            
        List<ESC_Case_Collaborator__c> refList=new List<ESC_Case_Collaborator__c>();
        ESC_Case_Collaborator__c referral = new ESC_Case_Collaborator__c();
            referral.ESC_Case__c= cs1.Id;
            referral.OwnerId= grp.Id;
            referral.ESC_Referral_Status__c='New';
            referral.ESC_Role__c='Accountable Resolver';
            refList.add(referral);
            insert refList;
            
           List<ESC_VSTS_Staging__c> StagingList= New List<ESC_VSTS_Staging__c>();
           ESC_VSTS_Staging__c vs = new ESC_VSTS_Staging__c ();
           vs.ESC_Account_Name__c='Test Account';
           vs.ESC_SAP_Account_Num__c='Test SAP Account';
           vs.ESC_Case_Product__c=cs1.ProductId;
           vs.ESC_Case_Product_Version__c=cs1.ESC_Product_Version__c;
           vs.ESC_Case_Subject__c=cs1.subject;
           vs.ESC_Case_Description__c=cs1.Description;
           vs.ESC_Case_Created_Date__c=system.now();
           vs.ESC_Case_Severity__c=cs1.ESC_Severity__c;
           vs.ESC_Case_Priority__c= cs1.Priority;
           vs.ESC_Case_Diagnosis__c=cs1.ESC_Diagnosis_Summary__c;
            vs.ESC_Case_Number__c = caselist1[0].CaseNumber;
           vs.ESC_Error_Log__c='';
           vs.ESC_Feed_Comment__c='Test Feed Comment';
           vs.ESC_RequestType__c='Create';
           vs.ESC_Staging_Status__c='Pending';
           vs.ESC_Case_Owner__c=cs1.OwnerId;
          vs.ESC_Last_Statusfrom_VSTS__c = 'Closed';
           StagingList.add(vs);
           insert StagingList;
  
           test.startTest();
            ESC_VSTS_StatusfromVSTS.VSTSStatusUpdate(StagingList);
           test.stopTest();
            
    }
      static testmethod void VSTSStatusMethod2(){
 
        
        Group grp = [Select id,Name from Group where Type='Queue' and DeveloperName='BR_LE_Development_Legal_One'];
        Profile profile = [SELECT Id FROM Profile where Name='LatAM Helpdesk Agent'];
        
        User testUser = new User(Alias = 'Tuvsts14', Email='Tuvsts14@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Tuvsts14', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = profile.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='Tuvsts14@ss.com');
            insert testUser;
            
        Account acc= new Account();
        	acc.Name='Test';
        	acc.SAPAccountNumber__c='Test123';
        	insert acc;
        	
        	//insert contact
        Contact con1 = new Contact();
            con1.LastName = '2Name';
            con1.Email = 'mail2g@mail.com';
            con1.Phone = '9889384214';
            con1.MobilePhone = '9889384214';
            con1.salutation = 'Ms.';
            con1.firstName = '2name';
            con1.AccountId = acc.Id;
            con1.Department = 'TR';
            con1.ESC_IsAllowRepDB__c=true;
            insert con1;
            
        Product2 product = new Product2();
            product.Name='Test';
            insert product;
        
        ESC_Product_Version__c prodVersion = new ESC_Product_Version__c();
            prodVersion.name='Test';
            prodVersion.ESC_Product__c=product.Id;
            insert prodVersion;
        
            //insert case
        List <Case> listCase= new List<Case>();
        Case cs1=new Case();
            cs1.ESC_Impact__c = '1-Whole Site';
            cs1.AccountId=acc.Id;
            cs1.OwnerId=testUser.Id;
            cs1.Description='testDescription';
            cs1.subject='test';
            cs1.ESC_Customer_Symptom__c='Content Addition';
            cs1.ESC_Diagnosis_Summary__c='Content Explanation';
            cs1.ESC_Severity__c='1 - High';
            cs1.Priority='2 - Medium';
            cs1.ContactId= con1.Id;
            cs1.ProductId=product.Id;
            cs1.GGO_Product_Complement__c='Test';
            cs1.ESC_Product_Version__c=prodVersion.Id;
            cs1.status ='Work in progress';
            cs1.ESC_Proactive_Type__c='Internal Origin';
            cs1.RecordtypeID=Schema.SObjectType.case.getRecordTypeInfosByName().get('Incident').getRecordTypeId();
            listcase.add(cs1);
        insert listcase;
        
         List<case> caselist1 = [select id, CaseNumber from Case where id =: cs1.id];
         
        
        List<FeedItem> feedList= new List<FeedItem>();
        FeedItem feed = new FeedItem();
            feed.Type= 'TextPost';
            feed.body='@BR_LE_Development_Legal_One test';
            feed.parentId=cs1.Id;
            insert feed;
            feedList.add(feed);
            
        List<ESC_Case_Collaborator__c> refList=new List<ESC_Case_Collaborator__c>();
        ESC_Case_Collaborator__c referral = new ESC_Case_Collaborator__c();
            referral.ESC_Case__c= cs1.Id;
            referral.OwnerId= grp.Id;
            referral.ESC_Referral_Status__c='New';
            referral.ESC_Role__c='Accountable Resolver';
            refList.add(referral);
            insert refList;
            
           List<ESC_VSTS_Staging__c> StagingList1= New List<ESC_VSTS_Staging__c>();
        
           
           test.startTest();
            ESC_VSTS_StatusfromVSTS.VSTSStatusUpdate(StagingList1);
           test.stopTest();
            
    }
    
}