objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SAP_Contact_ID__c</fullName>
        <description>TW SAP Account Number</description>
        <externalId>true</externalId>
        <label>SAP Contact ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LCRM_Contact_SSD__c.object
<CustomObject>
    <fields>
        <fullName>LCRM_Source_Contact_Id__c</fullName>
        <label>Source Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Contact Source System</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Source Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Account_Detail__c.object
<CustomObject>
    <fields>
        <fullName>AccountSSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account SSD</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Digital Subscriptions</relationshipLabel>
        <relationshipName>Digital_Product_AccountSSD_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_New_Service__c</fullName>
        <label>Best New Service</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_New_Subscription_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actual New Subscription Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Digital_Product_Account_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_New_Subscription__c</fullName>
        <label>Best New Subscription</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bundle_Product_Name__c</fullName>
        <inlineHelpText>Bundle product or parent product name</inlineHelpText>
        <label>Bundle Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bypass_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this Digital Subscription record will not get picked up and processed through the Digital Automation Process.</description>
        <label>Bypass Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Premium_New_Service__c</fullName>
        <label>Premium New Service</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premium_New_Subscription__c</fullName>
        <label>Premium New Subscription</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_Id__c</fullName>
        <description>Created to copy SAP Contact Id for US DLT-8973.</description>
        <label>SAP Contact Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZP_Cust_Number__c</fullName>
        <label>ZP Cust Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Digital Subscriptions</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Product Account  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/APTS_DigitalProductTriggerTest.cls
/**
 * Test class for testing the APTS_DigitalProductTriggerHelper and APTS_DigitalProductTriggerHandler classes.
 * These are the support classes for the Digital Subscriptions trigger.  
 */
/**
 * CHANGE HISTORY
 * =============================================================================
 * Date         Name                    Description
 * 2020-08-06   Brenda Shields          DLT-20508 Updated for new functionality test 
 * 2021-04-01   Brenda shields          DLT-21575 - Update logic to correctly set OCC and associated fields
 * =============================================================================
 */
/**
 * @description : Test class for the APTS_DigitalProductTriggerHelper and APTS_DigitalProductTriggerHandler classes
 */ 
@isTest
private class APTS_DigitalProductTriggerTest {

    @testSetup
    static void setup(){
    	
        Account acct = new Account(Name='Digital Test Account', SAPAccountNumber__c = '1234567890');
        insert acct;
        Product2 prd = DCTestData.createProduct('Test Product','12345','67890');
        system.debug(logginglevel.INFO, 'Products : ' + prd);
        Source_System_Detail__c acctssd = DCTestData.createSourceSystemDetail(acct);
        // create contact and ssd contact
        Contact oContact = DCTestData.createContactRec('Testcontact', acct.Id);
        insert oContact;
        LCRM_Contact_SSD__c oSSDContact = DCTestData.createContactSSD(oContact, acctssd);
        oSSDContact.LCRM_Source_Contact_Id__c = '1234567890';
        update oSSDContact;
    }

    @isTest
    static void insertDigitalSubscription() {
    	
        Source_System_Detail__c acctssd = [SELECT id FROM Source_System_Detail__c WHERE Source_System_Account_Number__c = '1234567890'];
        Product_Account_Detail__c pad = new Product_Account_Detail__c();
        pad.ZP_Cust_Number__c = '1234567890';
        pad.Actual_New_Service__c = '12345'; // match with Product1 product code
        pad.Actual_New_Subscription__c = '67890';
        pad.SAP_Contact_Id__c = '1234567890';
        
        Test.startTest();
        insert pad;
        Test.stopTest();
        
        pad = [SELECT id, AccountSSD__c, Actual_New_Subscription_Product__c FROM Product_Account_Detail__c WHERE ZP_Cust_Number__c = '1234567890' LIMIT 1];
        System.assertEquals(acctssd.id, pad.AccountSSD__c, 'Source System Detail:'+pad.AccountSSD__c);
    }

    @isTest
    static void digitalSubscriptionBundleProductTest() {
    	
        Source_System_Detail__c acctssd = [SELECT id FROM Source_System_Detail__c WHERE Source_System_Account_Number__c = '1234567890'];
        //Product2 prd = [SELECT id FROM Product2 WHERE Name = 'Test Product'];
        Product_Account_Detail__c pad = new Product_Account_Detail__c();
        pad.ZP_Cust_Number__c = '1234567890';
        pad.Bundle_product_Name__C = 'Test Product2';
        //pad.Premium_New_Service__c = '12345';
                
        Test.startTest();
        insert pad;
        Test.stopTest();
       
        pad = [SELECT id, AccountSSD__c, Actual_New_Subscription_Product__c,Premium_New_Service__c, Premium_New_Subscription__c FROM Product_Account_Detail__c WHERE ZP_Cust_Number__c = '1234567890' LIMIT 1];
        System.assertEquals(acctssd.id, pad.AccountSSD__c, 'Source System Detail:'+pad.AccountSSD__c);
        //System.assertEquals(prd.id,pad.Actual_New_Subscription_Product__c,'Actual New Subscription Product:'+pad.Actual_New_Subscription_Product__c);
    }
    
    @isTest
    static void updateDigitalSubscription() {
    	
        Source_System_Detail__c acctssd = [SELECT id FROM Source_System_Detail__c WHERE Source_System_Account_Number__c = '1234567890'];
        Product_Account_Detail__c pad = new Product_Account_Detail__c();
        pad.ZP_Cust_Number__c = '1234567890';
        insert pad;
        pad = [SELECT id, AccountSSD__c, Actual_New_Subscription_Product__c,Premium_New_Service__c, Premium_New_Subscription__c FROM Product_Account_Detail__c WHERE ZP_Cust_Number__c = '1234567890' LIMIT 1];
        pad.Premium_New_Service__c = '12345';
        pad.Premium_New_Subscription__c = '67890';

        Test.startTest();
        update pad;
        Test.stopTest();   
        
        pad = [SELECT id, AccountSSD__c, Actual_New_Subscription_Product__c,Premium_New_Service__c, Premium_New_Subscription__c FROM Product_Account_Detail__c WHERE ZP_Cust_Number__c = '1234567890' LIMIT 1];
        System.assertEquals(acctssd.id, pad.AccountSSD__c, 'Source System Detail:'+pad.AccountSSD__c);
    }
    
    @isTest
    static void bypassDigitalSubscription() {
		
		// create Digital Subscription with no matching SSD Account
		Product_Account_Detail__c pad = new Product_Account_Detail__c();
        pad.ZP_Cust_Number__c = 'XYZ4567890';
        pad.Actual_New_Service__c = '12345'; // match with Product1 product code
        pad.Actual_New_Subscription__c = '67890';
        
        Test.startTest();
        insert pad;
        Test.stopTest();
        
        pad = [SELECT id, Bypass_Automation__c FROM Product_Account_Detail__c WHERE ZP_Cust_Number__c = 'XYZ4567890' LIMIT 1];
        System.assertEquals(pad.Bypass_Automation__c, true, 'Source System Detail:' + pad.Bypass_Automation__c);
    }
    
}