objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRMOD URL</label>
</CustomObject>

objects/Product_Trial__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product Trials</relationshipLabel>
        <relationshipName>Product_Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Start_Date__c</fullName>
        <label>Trial Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Trial</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Trial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trial_User__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Trial Users</relationshipLabel>
        <relationshipName>Trial_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Trial__c</fullName>
        <label>Product Trial</label>
        <referenceTo>Product_Trial__c</referenceTo>
        <relationshipLabel>Trial Users</relationshipLabel>
        <relationshipName>Trial_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trial User</label>
    <nameField>
        <label>Trial User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProductTrialTriggerHandler_Test.cls
/**
 * Validates the functionality provided by the ProductTrialTriggerHandler class.
 *
 * @author  Nandita Shet
 * @version  2012-11-06
 */
 
 /**
 * CHANGE HISTORY
 * =============================================================================
 * Date         Name                    Description
 * 2012-11-06   Nandita Shet        Created                                                                   
 * =============================================================================
 */
 
@IsTest(seealldata = true)
private class ProductTrialTriggerHandler_Test {
    public static testmethod void UpdateAccountOnTrial_Test(){
        Account testAccount = UnitTest.getAccountInstance();
        insert testAccount;
        
        Opportunity testOpportunity = UnitTest.getOpportunityInstance(testAccount.Id);
        insert testOpportunity ;
        Contact testContact = UnitTest.getContactInstance(testAccount.Id);
        insert testContact;
        OpportunityContactRole testOpportunityContactRole = new OpportunityContactRole(ContactId=testContact.Id,OpportunityId =testOpportunity.Id,Role='Trial User');
        insert testOpportunityContactRole;
        Product_Trial__c testProductTrial = new Product_Trial__c(Opportunity__c = testOpportunity.Id,Trial_Start_Date__c=System.Today());
        insert testProductTrial;
        update testProductTrial;
        List<Trial_User__c> ListTrialUsers = [Select Product_Trial__c,Contact__c from Trial_User__c where Product_Trial__c =:testProductTrial.Id];
        System.debug(ListTrialUsers.size()+'****testmethod');
    }


}