objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BU_Segment__c</fullName>
        <description>Created as part of data segmentation for LOTUS, should hold different Business Segments. DPS-2734</description>
        <label>BU Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/KeyValueListStore__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueListStore</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BU_Segment__c</fullName>
        <description>Created as part of data segmentation for LOTUS, should hold different Business Segments. DPS-1442</description>
        <label>Frozen Market Current Year Segment L1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <label>Competitor Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Was_There_a_Competitor__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1099 Pro</fullName>
                </value>
                <value>
                    <fullName>5280 Magazine</fullName>
                </value>
                <value>
                    <fullName>AAC</fullName>
                </value>
                <value>
                    <fullName>ABA-ALI Continuing Professional Education</fullName>
                </value>
                <value>
                    <fullName>Abacus Law</fullName>
                </value>
                <value>
                    <fullName>Absolute Tax</fullName>
                </value>
                <value>
                    <fullName>Abstract Master</fullName>
                </value>
                <value>
                    <fullName>AccessData</fullName>
                </value>
                <value>
                    <fullName>Accountedge</fullName>
                </value>
                <value>
                    <fullName>Actionstep</fullName>
                </value>
                <value>
                    <fullName>Aderant</fullName>
                </value>
                <value>
                    <fullName>Aderant - Total Office</fullName>
                </value>
                <value>
                    <fullName>Advantage Law</fullName>
                </value>
                <value>
                    <fullName>Affinity</fullName>
                </value>
                <value>
                    <fullName>Allegro</fullName>
                </value>
                <value>
                    <fullName>AlphaTax</fullName>
                </value>
                <value>
                    <fullName>AlternaDev</fullName>
                </value>
                <value>
                    <fullName>Altman Weil</fullName>
                </value>
                <value>
                    <fullName>American Lawyer Media (ALM)</fullName>
                </value>
                <value>
                    <fullName>AMFS</fullName>
                </value>
                <value>
                    <fullName>Amicus Attorney</fullName>
                </value>
                <value>
                    <fullName>AmLaw Economic Survey</fullName>
                </value>
                <value>
                    <fullName>ASI</fullName>
                </value>
                <value>
                    <fullName>Atlantax Systems, Inc</fullName>
                </value>
                <value>
                    <fullName>ATO</fullName>
                </value>
                <value>
                    <fullName>Attorney at Law Magazine</fullName>
                </value>
                <value>
                    <fullName>Attorneys Online</fullName>
                </value>
                <value>
                    <fullName>Avalara</fullName>
                </value>
                <value>
                    <fullName>Avature</fullName>
                </value>
                <value>
                    <fullName>Avvo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Revenue_Date__c</fullName>
        <label>Expected Revenue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_GLI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The field is used for LCRM project.</description>
        <label>Is GLI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LATAM_Business_Unit__c</fullName>
        <label>Business Unit (LatAm)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bejerman</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>GTM</fullName>
                </value>
                <value>
                    <fullName>Integration Point</fullName>
                </value>
                <value>
                    <fullName>Laley</fullName>
                </value>
                <value>
                    <fullName>Mastersaf</fullName>
                </value>
                <value>
                    <fullName>Mexico - Corporate</fullName>
                </value>
                <value>
                    <fullName>Mexico - Print</fullName>
                </value>
                <value>
                    <fullName>Novaprolink</fullName>
                </value>
                <value>
                    <fullName>Paraguay</fullName>
                </value>
                <value>
                    <fullName>Peru</fullName>
                </value>
                <value>
                    <fullName>Revista - Online</fullName>
                </value>
                <value>
                    <fullName>Revista - Print</fullName>
                </value>
                <value>
                    <fullName>Revista - Telesales</fullName>
                </value>
                <value>
                    <fullName>SL - Corporate</fullName>
                </value>
                <value>
                    <fullName>TEDESCO</fullName>
                </value>
                <value>
                    <fullName>Uruguay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LATAM_Entitlement_Provided__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created as part of BLE-45</description>
        <label>Entitlement Provided</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <inlineHelpText>This field is only required when selecting &quot;Other (Specify Name)&quot; from within the Competitor Name field list of values.</inlineHelpText>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>This field is dependent on stage field as a part of DPS-5352.</description>
        <inlineHelpText>Primary reason we Won or Lost the sale.</inlineHelpText>
        <label>Win/Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Account/Relationship Management</fullName>
                </value>
                <value>
                    <fullName>Account Management</fullName>
                </value>
                <value>
                    <fullName>Additional Users / Upsell</fullName>
                </value>
                <value>
                    <fullName>Additional Users Required</fullName>
                </value>
                <value>
                    <fullName>AR/Disputed</fullName>
                </value>
                <value>
                    <fullName>Auto Cancelled/Rejected</fullName>
                </value>
                <value>
                    <fullName>Billing/Invoicing Problem</fullName>
                </value>
                <value>
                    <fullName>Billing System Cancellation</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Budget Cut</fullName>
                </value>
                <value>
                    <fullName>Budget Cut/Price Increase</fullName>
                </value>
                <value>
                    <fullName>Champion / primary user left organization</fullName>
                </value>
                <value>
                    <fullName>Change of Research Focus</fullName>
                </value>
                <value>
                    <fullName>Chose another Partner</fullName>
                </value>
                <value>
                    <fullName>Client do not recognize the sale</fullName>
                </value>
                <value>
                    <fullName>Closed Business</fullName>
                </value>
                <value>
                    <fullName>Commercial Terms</fullName>
                </value>
                <value>
                    <fullName>Company/Site Shut down</fullName>
                </value>
                <value>
                    <fullName>Company Closure</fullName>
                </value>
                <value>
                    <fullName>Competitor Replacement</fullName>
                </value>
                <value>
                    <fullName>Content</fullName>
                </value>
                <value>
                    <fullName>Contract Terms</fullName>
                </value>
                <value>
                    <fullName>Corporate Increase</fullName>
                </value>
                <value>
                    <fullName>Covid 19</fullName>
                </value>
                <value>
                    <fullName>Credit / Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Cross Border Migration</fullName>
                </value>
                <value>
                    <fullName>Currency Fluctuation</fullName>
                </value>
                <value>
                    <fullName>Customer Not Proceeding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>To be populated at the time of opportunity creation but changeable.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selling_Organization__c</fullName>
        <description>EDW	SALESORG	Selling Organization	Text</description>
        <label>Selling Organization</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Was_There_a_Competitor__c</fullName>
        <description>This field allows a user to select whether the Opportunity was going up against a Competitor.</description>
        <inlineHelpText>Must be provided when Win/Loss is populated with a &quot;Won&quot; or &quot;Lost&quot; value.  If &quot;Yes&quot; is selected, the Competitor Name field is required.</inlineHelpText>
        <label>Was There a Competitor?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RecordtypeIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will store the record type IDs which will be used in apex classes.</description>
    <fields>
        <fullName>recTypeId__c</fullName>
        <label>recTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Record type Ids</label>
</CustomObject>

classes/CaseCreation_Test.cls
/****
Test Class : Process Builder - Case Creation when Stage is 95
JIRA : DPS-15966
****/
@isTest(SeeAllData=false)
public class CaseCreation_Test{
  
  public static testmethod void oppGTMTestMethod(){  
        
        LCRMOpportunityTerritoryService obj= new LCRMOpportunityTerritoryService();
        test.starttest();
        KeyValueListStore__c kvc = new KeyValueListStore__c();
        kvc.name='ANZUsersProfileId';
        kvc.TextValue__c='00e30000001ZUki';
        insert kvc;
        KeyValueListStore__c kvc2 = new KeyValueListStore__c();
        kvc2.name='ReasonWithCompetitor';
        kvc2.TextValue__c='Content,Functionality,Price,Outsourced,Contract Terms,Poor TR Experience,Other';
        insert kvc2;
        RecordtypeIds__c rt = new RecordtypeIds__c();
        rt.name = 'Pre-Pipeline Opportunities';
        rt.recTypeId__c = '01230000001MA4h';
        insert rt;
        RecordtypeIds__c rt2 = new RecordtypeIds__c();
        rt2.name = 'Pipeline Opportunities';
        rt2.recTypeId__c = '01230000001MA4g';
        insert rt2;
        //List<Opportunity> listobj = new List<Opportunity>();  
        Account accObj = new Account();
        accObj.name = 'test acc';
        accObj.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GLI Account').getRecordTypeId();  
        accObj.BU_Region__c = 'Canada';
        accObj.Bu_Segment__c = 'Professional Tax';
        accObj.Is_GLI__c = true;
        insert accObj;
        
        Opportunity opp1= UnitTest.getOpportunityInstance(accObj.Id);
        opp1.Renewal_Flag__c = false;
        opp1.Selling_Organization__c = 'LRA';
        opp1.Expiration_Date__c = Date.Today().adddays(300);
        opp1.Expected_Revenue_Date__c = date.today();
        //listobj.add(testOpportunity);
        
        insert opp1;
        
        opp1.Sales_org__c = 'TSL';
        opp1.LATAM_Business_Unit__c = 'GTM';
        opp1.LATAM_Entitlement_Provided__c = FALSE;
        opp1.StageName = '95%';
        //opp1.Competitor_Name__c = 'BloomBerg';
        opp1.Reason__c = 'Test';
        opp1.Name__c = 'Test';
        //opp1.Was_There_a_Competitor__c = 'No';
        opp1.Expiration_Date__c = System.today().adddays(1);
        opp1.Category__c='SOFTWARE, RENOVACIÓN Y SERVICIOS';
        opp1.Sub_Category__c ='Migración';
        opp1.Sub_Category_2__c ='DFe';
        update opp1;
        
        
        
     }
     
     public static testmethod void oppGTMTestMethod2(){  
         
         LCRMOpportunityTerritoryService obj= new LCRMOpportunityTerritoryService();
        test.starttest();
        KeyValueListStore__c kvc = new KeyValueListStore__c();
        kvc.name='ANZUsersProfileId';
        kvc.TextValue__c='00e30000001ZUki';
        insert kvc;
        KeyValueListStore__c kvc2 = new KeyValueListStore__c();
        kvc2.name='ReasonWithCompetitor';
        kvc2.TextValue__c='Content,Functionality,Price,Outsourced,Contract Terms,Poor TR Experience,Other';
        insert kvc2;
        RecordtypeIds__c rt = new RecordtypeIds__c();
        rt.name = 'Pre-Pipeline Opportunities';
        rt.recTypeId__c = '01230000001MA4h';
        insert rt;
        RecordtypeIds__c rt2 = new RecordtypeIds__c();
        rt2.name = 'Pipeline Opportunities';
        rt2.recTypeId__c = '01230000001MA4g';
        insert rt2;
        //List<Opportunity> listobj = new List<Opportunity>();  
        Account accObj = new Account();
        accObj.name = 'test acc';
        accObj.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GLI Account').getRecordTypeId();  
        accObj.BU_Region__c = 'Canada';
        accObj.Bu_Segment__c = 'Professional Tax';
        accObj.Is_GLI__c = true;
        insert accObj;
        
        Opportunity opp1= UnitTest.getOpportunityInstance(accObj.Id);
        opp1.Renewal_Flag__c = false;
        opp1.Selling_Organization__c = 'LRA';
        opp1.Expiration_Date__c = Date.Today().adddays(300);
        opp1.Expected_Revenue_Date__c = date.today();
        //listobj.add(testOpportunity);
        
        insert opp1;
        
        opp1.Sales_org__c = 'TSL';
        opp1.LATAM_Business_Unit__c = 'Mastersaf';
        opp1.LATAM_Entitlement_Provided__c = FALSE;
        opp1.StageName = '95%';
        //opp1.Competitor_Name__c = 'BloomBerg';
        opp1.Reason__c = 'Test';
        opp1.Name__c = 'Test';
        //opp1.Was_There_a_Competitor__c = 'No';
        opp1.Expiration_Date__c = System.today().adddays(1);
        opp1.Category__c='SOFTWARE, RENOVACIÓN Y SERVICIOS';
        opp1.Sub_Category__c ='Migración';
        opp1.Sub_Category_2__c ='DFe';
        update opp1;
        
     }
     
     public static testmethod void oppGTMTestMethod4(){  
        
        LCRMOpportunityTerritoryService obj= new LCRMOpportunityTerritoryService();
        test.starttest();
        KeyValueListStore__c kvc = new KeyValueListStore__c();
        kvc.name='ANZUsersProfileId';
        kvc.TextValue__c='00e30000001ZUki';
        insert kvc;
        KeyValueListStore__c kvc2 = new KeyValueListStore__c();
        kvc2.name='ReasonWithCompetitor';
        kvc2.TextValue__c='Content,Functionality,Price,Outsourced,Contract Terms,Poor TR Experience,Other';
        insert kvc2;
        RecordtypeIds__c rt = new RecordtypeIds__c();
        rt.name = 'Pre-Pipeline Opportunities';
        rt.recTypeId__c = '01230000001MA4h';
        insert rt;
        RecordtypeIds__c rt2 = new RecordtypeIds__c();
        rt2.name = 'Pipeline Opportunities';
        rt2.recTypeId__c = '01230000001MA4g';
        insert rt2;
        //List<Opportunity> listobj = new List<Opportunity>();  
        Account accObj = new Account();
        accObj.name = 'test acc';
        accObj.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GLI Account').getRecordTypeId();  
        accObj.BU_Region__c = 'Canada';
        accObj.Bu_Segment__c = 'Professional Tax';
        accObj.Is_GLI__c = true;
        insert accObj;
        
        Opportunity opp1= UnitTest.getOpportunityInstance(accObj.Id);
        opp1.Renewal_Flag__c = false;
        opp1.Selling_Organization__c = 'LRA';
        opp1.Expiration_Date__c = Date.Today().adddays(300);
        opp1.Expected_Revenue_Date__c = date.today();
        //listobj.add(testOpportunity);
        
        insert opp1;
        
         opp1.Sales_org__c = 'TSL';
        opp1.LATAM_Business_Unit__c = 'Mastersaf';
        opp1.LATAM_Entitlement_Provided__c = FALSE;
        opp1.StageName = '95%';
        opp1.Reason__c = 'Test';
        opp1.Name__c = 'Test';
        opp1.Expiration_Date__c = System.today().adddays(1);
        //opp1.Category__c='SOFTWARE, RENOVACIÓN Y SERVICIOS';
        opp1.Sub_Category__c ='Software';
        update opp1;
        
     }
     
     public static testmethod void oppGTMTestMethod3(){  
        
        LCRMOpportunityTerritoryService obj= new LCRMOpportunityTerritoryService();
        test.starttest();
        KeyValueListStore__c kvc = new KeyValueListStore__c();
        kvc.name='ANZUsersProfileId';
        kvc.TextValue__c='00e30000001ZUki';
        insert kvc;
        KeyValueListStore__c kvc2 = new KeyValueListStore__c();
        kvc2.name='ReasonWithCompetitor';
        kvc2.TextValue__c='Content,Functionality,Price,Outsourced,Contract Terms,Poor TR Experience,Other';
        insert kvc2;
        RecordtypeIds__c rt = new RecordtypeIds__c();
        rt.name = 'Pre-Pipeline Opportunities';
        rt.recTypeId__c = '01230000001MA4h';
        insert rt;
        RecordtypeIds__c rt2 = new RecordtypeIds__c();
        rt2.name = 'Pipeline Opportunities';
        rt2.recTypeId__c = '01230000001MA4g';
        insert rt2;
        //List<Opportunity> listobj = new List<Opportunity>();  
        Account accObj = new Account();
        accObj.name = 'test acc';
        accObj.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GLI Account').getRecordTypeId();  
        accObj.BU_Region__c = 'Canada';
        accObj.Bu_Segment__c = 'Professional Tax';
        accObj.Is_GLI__c = true;
        insert accObj;
        
        Opportunity opp1= UnitTest.getOpportunityInstance(accObj.Id);
        opp1.Renewal_Flag__c = false;
        opp1.Selling_Organization__c = 'LRA';
        opp1.Expiration_Date__c = Date.Today().adddays(300);
        opp1.Expected_Revenue_Date__c = date.today();
        //listobj.add(testOpportunity);
        
        insert opp1;
        
        opp1.Sales_org__c = 'TSL';
        opp1.LATAM_Business_Unit__c = 'Mastersaf';
        opp1.LATAM_Entitlement_Provided__c = FALSE;
        opp1.StageName = '95%';
        //opp1.Competitor_Name__c = 'BloomBerg';
        opp1.Reason__c = 'Test';
        opp1.Name__c = 'Test';
        opp1.Category__c= 'SUSCRIPCION';
        //opp1.Was_There_a_Competitor__c = 'No';
        opp1.Expiration_Date__c = System.today().adddays(1);
        opp1.Sub_Category__c ='Nueva';
        opp1.Sub_Category_2__c ='Checkpoint';
        update opp1;
        
     }
  
}