objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of countries presented to the user when editing an address</description>
    <label>Country</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street_2__c</fullName>
        <description>Created as part of TR Store. Holds value for second line of billing address.</description>
        <label>Billing Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <inlineHelpText>If SAP Account Number is populated, changes made to this field will not be saved.</inlineHelpText>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sales_Org__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ACADEMIC</fullName>
                </value>
                <value>
                    <fullName>ACCOUNTING</fullName>
                </value>
                <value>
                    <fullName>AGENCY</fullName>
                </value>
                <value>
                    <fullName>AGENT</fullName>
                </value>
                <value>
                    <fullName>AGENT-3rdPARTYVENDOR</fullName>
                </value>
                <value>
                    <fullName>AGENT-DISTRIBUTOR</fullName>
                </value>
                <value>
                    <fullName>AGENT-FED LINK</fullName>
                </value>
                <value>
                    <fullName>AGENT-MONEYEXCHANGE</fullName>
                </value>
                <value>
                    <fullName>AGENT-RESELLER</fullName>
                </value>
                <value>
                    <fullName>AUTHOR</fullName>
                </value>
                <value>
                    <fullName>BARRISTER</fullName>
                </value>
                <value>
                    <fullName>BIOTECH/LIFE SCIENCE</fullName>
                </value>
                <value>
                    <fullName>BOOKSHOP</fullName>
                </value>
                <value>
                    <fullName>CENTRAL GOVERNMENT</fullName>
                </value>
                <value>
                    <fullName>CHEMICAL</fullName>
                </value>
                <value>
                    <fullName>CONSTRUCT/MAN/ENGINE</fullName>
                </value>
                <value>
                    <fullName>CONSULTING</fullName>
                </value>
                <value>
                    <fullName>CORPORATE</fullName>
                </value>
                <value>
                    <fullName>CORPORATION</fullName>
                </value>
                <value>
                    <fullName>COURT</fullName>
                </value>
                <value>
                    <fullName>ECOMM/INT/COMPUTING</fullName>
                </value>
                <value>
                    <fullName>EXTERNAL CUSTOMER</fullName>
                </value>
                <value>
                    <fullName>GOVERNMENT (FEDERAL)</fullName>
                </value>
                <value>
                    <fullName>FEDERAL GOVT(NON-US)</fullName>
                </value>
                <value>
                    <fullName>FINANCE/BANK/ACCOUNT</fullName>
                </value>
                <value>
                    <fullName>FIRM</fullName>
                </value>
                <value>
                    <fullName>FOOD PRODUCTION</fullName>
                </value>
                <value>
                    <fullName>GOVERNMENT (STATE, LOCAL)</fullName>
                </value>
                <value>
                    <fullName>HEALTHCARE</fullName>
                </value>
                <value>
                    <fullName>HK_ACAD_CITYU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sales_Org__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Organization</fullName>
                </value>
                <value>
                    <fullName>Academic Sales</fullName>
                </value>
                <value>
                    <fullName>Consortia</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_Sub_BU__c</fullName>
        <description>Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-1711</description>
        <label>BU Region</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Region__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TR Store Canada Print</fullName>
                </value>
                <value>
                    <fullName>TR Store US Print</fullName>
                </value>
                <value>
                    <fullName>TR Store Tax Professional</fullName>
                </value>
                <value>
                    <fullName>UE Store Canada PRINT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org of Lead</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>WEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <description>This field is used to support WSS Account SSD Data mapping and migration. (DPS-1113)</description>
        <label>Company Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Country_Code__c</fullName>
        <label>Country Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Customer_Group__c</fullName>
        <description>Created for US Legal Sales Users as part of LegalCRM-R4 project(CRM-6422)</description>
        <label>Customer Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Customer_Type__c</fullName>
        <label>Customer Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LCRM_Industry__c</fullName>
        <description>Created for USL R4</description>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Market_Segment__c</fullName>
        <label>Market Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_Street_2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Sub_BU__c</fullName>
        <description>Renamed from ‘Sub-BU’ to ‘Region’ as part of data segmentation for LOTUS. DPS-1445</description>
        <label>BU Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Name__c</fullName>
        <label>Source System Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Static_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>We will store key pair static values under this custom settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Static Values</label>
</CustomObject>

classes/DCPConvertLeadHelper.cls
/**
* @description
* Class: DCPCovertLead
* Purpose: Convert Lead  to Acct, Cont, Oppty and create SSD
* Created: 06/14/2021
* Author: Kavya Ganagaraju
* 
* CHANGE HISTORY
* =============================================================================
* Date         Name             JIRA        Description
* 06/14/2021   Kavya G          DCP-1693    Created
* =============================================================================
*/
public with sharing class DCPConvertLeadHelper {


    String supportEmail = '';
    /***************************************
     * @description Constructor
     *****************************************/
    public DCPConvertLeadHelper(){
        supportEmail = Static_Values__c.getValues('LeadSupportEmail').Value__c;
    }
   /****************************************************
     * @description
     ***************************************************/
    /*public class ConvertLeadWrapperDetails{
    
        public id leadId;
        public id cartId;
        public string emailId;  
        public id quoteId ; 
        public Map<string,decimal> leadToContractTermMap;
        public id trialID;//Added as part of DCP-4147
        public string trialStatus;//Added as part of DCP-4147
        public string reviewRequired;//Added as part of DCP-4147
        public string reviewRequiredNotes;//Added as part of DCP-4147
     }
*/
    /*************************************************
    * @description CreateOpptyWrap class
    **************************************************/
    public class CreateOpptyWrap{        
        public string accNamew ;
        public id accIDw ;
        public id conIDw ;
        public id accSsdw;
        public Lead lead;
        public DCPConvertLeadUtility.ReferenceDetails rdw ;
        public Source_System_Detail__C ssdRecw;
        public decimal contractTerm;
        /**
        * @description
        */
        public CreateOpptyWrap(){
                ssdRecw = new Source_System_Detail__C ();
                accNamew = '';
        }   
    }
    
    /**************************************************************
    * @description  CreateNewSsdWrap
    ***************************************************************/
    private class CreateNewSsdWrap{
        private lead lwr ;
        private Id oAccountw; 
        private string oAccountNamew;  
        private boolean shippingOnlyw;
       // private boolean reviewRequired; //Added by priyanka DCP-4231
        /**
        * @description
        */
        private CreateNewSsdWrap(){
           lwr = new Lead();
       }
   }

   /***************************************************************
     * @description createNewAccount: Create new Account, SSD records
     * @param l
     * @param existingContAcctmap
     * @return DCPConvertLeadUtility.ReferenceDetails
     **************************************************************/
    public  DCPConvertLeadUtility.ReferenceDetails createNewAccount(lead l,
                                            Map<String,String> existingContAcctmap){
        
        id accId;
        id conId;
        DCPConvertLeadUtility.ReferenceDetails refDetails =
                new DCPConvertLeadUtility.ReferenceDetails();
        Map<String, Source_System_Detail__c> sSDMap =
                        new  Map<String, Source_System_Detail__c>();

        for(string cid: existingContAcctmap.keyset()){
            accId = existingContAcctmap.get(cid);
            conId = cid;
        }

        try{
            if(existingContAcctmap.isEmpty()){

                Account oAccount           = new Account();
                oAccount.Name              = l.company; 
                oAccount.Email__c          = l.Email;
                oAccount.Phone             = l.Phone;
                oAccount.BillingCity       = l.Billing_City__c; 
                oAccount.BillingStreet     = l.Billing_Street__c;
                oAccount.BillingState      = l.Billing_State__c;
                oAccount.BillingCountry    = l.Billing_Country__c;
                oAccount.BillingPostalCode = l.Billing_Zip__c;
                oAccount.CurrencyIsoCode   = (l.Lead_Region__c==
                                              DCPConstants.UE_CAN_PRINT)? 
                                              DCPConstants.CAD_CURRENCYCODE :
                                              DCPConstants.USD_CURRENCYCODE;
                oAccount.Sales_Org__c = l.Sales_org__c;
               
                database.saveresult accSaveResults;
                accSaveResults = database.insert(oAccount,false);
                 
                accid = oAccount.id;

            }

            if(accId != null) {
                CreateNewSsdWrap cssdWrap = new CreateNewSsdWrap();
                cssdWrap.lwr           = l;
                cssdWrap.oAccountw     = accId;
                cssdWrap.oAccountNamew = l.company;
                cssdWrap.shippingOnlyw = false;
                //cssdWrap.reviewRequired = clwd.reviewRequired;   //added by priyanka DCP-4231               
                sSDMap = createNewSSD(cssdWrap);
            }else{
                
                Map<String,String> errorHandlerMap = new Map<String,String>{
                        'objectName'=>'Lead','expMsg'=>'Errors While Creation of Account',
                         +'webServiceName'=>'createNewAccount',
                         +'requestType'=>'Account Creation',
                         +'reqMsg'=>'Exception Class Name: DCPConvertlead',
                         +'recId'=>l.Id,'supportEmail'=>supportEmail,'toSupport'=>'true'};
                DCPNewSaleUtilityCls.logException(errorHandlerMap);                
            }

            refDetails.convertedAccId = accId;
            if(!sSDMap.isEmpty()){
                refDetails.accountSSDId = sSDMap.get(DCPConstants.BILL_TO).Id;
                refDetails.ssdRec = sSDMap.get(DCPConstants.BILL_TO);
                }
            }       
            catch(Exception e){
                
                Map<String,String> errorHandlerMap = new Map<String,String>{
                    'objectName'=>'Lead','expMsg'=>'Errors While Creation of Account / SSD'
                         + e.getMessage(),'webServiceName'=>'createNewAccount',
                         +'requestType'=>'Account Creation',
                         +'reqMsg'=>'Exception Class Name: DCPConvertlead',
                         +'recId'=>l.Id,'supportEmail'=>supportEmail,'toSupport'=>'true'};
                DCPNewSaleUtilityCls.logException(errorHandlerMap);             
        }
        
        return refDetails;
    } 

     /*****************************************************
     * @description createNewSSD Created new SSD record
     * @param cnsw
     * @return Map<string,Source_System_Detail__c>
     ****************************************************/

    public Map<string,Source_System_Detail__c> createNewSSD(CreateNewSsdWrap cnsw){
        lead l = cnsw.lwr;
        Id oAccount = cnsw.oAccountw;
        String oAccountName = cnsw.oAccountNamew;
        Boolean shippingOnly = cnsw.shippingOnlyw;
        //Boolean reviewRequired = cnsw.reviewRequired; // Added by priyanka DCP-4231
    
        string ssdRecordType = Static_Values__c.getValues('SSDRecordType').value__c;  
        Map<String, Source_System_Detail__c> sSDMap = new  Map<String, Source_System_Detail__c>();  
        Id ssdrectype =
            Schema.SObjectType.Source_System_Detail__c.getRecordTypeInfosByName().get(ssdRecordType).getRecordTypeId();
        LIST<Source_System_Detail__c> ssdList = new LIST<Source_System_Detail__c>();
            
        if(!shippingOnly){
            // This is for billing address SSD details.......
            Source_System_Detail__c ssd = new Source_System_Detail__c();        
            ssd.Name                        = oAccountName;
            ssd.Number_Street__c            = l.Billing_Street__c;
            ssd.LCRM_Street_2__c            = l.Billing_Street_2__c;
            ssd.City__c                     = l.Billing_City__c; 
            ssd.State__c                    = l.Billing_State__c; 
            ssd.Country__c                  = l.Billing_Country__c; 
            ssd.Postal_Code__c              = l.Billing_Zip__c; 
            ssd.Account_Name__c             = oAccount;
            ssd.RecordtypeId                = ssdrectype;
            ssd.Source_System_Name__c       = oAccountName;
            ssd.LCRM_Email__c               = l.Email;
            ssd.Company_Code__c             = DCPConstants.USL_SSD_COMPANY_CODE;
            ssd.CurrencyIsoCode             = (l.Lead_Region__c==DCPConstants.UE_CAN_PRINT)? 
                                                        DCPConstants.CAD_CURRENCYCODE :
                                                        DCPConstants.USD_CURRENCYCODE;
            ssd.LCRM_Sales_Org__c           = DCPConstants.SALESORG_WEST;
            ssd.LCRM_Sub_BU__c              = DCPConstants.BU_USL;
            ssd.LCRM_Industry__c            = DCPConstants.NA;
            ssd.LCRM_Country_Code__c        = DCPConstants.US;
            ssd.LCRM_Market_Segment__c      = l.Market_Segment__c;            
            ssd.LCRM_Phone__c               = l.Phone;
            /*ssd.Send_Digital_Orders_to_ZPND__c = reviewRequired; //Added by Priyanka DCP-4231
         // Mapping the fields as per DCP-3306 -Kavya S
            ssd.LCRM_Customer_Group__c = l.Customer_Group__c;
            ssd.LCRM_Customer_Type__c = l.Customer_Type__c ;
            ssd.LCRM_Industry__c = l.Market_Segment__c;*/
                        
            ssdList.add(ssd);            
            SSDMap.put(DCPConstants.BILL_TO,ssd);
        }
                     
        LIST<database.saveresult> ssdResult;
        ssdResult = database.insert(ssdList, false);
       
        if(!ssdList.isEmpty()){  
          return SSDMap;
        }else {
            return null;
        }    
    }
}