objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account_Name__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Product_Participation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Course</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testUpdateAccOnContactTrigger.cls
@isTest
public class testUpdateAccOnContactTrigger
{
    public static testmethod void testUpdateAccOnContactTrigger()
    {
        Account account = UnitTest.getAccountInstance();       
        account.Name = 'testAccount';
        account.Customer_Type__c = 'Induvidual';
        account.Customer_Group__c = 'ACADEMIC';
        account.Industry = 'Energy';
        account.SAPAccountNumber__c = '8888888888';
        insert account;
        
        Contact contact = new Contact();
        contact.LastName = 'testContact';
        contact.FirstName = 'testContact';
        //contact.AccountId = account.Id;
        insert contact;
        
        Course__c tCourse = new Course__c();
        tCourse.Account_Name__c =account.id;
        //tCourse.name= 'testCourse';
        tCourse.Contact_Name__c = contact.id;
        
        insert tCourse;
        
        }
}