objects/CustomDate__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Custom Date</label>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for User</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Bu__c</fullName>
        <description>The field has been created to define the sub bu of the user which will be used to populate the Sub bu field on objects Account,Lead,Opportunities,Activity etc. 
Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-2201, DPS-415</description>
        <label>BU Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>USL</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>AEM</fullName>
                </value>
                <value>
                    <fullName>LatAm</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/USL_ServiceNotesESI.cls
/**
 * Contains methods for ServiceNotes VF Page
 * Depends on ServiceNotesServices Class
 * Depends on ServiceNotesServicesWS and  ServiceNotesServicesWS Objects Class which are created using the wsdl file
 * Contains the method to build the request to get the list of service notes based on the date range entered on the VF page.
 * Contains the method to build the request to get the detail of the service note selected on the VF page
 *
 * @author  Srikanth Kuruva
 * @version  2012-12-13
 */
 /**
 * CHANGE HISTORY
 * =============================================================================
 * Date         Name                    Description
 * 2012-10-20   Sripriya Kongot         Modified - QC 2159 Fixed the sorting issue - Results will be sorted DESC by CreatedDate
 * 2012-10-20   Sripriya Kongot         Modified - QC 2140 Added pagination to display the results
 * 2017-03-31   Karthi                  Optimized the code as per JIRA STORY: PS0-1
 * 2018-06-13   Matthew Main            Cloned from ServiceNotes Class. Implementation of ESI Integration ESD-381
 * =============================================================================
 */
public without sharing class USL_ServiceNotesESI {
    public Account oAccount{get;set;}      
    public string dFromDt{get;set;}
    public string dToDt{get;set;}
    public string serviceNoteDetailId{get;set;}     
    public List<ServiceNotesServices.ServiceNoteItem> listServiceNotes{get;set;}      
    public ServiceNotesServices.ServiceNoteItem ServiceNoteDetail{get;set;}
    public List<ServiceNotesServices.ServiceNoteActivity> listServiceNoteActivities{get;set;}
    public String snId{get;set;}
    public Boolean RenderServiceNoteList{get;set;}
    public Boolean RenderServiceNoteDetail{get;set;}
    public String FilterByDepartmentValue{get;set;}
    public Boolean showFilter{get;set;}
    //public CustomDate__c DateRange{get;set;}
    public List<ServiceNotesServices.ServiceNoteItem> listServiceNotesResult{get;set;}
    public ServiceNoteItems ServiceNotesResults {get;set;}
    public User sCurrentUser{get;set;}
    public List<Source_System_Detail__c> listOfSSD;
    public String strSalesOrg;
    public List<String> accountSapIdList;


    public USL_ServiceNotesESI(ApexPages.StandardController controller) { 
        oAccount = new account();
        oAccount = (account) controller.getRecord();
        oAccount = [select Account_Indicator__c,ParentId,SAPAccountNumber__c, id from Account where id = :oAccount.Id];
        dFromDt = system.today().addMonths(-1).format();
        dToDt = system.today().format();
        ServiceNotesResults = new ServiceNoteItems();
        PageReference pg = getlistServiceNoteItems(); 
    }
   
        
    public PageReference getlistServiceNoteItems()
    {
        try{
        if(dFromDt == '' || dFromDt == null){
/*system.debug('dFromDt :'+dFromDt +'dToDt :'+dToDt);-- commented to reduce character for s2e optimization */
            ApexPages.Message mErrorMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter the Date Range.');
            ApexPages.addMessage(mErrorMsg);
        }
        else {
            RenderServiceNoteList = true;
            RenderServiceNoteDetail = false;
            ServiceNotesServices.ServiceNotesRequest oServiceNotesRequest = new ServiceNotesServices.ServiceNotesRequest();
            oServiceNotesRequest.sSystemId = 'SFDC CORE LEGAL';
 
            sCurrentUser = [select LanguageLocaleKey,Sales_Org__c,Sub_Bu__c from User where id = :UserInfo.getUserId()];
            Set<ID> accountIdSet = USLARHelper.getAccountSetList(oAccount);
            String strSubBu  = sCurrentUser.Sub_Bu__c;
            ListofSSD = new List<Source_System_Detail__c>();
            accountSapIdList = new List<String>();
            
            if(accountIdSet.size()>0 && String.isnotblank(strSubBu)){
                ListofSSD = USLARHelper.getSourceSystemDetails(accountIdSet,strSubBu);
                System.debug('ListofSSD:'+ListofSSD);
                if(ListofSSD.size()>0){
                    if(String.isnotblank(ListofSSD[0].LCRM_Sales_Org__c)){
                        strSalesOrg = ListofSSD[0].LCRM_Sales_Org__c;
                        for(Source_System_Detail__c SSD : ListofSSD){
                            if(String.IsNotBlank(SSD.Source_System_Account_Number__c)){
                                accountSapIdList.add(SSD.Source_System_Account_Number__c);
                            }
                        }//End For Loop
                    }
                }else if(ListofSSD == null || ListofSSD.isEmpty()){
                    System.debug('SSD List is blank');
                    Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,(Label.LCRMNoSubBUError)));
                }
                //End SSD List Size Checking
            }else{
                //Need to add new lable for SUB BU blank
                System.debug('Not found SUB BU');
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,Label.LCRMCurrentUsersSub_BU));
            }
            
            List<Decimal> accountSapList = new List<Decimal>();
            if(accountSapIdList != null){
                for(String s : accountSapIdList){
                   accountSapList.add(Decimal.valueOf(s));
                   
                }
                 oServiceNotesRequest.dcAcctSAPId = accountSapList;    
            }
            
            oServiceNotesRequest.dBegDt = date.parse(dFromDt);
            oServiceNotesRequest.dEndDt = date.parse(dToDt);


            listServiceNotesResult = ServiceNotesServices.getServiceNotesInfoESI(oServiceNotesRequest);


            listServiceNotes = listServiceNotesResult;
            //ServiceNotesResults = new ServiceNoteItems();
            ServiceNotesResults.listServiceNotesItems =  listServiceNotesResult;
            this.ServiceNotesResults.initPaging();  
            ShoworHideFilter();
          }
        }
        catch(Exception oException){
            if(oException.getMessage().contains('Unexpected character (\'U\' (code 85))')){
                ApexPages.addMessages(new AppUtil.AppException('401 Unauthorized response received from server. Please verify the username and password in the web service custom setting'));
            }
            else if(oException.getMessage().contains('timed out'))
              // ApexPages.addMessages(new AppUtil.AppException('A time-out error has occurred, please narrow your search criteria and try again.')); //Replaced with custom Label as part of S2E Optimization
              ApexPages.addMessages(new AppUtil.AppException(Label.ServiceNotesEx));
            
            else    
                ApexPages.addMessages(oException);
        }
        return null;
    }
    
    public boolean changeServiceNoteDetail(){
        ServiceNotesServices.ServiceNoteItemDetailRequest oServiceNoteItemDetailRequest = new ServiceNotesServices.ServiceNoteItemDetailRequest();
        oServiceNoteItemDetailRequest.sSystemId = 'SFDC CORE LEGAL';
        oServiceNoteItemDetailRequest.sServiceNoteId = ApexPages.currentPage().getParameters().get('snId');        
/*system.debug('oServiceNoteItemDetailRequest'+oServiceNoteItemDetailRequest);-- commented to reduce character for s2e optimization */




        try{
            ServiceNoteDetail = ServiceNotesServices.getServiceNoteItemDetailESI(oServiceNoteItemDetailRequest);
            if(ServiceNoteDetail != null) {
                listServiceNoteActivities = ServiceNoteDetail.ActivityCodeItemList;
                /*system.debug('ServiceNoteDetail'+ServiceNoteDetail);-- commented to reduce character for s2e optimization */
                RenderServiceNoteDetail = true;
                return null;
            }
        }
        catch(Exception e){
            ApexPages.addMessages(new AppUtil.AppException('Unable to retrieve the Service Note Detail.' + e));
            //throw e;
            RenderServiceNoteDetail =  false;
            return null;
        }


        //ApexPages.addMessages(new AppUtil.AppException('Unable to retrieve the Service Note Detail.'));
        return null;
    }

    public PageReference FilterByDepartment(){
        listServiceNotes = new List<ServiceNotesServices.ServiceNoteItem>();
        if(FilterByDepartmentValue!=''){
            listServiceNotes.clear();
            List<String> listDepartmentValues = FilterByDepartmentValue.split(',');
            for(ServiceNotesServices.ServiceNoteItem sni: listServiceNotesResult){
                for(string s : listDepartmentValues){
/*system.debug('sni.DepartmentDesc:'+sni.DepartmentDesc.toLowerCase()+'s:'+s.toLowerCase());-- commented to reduce character for s2e optimization */
                    if(sni.DepartmentDesc.toLowerCase().contains(s.trim().toLowerCase()))
                    {                        
                        listServiceNotes.add(sni);
                        break;
                    }
                }
            }
        }
        else{
            listServiceNotes.clear();
            listServiceNotes = listServiceNotesResult;
        }
        //ShoworHideFilter();
        //Reinitialize the result list & paging upon filtering
        ServiceNotesResults.listServiceNotesItems.clear();
        ServiceNotesResults.listServiceNotesItems =  listServiceNotes;
        this.ServiceNotesResults.initPaging();  
        return null;
    }
    
    public void ShoworHideFilter(){
        if(!listServiceNotes.isEmpty()){
            showFilter = true;
        }
        else{
            showFilter = false;
        }
    }
}