objects/Ent_Trial__c.object
<CustomObject>
    <description>created as part of DPS-21062 for  omni enterprise trial</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Trials1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Account_Number_Source__c</fullName>
        <label>External Account Number Source</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Account_Number__c</fullName>
        <label>External Account Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Trial Start Date</label>
        <type>Date</type>
    </fields>
    <label>Enterprise Trials</label>
    <nameField>
        <displayFormat>ET-{00000}</displayFormat>
        <label>Trial Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enterprise Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>DC_Product_Title__c</fullName>
        <externalId>true</externalId>
        <label>Product Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Trial__c</fullName>
        <description>DPS-20817 Flag to note that a free demo is available and would trigger the demo to display online or for omni channel</description>
        <label>Free Trial</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Offering__c</fullName>
        <label>Product Offering</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Relationship__c.object
<CustomObject>
    <description>Created as a part of DPS-21444</description>
    <fields>
        <fullName>Product_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of DPS-21444</description>
        <label>Product From</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Relationships (Product From)</relationshipLabel>
        <relationshipName>Product_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of DPS-21444</description>
        <label>Product To</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Relationships</relationshipLabel>
        <relationshipName>Product_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Link_Type__c</fullName>
        <description>Created as a part of DPS-21444</description>
        <label>Relationship Link Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Created  as a part of DPS-21444</description>
        <label>Relationship Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>Created as a part of DPS-21444</description>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Relationship</label>
    <nameField>
        <label>Product Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trial__c.object
<CustomObject>
    <description>As per DLT-5979 - This object is created to capture details of Trial.</description>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Start_Date__c</fullName>
        <label>Trial Start Date</label>
        <type>Date</type>
    </fields>
    <label>Trial</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Trial Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trial_Contact__c.object
<CustomObject>
    <description>created as part of DPS-21134 for omni enterprise trial</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Trials__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_Contact_Number_Source__c</fullName>
        <label>External Contact Number Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>One_Pass_ID__c</fullName>
        <label>One Pass ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It is checked if User has selected as a primary on Trial Console page</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Bounceback</fullName>
                </value>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>TimedOut</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Entitlement Error</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                    <isActive>false</isActive>
                    <label>Activated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trials__c</fullName>
        <label>Trial</label>
        <referenceTo>Ent_Trial__c</referenceTo>
        <relationshipLabel>Trial Contacts</relationshipLabel>
        <relationshipName>Trial_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Trial Contact</label>
    <nameField>
        <label>Trial Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Trial_Product__c.object
<CustomObject>
    <description>Created as part of DPS-20526 for omni enterprise trial</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Trial Products</relationshipLabel>
        <relationshipName>Trial_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>DPS-20709 - Enterprise Trials - Select Trial Product(s) - populate from Product relationship Object</description>
        <label>Relationship Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>DPS-20709 - Enterprise Trials - Select Trial Product(s) - populate from Product RelatedShip Object</description>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial</label>
        <referenceTo>Ent_Trial__c</referenceTo>
        <relationshipLabel>Trial Products</relationshipLabel>
        <relationshipName>Trial_Products1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Trial Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ODTDG_RetrieveAddedUsersTest.cls
@isTest(seeAllData=false)
public with sharing class ODTDG_RetrieveAddedUsersTest {


/********************************************************************************************************
*  @description method1: this is the test method to check ODTDG Retrieve added users
*********************************************************************************************************/
    @isTest
    static void method1() {
        
        Account acc = new account();
        acc.name = 'test';
        acc.BillingCountry = 'US';
        acc.Billingcity= 'Baltimore'; 
        acc.billingstate= 'AK';
        acc.BillingpostalCode='21204';
        insert acc;
        
        ent_Trial__c trc= new ent_Trial__c();
        trc.account__c = acc.id;
        trc.Trial_Start_Date__c  =system.today();
        trc.Trial_End_Date__c = system.today();
        trc.External_Account_Number__c = '4332938';
        trc.External_Account_Number_Source__c = 'SAP';
        insert trc;
        
        list<Trial_Contact__c> trialContacts = new list<Trial_Contact__c>();

        Trial_Contact__c trlCon = new Trial_Contact__c();
        trlCon.Email__c = 'mallik.rao2@mailinator.com';
        trlCon.Trials__c = trc.id;
        trlCon.name = 'test';
        trlCon.Status__c  = 'Draft';
        trlCon.First_Name__c = 'Fname';
        trlCon.Last_Name__c = 'lname';
        trlcon.Name= 'Test Name';
        trlcon.External_Contact_Number_Source__c= 'SAP';
        trlCon.Primary__c=true;
        trlCon.One_Pass_ID__c='A00001';
        trialContacts.add(trlCon);

        Trial_Contact__c trlCon1 = new Trial_Contact__c();
        trlCon1.Email__c = 'get2arpit@me.com';
        trlCon1.Trials__c = trc.id;
        trlCon1.name = 'test';
        trlCon1.Status__c  = 'Draft';
        trlCon1.First_Name__c = 'Fname';
        trlCon1.Last_Name__c = 'lname';
        trlcon1.Name= 'Test Name';
        trlcon1.External_Contact_Number_Source__c= 'OLC';
        trlCon1.Primary__c=false;
        trlCon1.One_Pass_ID__c='A00002';
        trialContacts.add(trlCon1);

        Trial_Contact__c trlCon2 = new Trial_Contact__c();
        trlCon2.Email__c = 'get2arpit2@me.com';
        trlCon2.Trials__c = trc.id;
        trlCon2.name = 'test2';
        trlCon2.Status__c  = 'Draft';
        trlCon2.First_Name__c = 'Fname2';
        trlCon2.Last_Name__c = 'lname2';
        trlcon2.Name= 'Test Name2';
        trlcon2.External_Contact_Number_Source__c= 'OLC';
        trlCon2.Primary__c=false;
        trlCon2.One_Pass_ID__c='A00003';
        trialContacts.add(trlCon2);

        insert trialContacts;
        
        
        Product2 prd = new Product2();
        prd.DC_Product_Title__c = 'sample product';
        prd.Name ='TEST';
        prd.ProductCode = '42514196';
        prd.Product_Offering__c='Westlaw Edge';
        prd.free_trial__c = 'Digital';
        insert prd;
        
        Trial_Product__c trprd = new Trial_Product__c();
        trprd.Product_Name__c = prd.id;
        trprd.Trial__c = trc.id;
        trprd.Name= 'Test Name';
        insert trprd;
        
        Product_Relationship__c p1 = new Product_Relationship__c();
        p1.Product_to__c = prd.Id;
        p1.Product_from__c = prd.Id;
        p1.Segment__c = 'In-house counsel';
        p1.Relationship_Link_Type__c ='best';
        p1.Relationship_Type__c = 'plan to plan';
        insert p1;

        Test.startTest();
        // Forming the request
        RestRequest primaryUser = new RestRequest();
        primaryUser.requestUri = '/services/apexrest/ODTDGCountryStates';
        primaryUser.addParameter('onePassId', 'A00001');
        //contactRequest.addParameter('productCode', '');
        primaryUser.httpMethod = 'GET';
        RestContext.request = primaryUser;

        // Testing the API
        List<ODTDG_RetrieveAddedUsers.UserDetails> res1 = ODTDG_RetrieveAddedUsers.retrieveUsersData(); 
        System.debug(LoggingLevel.INFO,'res1..... '+res1);       
        System.assert(res1 != null,'Value is Null');
       
        RestRequest inviteUser = new RestRequest();
        inviteUser.requestUri = '/services/apexrest/ODTDGCountryStates';
        inviteUser.addParameter('onePassId', 'A00002');
        //contactRequest.addParameter('productCode', '');
        inviteUser.httpMethod = 'GET';
        RestContext.request = inviteUser;

        // Testing the API
        List<ODTDG_RetrieveAddedUsers.UserDetails> res2 = ODTDG_RetrieveAddedUsers.retrieveUsersData(); 
        System.debug(LoggingLevel.INFO,'res2..... '+res2); 
        
        
        RestRequest inviteUser2 = new RestRequest();
        inviteUser2.requestUri = '/services/apexrest/ODTDGCountryStates';
        inviteUser2.addParameter('onePassId', 'A00003');
        //contactRequest.addParameter('productCode', '');
        inviteUser2.httpMethod = 'GET';
        RestContext.request = inviteUser2;

        // Testing the API
        List<ODTDG_RetrieveAddedUsers.UserDetails> res3 = ODTDG_RetrieveAddedUsers.retrieveUsersData(); 
        System.debug(LoggingLevel.INFO,'res3..... '+res3); 


        Test.stopTest();
                
        
    }
}