objects/ESC_Case_Collaborator__c.object
<CustomObject>
    <description>ESC_ Custom object to enable the Accountable Resolver, Case Collaborator, and Escalation processes in Enterprise Service Cloud program</description>
    <fields>
        <fullName>ESC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESC_ The related case to the referral</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals/Escalations</relationshipLabel>
        <relationshipName>Case_Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESC_Severity__c</fullName>
        <description>ESC_ The Severity field from the related case</description>
        <formula>TEXT( ESC_Case__r.ESC_Severity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Severity</label>
        <type>Text</type>
    </fields>
    <label>Referral/Escalation</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals/Escalations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESC_Case_Form_Extension__c.object
<CustomObject>
    <fields>
        <fullName>ESC_Approver_Id__c</fullName>
        <label>Approver Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Form Extension</relationshipLabel>
        <relationshipName>Case_Form_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ESC_Form_BU__c</fullName>
        <label>Form BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USL</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>TRTA Corp</fullName>
                </value>
                <value>
                    <fullName>Tax Profs - Content</fullName>
                </value>
                <value>
                    <fullName>Tax Profs - Software</fullName>
                </value>
                <value>
                    <fullName>Tax Profs - DT Tax</fullName>
                </value>
                <value>
                    <fullName>Tax Profs – Content</fullName>
                    <isActive>false</isActive>
                    <label>Tax Profs – Content</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ESC Form</label>
        <referenceTo>GenerateForm__c</referenceTo>
        <relationshipLabel>Case Form Extensions</relationshipLabel>
        <relationshipName>ESC_GenerateForm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_To_USL_Print_CD_Credits__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Route To USL Print CD Credits</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>USL_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USL_Approval_Type__c</fullName>
        <label>Charge Cancellation BU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USL_Customer_Service</fullName>
                    <label>USL Customer Service</label>
                </value>
                <value>
                    <fullName>CDN Customer Service</fullName>
                </value>
                <value>
                    <fullName>Findlaw_Customer_Service</fullName>
                    <label>Findlaw Customer Service</label>
                </value>
                <value>
                    <fullName>EBO_Collections</fullName>
                    <label>C2C USL Collections</label>
                </value>
                <value>
                    <fullName>Writeoff</fullName>
                </value>
                <value>
                    <fullName>EBO_Order_Management</fullName>
                    <label>C2C Order Management</label>
                </value>
                <value>
                    <fullName>USL_Print_Subscription</fullName>
                    <label>USL Print Subscription</label>
                </value>
                <value>
                    <fullName>Legal_Tracker</fullName>
                </value>
                <value>
                    <fullName>C2C UKI Collections</fullName>
                </value>
                <value>
                    <fullName>C2C CDN Collections</fullName>
                </value>
                <value>
                    <fullName>C2C TRTA Corps Collections</fullName>
                </value>
                <value>
                    <fullName>C2C Tax Profs – Content Collections</fullName>
                </value>
                <value>
                    <fullName>TRTA_Corporates</fullName>
                    <label>TRTA Corporates</label>
                </value>
                <value>
                    <fullName>C2C Tax Profs - Software Collections</fullName>
                </value>
                <value>
                    <fullName>C2C Tax Profs – DT Tax Collections</fullName>
                </value>
                <value>
                    <fullName>Tax Profs - Software</fullName>
                </value>
                <value>
                    <fullName>Tax Profs - DT Tax</fullName>
                </value>
                <value>
                    <fullName>Tax Profs - Content</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USL_Approver_name__c</fullName>
        <label>Approver name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USL_CSSWriteOffFormTypeID__c</fullName>
        <label>Select Form Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>718</fullName>
                    <label>GW - Good Will</label>
                </value>
                <value>
                    <fullName>719</fullName>
                    <label>SIF - Settlement</label>
                </value>
                <value>
                    <fullName>720</fullName>
                    <label>TPC - Third Party Check List</label>
                </value>
                <value>
                    <fullName>721</fullName>
                    <label>WO - Write Off/ Bad Debt</label>
                </value>
                <value>
                    <fullName>BNK</fullName>
                    <label>Bankruptcy/Assignment/Liquidation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USL_Requester_Title__c</fullName>
        <label>Requester Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
                <value>
                    <fullName>Prof.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USL_Requestor_ID__c</fullName>
        <label>Requestor ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USL_Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Case Form Extension</label>
    <nameField>
        <label>Case Form Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Form Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ESC_Case_Form_Extension_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ESC_Billing_Doc__c</fullName>
        <label>Billing Doc</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Form_Extension__c</fullName>
        <label>Case Form Extension</label>
        <referenceTo>ESC_Case_Form_Extension__c</referenceTo>
        <relationshipLabel>Case Form Extension Line Items</relationshipLabel>
        <relationshipName>Case_Form_Extension_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ESC_Line__c</fullName>
        <label>Line #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Net_Amount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ESC_Root_Cause__c</fullName>
        <label>Root Cause</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Order Processing</fullName>
                </value>
                <value>
                    <fullName>Sales/Acct Management</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Technical/System</fullName>
                </value>
                <value>
                    <fullName>Shipping/Returns</fullName>
                </value>
                <value>
                    <fullName>Data Setup</fullName>
                </value>
                <value>
                    <fullName>Print/CD Sub Recovery</fullName>
                </value>
                <value>
                    <fullName>Accounts Receivable</fullName>
                </value>
                <value>
                    <fullName>Findlaw</fullName>
                </value>
                <value>
                    <fullName>Correct Pricing Discounts</fullName>
                </value>
                <value>
                    <fullName>Financial Findlaw</fullName>
                </value>
                <value>
                    <fullName>Product Performance-Findlaw</fullName>
                </value>
                <value>
                    <fullName>Product Quality-Findlaw</fullName>
                </value>
                <value>
                    <fullName>Services-Findlaw</fullName>
                </value>
                <value>
                    <fullName>Training/Implementation</fullName>
                </value>
                <value>
                    <fullName>TRTA Corporates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USL_Input_Amount__c</fullName>
        <label>Input Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Case Form Extension Line Item</label>
    <nameField>
        <label>Case Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Form Extension Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LTS_Disable_Application_Automation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to disable the triggers, validation, workflows etc.</description>
    <fields>
        <fullName>LTS_Disable_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the validation Rules</description>
        <inlineHelpText>If checked, will disable all validation rules wherever this flag is used.</inlineHelpText>
        <label>Disable Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <label>Disable Application Automation</label>
</CustomObject>

classes/ESC_ApprovalProcessLWCController_Test.cls
@isTest
Private class ESC_ApprovalProcessLWCController_Test {
    
    @isTest
    static void testdata() {
                
        //create a user records  
        Profile prof = [SELECT Id FROM profile WHERE name='System Administrator']; 
        List <user> userlist= new List<user>();
        User us =  new User(FirstName = 'James' , LastName= 'ThomasTest',Alias = 'jttest',Email='james1.thomastest@thomsonreuters.com', emailencodingkey='UTF-8', 
                            UserName='james1.thomastest@thomsonreuters.com',languagelocalekey='en_US', localesidkey='en_US', 
                            profileid = prof.Id,timezonesidkey='America/Los_Angeles',CommunityNickname='James.ThomasTest');
        userlist.add(us);
        
        User us1 =  new User(FirstName = 'test' , LastName= 'thomsan',Alias = 'testom',Email='test.thomson@thomsonreuters.com', emailencodingkey='UTF-8', 
                             UserName='test.thomson@thomsonreuters.com',languagelocalekey='en_US', localesidkey='en_US', 
                             profileid = prof.Id,timezonesidkey='America/Los_Angeles',CommunityNickname='test.thomson');
        userlist.add(us1);
        
        insert userlist;
        
        System.RunAs(us)
        {
            Test.startTest();
            
            LTS_Disable_Application_Automation__c dis = new LTS_Disable_Application_Automation__c();
            dis.LTS_Disable_Validation_Rules__c =true;
            insert dis;
                        
            Account testAccount = ESC_GenericTestutility.TestAccountUtil('TestAccount' ,'TestAccount001','7786864710');  
            insert testAccount;
            
            //insert contact data
            Contact testContact = ESC_GenericTestutility.TestContactUtil(testAccount.id ,'Mile','lastname','test@tr.com');
            insert testContact;
            
            //List <Case> listcase= new List<Case>();
            Case testCase=ESC_GenericTestutility.testCaseUtil(testContact.id,TestAccount.id,'Work in Progress');
            testCase.ESC_Impact__c = '1-Whole Site';
            testCase.subject='tst';
            testCase.ESC_Customer_Symptom__c='Content Addition';
            testCase.ESC_Diagnosis_Summary__c='Content Explanation';
            testCase.ESC_Severity__c='1 - High';
            testCase.ESC_Case_Type__c = 'Incident';
            testCase.ESC_Apply_Milestone_Closure_Flag__c = true;
            testCase.RecordtypeID=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Incident').getRecordTypeId();
            
            insert testCase;
            
            Case testCase1=new Case (ContactId = testContact.id);
            insert testCase1;
            
            
            GenerateForm__C gf= new GenerateForm__C();
            GF.Name='Write Off Form';
            Insert GF;
            
            GenerateForm__c formname1 =new GenerateForm__c();
            formname1.Name='Billing Requests Form1';
            insert formname1;
            
            GenerateForm__c formname2 =new GenerateForm__c();
            formname2.Name='Billing Request Form';
            insert formname2;
            
            //string jsonMapRecs = testCase1.id;
            
            ESC_Case_Form_Extension__c esccfe = new ESC_Case_Form_Extension__c();
            ESCCFE.ESC_Form__c=GF.id;
            ESCCFE.ESC_Case__c=testcase.id;
            ESCCFE.ESC_Form_BU__c='Tax Profs - Software';
            ESCCFE.USL_Requester_Title__c=' Mr.';
            ESCCFE.USL_Requestor_ID__c='Testing';
            ESCCFE.USL_Total_Amount__c=450;
            ESCCFE.USL_CSSWriteOffFormTypeID__c = '718';
            ESCCFE.Route_To_USL_Print_CD_Credits__c=true;
            insert ESCCFE;
            
            ESCCFE.USL_Approval_Status__c='Awaiting Approval';
            ESCCFE.USL_Approver_name__c='Test thomson';
            ESCCFE.ESC_Approver_Id__c=us1.id;
            ESCCFE.USL_Approval_Type__c='Writeoff';
            ESCCFE.USL_CSSWriteOffFormTypeID__c='BNK';
            update ESCCFE;
            
            
            ESC_Case_Form_Extension_Line_Item__c esccfeLine1 =new ESC_Case_Form_Extension_Line_Item__c();
            ESCCFELine1.ESC_Billing_Doc__c='79000000095';
            ESCCFELine1.ESC_Line__c='0010';
            ESCCFELine1.ESC_Net_Amount__c=40;
            ESCCFELine1.USL_Input_Amount__c=0.45;
            ESCCFELine1.ESC_Root_Cause__c='Services-Findlaw';
            ESCCFELine1.ESC_Reason_Code__c='FL-SERV-Relationship/Overall experience';
            ESCCFELine1.USL_ODocType__c='YM';
            ESCCFELine1.USL_OShortDescription__c='Paid and cancelled 6117202889';
            ESCCFELine1.ESC_Case_Form_Extension__c=ESCCFE.id;
            ESCCFELine1.ESC_Type__c='FUll';
            ESCCFELine1.ESC_Request_Description__c='Non-Westlaw';
            //ESCCFELine1.ESC_Item_Amount__c=30000;
            // ESCCFELine1.USL_Input_Amount__c=1126;
            //ESCCFELine1.USL_Invoice_Type__c='Clear';
            insert ESCCFELine1;
            
            Knowledge__kav lstkno= new Knowledge__kav();
            lstkno.title='test 3445434';
            lstkno.summary='summary';
            lstkno.UrlName='test3445434';
            insert lstkno;
   
            Group g = new Group();
            g.Name = 'Test';
            g.type='Queue';
            insert g;
            
            QueueSobject mappingObject = new QueueSobject(QueueId = g.Id, SobjectType = 'ESC_Case_Collaborator__c');
            System.runAs(new User(Id = UserInfo.getUserId()))
            {insert mappingObject;}
            
            GroupMember gm = new GroupMember(
                GroupId = g.id,
                UserOrGroupId = us.id
            );
            System.runAs(new User(Id = UserInfo.getUserId()))
            {insert gm;}
            
            
            ESC_ApprovalProcessLWCController.lstrecid.add(ESCCFE.id);
            ESC_ApprovalProcessLWCController.lstrecid.add(testCase.id);
            ESC_ApprovalProcessLWCController.lstrecid.add(testCase1.id);
            ESC_ApprovalProcessLWCController.lstrecid.add(lstkno.id);
            ESC_ApprovalProcessLWCController.getApprovals();
            ESC_ApprovalProcessLWCController.gettargetobjectlst();
            
            
        }
        
        Test.stopTest();
         integer i = 1;
        integer j = 1;
        System.assertEquals(i,j,'message');
        
    }
    
    
}