objects/ESC_Case_Collaborator__c.object
<CustomObject>
    <description>ESC_ Custom object to enable the Accountable Resolver, Case Collaborator, and Escalation processes in Enterprise Service Cloud program</description>
    <fields>
        <fullName>ESC_CaseNumber__c</fullName>
        <description>ESC_ This field is the Case Number of the case referenced</description>
        <formula>ESC_Case__r.CaseNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Description__c</fullName>
        <description>ESC_ This field Copies the description from the related case</description>
        <label>Case Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Status__c</fullName>
        <formula>TEXT(ESC_Case__r.Status)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESC_ The related case to the referral</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals/Escalations</relationshipLabel>
        <relationshipName>Case_Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESC_End_Date__c</fullName>
        <description>ESC_ End date of the referral for reporting purposes</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ESC_Referral_Status__c</fullName>
        <description>ESC_ The current status of the referral. Rejected and Closed are the equivalent of the ISCLOSED statuses on referrals</description>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ESC_Role__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Customer Hold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Change</fullName>
                </value>
                <value>
                    <fullName>Pending Customer</fullName>
                </value>
                <value>
                    <fullName>Pending Other</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Role__c</fullName>
        <description>ESC_ Maintains the role of the referral function - Accountable Resolver, Collaborator, manager Escalation</description>
        <label>Referral Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accountable Resolver</fullName>
                    <default>true</default>
                    <label>Accountable Resolver</label>
                </value>
                <value>
                    <fullName>Collaborator</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Severity__c</fullName>
        <description>ESC_ The Severity field from the related case</description>
        <formula>TEXT( ESC_Case__r.ESC_Severity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Severity</label>
        <type>Text</type>
    </fields>
    <label>Referral/Escalation</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals/Escalations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESC_ServiceNow_Routing__c.object
<CustomObject>
    <description>This Object will hold the mapping of Area of the Business, Source, Assignment Group, Request type and the SLA field.</description>
    <fields>
        <fullName>ESC_ASSIGNMENT_GROUP__c</fullName>
        <label>ASSIGNMENT GROUP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_SOURCE__c</fullName>
        <label>SOURCE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_SegmentRegion__c</fullName>
        <label>SegmentRegion</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Sub_BU__c</fullName>
        <label>SUB-BU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ServiceNow Routing</label>
    <nameField>
        <displayFormat>SN-{00000000}</displayFormat>
        <label>ServiceNow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceNow Routing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESC_ServiceNow_Scheduler_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to store the Interval,batchsize and current job id of the service now staging scheduler</description>
    <fields>
        <fullName>ESC_No_Of_Retries__c</fullName>
        <label>NoOfRetries</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ServiceNow Scheduler Settings</label>
</CustomObject>

objects/ESC_ServiceNow_Staging__c.object
<CustomObject>
    <description>ESC_Staging_Object to hold the records to be sent to Service Now</description>
    <fields>
        <fullName>ESC_AssignmentGroup__c</fullName>
        <label>AssignmentGroup</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_BusinessArea__c</fullName>
        <label>BusinessArea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_CaseNumber__c</fullName>
        <label>CaseNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Id__c</fullName>
        <label>Case Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Case_Status__c</fullName>
        <label>Case Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Description__c</fullName>
        <description>This will hold the Description from referral</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_Employee_Number__c</fullName>
        <label>Employee Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_External_Task_Reference_Number__c</fullName>
        <label>External Task Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Feed_Comment__c</fullName>
        <label>Feed Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ESC_ID__c</fullName>
        <description>This will hold the Referral Id</description>
        <label>Referral ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_No_Of_Retries__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Retries</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ESC_RequestType__c</fullName>
        <label>RequestType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_SLA__c</fullName>
        <label>SLA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_SNOW_ID__c</fullName>
        <description>This will hold the Service Now Ticket Id</description>
        <externalId>true</externalId>
        <label>External Ticket Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_SourceLink__c</fullName>
        <label>SourceLink</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Staging_Status__c</fullName>
        <label>Staging Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Transmit_Status__c</fullName>
        <label>Transmit Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ServiceNow Staging</label>
    <nameField>
        <displayFormat>SNStag - {00000000}</displayFormat>
        <label>ServiceNow Staging</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceNow Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESC_SN_AssignmentGroup__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ESC_Assignment_Group__c</fullName>
        <label>Assignment Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Sub_BU__c</fullName>
        <label>SUB-BU</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ESC_SN_AssignmentGroup</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Rep_Employee_Number__c</fullName>
        <description>Unique Id for each User linked to TMS</description>
        <externalId>true</externalId>
        <label>Rep Employee Number</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ESC_CaseRefCreation.cls
public without sharing class ESC_CaseRefCreation{
    
    /*
This method will be invoked by SNOW Flow for Case Ref Creation
ESC_REF__c
*/
    
    @InvocableMethod(label='Create Ref on Case' description='Create Ref')
    public static void caseRefCreation(List<id> cs){
        
        
        if(cs == null)
            return;
        List<ESC_Case_Collaborator__c> reflst= new List<ESC_Case_Collaborator__c>();     
        Map<id,String> mapCase= new Map<id,String>();
       Map<id,List<ESC_Case_Collaborator__c>> mapCSIdList= new  Map<id,List<ESC_Case_Collaborator__c>>();
       ESC_SN_AssignmentGroup__c sngroup= ESC_SN_AssignmentGroup__c.getInstance(UserInfo.getUserId());
       
       for(Case objcs: [Select id,Subject,Description,BU_Segment__c from Case where id IN:cs]){
                mapCase.put(objcs.id,objcs.Description );       
               }
         
        if((Schema.sObjectType.ESC_Case_Collaborator__c.isAccessible() || Schema.sObjectType.ESC_Case_Collaborator__c.isQueryable())){
        reflst = [Select id,Owner.Name,ESC_Case__c,ESC_Role__c,ESC_End_Date__c,ESC_Case__r.ESC_REF__c,ESC_Case__r.description,ESC_Case__r.CaseNumber  from ESC_Case_Collaborator__c where ESC_Case__c IN :cs and Owner.Name=:sngroup.ESC_Assignment_Group__c];
        }
        for(ESC_Case_Collaborator__c ref:reflst){
            List<ESC_Case_Collaborator__c> listCsCollaborator= new List<ESC_Case_Collaborator__c>();
            if(ref.ESC_Role__c == 'Accountable Resolver' && ref.Owner.Name== sngroup.ESC_Assignment_Group__c ){
                mapCase.put(ref.esc_case__c,ref.ESC_Case__r.description);
               if(mapCSIdList.containsKey(ref.ESC_Case__c)){
                    listCsCollaborator = mapCSIdList.get(ref.ESC_Case__c);
                }
                listCsCollaborator.add(ref);
                mapCSIdList.put(ref.ESC_Case__c,listCsCollaborator);
                
                }
            
        }  
          
        
        
        ESC_Case_Collaborator__c referralRecord;
        Id refRecordTypeId=Schema.SObjectType.ESC_Case_Collaborator__c.getRecordTypeInfosByName().get('Service Cloud Referral').getRecordTypeId();
        system.debug('sngroup.ESC_Assignment_Group__c****'+sngroup.ESC_Assignment_Group__c);
        Id queueid= [select Id from Group where Name =:sngroup.ESC_Assignment_Group__c  and Type = 'Queue'].Id;
        List<ESC_Case_Collaborator__c> listRef= new List<ESC_Case_Collaborator__c>();
        List<ESC_Case_Collaborator__c> listexisting= new List<ESC_Case_Collaborator__c>();
        
        
        
       for(Id csId: mapCase.keySet()){
            
            referralRecord= new ESC_Case_Collaborator__c();
            if(mapCSIdList.size()==0 || mapCSIdList.get(csId)==null){
                referralRecord.RecordTypeId = refRecordTypeId;
                referralRecord.ESC_Case__c=csId;
                referralRecord.ESC_Role__c='Accountable Resolver';
                referralRecord.ESC_Referral_Status__c='New';
                referralRecord.ESC_Case_Description__c=mapCase.get(csId);
                referralRecord.OwnerID=queueid;
                listRef.add(referralRecord);
            }
            else{
                for(ESC_Case_Collaborator__c ecc:  mapCSIdList.get(csId)){
                if(ecc.ESC_End_Date__c!= null){
                   ecc.ESC_End_Date__c = null;
                   ecc.ESC_Referral_Status__c = 'Accepted';
                }
                listexisting.add(ecc);
                }
            }
        }
        if(listRef.size()>0 && (Schema.sObjectType.ESC_Case_Collaborator__c.isAccessible() || Schema.sObjectType.ESC_Case_Collaborator__c.isCreateable())){
            insert listRef;
        }
        
        
        if(!listexisting.IsEmpty() && (Schema.sObjectType.ESC_Case_Collaborator__c.isAccessible() || Schema.sObjectType.ESC_Case_Collaborator__c.isUpdateable())){
            ESC_ReferalTriggerHelperClass.EndDatingOldReferral(listexisting);
            Update listexisting;
            listRef.addall(listexisting);
        }
       
        list<ESC_Case_Collaborator__c> insertrefList = new list<ESC_Case_Collaborator__c>();
        Set<id> refIdSet = new Set<Id>();
        
        
        List<ESC_ServiceNow_Staging__c> snStagingListtoInsrt= new  List<ESC_ServiceNow_Staging__c>();
       for(ESC_Case_Collaborator__c ecc:listRef){
          refIdSet.add(ecc.id);
       }
       
       List<ESC_ServiceNow_Staging__c> servicenowStaginglist =[Select id,ESC_Description__c,ESC_ID__c,ESC_Transmit_Status__c,ESC_Staging_Status__c from ESC_ServiceNow_Staging__c where ESC_ID__c IN:refIdSet];
       
      
         
         insertrefList=[Select Id,ESC_Case__c,ESC_CaseNumber__c,ESC_Case__r.Description,ESC_Case__r.ESC_SLA__c,ESC_Case__r.ESC_SLA_Justification__c,ESC_Case__r.BU_Segment__c,ESC_Case__r.LCRM_Sub_BU__c,ESC_Case__r.ESC_Severity__c,ESC_Case__r.ESC_External_Task_Reference_Number__c,ESC_Case__r.ESC_External_Ticket_Number__c from ESC_Case_Collaborator__c where Id in :refIdSet];
        
        if(servicenowStaginglist.size()== 0 && insertrefList.size()>0){
           snStagingListtoInsrt = StagingUpdater(insertrefList,'Create','');
        }
        else if(servicenowStaginglist.size()>0 && insertrefList.size()>0){
         snStagingListtoInsrt = StagingUpdater(insertrefList,'Update','');
        }
        if(snStagingListtoInsrt.size()>0 &&(Schema.sObjectType.ESC_ServiceNow_Staging__c.isAccessible() || Schema.sObjectType.ESC_ServiceNow_Staging__c.isCreateable())){
            system.debug('snStagingListtoInsrt***'+ snStagingListtoInsrt);
            insert snStagingListtoInsrt;
        }
    }
    
    
            
    public static List<ESC_ServiceNow_Staging__c> StagingUpdater(List<ESC_Case_Collaborator__c> RefList, String Action, String Type) {
        String IntegrationSetting = 'SNOW';
        List<ESC_ServiceNow_Staging__c> SNowUpdateList = new List<ESC_ServiceNow_Staging__c>();
        Map<Id,String> ProfileNameMap = new Map<Id,String>();
        Map<string,ESC_ServiceNow_Routing__c> SNRoutingMap = new Map<string,ESC_ServiceNow_Routing__c>();
        Map<Id,Id> Case_RefMap = new Map<Id,Id>();
        ESC_ServiceNow_Scheduler_Settings__c SNSettings = ESC_ServiceNow_Scheduler_Settings__c.getInstance('ServiceNowSettings');
        Integer NoOfRetries = Integer.valueOf(SNSettings.ESC_No_Of_Retries__c);
        
          for(ESC_ServiceNow_Routing__c SNR:[Select ESC_SOURCE__c,ESC_Sub_BU__c,ESC_ASSIGNMENT_GROUP__c,ESC_SegmentRegion__c from ESC_ServiceNow_Routing__c]){
            SNRoutingMap.put(SNR.ESC_SegmentRegion__c,SNR);
        }  
        
        List<User> u = [Select id,name,Rep_Employee_Number__c,FederationIdentifier from User Where id =: UserInfo.getUserId()];
        for(ESC_Case_Collaborator__c Ref:RefList){
            system.debug(ref);
            ESC_ServiceNow_Staging__c Staging = new ESC_ServiceNow_Staging__c();
            Staging.ESC_ID__c = Ref.id;
            Staging.ESC_Staging_Status__c ='Pending';
            String RegionSegment;
           if(LotusUser.getLotusUser() == true){
                RegionSegment =Ref.ESC_Case__r.BU_Segment__c + Ref.ESC_Case__r.LCRM_Sub_BU__c;
           }
           else{
                RegionSegment =Ref.ESC_Case__r.LCRM_Sub_BU__c;
           }
            system.debug('RegionSegment****'+RegionSegment);
            system.debug('SNRoutingMap****'+SNRoutingMap);
            if(SNRoutingMap.get(RegionSegment) !=null){
            Staging.ESC_BusinessArea__c = SNRoutingMap.get(RegionSegment).ESC_Sub_BU__c;
            Staging.ESC_Source__c = SNRoutingMap.get(RegionSegment).ESC_SOURCE__c;
            Staging.ESC_AssignmentGroup__c = SNRoutingMap.get(RegionSegment).ESC_ASSIGNMENT_GROUP__c;
           }
            Staging.ESC_Description__c =Ref.ESC_Case__r.Description;
            if(Action=='Create'){
            Staging.ESC_RequestType__c = Label.ESC_SN_ReqTypeCreate;/*****check******/
            }
            staging.ESC_Case_Status__c = 'Open';
            if(Action=='Update'){
            Staging.ESC_RequestType__c = 'Update';
            staging.ESC_External_Task_Reference_Number__c = Ref.ESC_Case__r.ESC_External_Task_Reference_Number__c;
            staging.ESC_SNOW_ID__c = Ref.ESC_Case__r.ESC_External_Ticket_Number__c;
            if(Type=='CloseComplete'){
            staging.ESC_Case_Status__c = 'CloseComplete';  
            }
            if(Type=='FeedComment'){
            staging.ESC_Feed_Comment__c = ''; 
            }
            }
            if(Ref.ESC_Case__r.ESC_Severity__c != null && Ref.ESC_Case__r.ESC_Severity__c != 'Null'){
            Staging.ESC_SLA__c= Ref.ESC_Case__r.ESC_Severity__c;
            }
            Else{
            Staging.ESC_SLA__c= 'N/A';
            }
            Staging.ESC_CaseNumber__c = Ref.ESC_CaseNumber__c;
            staging.ESC_Case_Id__c = Ref.ESC_Case__c; //(18 digits case id)
            staging.ESC_Employee_Number__c = u[0].FederationIdentifier;
            //staging.ESC_External_Task_Reference_Number__c = '';  
            Staging.ESC_SourceLink__c = URL.getSalesforceBaseUrl().toExternalForm()+'/'+Ref.ESC_Case__c; //for attachment           
            
            SNowUpdateList.add(staging);
            }
     
        return SNowUpdateList;   
    }   
}