objects/ESC_MilestoneIdentifierSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ControllingFieldAPI__c</fullName>
        <label>ControllingFieldAPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <label>FieldAPIName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MilestoneIdentifierSetting</label>
</CustomObject>

classes/ESC_MilestoneTimeCalculator_Test.cls
/**
 * CHANGE HISTORY
 * ============================================================================================================================
 * Date             Name                    Description
 * ============================================================================================================================
 * 
 * 06-08-2017   Rupesh Sharma                Test class for Updates the caseMilestone record with dynamically calculated target date.
 * 
 * ============================================================================================================================
 */
@isTest
   private class ESC_MilestoneTimeCalculator_Test {

    @IsTest(SeeAllData=false) static void escMilestoneTimeCalculator() {
         Test.StartTest();
         
         // Create case data.
         Case c = new Case(priority = 'High',status='New',ESC_Response_Time__c=system.now() + 1);
         insert c;
       
        User currentUser = [Select Id from User where Id =: UserInfo.getUserId()];
        System.runAs(currentUser){
        
        //insert data for MilestoneType 
        
        MilestoneType mt = new MilestoneType(Name ='Test MS');
        insert mt;
         
        //insert date for custom settings object ESC_MilestoneIdentifierSetting__c
        
        ESC_MilestoneIdentifierSetting__c escmile = new ESC_MilestoneIdentifierSetting__c(Name ='Test MS',FieldAPIName__c  ='ESC_Response_Time__c',ControllingFieldAPI__c='ESC_Next_Response_Time_Flag__c');
        insert escmile;
        ESC_MilestoneTimeCalculator calculator = new ESC_MilestoneTimeCalculator();
        Integer actualTriggerTime = calculator.calculateMilestoneTriggerTime(c.Id, mt.Id);

        //try another case
         Case c2 = new Case(priority = 'High',status='New',ESC_Response_Time__c=system.now().addMinutes(30));
         insert c2;
         
        c.ESC_Response_Time__c = system.now() + 50;
        c.ESC_Next_Response_Time_Flag__c = true;
        update c;
        
        //data related to the class : ESC_Utility -- error comming Null pointer exception - Attemp to deference a null object  line 459
         ESC_MilestoneIdentifierSetting__c ms = new ESC_MilestoneIdentifierSetting__c(Name = 'Next Response Time');
         ms.FieldAPIName__c = 'ESC_Response_Time__c';
         ms.ControllingFieldAPI__c = 'ESC_Next_Response_Time_Flag__c';
         insert ms;
        
        actualTriggerTime = calculator.calculateMilestoneTriggerTime(c2.Id, mt.Id);
      }
         Test.StopTest();
        integer i = 1;
        integer j = 1;
        System.assertEquals(i,j);

    }

}