objects/ESC_Case_Collaborator__c.object
<CustomObject>
    <description>ESC_ Custom object to enable the Accountable Resolver, Case Collaborator, and Escalation processes in Enterprise Service Cloud program</description>
    <fields>
        <fullName>ESC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESC_ The related case to the referral</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals/Escalations</relationshipLabel>
        <relationshipName>Case_Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESC_Referral_Status__c</fullName>
        <description>ESC_ The current status of the referral. Rejected and Closed are the equivalent of the ISCLOSED statuses on referrals</description>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ESC_Role__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Customer Hold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Change</fullName>
                </value>
                <value>
                    <fullName>Pending Customer</fullName>
                </value>
                <value>
                    <fullName>Pending Other</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Referral/Escalation</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals/Escalations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ESC_VSTS_Staging__c.object
<CustomObject>
    <description>ESC_VSTS_Staging to hold the records to be sent to TFS</description>
    <fields>
        <fullName>ESC_Case_Id__c</fullName>
        <label>Case Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_Referral_Id__c</fullName>
        <description>This will hold the Referral Id</description>
        <label>Referral_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_VSTS_Id__c</fullName>
        <label>VSTS Ticket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>VSTS Staging</label>
    <nameField>
        <displayFormat>VSTS-{00000000}</displayFormat>
        <label>VSTS Stagging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VSTS Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ESC_VSTSCreateacknowledgementClass.cls
public class ESC_VSTSCreateacknowledgementClass{
    
    /*
    This method will be invoked by VSTS staging object when the VSTS Id Staging table is updated by ESI/VSTS
    */
    
    @InvocableMethod(label='VSTS Create acknowledgement' description='Chatter creation on case from VSTS Ticket Create')
    public static void VSTSCreateacknowledgementMethod(List<ESC_VSTS_Staging__c> VSTSStaging){
       if(VSTSStaging == null || VSTSStaging.isEmpty())
            return;
        map<string,ESC_VSTS_Staging__c> MapStag=new Map<string,ESC_VSTS_Staging__c>();
        List<Id> lstReferral = new List<Id>();
        List<ESC_Case_Collaborator__c> Referlist = new List<ESC_Case_Collaborator__c>();
        List<FeedItem> listpost= new List<FeedItem>();
        List<String> caseListId= new List<String>();
        List<Case> caseList= new List<Case>();
    
        for(ESC_VSTS_Staging__c si:VSTSStaging){
            if(si.ESC_VSTS_Id__c  != ''&& si.ESC_VSTS_Id__c !=null && si.ESC_Referral_Id__c != null){
               lstReferral.add(si.ESC_Referral_Id__c);
               MapStag.put(si.ESC_Referral_Id__c,si);
               caseListId.add(si.ESC_Case_Id__c);
            }
        }
        if(caseListId.size()>0){
            caseList = [select id,CaseNumber,Status,ESC_VSTS_Id__c from Case where Id IN :caseListId];
        }
        system.debug('MapStag****'+ MapStag + 'lstReferral***' +lstReferral );
        //system.debug('caseList--> '+caseList);
        
        if(lstReferral.size()>0){
            Referlist = [select id,name,ESC_Case__c,ESC_Referral_Status__c,OwnerId,owner.name from ESC_Case_Collaborator__c where Id IN :lstReferral];
            
        }
        
        
        List<Case> caseList1= new List<Case>();
        for (Case ca:caseList) {
            for(ESC_VSTS_Staging__c evs : VSTSStaging)
            {
                ca.ESC_VSTS_Id__c = evs.ESC_VSTS_Id__c;
            }
                caseList1.add(ca);
        }
        
        
        if(caseList1.size()>0){
            Update caseList1;
        }
        
        for(ESC_Case_Collaborator__c c:Referlist){
            String chatterPost;
            if(MapStag.get(c.Id)!=null){
             chatterPost= 'The Referral: '+c.Name+' '+Label.ESC_VSTS_ChatterLabel;
           
            //Adding a Text post
             FeedItem post = new FeedItem();
             post.ParentId = c.ESC_Case__c; 
             post.Body = chatterPost;
             listpost.add(post);
             system.debug('listpost****'+ listpost);
            }   
        }
       
       if(listpost.size()>0){
            Insert listpost;
        }
        
        
    }
    
}