objects/ESC_IntrusiveNotificationsSchema__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Components to be shown in notifications for any object</description>
    <fields>
        <fullName>ESC_BodyMsgFields__c</fullName>
        <description>API Name of fields in csv</description>
        <inlineHelpText>API Name of fields in csv</inlineHelpText>
        <label>Fields To Be Displayed In MSG (IN CSV)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESC_ObjectAPIName__c</fullName>
        <description>The API Name of object</description>
        <label>ObjectAPIName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IntrusiveNotificationsSchema</label>
</CustomObject>

classes/ESC_IntrusiveNotificationController_Test.cls
@isTest
private class ESC_IntrusiveNotificationController_Test {

    @IsTest(SeeAllData=false) static void escIntrusiveNotificationTest() {
        Test.StartTest();
        
    
       ESC_IntrusiveNotificationsSchema__c inf = new ESC_IntrusiveNotificationsSchema__c();
       inf.ESC_BodyMsgFields__c = 'ContactID,AccountID,CaseNumber';
       inf.ESC_ObjectAPIName__c ='Case';
       inf.Name = 'Name';
       insert inf;
       
       
        ESC_IntrusiveNotificationController nc = new ESC_IntrusiveNotificationController();
        nc.getPushTopicNames();
        nc.getObjectIdentifierMap();
        nc.getIntrusiveSchemaMSG();
      
        Test.StopTest();
        
        integer i = 1;
        integer j = 1;
        System.assertEquals(i,j);
    }

}