objects/ESC_Case_Form_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Detail_Other_Westlaw_Access_Control__c</fullName>
        <label>Detail:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Detail_Other_Westlaw_Preferences__c</fullName>
        <label>Detail:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Out_of_Plan_Icon__c</fullName>
        <label>Display Out of Plan Icon?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESC_Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Form Extension</relationshipLabel>
        <relationshipName>Case_Form_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ESC_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ESC Form</label>
        <referenceTo>GenerateForm__c</referenceTo>
        <relationshipLabel>Case Form Extensions</relationshipLabel>
        <relationshipName>ESC_GenerateForm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Folder_Billing_Option__c</fullName>
        <label>Folder Billing Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I PAY YOU PAY</fullName>
                </value>
                <value>
                    <fullName>ONE PAY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LSI_Web_Import__c</fullName>
        <label>LSI Web Import?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Concurrent_Access__c</fullName>
        <label>Max Concurrent Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>250</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Print_Billing_Option__c</fullName>
        <label>Print Billing Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Lines</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProDoc_Web_Import__c</fullName>
        <label>ProDoc Web Import?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Share_Folders__c</fullName>
        <label>Share Folders?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skip_Out_of_Plan__c</fullName>
        <label>Skip Out of Plan?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USL_All_Users_CA__c</fullName>
        <label>All Users</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USL_Concurrent_Access__c</fullName>
        <label>Concurrent Access?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Usage_Billing_Option__c</fullName>
        <label>Usage Billing Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ask at Sign-on</fullName>
                </value>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Westlaw_LT__c</fullName>
        <label>Link Translation?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Form Extension</label>
    <nameField>
        <label>Case Form Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Form Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ESC_Case_Form_Extension_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ESC_Case_Form_Extension__c</fullName>
        <label>Case Form Extension</label>
        <referenceTo>ESC_Case_Form_Extension__c</referenceTo>
        <relationshipLabel>Case Form Extension Line Items</relationshipLabel>
        <relationshipName>Case_Form_Extension_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Form Extension Line Item</label>
    <nameField>
        <label>Case Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Form Extension Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GenerateForm__c.object
<CustomObject>
    <label>CSS Form</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/USL_AccLevelPwdControllerTest.cls
@isTest
public class USL_AccLevelPwdControllerTest {
    
    static testMethod void testAccLevelPwdController(){
        case c = new Case();
        insert c;
       	GenerateForm__c cf = new GenerateForm__c();
        insert cf;
        case c1 = new Case();
        insert c1;
       	GenerateForm__c cf1 = new GenerateForm__c();
        insert cf1;
        
       //List<ESC_Case_Form_Extension__c> cflist= new List<ESC_Case_Form_Extension__c>();
        
        ESC_Case_Form_Extension__c cfe = new ESC_Case_Form_Extension__c();
        cfe.ESC_Case__c = c.id;
        cfe.ESC_Form__c = cf.id;
        cfe.USL_Concurrent_Access__c = 'Yes';
        cfe.Share_Folders__c = 'Yes';
        cfe.Westlaw_LT__c = 'Yes';
        cfe.LSI_Web_Import__c = 'Yes';
        cfe.Display_Out_of_Plan_Icon__c = 'Yes';
        cfe.Skip_Out_of_Plan__c = 'Yes';
        cfe.Folder_Billing_Option__c = 'I PAY YOU PAY';
        cfe.Detail_Other_Westlaw_Access_Control__c = 'true';
        cfe.ProDoc_Web_Import__c = 'Yes';
        cfe.Max_Concurrent_Access__c = '2';
        cfe.Print_Billing_Option__c = 'Document';
        cfe.Usage_Billing_Option__c = 'Ask at Sign-on';
        cfe.Detail_Other_Westlaw_Preferences__c = 'true';
        Insert cfe;
        
              
        ESC_Case_Form_Extension_Line_Item__c cfeli = new ESC_Case_Form_Extension_Line_Item__c();
        cfeli.ESC_Case_Form_Extension__c=cfe.id;
        insert cfeli;
        List<ESC_Case_Form_Extension_Line_Item__c> cflilist= new List<ESC_Case_Form_Extension_Line_Item__c>();
        cflilist.add(cfeli);
        Test.startTest();
        PageReference pageRef = Page.USL_AccLevelPwdForm;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('caseid', c.id);
        ApexPages.currentPage().getParameters().put('formId', cf.id);
        ApexPages.currentPage().getParameters().put('sn', 'USL_Concurrent_Access__c');
        ApexPages.currentPage().getParameters().put('sename', 'USL_Concurrent_Access__c');
        ApexPages.currentPage().getParameters().put('secn', 'USL_Concurrent_Access__c');
        ApexPages.currentPage().getParameters().put('rn', '0');
        USL_AccLevelPwdController uspc= new USL_AccLevelPwdController();
        uspc.userFldmap.put('USL_Concurrent_Access__c','USL_All_Users_CA__c');
        uspc.SecheaderMap.put('USL_Concurrent_Access__c','USL_All_Users_CA__c');
        uspc.option1=true;
        uspc.Showsec();
        uspc.validate();
        uspc.iserror=false;
        uspc.Submit();
        uspc.usertoggle();
        uspc.hidesec('USL_Concurrent_Access__c',true);
        uspc.Tablemap.put('USL_Concurrent_Access__c',cflilist);
        uspc.addRow();
        uspc.deleteRow();
        Test.stopTest();
      
      
    }
    static testMethod void testmethod2(){
        case c = new Case();
        insert c;
       	GenerateForm__c cf = new GenerateForm__c();
        insert cf;
        case c1 = new Case();
        insert c1;
       	GenerateForm__c cf1 = new GenerateForm__c();
        insert cf1;
        
       //List<ESC_Case_Form_Extension__c> cflist= new List<ESC_Case_Form_Extension__c>();
        
        ESC_Case_Form_Extension__c cfe = new ESC_Case_Form_Extension__c();
        cfe.ESC_Case__c = c.id;
        cfe.ESC_Form__c = cf.id;
        cfe.USL_Concurrent_Access__c = 'Yes';
        cfe.Share_Folders__c = 'Yes';
        cfe.Westlaw_LT__c = 'Yes';
        cfe.LSI_Web_Import__c = 'Yes';
        cfe.Display_Out_of_Plan_Icon__c = 'Yes';
        cfe.Skip_Out_of_Plan__c = 'Yes';
        cfe.Folder_Billing_Option__c = 'I PAY YOU PAY';
        cfe.Detail_Other_Westlaw_Access_Control__c = 'true';
        cfe.ProDoc_Web_Import__c = 'Yes';
        cfe.Max_Concurrent_Access__c = '2';
        cfe.Print_Billing_Option__c = 'Document';
        cfe.Usage_Billing_Option__c = 'Ask at Sign-on';
        cfe.Detail_Other_Westlaw_Preferences__c = 'true';
        cfe.USL_All_Users_CA__c='No';
        Insert cfe;
        
              
        ESC_Case_Form_Extension_Line_Item__c cfeli = new ESC_Case_Form_Extension_Line_Item__c();
        cfeli.ESC_Case_Form_Extension__c=cfe.id;
        insert cfeli;
        
        Test.startTest();
        PageReference pageRef = Page.USL_AccLevelPwdForm;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('caseid', c.id);
        ApexPages.currentPage().getParameters().put('formId', cf.id);
        ApexPages.currentPage().getParameters().put('sn', 'USL_Concurrent_Access__c');
        ApexPages.currentPage().getParameters().put('sename', 'USL_Concurrent_Access__c');
        ApexPages.currentPage().getParameters().put('rn', '0');
        USL_AccLevelPwdController uspc= new USL_AccLevelPwdController();
        uspc.option2=true;
        uspc.Showsec();
        uspc.option3=true;
        uspc.Showsec();
        uspc.option3=true;
        uspc.Showsec();
        uspc.option4=true;
        uspc.Showsec();
        uspc.option5=true;
        uspc.Showsec();
        uspc.option6=true;
        uspc.Showsec();
        uspc.option7=true;
        uspc.Showsec();
        
        uspc.userFldmap.put('USL_Concurrent_Access__c','USL_All_Users_CA__c');
        uspc.SecheaderMap.put('USL_Concurrent_Access__c','USL_All_Users_CA__c');
        uspc.Tablemap.put('USL_Concurrent_Access__c',new List<ESC_Case_Form_Extension_Line_Item__c>{cfeli});
        uspc.validate();
        uspc.Submit();
        uspc.usertoggle();
        uspc.hidesec('USL_Concurrent_Access__c',true);
        Test.stopTest();
      
      
    }
}