objects/ESC_Case_Special_Instruction__c.object
<CustomObject>
    <fields>
        <fullName>ESC_Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Special Instructions</relationshipLabel>
        <relationshipName>Case_Special_Instructions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ESC_Special_Instruction__c</fullName>
        <label>Special Instruction</label>
        <referenceTo>ESC_Special_Instruction__c</referenceTo>
        <relationshipLabel>Case Special Instructions</relationshipLabel>
        <relationshipName>Case_Special_Instructions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Special Instruction</label>
    <nameField>
        <displayFormat>CaSI-{00000000}</displayFormat>
        <label>Case Special Instruction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Special Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ESC_Special_Instruction__c.object
<CustomObject>
    <fields>
        <fullName>ESC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Special Instructions</relationshipLabel>
        <relationshipName>Special_Instructions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ESC_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Special Instruction</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ESC_ContactSICaseUtility.cls
public without sharing class ESC_ContactSICaseUtility{
    
    @InvocableMethod(label='Copy Contact SI for Case' description='Copies the contact specific instructions to case')
    public static void inheritIntCaseSpecialInstructions(List<ESC_Special_Instruction__c> specialInstruction){
        List<ESC_Case_Special_Instruction__c> lstcssis = new List<ESC_Case_Special_Instruction__c>();
        Set<Id> setConId = new Set<Id>();
        Map<Id, List<Id>> mapconcase = new Map<Id, List<Id>>();
        for(ESC_Special_Instruction__c si:specialInstruction){
            if(si.ESC_contact__c!=null){
                setConId.add(si.ESC_contact__c);
            }
        }
        List<Case> caselst = new List<Case>();
        if(Schema.sObjectType.Case.isAccessible() || Schema.sObjectType.Case.isQueryable()){
        caselst  = [select Id,contactId from Case where IsClosed != true and ContactId IN :setConId];
        }
        for(Case c: caselst){
            if(!mapconcase.containskey(c.contactId)){
                mapconcase.put(c.contactId, new List<Id>{c.Id});
            }else{
                mapconcase.get(c.contactId).add(c.Id);
            }
        }
        //check for the record type of special instruction
        //put in validations, null checks etc.
        system.debug(specialInstruction);
        for(ESC_Special_Instruction__c si:specialInstruction){
            if(si.ESC_status__c == 'Active' && si.ESC_Contact__c!=null){
                if(mapconcase.containskey(si.ESC_Contact__c)){
                    for(Id csid:mapconcase.get(si.ESC_Contact__c)){
                        ESC_Case_Special_Instruction__c csi = new ESC_Case_Special_Instruction__c();
                        csi.ESC_Case__c = csid;
                        csi.ESC_special_instruction__c = si.id;
                        lstcssis.add(csi);
                    }
                }
            }
        }           
        
        system.debug(lstcssis);
        if(lstcssis.size()>0 && (Schema.sObjectType.ESC_Case_Special_Instruction__c.isAccessible() || Schema.sObjectType.ESC_Case_Special_Instruction__c.isCreateable())){  
            insert lstcssis;        
        }
    }
}