objects/FieldId__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>DQA_Request_Case__c</fullName>
        <label>DQA Request Case</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Field Ids</label>
</CustomObject>

objects/LCRM_Training_Event_Case_Product__c.object
<CustomObject>
    <description>This is a junction object between Case and Product. This is to link one training event case record to one or multiple products.</description>
    <fields>
        <fullName>LCRM_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.LCRM_Sub_Bu__c</field>
                <operation>equals</operation>
                <value>UKI</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Training Event Case Products</relationshipLabel>
        <relationshipName>Training_Event_Case_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Training_Event_Case__c</fullName>
        <label>Training Event Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Training Event Case Products</relationshipLabel>
        <relationshipName>Training_Event_Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Event Case Product</label>
    <nameField>
        <displayFormat>TCP – {00000}</displayFormat>
        <label>Training Event Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Event Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LCRM_Sub_Bu__c</fullName>
        <label>BU Region</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Event__c.object
<CustomObject>
    <description>This is the object for Training Event.</description>
    <fields>
        <fullName>LCRM_Sub_Bu__c</fullName>
        <description>Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-2199</description>
        <label>BU Region</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Training Event</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Training Event Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Events</pluralLabel>
    <recordTypes>
        <fullName>GLI</fullName>
        <active>true</active>
        <label>GLI</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sub_Bu__c</fullName>
        <description>The field has been created to define the sub bu of the user which will be used to populate the Sub bu field on objects Account,Lead,Opportunities,Activity etc. 
Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-2201, DPS-415</description>
        <label>BU Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>USL</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>AEM</fullName>
                </value>
                <value>
                    <fullName>LatAm</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LCRMCasetoTrainingEventController_Test.cls
@isTest
public class LCRMCasetoTrainingEventController_Test{

@testSetup static void testDataSetUp() { 
        recordtype caseRT = [select id from recordtype where name ='GLI Training Event Request' and sobjecttype='Case' limit 1]; 
        Profile ukiProfile = [SELECT Id FROM profile WHERE name='UKI Users'];
        PermissionSet trainingPermissionSet = [SELECT Id FROM PermissionSet WHERE name='LCRM_GLI_Training_Users'];  
                
        User gliUser = UnitTest.getUserInstance();
        gliUser.Username = 'TestUser1@TR.com';
        gliUser.profileid = ukiProfile.Id;
        gliUser.Sub_Bu__c = 'UKI';
        insert gliUser;
		
        System.runAs(new User(Id=UserInfo.getUserId())){
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = trainingPermissionSet.Id, AssigneeId = gliUser.Id);
            insert psa; 
        }
        
        FieldId__c fi = new FieldId__c(DQA_Request_Case__c='012S00000000o9r');
        insert fi;
        Case gliCase = UnitTest.getCaseInstance();
        gliCase.Is_GLI__c = true;
        gliCase.RecordTypeId = caseRT.Id;
        gliCase.OwnerId = gliUser.Id;
        insert gliCase;
        
        Product2 gliProduct = new Product2();
        gliProduct.Name = 'Test Product';
        gliProduct.IsActive = true;
        gliProduct.LCRM_Sub_Bu__c = 'UKI';
        insert gliProduct;
        
        LCRM_Training_Event_Case_Product__c tecp = new LCRM_Training_Event_Case_Product__c (LCRM_Training_Event_Case__c=gliCase.Id,LCRM_Product__c=gliProduct.Id);
        insert tecp;
      }
    
    //user is not an admin user
    @isTest public static void testConvertCaseByNonAdminUser(){
        Case gliCase = [SELECT Id FROM Case LIMIT 1];
        User gliUser = [SELECT id FROM User WHERE Username = 'TestUser1@TR.com'];
        
        PageReference oPage = Page.LCRMCasetoTrainingEvent;
        Test.setCurrentPage(oPage);
        
        LCRMCasetoTrainingEventController controller = new LCRMCasetoTrainingEventController(new ApexPages.StandardController(gliCase));
        Test.startTest();
            system.runAs(gliUser){
                controller.onPageLoad();
            }
        Test.stopTest();
    }
    
    //user is an admin user
    @isTest public static void testConvertCaseByAdminUser(){
        Case gliCase = [SELECT Id,OwnerId FROM Case LIMIT 1];
        User gliUser = [SELECT id FROM User WHERE Username = 'TestUser1@TR.com'];
        Group adminGroup = [SELECT Id FROM Group WHERE Name = 'GLI Training Admins'];
        
        gliCase.Subject = 'Test Case 1';
        update gliCase;
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            GroupMember gm = new GroupMember(GroupId=adminGroup.Id,UserorGroupId=gliUser.Id);
            insert gm;
        }
        
        PageReference oPage = Page.LCRMCasetoTrainingEvent;
        Test.setCurrentPage(oPage);
        
        LCRMCasetoTrainingEventController controller = new LCRMCasetoTrainingEventController(new ApexPages.StandardController(gliCase));
        Test.startTest();
           system.runAs(gliUser){
                controller.onPageLoad();
           }
        Test.stopTest(); 
        Training_Event__c te = [SELECT Id FROM Training_Event__c LIMIT 1];
        System.assert(te.id!=null,'Training Event not created');
        System.assert(gliCase.Status=='Converted','Status not set to converted,status is:'+gliCase.Status);
        
    }
    
    //getting an exception while trying to create a training event
    @isTest public static void testConvertCaseWithException(){
        Case gliCase = [SELECT Id,OwnerId FROM Case LIMIT 1];
        User gliUser = [SELECT id FROM User WHERE Username = 'TestUser1@TR.com'];
        Group adminGroup = [SELECT Id FROM Group WHERE Name = 'GLI Training Admins'];
        
        GroupMember gm = new GroupMember(GroupId=adminGroup.Id,UserorGroupId=gliUser.Id);
        insert gm;
        
        PageReference oPage = Page.LCRMCasetoTrainingEvent;
        Test.setCurrentPage(oPage);
        
        LCRMCasetoTrainingEventController controller = new LCRMCasetoTrainingEventController(new ApexPages.StandardController(gliCase));
        Test.startTest();
            system.runAs(gliUser){
                try{   
                    controller.onPageLoad();
                }
                catch(Exception e){
                    System.assert(e.getMessage().contains('Insert failed.'),e.getMessage());
                }
            }
        Test.stopTest();
    }
	
    //user is a GLI Sales User
    @isTest public static void testConvertCaseByGLISalesUser(){
        Case gliCase = [SELECT Id FROM Case LIMIT 1];
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'GLI Sales User'].Id,
            LastName = 'last',
            Email = 'puser000@amamama.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert u;
        PermissionSet trainingPermissionSet = [SELECT Id FROM PermissionSet WHERE name='LCRM_USL_Training_Users'];
        System.runAs(new User(Id=UserInfo.getUserId())){
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = trainingPermissionSet.Id, AssigneeId = u.Id);
            insert psa; 
        }
        PageReference oPage = Page.LCRMCasetoTrainingEvent;
        Test.setCurrentPage(oPage);
        
        LCRMCasetoTrainingEventController controller = new LCRMCasetoTrainingEventController(new ApexPages.StandardController(gliCase));
        Test.startTest();
        system.runAs(u){
            controller.onPageLoad();
        }
        
        Test.stopTest();
    }
	
    //user is a GLI Sales Ops User
    @isTest public static void testConvertCaseByGLISalesOpsUser(){
        Case gliCase = [SELECT Id FROM Case LIMIT 1];
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'GLI Sales Ops User'].Id,
            LastName = 'last',
            Email = 'puser000@amamama.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert u;
        PermissionSet trainingPermissionSet = [SELECT Id FROM PermissionSet WHERE name='LCRM_USL_Training_Users'];
        System.runAs(new User(Id=UserInfo.getUserId())){
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = trainingPermissionSet.Id, AssigneeId = u.Id);
            insert psa; 
        }
        PageReference oPage = Page.LCRMCasetoTrainingEvent;
        Test.setCurrentPage(oPage);
        
        LCRMCasetoTrainingEventController controller = new LCRMCasetoTrainingEventController(new ApexPages.StandardController(gliCase));
        Test.startTest();
        system.runAs(u){
            controller.onPageLoad();
        }
        
        Test.stopTest();
    }
	
}