objects/Invite_Colleagues__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>One_Pass_Identifier__c</fullName>
        <label>One Pass Identifier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SapContactId__c</fullName>
        <label>SAP Contact #</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>contains the count for one pass error service to limit the schedulable class.</description>
        <inlineHelpText>no of times one pass error service called</inlineHelpText>
        <label>Service Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ssd</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>Invited Colleagues</relationshipLabel>
        <relationshipName>Invited_Colleagues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Start_Date__c</fullName>
        <label>Trial Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Timed-out</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Entitlement Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipName>Invite_Colleagues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Auth_ID__c</fullName>
        <label>User Auth ID</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Invited Colleagues</label>
    <nameField>
        <label>Invited Colleagues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invited Colleagues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_ID__c</fullName>
        <label>Global Trial ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Source__c</fullName>
        <label>Trial Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Timed-out</fullName>
                </value>
                <value>
                    <fullName>Bounceback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trial__c.object
<CustomObject>
    <description>As per DLT-5979 - This object is created to capture details of Trial.</description>
    <fields>
        <fullName>Contact_LeadId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Lead ID</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>On-Demand Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvitedDateTime__c</fullName>
        <label>Invited Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Lapsed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Lapsed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ODT_SAP_Account_Number__c</fullName>
        <description>This is field will capture SAP account number of the SSD for which trial is being initiated.</description>
        <label>Account Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>One_Pass_Identifier__c</fullName>
        <label>One Pass Identifier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Type__c</fullName>
        <label>Profile Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EXISTING_USER_SAME_DOMAIN</fullName>
                    <default>true</default>
                    <label>EXISTING_USER_SAME_DOMAIN</label>
                </value>
                <value>
                    <fullName>EXISTING_USER_NEW_DOMAIN</fullName>
                </value>
                <value>
                    <fullName>NET_NEW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>contains the count for one pass error service to limit the schedulable class.</description>
        <inlineHelpText>no of times one pass error service called</inlineHelpText>
        <label>Service Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_System_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ssd</label>
        <referenceTo>Source_System_Detail__c</referenceTo>
        <relationshipLabel>On-Demand Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <label>Trial Id(s)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Source__c</fullName>
        <label>Trial Source</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trial_Start_Date__c</fullName>
        <label>Trial Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Bounceback</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Timed-out</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Entitlement Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Auth_ID__c</fullName>
        <label>User Auth ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Trial</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Trial Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ODT_OnePassErrorINC.cls
/**
 * ODT_OnePassErrorINC Description
 *  DLT-20639 - 18-09-202 - Refactored Code ,Solved PMD violations ,,Removed Limit Condition
 */
public class ODT_OnePassErrorINC implements DataBase.Batchable < sObject > , Database.AllowsCallouts {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([Select ID, Source_System_Detail__c, Email__c, First_Name__c, Last_Name__c, Primary_User__c, Trial__c, SapContactId__c, Trial__r.ODT_SAP_Account_Number__c, User_Auth_ID__c, One_Pass_Identifier__c, Service_Count__c, Trial__r.Profile_Type__c,
            Trial__r.Contact_LeadId__c, Trial__r.Id, Trial__r.Contact_LeadId__r.Company, Trial__r.Trial_Source__c, Trial__r.Trial_End_Date__c, Trial__r.Is_Lapsed__c, Trial__r.Trial_Start_Date__c, Trial__r.Trial_Id__c, GUID__c FROM Invite_Colleagues__c where Trial_Status__c = 'Entitlement Error' AND Trial__r.InvitedDateTime__c>=LAST_N_DAYS:7]);
  }

    public void execute(Database.BatchableContext bc, List < Invite_Colleagues__c > scope) {
        for (Invite_Colleagues__c ic: scope) {
            ODT_OnePassErrorService.checkError(null, ic, 'IC');
        }
    }

    public void finish(Database.BatchableContext bc) {
        System.Debug('Invited Colleagues Batch completed');
    }

}