objects/Invite_Colleagues__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Start_Date__c</fullName>
        <label>Trial Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Timed-out</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Entitlement Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipName>Invite_Colleagues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invited Colleagues</label>
    <nameField>
        <label>Invited Colleagues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invited Colleagues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ODT_Product_Bundle__c.object
<CustomObject>
    <fields>
        <fullName>Bundle_ID__c</fullName>
        <label>Bundle ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Expiry_Days__c</fullName>
        <label>Trial Expiry Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ODT Product Bundle</label>
    <nameField>
        <label>ODT Product Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ODT Product Bundle</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trial__c.object
<CustomObject>
    <description>As per DLT-5979 - This object is created to capture details of Trial.</description>
    <fields>
        <fullName>ODT_Product_Bundle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup relation to the product bundle object.</description>
        <label>ODT Product Bundle</label>
        <referenceTo>ODT_Product_Bundle__c</referenceTo>
        <relationshipLabel>Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <label>Trial Id(s)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Initiated_Mode__c</fullName>
        <label>Trial Initiated Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started by Marketing</fullName>
                    <default>true</default>
                    <label>Started by Marketing</label>
                </value>
                <value>
                    <fullName>Started Immediately</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial_Start_Date__c</fullName>
        <label>Trial Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Bounceback</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Timed-out</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Entitlement Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trial</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Trial Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ODT_StartImmediateTrialHandler.cls
/**============================================================================================
Name              : ODT_StartImmediateTrialHandler
Description       : This class is developed as part of CXD-ODT project : DLT-16452
                    The class serves as a controller for the VF page 'ODT_StartImmediateTrial' in order to fetch invited colleague details along with product details.
                    And changes the Trial Status of Trial and related Invited Colleague.

Author            : Sneha Wali

Changes:
        DLT-19237 : [SFDC] Add Trail End date function to check according ODT bundle data
==============================================================================================**/
public without sharing class ODT_StartImmediateTrialHandler {

    public Trial__c trialList {get; set;}
    public String trialId {get; set;}
    public String firstName{get; set;}
    public String lastName {get; set;}
    public String email {get; set;}
    public String checkboxText{get; set;}
    public boolean trialStartImmediate{get;set;}
    public Integer  Trailexpiryduration;
    
    public ODT_StartImmediateTrialHandler(ApexPages.StandardController controller) {
        trialStartImmediate = false;
    }
    
    // Method to fetch Invited Colleagues and product related to Trial
    public void getInvitedColleagueTrial() {  
        checkboxText=label.ODT_CheckBox_Text;
        trialId = ApexPages.currentPage().getparameters().get('id');             
        
        if(!String.isBlank(trialId)) {           
            trialList = [SELECT ID,Name,Trial_Status__c,ODT_Product_Bundle__r.Trial_Expiry_Days__c,Trial_Id__c,ODT_Product_Bundle__r.Bundle_ID__c,ODT_Product_Bundle__r.Product_Category__c,(SELECT Id,Trial_Status__c,First_Name__c,Last_Name__c,Email__c FROM Invite_Colleagues__r WHERE Primary_User__c = true)
                FROM Trial__c 
                WHERE ID = :trialId];    
            Trailexpiryduration=Integer.valueof(trialList.ODT_Product_Bundle__r.Trial_Expiry_Days__c);  // Added  as part of DLT-19237
                
        }
              
    }
    
    public Trial__c getTrial() {
        return trialList;
    }

    
    public PageReference updateStatus() {
        trialList.Trial_Start_Date__c = date.today();
        // DLT-19237 Starts here
        if(Trailexpiryduration!=null)
        {
            trialList.Trial_End_Date__c = date.today()+Trailexpiryduration;
        }
        // DLT-19237 ends here
        trialList.Trial_Initiated_Mode__c='Started Immediately';
        
        IF(trialList.Trial_Status__c == 'Invited'){
            trialList.Trial_Status__c = 'Rep Initiated'; 
        }        
        update trialList;
        if(!Test.isRunningTest()){
            ODT_TrialReInitiate_AddUser_Callout callout = new ODT_TrialReInitiate_AddUser_Callout(trialList.ID, true, true);
            Id jobID=System.enqueueJob(callout);
        }
        trialStartImmediate = true;
        return null;
    }
    
    public PageReference back(){
       PageReference myVFPage = new PageReference('/'+trialId);
       myVFPage.setRedirect(true);
       return myVFPage;
    }

}