objects/KeyValueListStore__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueListStore</label>
</CustomObject>

objects/LCRM_Integration_defaults_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DPS-1952-All LCRM Team going to use the values.Created by Radhika Pawar</description>
    <fields>
        <fullName>LCRM_WebserviceName__c</fullName>
        <label>LCRM_WebserviceName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LCRM Integration defaults Values</label>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_Sub_BU__c</fullName>
        <description>Renamed from ‘Sub-BU’ to ‘Region’ as part of data segmentation for LOTUS. DPS-1445</description>
        <label>BU Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Segment__c</fullName>
        <description>Created as part of data segmentation for LOTUS, should hold different Business Segments. DPS-2201, DPS-415</description>
        <label>BU Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Segment</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/USL_Integration_defaults__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>USL Integration defaults</label>
</CustomObject>

objects/WebServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for external web service endpoints and credentials.</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The web service url as defined by the service provider</description>
        <inlineHelpText>The web service url as defined by the service provider</inlineHelpText>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>The password required by the service provider for authentication</description>
        <inlineHelpText>The password required by the service provider for authentication</inlineHelpText>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <defaultValue>20</defaultValue>
        <description>Length of time (in seconds) the callout waits for a response from the service provider before producing an error</description>
        <inlineHelpText>Length of time (in seconds) the callout waits for a response from the service provider before producing an error</inlineHelpText>
        <label>Timeout</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>The username required by the service provider for authentication</description>
        <inlineHelpText>The username required by the service provider for authentication</inlineHelpText>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Web Service Settings</label>
</CustomObject>

globalValueSets/Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Professional Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <description>Used to track users segment to assign records and pricebooks.</description>
    <masterLabel>User Segment</masterLabel>
</GlobalValueSet>

classes/USLARHelper.cls
/**
 * @Comment Class Name : USLARHelper  
 * @description
 Code behind the Service Notes button on the account
  PURPOSE:    GLIEDW, Integration between Salesforce and EDW and middleware system is ESI.
  RestWebService is used for developing the subscription functionality.
 *
 */
public without sharing class USLARHelper {
    
    public static USLARWrapper.ARrequest USLARRequestHelper(String SAPNumber,String CompId,String OrgId,String configGrp,String Begindate,String Enddate){
         USLARWrapper.ARrequest odReqWrap = new USLARWrapper.ARrequest();
         USLARWrapper.oAccount acc = new USLARWrapper.oAccount();
         acc.accountNumber=SAPNumber;
           odReqWrap.Account=acc;
           USLARWrapper.EsiHeader eh=new USLARWrapper.EsiHeader(CompId,OrgId,'',configGrp);
           odReqWrap.esiHeader=eh;
           USLARWrapper.Filter fil=new USLARWrapper.Filter(Begindate,Enddate,true,true,true);
           odReqWrap.filter=fil;
        return odReqWrap;
    }
    
    public static HttpResponse USLARCalloutHelper(String WebServiceName,String jsonString){
        // USLARWrapper ARresponse = new USLARWrapper();
         LCRM_Integration_defaults_Values__c integrationDefault = LCRM_Integration_defaults_Values__c.getvalues(Label.LCRMARInvoicelist);
        HttpResponse Response = new HttpResponse();
        try {
            // Send HTTP Request and assign responseHttp http = new Http(); 
             Http http = new Http();
             HttpRequest HTrequest = new HttpRequest();
             HTrequest = getHttpRequestAR(WebServiceName,jsonString);
             system.debug('HTrequest'+HTrequest.getbody());
             Response = http.Send(HTrequest);
            system.debug('Response'+Response.getBody());
            if(Response.getStatusCode() != 200 && WebServiceName!= integrationDefault.LCRM_WebserviceName__c) {
                ESC_HandlerCustomException commonCalloutException = new ESC_HandlerCustomException();
               commonCalloutException.setMessage('A callout exception occurred with a status of: ' + Response.getStatusCode());
               throw commonCalloutException;
            }

           // response.isSuccess = TRUE;
          //  response.responseBodyJSON = httpCalloutResponse.getBody();
        } catch (Exception e) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
        }

        return response;
    }
    
    Public static HttpRequest getHttpRequestAR(String WebServiceName,String jsonString){
        HttpRequest request = new HttpRequest();
        try{
        WebServiceSettings__c oWebServiceSettings = AppUtil.getWebServiceSettings(WebServiceName);
        
        request.setEndpoint(oWebServiceSettings.Endpoint__c);
      // request.setEndpoint('https://api.thomsonreuters.com/ebs/invoice/qa/getInvoiceOpenClearedItems');
        request.setMethod('POST');
        // Specify the required user name and the password to access the endpoint 
        // As well as the header and header information 
        Blob headerValue = Blob.valueOf(oWebServiceSettings.Username__c + ':' + oWebServiceSettings.Password__c);
        String authorizationHeader = 'Basic ' +
        EncodingUtil.base64Encode(headerValue);
        request.setHeader('Content-Type', 'application/json');
        // Header info with remote server user name and password
        request.setHeader('Authorization', authorizationHeader);
        // timeout in milliseconds       
        request.setTimeout((oWebServiceSettings.Timeout__c * 1000).intValue());
      
        if(String.IsNotBlank(jsonString)){
            request.setBody(jsonString);
        }
         
    
    }
    catch (Exception e) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
        }
        
        return request;
}
    public static Set<ID> getAccountSetList(Account oAccount){
        System.debug('Account Data:**'+oAccount);
        Set<ID> accountIdSet = new Set<ID>();

        if(oAccount.parentid!=null || oAccount.Account_Indicator__c=='Branch'){
            accountIdSet.add(oAccount.id);
        }
        else{

            List<Account> acclst= new List<Account>();
            acclst = [select id,SAPAccountNumber__c from account where id in :AccountDetailController.getChildAccountIds(oAccount.id)];
            System.debug('acclst:-'+acclst);

            for(Account acc:[select id,SAPAccountNumber__c from account where id in :AccountDetailController.getChildAccountIds(oAccount.id)]){
                accountIdSet.add(acc.id);
            }
        }

        System.debug('###########################accountIdSet:-'+accountIdSet);


        return accountIdSet;

    }

    /**
     * public getSourceSystemDetails method
     * @description : Get the source system details based on current logged in users sales org value should be matched with SSD sales Org field value
     * @param listAccId
     * @param strSubBu
     * @return List<Source_System_Detail__c> list Return description
     */
    public static List<Source_System_Detail__c> getSourceSystemDetails(Set<Id> listAccId,String strSubBu){
       String tempSubBuValues = KeyValueListStore__c.getInstance('LCRMServiceNotesUserSubBu').TextValue__c;//Gets the SUBBU value from KeyValueListStore__c custom settings
        Set<String> subBuValueSet = new Set<String>();
        for(String val : tempSubBuValues.split(',')){
            subBuValueSet.add(val); 
           
        } 
        system.debug(LoggingLevel.DEBUG,'@@@SubBuValueSet'+subBuValueSet+'----'+strSubBu);
        if ((Schema.sObjectType.Source_System_Detail__c.isAccessible() || Schema.sObjectType.Source_System_Detail__c.isQueryable()) && !String.isBlank(strSubBu)) {
        //if( !String.isBlank(strSubBu)){
            System.debug(LoggingLevel.DEBUG,'USL');
            return [Select id,name,Source_System_Account_Number__c,Account_Name__c,LCRM_Sales_Org__c,LCRM_Sub_BU__c from Source_System_Detail__c Where Account_Name__c in :listAccId and Source_System_Account_Number__c != null and LCRM_Sub_BU__c  IN: subBuValueSet and LCRM_Sales_Org__c!= null];
        }else{
           
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,system.Label.LCRMSubBuMissed));
            return null;
        }
    }
    
    public static USL_Integration_defaults__c getIntegrationDefaults(String segment, String region){
        
        USL_Integration_defaults__c val;
        
        List<USL_Integration_defaults__c> lstDefaults = USL_Integration_defaults__c.getall().values();
        
        for(USL_Integration_defaults__c values : lstDefaults)
        {
            if(values.Segment__c == segment && values.region__c == region)
            {
                val = values;
                break;
            }
        }

        if(val == null)
        {
            val = USL_Integration_defaults__c.getValues('Integrationdefaults');
        }
        
        return val;
    }
}