objects/KeyValueListStore__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueListStore</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
            <filterItems>
                <field>$User.Sub_Bu__c</field>
                <operation>equals</operation>
                <value>LatAm</value>
            </filterItems>
            <filterItems>
                <field>Account.GLI_Business_Unit__c</field>
                <operation>contains</operation>
                <value>LatAm</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>$User.Sub_Bu__c</field>
                <operation>notEqual</operation>
                <value>LatAm</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Non-Converted Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU_Segment__c</fullName>
        <description>Created as part of data segmentation for LOTUS, should hold different Business Segments. DPS-1711</description>
        <inlineHelpText>Customer information is frozen once a year - a Sales User can set this upon Account Creation, but otherwise this is a view-only field</inlineHelpText>
        <label>Frozen Market Current Year Segment L1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_GLI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field created for LCRM project</description>
        <label>Is GLI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LCRM_Sub_BU__c</fullName>
        <description>Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-1711</description>
        <label>BU Region</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/XREFAccountSegment__c.object
<CustomObject>
    <fields>
        <fullName>BU_Segment__c</fullName>
        <label>BU Segment</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>XREFAccountSegmentUpdate</label>
    <nameField>
        <label>AccountId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XREFAccountSegmentUpdates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/BU_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Professional Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <masterLabel>BU Segment</masterLabel>
</GlobalValueSet>

classes/LOTUSUpdateLeadSegmentBatch.cls
global class LOTUSUpdateLeadSegmentBatch implements Database.Batchable<sObject>{

   String Query;
   Map<Id, Account> accountIdSegmentMap;
   List<XREFAccountSegment__c> accountSegmentList;
   List<Lead> leadList = new List<Lead>();
   Set<Id> accountIdSet = new Set<Id>();
   List<String> BuRegionList = new List<String>();
   public Set<String> BuRegionValueSet=new Set<String>();
   global LOTUSUpdateLeadSegmentBatch(Map<Id, Account> accountIdSegmentMap, List<XREFAccountSegment__c> accountSegmentList){
       KeyValueListStore__c BuRegionValueStore = KeyValueListStore__c.getValues('LTS_BURegion_Values');
       if(BuRegionValueStore !=null && BuRegionValueStore.TextValue__c !=null && BuRegionValueStore.TextValue__c != ''){
            BuRegionList = BuRegionValueStore.TextValue__c.split(',');
        } 
                     
        for(String BuRegion : BuRegionList){            
            BuRegionValueSet.add(BuRegion);
        }   
      this.accountIdSegmentMap = accountIdSegmentMap;
      this.accountSegmentList = accountSegmentList;
      this.accountIdSet = accountIdSegmentMap.keySet();
      Query='SELECT Id, Account__c,LCRM_Sub_BU__c, BU_Segment__c FROM Lead WHERE Is_GLI__c = TRUE AND LCRM_Sub_BU__c IN :BuRegionValueSet AND Account__c IN :accountIdSet';
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, List<sObject> scope){
     for(sobject s : scope){
        Lead l = (Lead)s;
        leadList.add(l);
     }
     if(!leadList.isEmpty()){
        LOTUSChildObjectSegmentUpdate.leadSegmentUpdate(leadList, accountIdSegmentMap);
     }
    }

   global void finish(Database.BatchableContext BC){
       Database.executeBatch(New LOTUSUpdateCaseSegmentBatch(accountIdSegmentMap, accountSegmentList), 200);
   }
}