objects/KeyValueListStore__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueListStore</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LCRM_Product_Count__c</fullName>
        <description>Opportunity Product count where Action is Add or Renew (Exclude cancelled or discarded products)</description>
        <label>Total Product Count</label>
        <summaryFilterItems>
            <field>OpportunityLineItem.LCRM_Action__c</field>
            <operation>equals</operation>
            <value>Add, Renew</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LCRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Cancel</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Extended Negotiation</fullName>
                </value>
                <value>
                    <fullName>Extended Access</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_Transaction_Type__c</fullName>
        <description>Indicates if the transaction would be Standard, Short Term, Multi Year, Pro-Rata, Bridge, Paid Trial, Replacement or Evergreen</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>Multi-Year Deal</fullName>
                </value>
                <value>
                    <fullName>Non-Standard</fullName>
                </value>
                <value>
                    <fullName>Evergreen</fullName>
                </value>
                <value>
                    <fullName>Replacement</fullName>
                </value>
                <value>
                    <fullName>Pro-Rata</fullName>
                </value>
                <value>
                    <fullName>Bridge</fullName>
                </value>
                <value>
                    <fullName>Paid Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OpportunityID18__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OpportunityID18</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LTGS_Custom_Settings_Url.cls
/**
 */
 /**
* CHANGE HISTORY
* =============================================================================
* Date         Name                    Description
* 
* 2/28/2019   Ankit Raj       Controller class for the below lightning components
                                            LTGS_Create_Quote
                                            LTGS_Create_Trial
                                            LTGS_New_Competitive_Info
                                            LTGS_Request_Extension
                                            LTGS_Service_Request_Report

* =============================================================================
*/ 

public without sharing class LTGS_Custom_Settings_Url {

    /****************************************************************************************************************************
                getCustomSettings() fetches the KeyValueListStore__c custom setting text_value__c field value
    *****************************************************************************************************************************/ 
     
    @AuraEnabled
    public static String getCustomSettings(String recordName){
        String url;
       
        KeyValueListStore__c keyValue= KeyValueListStore__c.getValues(recordName);
        if(keyValue != null){
        url= keyValue.TextValue__c;
        }
        return url;
    }
    
    
    /****************************************************************************************************************************
            optyDetails() returns the current opportunity record details
    *****************************************************************************************************************************/ 
    
    @AuraEnabled
    public static Opportunity optyDetails(Id recordId)
    {
        Opportunity opp;
        if (Schema.sObjectType.Opportunity.isQueryable()){
         opp = [select id,Name,OpportunityID18__c,LCRM_Product_Count__c,StageName,LCRM_Transaction_Type__c,LCRM_Status__c from Opportunity where id =: recordId];
        }
        return opp;
        
        
    }
}