objects/LCRM_Exception_Handling__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for showing error messages which are received from external system IF any exceptions occurs then only</description>
    <fields>
        <fullName>Destination_System__c</fullName>
        <label>Destination System</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Description__c</fullName>
        <label>Status Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UI_Error_Message_English__c</fullName>
        <label>UI Error Message English</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Webservice_Name__c</fullName>
        <label>Webservice Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webservice_type__c</fullName>
        <label>Webservice type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LCRM Exception Handling</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for Product</description>
        <label>xx-Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SCSI</fullName>
                </value>
                <value>
                    <fullName>SFWS</fullName>
                </value>
                <value>
                    <fullName>SMG</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>TSCE</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>West Group:WEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Name__c</fullName>
        <label>Source System Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for User</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Bu__c</fullName>
        <description>The field has been created to define the sub bu of the user which will be used to populate the Sub bu field on objects Account,Lead,Opportunities,Activity etc. 
Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-2201, DPS-415</description>
        <label>BU Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>USL</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>AEM</fullName>
                </value>
                <value>
                    <fullName>LatAm</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WebServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for external web service endpoints and credentials.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the service is active. If Active is unchecked then no callouts to this service will be allowed.</description>
        <inlineHelpText>Determines if the service is active. If Active is unchecked then no callouts to this service will be allowed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The web service url as defined by the service provider</description>
        <inlineHelpText>The web service url as defined by the service provider</inlineHelpText>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>The password required by the service provider for authentication</description>
        <inlineHelpText>The password required by the service provider for authentication</inlineHelpText>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Unavailable_Message__c</fullName>
        <description>The message displayed to the user in the event the service is inactive or unavailable for use</description>
        <inlineHelpText>The message displayed to the user in the event the service is inactive or unavailable for use</inlineHelpText>
        <label>Service Unavailable Message</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <defaultValue>20</defaultValue>
        <description>Length of time (in seconds) the callout waits for a response from the service provider before producing an error</description>
        <inlineHelpText>Length of time (in seconds) the callout waits for a response from the service provider before producing an error</inlineHelpText>
        <label>Timeout</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>The username required by the service provider for authentication</description>
        <inlineHelpText>The username required by the service provider for authentication</inlineHelpText>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Web Service Settings</label>
</CustomObject>

classes/LCRMOrderDetail_Test.cls
/**
 * Validates the functionality provided by the LCRMOrderDetailController class
 *
 * @author  Seema Nagdev
 * @version 2017-11-10
 */

@istest (seealldata=false)
public class LCRMOrderDetail_Test {
      @isTest static void testOrderDetails(){
        Profile testprofile = [SELECT Id FROM Profile WHERE Name = 'GLI Sales User' limit  1];
        User testUser = new User(
            Alias = 'sUser',
            Email = 'abc1@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'es',
            LocaleSidKey = 'es',
            ProfileId = testprofile.id,
            Sales_Org__c = 'WEST',
            Sub_Bu__c = 'USL',
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'abc123@testorg.com'
        );
        insert testUser;

        System.runAs(testUser) {
            Account testAcc1 = new Account();
            testAcc1 = UnitTest.getAccountInstance();
            testAcc1.SAPAccountNumber__c = '5491';
            insert testAcc1;

            Account testAcc2 = new Account();
            testAcc2 = UnitTest.getAccountInstance();
            testAcc2.SAPAccountNumber__c = '5491344';
            insert testAcc2;

            List < Source_System_Detail__c > ListofSSD = new List < Source_System_Detail__c > ();
            Source_System_Detail__c SSDwithSAPNo = new Source_System_Detail__c();
            SSDwithSAPNo.name = 'SSD1_01';
            SSDwithSAPNo.Source_System_Account_Number__c = '1000000040';
            SSDwithSAPNo.Account_Name__c = testAcc1.id;
            SSDwithSAPNo.Source_System_Name__c = 'LCRMGLI';
            SSDwithSAPNo.LCRM_Sales_Org__c = 'WEST';
            ListofSSD.add(SSDwithSAPNo);

            Source_System_Detail__c SSDSAPNo = new Source_System_Detail__c();
            SSDSAPNo.name = 'SSD1_02';
            SSDSAPNo.Source_System_Account_Number__c = '1000000846';
            SSDSAPNo.Account_Name__c = testAcc1.id;
            SSDSAPNo.Source_System_Name__c = 'LCRMGLISSD';
            SSDSAPNo.LCRM_Sales_Org__c = 'WEST';
            ListofSSD.add(SSDSAPNo);

            if (ListofSSD.size() > 0) {
                insert ListofSSD;
            }
            Product2 prod = new Product2();
            prod.ProductCode = '41477272';
            prod.Name = 'TestProduct';
            //prod.CurrencyIsoCode = 'USD - U.S. Dollar'; 
            insert prod;
    
    
            
            List<WebServiceSettings__c> lstofWebServ = new List<WebServiceSettings__c>();
            WebServiceSettings__c Webserve = new WebServiceSettings__c();
            Webserve.name = 'LCRM_GetOrderDetail';       
            Webserve.Active__c = true;
            Webserve.Endpoint__c = 'https://esi-dev.thomsonreuters.com/osb/OrdersRequest_Service/ProxyService/OrderInbound/PS_OrdersRequest_REST/GetOrderDetails';
            Webserve.Password__c = 'esidevuser123';
            Webserve.Service_Unavailable_Message__c = 'OrderDetail Service is unavailable';
            Webserve.Timeout__c = 120;
            Webserve.Username__c = 'esidevuser';
            lstofWebServ.add(Webserve);
            
            if(lstofWebServ.size()>0){
                insert lstofWebServ;
            }
    
           Test.startTest();
            //Test.setMock(HttpCalloutMock.class, new MockLCRMOrderDetailServiceTest());
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('LCRMOrderDetailMockResponse');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);
            ApexPages.standardController sc = new ApexPages.standardController(testAcc1);
            Test.setCurrentPageReference(Page.LCRMOrderDetail);
            LCRMOrderDetailController oOrders = new LCRMOrderDetailController(sc);
            oOrders.getOrderDetails();
            Test.stopTest();
            System.assertEquals('41477272', oOrders.odItems[0].MaterialNumber);
           
            }
    } 
    
    @isTest static void testOrderDetailException(){
        
        Profile testprofile = [SELECT Id FROM Profile WHERE Name = 'GLI Sales User' limit 1];
        User testUser = new User(
            Alias = 'sUser',
            Email = 'abc1@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'es',
            LocaleSidKey = 'es',
            ProfileId = testprofile.id,
            Sales_Org__c = 'WEST',
            Sub_Bu__c = 'USL',
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'abc123@testorg.com'
        );
        insert testUser;

        System.runAs(testUser) {
            Account oAccount= new Account();
            oAccount = UnitTest.getAccountInstance();
            oAccount.SAPAccountNumber__c = '5491';
            insert oAccount;

            List < Source_System_Detail__c > ListofSSD = new List < Source_System_Detail__c > ();
            Source_System_Detail__c SSDwithSAPNo = new Source_System_Detail__c();
            SSDwithSAPNo.name = 'SSD1_01';
            SSDwithSAPNo.Source_System_Account_Number__c = '1000000040';
            SSDwithSAPNo.Account_Name__c = oAccount.id;
            SSDwithSAPNo.Source_System_Name__c = 'LCRMGLI';
            SSDwithSAPNo.LCRM_Sales_Org__c = 'WEST';
            ListofSSD.add(SSDwithSAPNo);

            Source_System_Detail__c SSDSAPNo = new Source_System_Detail__c();
            SSDSAPNo.name = 'SSD1_02';
            SSDSAPNo.Source_System_Account_Number__c = '1000000846';
            SSDSAPNo.Account_Name__c = oAccount.id;
            SSDSAPNo.Source_System_Name__c = 'LCRMGLISSD';
            SSDSAPNo.LCRM_Sales_Org__c = 'WEST';
            ListofSSD.add(SSDSAPNo);

            if (ListofSSD.size() > 0) {
                insert ListofSSD;
            }

           
            List<WebServiceSettings__c> lstofWebServ = new List<WebServiceSettings__c>();
            WebServiceSettings__c Webserve = new WebServiceSettings__c();
            Webserve.name = 'LCRM_GetOrderDetail';       
            Webserve.Active__c = true;
            Webserve.Endpoint__c = 'https://esi-dev.thomsonreuters.com/osb/OrdersRequest_Service/ProxyService/OrderInbound/PS_OrdersRequest_REST/GetOrderDetails';
            Webserve.Password__c = 'esidevuser123';
            Webserve.Service_Unavailable_Message__c = 'OrderDetail Service is unavailable';
            Webserve.Timeout__c = 120;
            Webserve.Username__c = 'esidevuser';
            lstofWebServ.add(Webserve);
            
            if(lstofWebServ.size()>0){
                insert lstofWebServ;
            }
            List<LCRM_Exception_Handling__c> lstExceptionHandle = new List<LCRM_Exception_Handling__c>();
            LCRM_Exception_Handling__c exp = new LCRM_Exception_Handling__c();
            exp.Name = '1';
            exp.Destination_System__c = 'SAP';
            exp.Status_Code__c = '400';
            exp.Status_Description__c = 'SalesDocNotFound';
            exp.Status_Reason__c = 'Sales doc not found by doc #';
            exp.UI_Error_Message_English__c = 'No Order Details found in SAP for the selected order.';
            exp.Webservice_Name__c = 'LCRM_GetOrderDetail';
            exp.Webservice_type__c = 'REST';
            lstExceptionHandle.add(exp);
             if(lstExceptionHandle.size()>0){
                insert lstExceptionHandle;
            }
            
            Test.startTest();
            //Test.setMock(HttpCalloutMock.class, new MockLCRMOrderDetailExceptionTest());
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('LCRMOrderDetailMockException');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);
            ApexPages.StandardController oStandardController1 = new ApexPages.StandardController(oAccount);
            LCRMOrderDetailController oOrders = new LCRMOrderDetailController(oStandardController1);
            oOrders.getOrderDetails();
            Test.stopTest(); 
            System.assertEquals('SalesDocNotFound', oOrders.ExceptionMesginfo.statusDescription);
            } 
    } 

     @isTest static void testOrderDetailExceptionLogger(){
        
        Profile testprofile = [SELECT Id FROM Profile WHERE Name = 'GLI Sales User' limit 1];
        User testUser = new User(
            Alias = 'sUser',
            Email = 'abc1@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'es',
            LocaleSidKey = 'es',
            ProfileId = testprofile.id,
            Sales_Org__c = 'WEST',
            Sub_Bu__c = 'USL',
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'abc123@testorg.com'
        );
        insert testUser;

        System.runAs(testUser) {
            Account oAccount= new Account();
            oAccount = UnitTest.getAccountInstance();
            oAccount.SAPAccountNumber__c = '5491';
            insert oAccount;

            List < Source_System_Detail__c > ListofSSD = new List < Source_System_Detail__c > ();
            Source_System_Detail__c SSDwithSAPNo = new Source_System_Detail__c();
            SSDwithSAPNo.name = 'SSD1_01';
            SSDwithSAPNo.Source_System_Account_Number__c = '1000000040';
            SSDwithSAPNo.Account_Name__c = oAccount.id;
            SSDwithSAPNo.Source_System_Name__c = 'LCRMGLI';
            SSDwithSAPNo.LCRM_Sales_Org__c = 'WEST';
            ListofSSD.add(SSDwithSAPNo);

            if (ListofSSD.size() > 0) {
                insert ListofSSD;
            }

           
            List<WebServiceSettings__c> lstofWebServ = new List<WebServiceSettings__c>();
            WebServiceSettings__c Webserve = new WebServiceSettings__c();
            Webserve.name = 'LCRM_GetOrderDetail';       
            Webserve.Active__c = true;
            Webserve.Endpoint__c = 'https://esi-dev.thomsonreuters.com/osb/OrdersRequest_Service/ProxyService/OrderInbound/PS_OrdersRequest_REST/GetOrderDetails';
            Webserve.Password__c = 'esidevuser123';
            Webserve.Service_Unavailable_Message__c = 'OrderDetail Service is unavailable';
            Webserve.Timeout__c = 120;
            Webserve.Username__c = 'esidevuser';
            lstofWebServ.add(Webserve);
            
            if(lstofWebServ.size()>0){
                insert lstofWebServ;
            }
            List<LCRM_Exception_Handling__c> lstExceptionHandle = new List<LCRM_Exception_Handling__c>();
            LCRM_Exception_Handling__c exp = new LCRM_Exception_Handling__c();
            exp.Name = '1';
            exp.Destination_System__c = 'SAP';
            exp.Status_Code__c = '400';
            exp.Status_Description__c = 'Invalid documentID';
            exp.Status_Reason__c = 'Sales doc not found by doc #';
            exp.UI_Error_Message_English__c = 'No Order Details found in SAP for the selected order.';
            exp.Webservice_Name__c = 'LCRM_GetOrderDetail';
            exp.Webservice_type__c = 'REST';
            lstExceptionHandle.add(exp);
             if(lstExceptionHandle.size()>0){
                insert lstExceptionHandle;
            }
            
             Test.startTest();
            //Test.setMock(HttpCalloutMock.class, new MockLCRMOrderDetailExceptionTest2());
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('LCRMOrderDetailMockException');
            mock.setStatusCode(400);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);
            ApexPages.StandardController oStandardController1 = new ApexPages.StandardController(oAccount);
            LCRMOrderDetailController oOrders = new LCRMOrderDetailController(oStandardController1);
            oOrders.getOrderDetails();
            Test.stopTest(); 
            System.assert(ApexPages.getMessages().get(0).getDetail().contains(Label.LCRMWebServiceError)); 
            } 
    } 

    
    
}