objects/LCRM_Contact_SSD__c.object
<CustomObject>
    <fields>
        <fullName>LCRM_Contact_ID__c</fullName>
        <label>SAP Contact ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCRM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Source System Detail</relationshipLabel>
        <relationshipName>Contact_SSDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Legacy_Contact_Type__c</fullName>
        <label>Source System Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAPWRP</fullName>
                </value>
                <value>
                    <fullName>SAPMEP</fullName>
                </value>
                <value>
                    <fullName>CRMOD</fullName>
                </value>
                <value>
                    <fullName>ENTWRP</fullName>
                </value>
                <value>
                    <fullName>HANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_Source_Contact_Id__c</fullName>
        <label>Source Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Contact Source System</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Source Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LCRM_Sub_BU__c</fullName>
        <description>Renamed from ‘Sub-BU’ to ‘Region’ as part of data segmentation for LOTUS. DPS-1445</description>
        <label>BU Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WebServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for external web service endpoints and credentials.</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The web service url as defined by the service provider</description>
        <inlineHelpText>The web service url as defined by the service provider</inlineHelpText>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>The password required by the service provider for authentication</description>
        <inlineHelpText>The password required by the service provider for authentication</inlineHelpText>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Unavailable_Message__c</fullName>
        <description>The message displayed to the user in the event the service is inactive or unavailable for use</description>
        <inlineHelpText>The message displayed to the user in the event the service is inactive or unavailable for use</inlineHelpText>
        <label>Service Unavailable Message</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <defaultValue>20</defaultValue>
        <description>Length of time (in seconds) the callout waits for a response from the service provider before producing an error</description>
        <inlineHelpText>Length of time (in seconds) the callout waits for a response from the service provider before producing an error</inlineHelpText>
        <label>Timeout</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>The username required by the service provider for authentication</description>
        <inlineHelpText>The username required by the service provider for authentication</inlineHelpText>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Web Service Settings</label>
</CustomObject>

classes/webServiceClass.cls
/**
* CHANGE HISTORY
* =============================================================================
* Date         Name                    Description
* 2018-06-14   Matthew Main            Creating OnePass Integration Per ESD-312
* =============================================================================
*/

public virtual class webServiceClass {

    String webServiceName {get;set;}
    public String endpointURL {get;set;}
    String userName {get;set;}
    String password {get;set;}
    String serviceUnavailableString {get;set;}
    public Integer timeout {get;set;}
    private String authorizationHeader;


    public webServiceClass(String serviceName){
        webServiceName = serviceName;
        WebServiceSettings__c oWebServiceSettings = AppUtil.getWebServiceSettings(WebServiceName);

        timeout = (oWebServiceSettings.Timeout__c * 1000).intValue();
        username = oWebServiceSettings.Username__c;
        password = oWebServiceSettings.Password__c;
        serviceUnavailableString = oWebServiceSettings.Service_Unavailable_Message__c;
        endpointURL = oWebServiceSettings.Endpoint__c;


    }
    public webServiceClass(){

    }

    public static List<Source_System_Detail__c> getSourceSystemDetails(Set<Id> listAccId,String strSubBu){
        System.debug('**call Method getSourceSystemDetails**');
        if(strSubBu == 'USL'){
            System.debug('USL');
            return [Select id,name,Source_System_Account_Number__c,Account_Name__c,LCRM_Sales_Org__c,LCRM_Sub_BU__c from Source_System_Detail__c Where Account_Name__c in :listAccId and Source_System_Account_Number__c != null and LCRM_Sub_BU__c  IN ('USL') and LCRM_Sales_Org__c!= null];
        }else{
            System.debug('Other Profiles ');
            return [Select id,name,Source_System_Account_Number__c,Account_Name__c,LCRM_Sales_Org__c,LCRM_Sub_BU__c from Source_System_Detail__c Where Account_Name__c in :listAccId and Source_System_Account_Number__c != null and LCRM_Sub_BU__c=:strSubBu and LCRM_Sales_Org__c!= null];
        }
    }
/*
    public static List<LCRM_Contact_SSD__c> getContactSourceSystemsDetails(List<Id> listConId, String strSubBu){
        System.debug('**call Method getContactSourceSystems**');
        if(strSubBu == 'USL'){
            System.debug('USL');
            try {
                List<LCRM_Contact_SSD__c> contactSSD = [Select id, name, LCRM_Contact__c, LCRM_Contact_ID__c, LCRM_Source_Contact_Id__c from LCRM_Contact_SSD__c Where LCRM_Contact__c in :listConId and LCRM_Legacy_Contact_Type__c = 'sapwrp'];
                System.debug('############## ContactSSD:' + contactSSD);
                return contactSSD;
            }
            catch(exception e){
                System.debug('Exception in webServiceClass.getContactSourceSystemsDetails:' + e.getMessage());
                throw e;
            }
            }else{
            System.debug('Other Profiles ');
            return [Select id, name, LCRM_Contact__c, LCRM_Contact_ID__c, LCRM_Source_Contact_Id__c from LCRM_Contact_SSD__c Where LCRM_Contact__c in :listConId and LCRM_Legacy_Contact_Type__c = 'sapwrp'];
        }

    }
*/
    /*public abstract String getEndpoint(String orgId);

    public abstract void setEndpoint();
*/
    public String getAuthorizationString(){
        if(authorizationHeader == null) {
            Blob blobCredentials = Blob.valueOf(userName + ':' + password);
            authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(blobCredentials);
        }

        return authorizationHeader;

    }




}