objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Elite</fullName>
        <active>true</active>
        <businessProcess>Legal</businessProcess>
        <description>Record type for lcrm project</description>
        <label>Elite</label>
    </recordTypes>
    <recordTypes>
        <fullName>S2E</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <description>Record type used by all S2E users profiles.</description>
        <label>S2E</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LCRMLeadRTUpdateTest.cls
/**
* Test Class for LCRMLeadRTUpdate batch class
*
*/

/**
* CHANGE HISTORY
* =============================================================================
* Date         Name                    Description
* 2017-04-27   TCS                     Created     
* =============================================================================
*/
@isTest
private class LCRMLeadRTUpdateTest {

    private static testMethod void testLeadRecordTypeUpdate1() {
        
        Id rtId;
        Id rtEliteId;
        rtId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('S2E').getRecordTypeId();
        rtEliteId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Elite').getRecordTypeId();
        
        Lead oLead = UnitTest.getLeadInstance();
        oLead.LastName='TestLastName#123';
        oLead.Company = 'UTLeadAccount';
        oLead.Billing_City__c = 'test';
        oLead.Billing_Street__c = 'test';
        oLead.Billing_State__c = 'CA';
        oLead.Billing_Country__c = 'US';
        oLead.email = 'abc@gmail.com';
        oLead.recordTypeid = rtEliteId;
        insert oLead;
        
        Lead oLeadRetrieved = [select id, recordTypeid from Lead where id = :oLead.Id ];
        
        system.assertEquals(rtEliteId, oLeadRetrieved.RecordTypeId);
        
        Test.startTest();  
                LCRMLeadRTUpdate  obj1 = new LCRMLeadRTUpdate ();
                Database.executeBatch(obj1);
                obj1.createExceptionLog('Test Error','#111');
                system.assert(true);
        Test.stopTest();
        
        oLeadRetrieved = [select id, recordTypeid from Lead where id = :oLead.Id ];
        system.assertEquals(rtId, oLeadRetrieved.RecordTypeId);
    }

}