objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street_2__c</fullName>
        <description>Created as part of TR Store. Holds value for second line of billing address.</description>
        <label>Billing Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_GLI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field created for LCRM project</description>
        <label>Is GLI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Microsite__c</fullName>
        <label>Lead Microsite</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deloitte</fullName>
                </value>
                <value>
                    <fullName>PWC</fullName>
                </value>
                <value>
                    <fullName>TR Store</fullName>
                </value>
                <value>
                    <fullName>Triform</fullName>
                </value>
                <value>
                    <fullName>Deskcopy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Region__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TR Store Canada Print</fullName>
                </value>
                <value>
                    <fullName>TR Store US Print</fullName>
                </value>
                <value>
                    <fullName>TR Store Tax Professional</fullName>
                </value>
                <value>
                    <fullName>UE Store Canada PRINT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_Unit__c</fullName>
        <description>An internal business group that reports up through the same leadership</description>
        <inlineHelpText>An internal business group that reports up through the same leadership</inlineHelpText>
        <label>Operating Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Acritas</fullName>
                </value>
                <value>
                    <fullName>Acuigen</fullName>
                    <isActive>false</isActive>
                    <label>Acuigen</label>
                </value>
                <value>
                    <fullName>Beaton</fullName>
                    <isActive>false</isActive>
                    <label>Beaton</label>
                </value>
                <value>
                    <fullName>BTI</fullName>
                    <isActive>false</isActive>
                    <label>BTI</label>
                </value>
                <value>
                    <fullName>CANZ</fullName>
                </value>
                <value>
                    <fullName>Caselines</fullName>
                    <label>CaseLines</label>
                </value>
                <value>
                    <fullName>Corp</fullName>
                </value>
                <value>
                    <fullName>Corp-Global 7</fullName>
                </value>
                <value>
                    <fullName>Corp-Large</fullName>
                </value>
                <value>
                    <fullName>Corp-SMB</fullName>
                </value>
                <value>
                    <fullName>Corp-Strategic</fullName>
                </value>
                <value>
                    <fullName>Corp-Unknown</fullName>
                </value>
                <value>
                    <fullName>Elite (LES)</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>Govt</fullName>
                </value>
                <value>
                    <fullName>LLF</fullName>
                </value>
                <value>
                    <fullName>LMLF</fullName>
                    <isActive>false</isActive>
                    <label>LMLF</label>
                </value>
                <value>
                    <fullName>LMS</fullName>
                    <isActive>false</isActive>
                    <label>LMS</label>
                </value>
                <value>
                    <fullName>McKinsey</fullName>
                    <isActive>false</isActive>
                    <label>McKinsey</label>
                </value>
                <value>
                    <fullName>MLF</fullName>
                </value>
                <value>
                    <fullName>Nisus Consulting</fullName>
                    <isActive>false</isActive>
                    <label>Nisus Consulting</label>
                </value>
                <value>
                    <fullName>Pondera</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>SLF</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                    <isActive>false</isActive>
                    <label>Tax</label>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Wicker Park</fullName>
                    <isActive>false</isActive>
                    <label>Wicker Park</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAPAccountNumber__c</fullName>
        <label>SAP Account Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org of Lead</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>WEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShipToSSD_TRStore__c</fullName>
        <label>ShipToSSD TRStore</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_FirstName__c</fullName>
        <label>Shipping FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_LastName__c</fullName>
        <label>Shipping LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Phone__c</fullName>
        <description>Shipping Phone Number, populated by TR Store.</description>
        <label>Shipping Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Shipping_Street_2__c</fullName>
        <description>Created as part of TR Store. Holds value for second line of Shipping address.</description>
        <label>Shipping Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRstore_Billadd_differenceto_shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TRstore Billadd differenceto shipping</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>GLI</fullName>
        <active>true</active>
        <businessProcess>Legal</businessProcess>
        <description>Record type used for US legal</description>
        <label>GLI</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Static_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>We will store key pair static values under this custom settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Static Values</label>
</CustomObject>

classes/DCPLeadServiceHelper.cls
/**
* @file name          : DCPLeadServiceHelper
* @description        : This class helper class for DCPLeadService class
* @author             : Servendra Kumar
* @group              : TR
* @last modified by   : Servendra Kumar
* @last modified on   : 05/20/2021
* @modification log   : CHANGE HISTORY
* =============================================================================
* Date         Name               JIRA         Description
* 05/20/2021   Servendra Kumar    DCP-1678     Created 
* =============================================================================
**/
public with sharing class DCPLeadServiceHelper {

    public static Lead lead = new Lead();
    
    /**  
    *  @description  firstString - From list of values it will return first value
    *  @param anyStringList : this will holds list of string 
    *  @return string from that list of values - first value  
    **/    
    public static String firstString(LIST<string> anyStringList){
        
         if(!anyStringList.isEmpty()){
            return anyStringList[0];
        }
        
        return null;
    }
    
    
    /**
    *  @description  getValuesFromStaticValuesCs - get values from custom settings  
    *  @param csName : string for custom settings name 
    *  @return string return type 
    **/    
    
    public static string getValuesFromStaticValuesCs(string csName){
        
        if(Static_Values__c.getAll().containsKey(csName)){
           return  Static_Values__c.getAll().get(csName).Value__c;
        }        
        return null;        
    }
    
    /**
    *  queryLeadDetails: Common Method to query lead details based on email ID and cart ID
    *  @input email ID, cart ID, boolean:isCreated, @returns List of Lead
    *  @description  queryLeadDetails  -  query lead details 
    *  @param emailIdList : lead string  
    *  @param cartList : Cart details 
    *  @param isCreated : cart created Boolean 
    *  @return : LIST<Lead> all leads 
    **/     
    public static List<Lead> queryLeadDetails(List<string> emailIdList, List<string> cartList,boolean isCreated){
        List<Lead> leadInfo= new List<Lead>();
                    
        system.debug(loggingLevel.INFO,'DCP cart List....'+cartList);
         
        if(isCreated){
            if (Schema.sObjectType.Lead.isAccessible()){
                leadInfo = [SELECT Id, Name,firstname,city,street,state ,country, postalcode, Lead_Region__c, lastname, Email,phone, isconverted, convertedAccountid, convertedcontactid,Product_Configuration__c, convertedopportunityId,company, Billing_Street__c, Billing_City__c, Billing_State__c, Billing_Country__c, Billing_Zip__c,SAPAccountNumber__c,TRstore_Billadd_differenceto_shipping__c,ShipToSSD_TRStore__c, Market_Segment__c,Lead_Microsite__c,Shipping_Phone__c,Shipping_FirstName__c,Shipping_LastName__c,Billing_Street_2__c,Shipping_Street_2__c from
                           Lead WHERE ( Email In: emailIdList OR Product_Configuration__c IN: cartList) AND Status != 'Disqualified' AND isConverted = false ORDER BY createdDate DESC];
            
            }
        }else{
            if (Schema.sObjectType.Lead.isAccessible()){  
                system.debug(loggingLevel.INFO,'lead id from PE'+emailIdList);
                leadInfo = [SELECT Id, Name,firstname,city,street,state ,Lead_Region__c,country,postalcode, lastname, Email,phone, isconverted, convertedAccountid, convertedcontactid,Product_Configuration__c, convertedopportunityId,company, Billing_Street__c, Billing_City__c, Billing_State__c, Billing_Country__c, Billing_Zip__c,SAPAccountNumber__c,TRstore_Billadd_differenceto_shipping__c,ShipToSSD_TRStore__c, Market_Segment__c,Lead_Microsite__c,Shipping_Phone__c,Shipping_FirstName__c, Shipping_LastName__c,Billing_Street_2__c,Shipping_Street_2__c from 
                            Lead WHERE Id In: emailIdList AND Product_Configuration__c IN: cartList ORDER BY createdDate DESC] ;
            }
        }
        
        system.debug(LoggingLevel.Info,'leadInfo'+leadInfo);
        return leadInfo;
        
    }
    /**
    *  mapCustomerDetails : map customer details on the lead fields.
    *  @input PlatForm DCPLeadRequestHandler   
    *  @description  mapCustomerDetails - map customer details  
    *  @param leadInfo : main json 
    *  @return : lead
    *   
    **/
    public static Lead mapCustomerDetails(DCPLeadRequestHandler.DCPCustomerDetails leadInfo){ 
        if(leadInfo != null){       
            lead.Is_GLI__c = true; 
            lead.firstname = leadInfo.firstName;
            lead.lastname = leadInfo.lastName;
            lead.Email = leadInfo.businessEmail;   
            lead.leadSource='Website';     
            lead.sales_org__c='GLI';  
            lead.Shipping_Phone__c = leadInfo.shippingPhoneNumber;
            lead.Operating_Unit__c = 'Print';
            
            system.debug(LoggingLevel.Info,'leadInfo.businessPhoneNumber..........'+leadInfo.businessPhoneNumber);
            if( leadInfo.businessPhoneNumber != null && leadInfo.businessPhoneNumber != ''){
                lead.MobilePhone = leadInfo.businessPhoneNumber;
                lead.phone = leadInfo.businessPhoneNumber;
            }
            
            if(leadInfo.shippingFirstName != null){
                lead.Shipping_FirstName__c = leadInfo.shippingFirstName;  
            }
            if(leadInfo.shippingLastName != null){
                lead.Shipping_LastName__c = leadInfo.shippingLastName;  
            }
            if(leadInfo.isPhysicalSameAsBillingAddress != null){
                lead.TRstore_Billadd_differenceto_shipping__c = !(leadInfo.isPhysicalSameAsBillingAddress);  
            }
            if(Static_Values__c.getAll().get('LeadRecordTypeName') != null){
                string rtName= Static_Values__c.getAll().get('LeadRecordTypeName').value__c;
                lead.recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get(rtName).getRecordTypeId();
            }    
            /*  if(!aemConnectUsers.isEmpty()){
                lead.ownerId = aemConnectUsers[0].id; 
            }*/ 
        }
        mapOrganizationDetails(leadInfo);
        return lead;
    }
    /**
    *  mapOrganizationDetails : map organization details and shipping details on the lead fields.
    *  @input PlatForm DCPLeadRequestHandler.DCPCustomerDetails   
    *  @description  mapOrganizationDetails - Map the lead organization details 
    *  @param leadInfo : Parameter to have main lead json 
    *    
    **/
    private static void mapOrganizationDetails(DCPLeadRequestHandler.DCPCustomerDetails leadInfo){
        
        if(leadInfo.organizationDetails != null ) {
            DCPLeadRequestHandler.DCPLAccountDetails accountdetails = leadInfo.organizationDetails;       
            lead.SAPAccountNumber__c = accountdetails.AccountANumber;
            lead.company = accountdetails.organizationName;
            
            if(accountdetails.organizationType != null){
                lead.Market_Segment__c = accountdetails.organizationType;
            }
            
            if(accountdetails.billingAddress != null){                       
                DCPLeadRequestHandler.CustomerAddress billingaddress = accountdetails.billingAddress;     
                
                lead.Billing_Street__c = billingaddress.street1;
                lead.Billing_Street_2__c = billingaddress.street2;
                lead.Billing_City__c = billingaddress.city;
                lead.Billing_State__c = billingaddress.state;
                lead.Billing_Country__c = billingaddress.country;
                lead.Billing_Zip__c = billingaddress.zipCode;
                
            }     
        }
        if(leadInfo.shippingAddress != null){                       
            DCPLeadRequestHandler.CustomerAddress shippingAddress = leadInfo.shippingAddress;     
            
            lead.street = shippingAddress.street1;
            lead.Shipping_Street_2__c = shippingAddress.street2;
            lead.city = shippingAddress.city;
            lead.state = shippingAddress.state;
            lead.country = shippingAddress.country;
            lead.postalcode = shippingAddress.zipCode;
            if(shippingAddress.accNumber != null){
                lead.ShipToSSD_TRStore__c = shippingAddress.accNumber;
            }
                    
        }
    }
    

    

    /**
    *  @description  fetchLangParams - main method to get Lang Main param 
    *  @param lang : param to get the lang 
    *  @return string 
    **/
    public static string fetchLangParams(string lang){        
        return (Static_Values__c.getAll().containsKey(lang))? Static_Values__c.getAll().get(lang).Value__c : 'English';                        
    }

    /**
    *  mapLeadrecId : maps the Lead id based on email and cart id, if both matches we need to get that lead id.
    *  @input PlatForm DCPLeadRequestHandler   
    *  @description  mapLeadrecId - this is the method map the existing lead  
    * @param emailIds
    * @param cartIds
    *  @return
    *    
    **/
    public static id mapLeadrecId(LIST<String> emailIds, LIST<String> cartIds){
        id leadIdP1;
        id leadIdP2;
        id leadIdP3;       
        string serviceEmail =  firstString(emailIds);
        string serviceCartId = firstString(cartIds);       
        for(Lead l: queryLeadDetails(emailIds, cartIds,true)){
            if(l.email == serviceEmail  && l.Product_Configuration__c == serviceCartId && leadIdP1 == null){
                leadIdP1 = l.id;
                break;
            }else if(l.Product_Configuration__c == serviceCartId && leadIdP2  == null) {
                leadIdP2 = l.id;
            }else if(leadIdP3 == null){
                leadIdP3 = l.id;
            }
        }
         
        return mapFinalLeadId(leadIdP1 , leadIdP2, leadIdP3);
         
    }
    
    /** 
    *  @description  mapFinalLeadId - here we are mapping Lead ids from above 3 lead ids
    *  @param leadIdP1 : first Lead id
    *  @param leadIdP2 : Second Lead id
    *  @param leadIdP3 : Third Lead id
        @return
    *  
    *    
    **/     
    public static Id mapFinalLeadId(id leadIdP1, id leadIdP2, id leadIdP3){
        
        if(leadIdP1 != null || leadIdP2 != null || leadIdP3 != null){
            return ((leadIdP1 != null)? leadIdP1 :((leadIdP2 != null)? leadIdP2 : leadIdP3));
        }
        return null;
        
    }
}