objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Is_GLI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field created for LCRM project</description>
        <label>Is GLI</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LTS_Disable_Application_Automation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to disable the triggers, validation, workflows etc.</description>
    <fields>
        <fullName>LTS_Disable_Process_Builders__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the process builders</description>
        <inlineHelpText>If checked, will disable all process builder wherever this flag is used.</inlineHelpText>
        <label>Disable Process Builders</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTS_Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the triggers</description>
        <inlineHelpText>If checked, will disable all triggers wherever this flag is used.</inlineHelpText>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTS_Disable_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the validation Rules</description>
        <inlineHelpText>If checked, will disable all validation rules wherever this flag is used.</inlineHelpText>
        <label>Disable Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTS_Disable_Workflow_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable all the Workflow Rules</description>
        <inlineHelpText>If checked, will disable all workflow rule wherever this flag is used.</inlineHelpText>
        <label>Disable Workflow Rules</label>
        <type>Checkbox</type>
    </fields>
    <label>Disable Application Automation</label>
</CustomObject>

classes/HVS_CallDisposition_Test.cls
/**
@description HVS_CallDisposition_Test 
LCRM_HVS_Lead_Update process builder
HVS_Update_CallDisposition process builder
 *
 */
@isTest
public class HVS_CallDisposition_Test {
    
    @istest
    static void method1(){
        LTS_Disable_Application_Automation__c ltstemp = new LTS_Disable_Application_Automation__c();
        ltstemp.LTS_Disable_Process_Builders__c = false;
        ltstemp.LTS_Disable_Triggers__c = true;
        ltstemp.LTS_Disable_Validation_Rules__c = true;
        ltstemp.LTS_Disable_Workflow_Rules__c = true;
        ltstemp.Name = 'temp';
        ltstemp.SetupOwnerId = userinfo.getuserid();
        insert ltstemp;
        
        Lead lead = new Lead();
        lead.Company = 'Test 1 New Company';
        lead.FirstName = 'Martha2';
        lead.LastName = 'Belly2';       
        lead.LeadSource = 'Not Converted';
        lead.Is_GLI__c = true;
        insert lead;
     
        System.assertEquals(lead!= null , true,'Lead check');
        List<Task> tasks = new List<Task>();
        tasks.add(new Task(
            ActivityDate = Date.today().addDays(7),
            LCRM_Activity_Type__c='Call Outbound',
            Activity_category__c = 'Appointment Request',
            Call_Disposition__c = 'Connected' ,
            Subject='Sample Task',        
            whoId= lead.id,     
            OwnerId = UserInfo.getUserId(),
            Status='Completed'));
        insert tasks;
    }
    @istest
    static void method2(){
        LTS_Disable_Application_Automation__c ltstemp = new LTS_Disable_Application_Automation__c();
        ltstemp.LTS_Disable_Process_Builders__c = false;
        ltstemp.LTS_Disable_Triggers__c = true;
        ltstemp.LTS_Disable_Validation_Rules__c = true;
        ltstemp.LTS_Disable_Workflow_Rules__c = true;
        ltstemp.Name = 'temp';
        ltstemp.SetupOwnerId = userinfo.getuserid();
        insert ltstemp;
        
        Lead lead = new Lead();
        lead.Company = 'Test 1 New Company';
        lead.FirstName = 'Martha2';
        lead.LastName = 'Belly2';       
        lead.LeadSource = 'Not Converted';
        lead.Is_GLI__c = true;
        insert lead;
        System.assertEquals(lead!= null , true,'Lead check');
        List<Task> tasks = new List<Task>();
        tasks.add(new Task(
            ActivityDate = Date.today().addDays(7),
            LCRM_Activity_Type__c='Call Outbound',
            Activity_category__c = 'Appointment Request',
            Call_Disposition__c = 'Not Interested' ,
            Subject='Sample Task 2 ',        
            whoId= lead.id,     
            OwnerId = UserInfo.getUserId(),
            Status='Completed'));
        insert tasks;
    }
    @istest
    static void method3(){
        LTS_Disable_Application_Automation__c ltstemp = new LTS_Disable_Application_Automation__c();
        ltstemp.LTS_Disable_Process_Builders__c = true;
        ltstemp.LTS_Disable_Triggers__c = true;
        ltstemp.LTS_Disable_Validation_Rules__c = true;
        ltstemp.LTS_Disable_Workflow_Rules__c = true;
        ltstemp.Name = 'temp';
        ltstemp.SetupOwnerId = userinfo.getuserid();
        insert ltstemp;
        
        Lead lead = new Lead();
        lead.Company = 'Test 1 New Company';
        lead.FirstName = 'Martha2';
        lead.LastName = 'Belly2';       
        lead.LeadSource = 'Not Converted';
        lead.Is_GLI__c = true;
        insert lead;
        System.assertEquals(lead!= null , true,'Lead check');
        List<Task> tasks = new List<Task>();
        tasks.add(new Task(
            ActivityDate = Date.today().addDays(7),
            Activity_category__c = 'Appointment Requested',
            Call_Disposition__c = 'Connected' ,
            Subject='Sample Task',        
            whoId= lead.id,     
            OwnerId = UserInfo.getUserId(),
            Status='Completed'));
        insert tasks;
    }
    
}