objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Scoring_Combined__c</fullName>
        <description>Email automation scoring field combination of attribute and interaction scoring.</description>
        <label>Lead Score</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org of Lead</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>WEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Desc__c</fullName>
        <label>Source Desc</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LeadSource</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3rd Party Call Center</fullName>
                </value>
                <value>
                    <fullName>3rd Party Social Event</fullName>
                </value>
                <value>
                    <fullName>Accountant</fullName>
                </value>
                <value>
                    <fullName>Advance Search</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Andromeda</fullName>
                </value>
                <value>
                    <fullName>Banner Ads</fullName>
                </value>
                <value>
                    <fullName>Business Law Solution</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Commercial Info Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer Referral</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Data.com</fullName>
                </value>
                <value>
                    <fullName>Data Research</fullName>
                </value>
                <value>
                    <fullName>Demo Request</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Direct Email</fullName>
                </value>
                <value>
                    <fullName>Direct Mail</fullName>
                </value>
                <value>
                    <fullName>Drop-Off/Email</fullName>
                </value>
                <value>
                    <fullName>eCommerce ANZ</fullName>
                </value>
                <value>
                    <fullName>Eloqua-ANZ</fullName>
                </value>
                <value>
                    <fullName>Eloqua-SLF</fullName>
                </value>
                <value>
                    <fullName>Email Nurturing</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>External Call Center</fullName>
                </value>
                <value>
                    <fullName>External referral</fullName>
                </value>
                <value>
                    <fullName>F&amp;R: Financial</fullName>
                </value>
                <value>
                    <fullName>F&amp;R: FXall</fullName>
                </value>
                <value>
                    <fullName>F&amp;R: GRC</fullName>
                </value>
                <value>
                    <fullName>FindLaw.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LM_SLA__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Picklist of all channels</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>Large Medium Law</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>Practical Law</fullName>
                </value>
                <value>
                    <fullName>Small Law</fullName>
                </value>
                <value>
                    <fullName>State Government</fullName>
                </value>
                <value>
                    <fullName>Demand Center Qualified Lead</fullName>
                </value>
                <value>
                    <fullName>Demand Center Prospect</fullName>
                </value>
                <value>
                    <fullName>Demand Center Lead Queue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Score__c</fullName>
        <description>Picklist of all the lead scores</description>
        <label>Lead Score</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>A1</fullName>
                </value>
                <value>
                    <fullName>A2</fullName>
                </value>
                <value>
                    <fullName>A3</fullName>
                </value>
                <value>
                    <fullName>A4</fullName>
                </value>
                <value>
                    <fullName>B1</fullName>
                </value>
                <value>
                    <fullName>B2</fullName>
                </value>
                <value>
                    <fullName>B3</fullName>
                </value>
                <value>
                    <fullName>B4</fullName>
                </value>
                <value>
                    <fullName>C1</fullName>
                </value>
                <value>
                    <fullName>C2</fullName>
                </value>
                <value>
                    <fullName>C3</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Notification_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Email to be sent to User when Lead matches criteria</description>
        <label>Send Notification Email</label>
        <type>Checkbox</type>
    </fields>
    <label>LM SLA</label>
    <nameField>
        <label>Lead Management SLA</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LM SLA&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>IF (Profile.Name = &quot;TR Legal Read-Only User&quot;, &quot;Tier 2&quot;, 
IF (UserRole.Name = &quot;Director&quot;, &quot;Tier 2&quot;, 
IF (UserRole.Name = &quot;WPD - Marketing&quot;, &quot;Tier 2&quot;, 
IF (Profile.Name = &quot;TR Legal FindLaw User&quot;, &quot;FindLaw&quot;, 
IF (BEGINS(UserRole.Name, &quot;Large Law&quot;), &quot;Large Law&quot;, 
IF (BEGINS(UserRole.Name, &quot;Law Firm&quot;), &quot;Large Law&quot;, 
IF (BEGINS(UserRole.Name, &quot;National&quot;), &quot;Large Law&quot;, 
IF (BEGINS(UserRole.Name, &quot;LL&quot;), &quot;Large Law&quot;, 
IF (BEGINS(UserRole.Name, &quot;SAM&quot;), &quot;Small Law&quot;, 
IF (BEGINS(UserRole.Name, &quot;Small Law&quot;), &quot;Small Law&quot;, 
IF (BEGINS(UserRole.Name, &quot;Home Office&quot;), &quot;Inside Sales&quot;, 
IF (BEGINS(UserRole.Name, &quot;Corp&quot;), &quot;Corp&quot;, 
IF (CONTAINS(UserRole.Name, &quot;Govt&quot;), &quot;Govt&quot;, 
IF (BEGINS(UserRole.Name, &quot;WPD&quot;), &quot;WPD&quot;, 
IF (BEGINS(UserRole.Name, &quot;ANZ&quot;), &quot;ANZ&quot;, 
IF (BEGINS(UserRole.Name, &quot;AU&quot;), &quot;AU&quot;, 
IF (BEGINS(UserRole.Name, &quot;HK&quot;), &quot;HK&quot;, 
IF (BEGINS(UserRole.Name, &quot;NZ&quot;), &quot;NZ&quot;, 
IF (BEGINS(Profile.Name, &quot;ANZ&quot;), &quot;ANZ&quot;, 
IF (CONTAINS(Profile.Name, &quot;Admin&quot;), &quot;MIS/Admin&quot;, 

UserRole.Name 
))))))))))))))))))))</formula>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for User</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LeadCreateSendMail_Test.cls
@IsTest(seeAllData=TRUE)
public class LeadCreateSendMail_Test{
    
    public static Group g;
    public static Group gp;
    
    public static testMethod void Testsave(){
    
     string testprofile = [SELECT Id FROM profile WHERE name='System Administrator'].id;   
         
        User testuser = [select Id from User where ProfileId =:testprofile limit 1];
        Group grp = [Select Id from Group where Type = 'Queue' and Name = 'ANZ Sales Leads' limit 1];
        
        LM_SLA__C LMSLA1 = new LM_SLA__C();
        LMSLA1.Lead_Score__c='A2';    
        LMSLA1.Send_Notification_Email__c=true;
        LMSLA1.Channel__c='Tax Profile';
       // LMSLA1.add(LMSLA1);
        insert LMSLA1;
        list<Lead> NewLeadList = new list<Lead>();
       // Map<id,Lead> NewLeadList1 = new map<id,Lead>();
        Lead NewLeadListinsert = new lead();
        //                      NewLeadListinsert.lead.id='2F07M29000000KroJ';
        NewLeadListinsert.Company='TCS';
        //   .. NewLeadListinsert.name='TCS1';
        NewLeadListinsert.firstname='Test1';
        NewLeadListinsert.lastname='Test2';
        NewLeadListinsert.Business_Org__c='Tax Profile';
        NewLeadListinsert.Lead_Scoring_Combined__c='A2';
         NewLeadListinsert.Ownerid=grp.id;
        NewLeadListinsert.Source_Desc__c='UAT';
        NewLeadListinsert.Description='test Lead';
        NewLeadListinsert.Billing_Street__c='Gokul';
        NewLeadListinsert.Billing_City__c='Bangalore';
        NewLeadListinsert.Billing_Zip__c='343434';
        NewLeadListinsert.Billing_State__c='Karnataka';
        NewLeadListinsert.Source__c='UAT';
        NewLeadListinsert.Phone='349876254245';
        NewLeadListinsert.Email='test@gamil.com';
        NewLeadListinsert.Sales_Org__c = 'LRA';
        NewLeadList.add(NewLeadListinsert);
        insert NewLeadList;    
    LeadCreateSendMail.NewLeadCreation(NewLeadList);
        
  /*  g = new Group(
    Name = 'unit test group',
    DeveloperName = 'unit_test_group',
    Type = 'Queue'
);
insert g;

GroupMember gp1 = new GroupMember(
    GroupId = g.Id,
    UserOrGroupId = testuser.Id
);
insert gp1; */
    
  }
  
  
    public static testMethod void TestsaveUser(){
    
     string testprofile = [SELECT Id FROM profile WHERE name='System Administrator' ].id;   
         
        User testuser = [select Id from User where ProfileId =:testprofile and isActive=true limit 1];
        Group grp = [Select Id from Group where Type = 'Queue' and Name = 'ANZ Sales Leads' limit 1];
        
        LM_SLA__C LMSLA2 = new LM_SLA__C();
        LMSLA2.Lead_Score__c='A2';    
        LMSLA2.Send_Notification_Email__c=true;
        LMSLA2.Channel__c='User Profile';
       // LMSLA1.add(LMSLA1);
        insert LMSLA2;
        list<Lead> NewLeadList1 = new list<Lead>();
       // Map<id,Lead> NewLeadList1 = new map<id,Lead>();
        Lead NewLeadListinsert1 = new lead();
        //                      NewLeadListinsert.lead.id='2F07M29000000KroJ';
        NewLeadListinsert1.Company='TCS1';
        //   .. NewLeadListinsert.name='TCS1';
        NewLeadListinsert1.firstname='Test2';
        NewLeadListinsert1.lastname='Test3';
        NewLeadListinsert1.Business_Org__c='User Profile';
        NewLeadListinsert1.Lead_Scoring_Combined__c='A2';
         NewLeadListinsert1.Ownerid=testuser.id;
        NewLeadListinsert1.Source_Desc__c='UAT';
        NewLeadListinsert1.Description='test Lead';
        NewLeadListinsert1.Billing_Street__c='Gokul';
        NewLeadListinsert1.Billing_City__c='Bangalore';
        NewLeadListinsert1.Billing_Zip__c='343434';
        NewLeadListinsert1.Billing_State__c='Karnataka';
        NewLeadListinsert1.Source__c='UAT';
        NewLeadListinsert1.Phone='349876254245';
        NewLeadListinsert1.Email='test@gamil.com';
        NewLeadListinsert1.Sales_Org__c = 'LRA';
        NewLeadList1.add(NewLeadListinsert1);
        insert NewLeadList1;    
    LeadCreateSendMail.NewLeadCreation(NewLeadList1);
          
  }
 
}