objects/Material_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store the values of Material Type</description>
    <label>Material Type</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Renewal_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Selling_Organization__c</fullName>
        <description>EDW	SALESORG	Selling Organization	Text</description>
        <label>Selling Organization</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Uplift</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RenewalCheck__c</fullName>
        <formula>Opportunity.Renewal_Flag__c == TRUE &amp;&amp; Opportunity.RecordType.Name == &apos;LATAM Renewal Opportunity&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RenewalCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>This field will display the type of revenue for the product.</description>
        <label>Revenue Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incremental</fullName>
                    <default>true</default>
                    <label>Incremental</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Pro_Business_Channel__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Pro_Business_Channel</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Material_Type__c</fullName>
        <description>SAP Material Type</description>
        <label>Material Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Media_high_Level__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store the values of media High level of product</description>
    <label>Product_Media high Level</label>
</CustomObject>

classes/deleteOpportunityProdController_Test.cls
@istest(seeAllData=false)
private class deleteOpportunityProdController_Test{
    static testMethod void testControllerOpportunity(){
        
        UnitTest.createTestData();
        Material_Type__c oMaterial = new Material_Type__c ();
        oMaterial.name = 'ZFNV';
        insert oMaterial;
        
        Product_Media_high_Level__c oPMHL = new Product_Media_high_Level__c();
        oPMHL.name ='Audio';
        insert oPMHL;
        
        Pro_Business_Channel__c oPBC = new Pro_Business_Channel__c();
        oPBC.name = 'GBL-Legal';
        insert oPBC;
        
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        
        Account testAcc = UnitTest.getAccountInstance();
        insert testAcc;
        
        Contact testcontact= UnitTest.getContactInstance(testAcc.Id);
        testcontact.LastName = 'testContact';
        testcontact.FirstName = 'testContact';
        testcontact.AccountId = testAcc.Id;
        testcontact.email = 'testfirst.testlast@thomson.com';
        insert testcontact;
        
        Opportunity testOpp1 = UnitTest.getOpportunityInstance(testAcc.Id);
        testOpp1.Renewal_Flag__c = true;
        testOpp1.Selling_Organization__c = 'LRA';
        testOpp1.currencyIsoCode = 'USD';
        testOpp1.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('LATAM Renewal Opportunity').getRecordTypeId();
        insert testOpp1;
        
        Product2 testProd =UnitTest.getProductInstance();
        insert testProd;
        
        PricebookEntry testEntry = new PricebookEntry(CurrencyIsoCode='USD',isactive=true,Pricebook2id=Test.getStandardPricebookId(),Product2Id=testProd.id,unitprice=1,UseStandardPrice=false);
        insert testEntry;
        
        PricebookEntry testEntry1 = new PricebookEntry(CurrencyIsoCode='USD',isactive=true,Pricebook2id=customPB.Id,Product2Id=testProd.id,unitprice=1,UseStandardPrice=false);
        insert testEntry1;
        
        OpportunityLineItem testLineItem = new OpportunityLineItem(opportunityId=testOpp1.id,PricebookEntryId=testEntry1.id,unitprice=100,Quantity=1, Revenue_Type__c ='Renewal');
        //testLineItem.RenewalCheck__c = true;
        testLineItem.Activity_Type__c = 'Cancelled';        
        insert testLineItem;
        
        Test.startTest();
        PageReference pref=Page.deleteOpportunityProd;
        ApexPages.StandardController stdController = new ApexPages.StandardController(testLineItem);
        //stdController.setSelected(testLineItem);
        deleteOpportunityProdController objDelOLI = new deleteOpportunityProdController(stdController);        
        objDelOLI.restrictDelete();
        objDelOLI.returntoOppty();
    }
}