objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Pricing Approval</fullName>
                </value>
                <value>
                    <fullName>Pricing Approved</fullName>
                </value>
                <value>
                    <fullName>Pricing Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Quote Approved</fullName>
                </value>
                <value>
                    <fullName>Quote Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation Approval</fullName>
                </value>
                <value>
                    <fullName>Cancellation Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancellation Approved</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Pending Removal</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reservation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reservation_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservation Number</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Reserve Account to a user of a channel (portal)</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field will identify the manager who will work with the partner on the reservation.</description>
        <label>Partner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reservations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReservationTriggerHandler.cls
/********************************************************************************************
    Class: ReservationTriggerHandler
    DevelopedBy: Shovon 
    Purpose: SFD-497
    *********************************************************************************************/
    public class ReservationTriggerHandler{
    public static void updateOpportunityOnReservationUpdate(List<Reservation__c> ListReservation, Map<Id, Reservation__c> MapNewReservation, Map<Id, Reservation__c> MapOldReservation){
        List<Reservation__c> updatedReservationList = new List<Reservation__c>();
        List<Opportunity> updatedOpportunityList;
        for(Reservation__c r: ListReservation){
            if(r.Partner_Manager__c != MapOldReservation.get(r.Id).Partner_Manager__c){
                updatedReservationList.add(r);
            }
        }
        if(!updatedReservationList.isEmpty()){
            updatedOpportunityList = new List<Opportunity>([SELECT Id, Reservation_Number__c, Reservation_Manager__c FROM Opportunity WHERE Reservation_Number__c IN: updatedReservationList]);
        }
        if(updatedOpportunityList != null){
            for(Opportunity opp: updatedOpportunityList){
                opp.Reservation_Manager__c = MapNewReservation.get(opp.Reservation_Number__c). Partner_Manager__c;
            }
            Database.update(updatedOpportunityList, false);
        }
    
    }
    public static void mandatePartnerManagerOnApproval(List<Reservation__c> ListReservation, Map<Id, Reservation__c> MapOldReservation){
        for(Reservation__c r: ListReservation){
            if(r.Approval_Status__c == 'Approved'&& r.Approval_Status__c != MapOldReservation.get(r.Id).Approval_Status__c && r.Partner_Manager__c == null){
                String errorMsg = System.Label.Partner_Manager_mandatory_validation;
                r.addError(errorMsg);
            }
        }
    }
}