objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Customer_Master_Att_5__c</fullName>
        <description>This field is created as a part of CRM -6622</description>
        <label>Account Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sub_Bu__c</fullName>
        <description>The field has been created to define the sub bu of the user which will be used to populate the Sub bu field on objects Account,Lead,Opportunities,Activity etc. 
Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-2201, DPS-415</description>
        <label>BU Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>USL</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>AEM</fullName>
                </value>
                <value>
                    <fullName>LatAm</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UpdateMultiListAccountTierHandler.cls
/*
* Description   : CRM-8693 : Handler for Updating Multi-picklist Account Tier on Account when Customer Master Attribute 5 on SSD is Inserted or Updated.    
* Author        : Noopur Rathod 
* Change History: 06-Nov-2017 Initial Version               
*/

public class UpdateMultiListAccountTierHandler {
          
    private static Boolean isRunOnce = true;
    public static Boolean checkRecursive(){
           if(isRunOnce){
            isRunOnce=false;
            return true;
           } else{
            return isRunOnce;
           }
    }
  
    /*
        This method will update 'Account Tier' field on account when 
       'Customer Master Attribute 5' field on SSD will be inserted or updated.
    */  
    public static void updateAccountTier(List<Source_System_Detail__c> ssdList){
        Id loggedInUserId = UserInfo.getUserId();
        boolean uslUser =false;
       
        String profileName = [SELECT Profile.Id, Profile.Name from User Where Id =:loggedInUserId].Profile.Name;
        String subbu = [SELECT Sub_Bu__c from User Where Id =:loggedInUserId].Sub_Bu__c;
        if(profileName == 'System Administrator' || profileName == 'GLI Sales User' || profileName == 'GLI Sales Ops User' || subbu == 'FindLaw' || subbu == 'USL' || subbu == 'LMS'){
             uslUser = true;
        }
        
        if(uslUser ){
            Map<Id, String> accIds = new Map<Id, String>();
            Set<String> custMaster = new Set<String>();
            for(Source_System_Detail__c ssd: ssdList){
                accIds.put(ssd.Account_Name__c,ssd.LCRM_Customer_Master_Att_5__c); 
                custMaster.add(ssd.LCRM_Customer_Master_Att_5__c);
            } 
            
            List<Account> acctsToUpdate = [Select Id,Account_Tier__c from Account where id in:accIds.keySet()];
            List<Account> accountTier = new List<Account>();
            
            for(Account a : acctsToUpdate) {
                for(String customer: custMaster){
                   if(mapOfSSD.containsKey(customer)){
                     a.Account_Tier__c = mapOfSSD.get(customer);
                     accountTier.add(a);
                    }      
                }
            }
           update accountTier;  
        }
    }

    static Map<String,String> mapOfSSD = new  Map<String,String>();
    
    static{
        mapOfSSD.put( 'XS','Dedicated State Govt');
        mapOfSSD.put( 'X','Key Connection - LMLF or Corp');
        mapOfSSD.put( 'XA','Academic Key Connect');
        mapOfSSD.put( 'LP','LLF Premier Service');
    }
}