objects/Source_System_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the Name of the associated Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_System_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCRM_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEST</fullName>
                </value>
                <value>
                    <fullName>CARS</fullName>
                </value>
                <value>
                    <fullName>TA61</fullName>
                </value>
                <value>
                    <fullName>TA78</fullName>
                </value>
                <value>
                    <fullName>S100</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>INWL</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>TRFR</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_Account_Number__c</fullName>
        <label>Source System Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Name__c</fullName>
        <label>Source System Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Source System</label>
    <nameField>
        <label>Source System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Source Systems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>Holds Sales Org for User</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BEJE</fullName>
                </value>
                <value>
                    <fullName>BKRS</fullName>
                </value>
                <value>
                    <fullName>CHWL</fullName>
                </value>
                <value>
                    <fullName>DFCL</fullName>
                </value>
                <value>
                    <fullName>EDIC</fullName>
                </value>
                <value>
                    <fullName>GLI</fullName>
                </value>
                <value>
                    <fullName>GSI</fullName>
                </value>
                <value>
                    <fullName>LLEY</fullName>
                </value>
                <value>
                    <fullName>LLPA</fullName>
                </value>
                <value>
                    <fullName>LLUR</fullName>
                </value>
                <value>
                    <fullName>LPCL</fullName>
                </value>
                <value>
                    <fullName>LPTC</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>RV01</fullName>
                </value>
                <value>
                    <fullName>SMGE</fullName>
                </value>
                <value>
                    <fullName>SMHK</fullName>
                </value>
                <value>
                    <fullName>SMMY</fullName>
                </value>
                <value>
                    <fullName>SMSG</fullName>
                </value>
                <value>
                    <fullName>SSRL</fullName>
                </value>
                <value>
                    <fullName>TGPS</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Bu__c</fullName>
        <description>The field has been created to define the sub bu of the user which will be used to populate the Sub bu field on objects Account,Lead,Opportunities,Activity etc. 
Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-2201, DPS-415</description>
        <label>BU Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>USL</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>AEM</fullName>
                </value>
                <value>
                    <fullName>LatAm</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/USL_Integration_defaults__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Applicationid__c</fullName>
        <label>Applicationid</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Companyid__c</fullName>
        <label>Companyid</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Messageid__c</fullName>
        <label>Messageid</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>USL Integration defaults</label>
</CustomObject>

classes/USLSubbillingcontroller_test.cls
@isTest
public class USLSubbillingcontroller_test {
      @isTest static void testsubbillingDetails(){
        Profile testprofile = [SELECT Id FROM Profile WHERE Name = 'USL Helpdesk Agent'];
        User testUser = new User(
            Alias = 'sUser',
            Email = 'abc1@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'es',
            LocaleSidKey = 'es',
            ProfileId = testprofile.id,
            Sales_Org__c = 'WEST',
            Sub_Bu__c = 'USL',
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'abc123@testorg.com'
        );
        insert testUser;

        System.runAs(testUser) {
            Account testAcc1 = new Account();
            testAcc1 = UnitTest.getAccountInstance();
            testAcc1.SAPAccountNumber__c = '5491';
            insert testAcc1;

            Account testAcc2 = new Account();
            testAcc2 = UnitTest.getAccountInstance();
            testAcc2.SAPAccountNumber__c = '5491344';
            insert testAcc2;

            List < Source_System_Detail__c > ListofSSD = new List < Source_System_Detail__c > ();
            Source_System_Detail__c SSDwithSAPNo = new Source_System_Detail__c();
            SSDwithSAPNo.name = 'SSD1_01';
            SSDwithSAPNo.Source_System_Account_Number__c = '1000000040';
            SSDwithSAPNo.Account_Name__c = testAcc1.id;
            SSDwithSAPNo.Source_System_Name__c = 'LCRMGLI';
            SSDwithSAPNo.LCRM_Sales_Org__c = 'WEST';
            ListofSSD.add(SSDwithSAPNo);
             USL_Integration_defaults__c int1 = new USL_Integration_defaults__c();
        int1.Applicationid__c = 'ESCU';
        int1.Companyid__c = 'WEST';
        int1.name = 'Integrationdefaults';
        insert int1;
            
        //    USLARInvoicedetailwrapper.EsiHeader esi=new USLARInvoicedetailwrapper.EsiHeader(val.Applicationid__c,val.Companyid__c,val.Messageid__c);

             
            Source_System_Detail__c SSDSAPNo = new Source_System_Detail__c();
            SSDSAPNo.name = 'SSD1_02';
            SSDSAPNo.Source_System_Account_Number__c = '1000000846';
            SSDSAPNo.Account_Name__c = testAcc1.id;
            SSDSAPNo.Source_System_Name__c = 'LCRMGLISSD';
            SSDSAPNo.LCRM_Sales_Org__c = 'WEST';
            ListofSSD.add(SSDSAPNo);

            if (ListofSSD.size() > 0) {
                insert ListofSSD;
                  }
             
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockUSLSubbillingcontroller());
            PageReference pageRef = Page.USLSubBilling;
            pageRef.getParameters().put('0110160241','000010');
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(ListofSSD[0]);
            USLSubbillingcontroller controller = new USLSubbillingcontroller(sc);  
           // USLSubbillingplanwrapper wrap1 = new USLSubbillingplanwrapper ();
            USLSubbillingplanwrapper.Billingresponsewrapper wrap = new USLSubbillingplanwrapper.Billingresponsewrapper();
            USLSubbillingplanwrapper wrap1 = new USLSubbillingplanwrapper();
            USLSubbillingplanwrapper.EsiHeader esi= new USLSubbillingplanwrapper.EsiHeader('test','123');
            USLSubbillingplanwrapper.SubscriptionDetails subs = new USLSubbillingplanwrapper.SubscriptionDetails('123','456');
            USLSubbillingplanwrapper.Billingresponsewrapper bill = new USLSubbillingplanwrapper.Billingresponsewrapper();           
            USLSubbillingplanwrapper.cls_billPlanHeader clsbill = new USLSubbillingplanwrapper.cls_billPlanHeader();
            clsbill.subscriptionNumber='0110160241';
            clsbill.endDate='0000-00-00';
           // clsbill.cls_billPlanHeader();
            USLSubbillingplanwrapper.cls_subscriptionLines clssub = new USLSubbillingplanwrapper.cls_subscriptionLines();
            clssub.subscriptionLineNumber='000010';
            USLSubbillingplanwrapper.cls_billPlanInfo clsbillinfo = new USLSubbillingplanwrapper.cls_billPlanInfo();
            clsbillinfo.billPlanNumber='0000614928';
            clsbillinfo.billPlanStartDate='2001-09-25';
            clsbillinfo.billPlanEndDate='2001-09-25';
            clsbillinfo.billPlanType='Z3';
            clsbillinfo.billPlanDescription='Z3'; 
            USLSubbillingplanwrapper.cls_billPlanDetails clsbilldet = new USLSubbillingplanwrapper.cls_billPlanDetails();
            clsbilldet.settlementDate='0000-00-00';
            clsbilldet.billItemStartDate='0000-00-00';
            clsbilldet.billItemEndDate='0000-00-00';
            clsbilldet.billItemPrice='00.00';
            clsbilldet.billCurrency='USD';
            clsbilldet.block='';
            clsbilldet.billItemStatus='';
            clsbilldet.billItemType='';
            clsbilldet.manaulDateInd='';
            clsbilldet.correctionDateInd='';
            clsbilldet.paymentTerms='';
            clsbilldet.dateCategory='';
            USLSubbillingplanwrapper.cls_statusDetails clsstat = new USLSubbillingplanwrapper.cls_statusDetails();
            clsstat.statusCode='200';
            clsstat.statusDescription='Success';
            clsstat.statusDetailMessage='Get Billing Plans Success';
           // wrap.Billingresponsewrapper();
            Test.setCurrentPageReference(new PageReference('Page.USLSubBilling'));      
            Test.stopTest();
            }

       
    } 
}