objects/Training_Event__c.object
<CustomObject>
    <description>This is the object for Training Event.</description>
    <fields>
        <fullName>Account_Level__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Level</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SAPAccountNumber__c</fullName>
        <formula>Account__r.SAPAccountNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Completed-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Contacting</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Date__c</fullName>
        <label>Training Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Training_Duration__c</fullName>
        <description>Training Duration in no.of hours</description>
        <inlineHelpText>Training Duration in no.of hours</inlineHelpText>
        <label>Training Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Name__c</fullName>
        <label>Training Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Event</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Training Event Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Training_Event_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Master Lookup to Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Event_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Training_Date__c</fullName>
        <formula>Training_Event__r.Training_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Training_Event__c</fullName>
        <label>Training Event</label>
        <referenceTo>Training_Event__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Training_Event_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Event Account</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Training Account Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Event Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Training_Event_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Event_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Training_Event__c</fullName>
        <label>Training Event</label>
        <referenceTo>Training_Event__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Training_Event_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_trained_Date__c</fullName>
        <label>User Trained Date</label>
        <type>Date</type>
    </fields>
    <label>Training Event Contact</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Identifer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Event Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Training_Event_Topic__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>Training_Topic__r.Category__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <formula>Training_Topic__r.Topic__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Topic</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Event_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Event Contact</label>
        <referenceTo>Training_Event_Contact__c</referenceTo>
        <relationshipLabel>Training Event Topics</relationshipLabel>
        <relationshipName>Training_Event_Topics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Topic__c</fullName>
        <label>Training Topic</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Training_Topic__c</referenceTo>
        <relationshipLabel>Training Event Topics</relationshipLabel>
        <relationshipName>Training_Event_Topics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Event Topic</label>
    <nameField>
        <displayFormat>TT-{000000}</displayFormat>
        <label>Training Event Topic Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Event Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Training_Topic__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Training Topic</label>
    <nameField>
        <displayFormat>TT-{000000}</displayFormat>
        <label>Training Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testMassEditTrainingContacts.cls
@isTest
public class testMassEditTrainingContacts
{
    public static testmethod void testMassEditTrainingContacts()
    {
        List<Account> listAccount = new List<Account>();
        listAccount = [select Name,Customer_Type__c, Customer_Group__c, Industry, SAPAccountNumber__c from Account where SAPAccountNumber__c = '1000550771'];
        Account account = UnitTest.getAccountInstance();
        if(listAccount.isEmpty())
        {
            account.Name = 'testAccount';
            account.Customer_Type__c = 'Induvidual';
            account.Customer_Group__c = 'ACADEMIC';
            account.Industry = 'Energy';
            account.SAPAccountNumber__c = '1000550771';
            insert account;
        }
        else
        {
            account = listAccount[0];
        }
        Contact contact = UnitTest.getContactInstance(account.Id);
        contact.AccountId = account.Id;
        contact.LastName = 'testContact';
        contact.FirstName = 'testContact';
        contact.MailingCity = 'London';
        insert contact;
        
        Contact contact2 = UnitTest.getContactInstance(account.Id);
        contact2.AccountId = account.Id;
        contact2.LastName = 'testContact2';
        contact2.FirstName = 'testContact2';
        contact2.MailingCity = 'London';
        insert contact2;
        
        
        Training_Event__c testTrainingEvent = new Training_Event__c();
        testTrainingEvent.Training_Name__c = 'testTrainingEvent';
        testTrainingEvent.Training_Date__c = System.Today();
        testTrainingEvent.Status__c = 'Pending';
        testTrainingEvent.Account_Level__c = true;
        testTrainingEvent.Account__c = account.Id;        
        testTrainingEvent.Notes__c = 'test notes'; 
        testTrainingEvent.Training_Duration__c =2;
        insert testTrainingEvent;
        
               
        Training_Event_Account__c testTrainingEventAccount = new Training_Event_Account__c();
        testTrainingEventAccount.Training_Event__c = testTrainingEvent.Id;
        testTrainingEventAccount.Account__c = account.Id;
        insert testTrainingEventAccount;
        
        List<Training_Event_Contact__c> listTrainingEventContact = new List<Training_Event_Contact__c>();
        Training_Event_Contact__c testTrainingEventContact = new Training_Event_Contact__c();
        testTrainingEventContact.Contact_Name__c = contact.Id;
        testTrainingEventContact.Training_Event__c = testTrainingEvent.Id;
        insert testTrainingEventContact;
        listTrainingEventContact.add(testTrainingEventContact);
        
        Training_Event_Contact__c testTrainingEventContact2 = new Training_Event_Contact__c();
        testTrainingEventContact2.Contact_Name__c = contact2.Id;
        testTrainingEventContact2.Training_Event__c = testTrainingEvent.Id;
        insert testTrainingEventContact2;
        listTrainingEventContact.add(testTrainingEventContact2);
        
        
        List<Training_Topic__c> testlistTrainingTopics = new List<Training_Topic__c>();
        Training_Topic__c testTrainingTopic = new Training_Topic__c();
        testTrainingTopic.Category__c = 'BIGX';
        testTrainingTopic.Topic__c = 'BIGX';
        testlistTrainingTopics.add(testTrainingTopic);
        testTrainingTopic = new Training_Topic__c();
        testTrainingTopic.Category__c = 'NAL PRODUCTS';
        testTrainingTopic.Topic__c = 'PROV - PROVIEW';
        testlistTrainingTopics.add(testTrainingTopic);
        testTrainingTopic = new Training_Topic__c();
        testTrainingTopic.Category__c = '1Point Online';
        testTrainingTopic.Topic__c = 'General Functionality';
        testlistTrainingTopics.add(testTrainingTopic);
        insert testlistTrainingTopics;        
        
        Training_Topic__c topc = new Training_Topic__c();
        topc.Topic__c ='1Point Online';
        topc.Category__c ='ANZ';
        insert topc;
        
        Training_Event_Topic__c tTopicCont = new Training_Event_Topic__c();
        tTopicCont.Training_Topic__c = topc.id;
        tTopicCont.Training_Event_Contact__c = testTrainingEventContact.id;
        insert tTopicCont;
        
        List<Training_Event_Contact__c> listTrainingEventContact1 = new List<Training_Event_Contact__c>();        
        
        pageReference pgMassEditTrainingContacts = page.massEditTrainingEventContacts;
        Test.setCurrentPage(pgMassEditTrainingContacts);
        ApexPages.currentPage().getParameters().put('id', testTrainingEvent.Id);
        
        ApexPages.StandardSetController sc1 = new ApexPages.StandardSetController(listTrainingEventContact1);
        sc1.setSelected(listTrainingEventContact1);              
        MassEditTrainingContacts controller1 = new MassEditTrainingContacts(sc1);
        controller1.toggleSort();
        
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(listTrainingEventContact);
        sc.setSelected(listTrainingEventContact);                
        MassEditTrainingContacts controller = new MassEditTrainingContacts(sc);
        
        list<SelectOption> topicCategory= controller.getlistCategories();
        Test.StartTest();
        controller.setBool();
        controller.oPagingContacts.moveNext(); 
        controller.oPagingContacts.movePrev(); 
        String trngId= controller.getTrngEvntId();  
        PageReference pg1= controller.saveTopics();      
        controller.sSearchValue5= 'BIGX';
        controller.selTopics ='PROV - PROVIEW';
        controller.selTopicsList();
        PageReference pg2= controller.findResults();
        controller.listTrainingEventContacts[0].bSelected = true;
        //PageReference pg3= controller.saveTopics();
        controller.selTopics ='General Functionality';
        PageReference pg4= controller.saveTopics();
        controller.toggleSort();        
        date myDate = date.parse(controller.dTrainedDate);
        controller.listTrainingEventContacts[0].oTrainingEventContact.User_trained_Date__c=myDate ;
        controller.SaveAndReturn();
        controller.Save();
        controller.SaveMassDate();
        controller.tTopicDel ='BIGX';
        controller.tContactDel =testTrainingEventContact.id;
        controller.RemoveTrainingContactTopic();
        controller.RemoveSelected();
        Test.Stoptest();        
    }
    // added to cover lightning theme4d
     public static testmethod void testMassEditTrainingContacts1()
     
    {   
    User u = new User(
                ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
                LastName = 'last',
                Email = 'puser000@amamama.com',
                Username = 'puser000@amamama.com' + System.currentTimeMillis(),
                CompanyName = 'TEST',
                Title = 'title',
                Alias = 'alias',
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                UserPreferencesLightningExperiencePreferred =true
            );
            insert u;
            
        List<Account> listAccount = new List<Account>();
        listAccount = [select Name,Customer_Type__c, Customer_Group__c, Industry, SAPAccountNumber__c from Account where SAPAccountNumber__c = '1000550771'];
        Account account = UnitTest.getAccountInstance();
        if(listAccount.isEmpty())
        {
            account.Name = 'testAccount';
            account.Customer_Type__c = 'Induvidual';
            account.Customer_Group__c = 'ACADEMIC';
            account.Industry = 'Energy';
            account.SAPAccountNumber__c = '1000550771';
            insert account;
        }
        else
        {
            account = listAccount[0];
        }
        Contact contact = UnitTest.getContactInstance(account.Id);
        contact.AccountId = account.Id;
        contact.LastName = 'testContact';
        contact.FirstName = 'testContact';
        contact.MailingCity = 'London';
        insert contact;
        
        Contact contact2 = UnitTest.getContactInstance(account.Id);
        contact2.AccountId = account.Id;
        contact2.LastName = 'testContact2';
        contact2.FirstName = 'testContact2';
        contact2.MailingCity = 'London';
        insert contact2;
        
        Training_Event__c testTrainingEvent = new Training_Event__c();
        testTrainingEvent.Training_Name__c = 'testTrainingEvent';
        testTrainingEvent.Training_Date__c = System.Today();
        testTrainingEvent.Status__c = 'Pending';
        testTrainingEvent.Account_Level__c = true;
        testTrainingEvent.Account__c = account.Id;        
        testTrainingEvent.Notes__c = 'test notes';
        testTrainingEvent.Training_Duration__c =2;
        insert testTrainingEvent;
        
               
        Training_Event_Account__c testTrainingEventAccount = new Training_Event_Account__c();
        testTrainingEventAccount.Training_Event__c = testTrainingEvent.Id;
        testTrainingEventAccount.Account__c = account.Id;
        insert testTrainingEventAccount;
        
        List<Training_Event_Contact__c> listTrainingEventContact = new List<Training_Event_Contact__c>();
        Training_Event_Contact__c testTrainingEventContact = new Training_Event_Contact__c();
        testTrainingEventContact.Contact_Name__c = contact.Id;
        testTrainingEventContact.Training_Event__c = testTrainingEvent.Id;
        insert testTrainingEventContact;
        listTrainingEventContact.add(testTrainingEventContact);
        
        Training_Event_Contact__c testTrainingEventContact2 = new Training_Event_Contact__c();
        testTrainingEventContact2.Contact_Name__c = contact2.Id;
        testTrainingEventContact2.Training_Event__c = testTrainingEvent.Id;
        insert testTrainingEventContact2;
        listTrainingEventContact.add(testTrainingEventContact2);
        
        List<Training_Event_Contact__c> listTrainingEventContact1 = new List<Training_Event_Contact__c>();        
        
        pageReference pgMassEditTrainingContacts = page.massEditTrainingEventContacts;
        Test.setCurrentPage(pgMassEditTrainingContacts);
        ApexPages.currentPage().getParameters().put('id', testTrainingEvent.Id);
        
        ApexPages.StandardSetController sc1 = new ApexPages.StandardSetController(listTrainingEventContact1);
        sc1.setSelected(listTrainingEventContact1);              
        MassEditTrainingContacts controller1 = new MassEditTrainingContacts(sc1);
        controller1.toggleSort();
        
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(listTrainingEventContact);
        sc.setSelected(listTrainingEventContact);                
        MassEditTrainingContacts controller = new MassEditTrainingContacts(sc);
        controller.RemoveSelected(); 
         
        PageReference pg4= controller.saveTopics();
        
        controller.toggleSort(); 
        
         system.runAs(u){
                MassEditTrainingContacts.isTheme4d = true;
                Test.startTest();
                controller.SaveAndReturn();
                Test.stopTest();

            }
    }
    
    // added to cover negative scenario 
     public static testmethod void testMassEditTrainingContacts3()
    {
        List<Account> listAccount = new List<Account>();
        listAccount = [select Name,Customer_Type__c, Customer_Group__c, Industry, SAPAccountNumber__c from Account where SAPAccountNumber__c = '1000550771'];
        Account account = UnitTest.getAccountInstance();
        if(listAccount.isEmpty())
        {
            account.Name = 'testAccount';
            account.Customer_Type__c = 'Induvidual';
            account.Customer_Group__c = 'ACADEMIC';
            account.Industry = 'Energy';
            account.SAPAccountNumber__c = '1000550771';
            insert account;
        }
        else
        {
            account = listAccount[0];
        }
        Contact contact = UnitTest.getContactInstance(account.Id);
        contact.AccountId = account.Id;
        contact.LastName = 'testContact';
        contact.FirstName = 'testContact';
        contact.MailingCity = 'London';
        insert contact;
        
        Contact contact2 = UnitTest.getContactInstance(account.Id);
        contact2.AccountId = account.Id;
        contact2.LastName = 'testContact2';
        contact2.FirstName = 'testContact2';
        contact2.MailingCity = 'London';
        insert contact2;
        
        
        Training_Event__c testTrainingEvent = new Training_Event__c();
        testTrainingEvent.Training_Name__c = 'testTrainingEvent';
        testTrainingEvent.Training_Date__c = System.Today();
        testTrainingEvent.Status__c = 'Pending';
        testTrainingEvent.Account_Level__c = true;
        testTrainingEvent.Account__c = account.Id;        
        testTrainingEvent.Notes__c = 'test notes';
        testTrainingEvent.Training_Duration__c =2;
        insert testTrainingEvent;
        
               
        Training_Event_Account__c testTrainingEventAccount = new Training_Event_Account__c();
        testTrainingEventAccount.Training_Event__c = testTrainingEvent.Id;
        testTrainingEventAccount.Account__c = account.Id;
        insert testTrainingEventAccount;
        
        List<Training_Event_Contact__c> listTrainingEventContact = new List<Training_Event_Contact__c>();
        Training_Event_Contact__c testTrainingEventContact = new Training_Event_Contact__c();
        testTrainingEventContact.Contact_Name__c = contact.Id;
        testTrainingEventContact.Training_Event__c = testTrainingEvent.Id;
        insert testTrainingEventContact;
        listTrainingEventContact.add(testTrainingEventContact);
        
        Training_Event_Contact__c testTrainingEventContact2 = new Training_Event_Contact__c();
        testTrainingEventContact2.Contact_Name__c = contact2.Id;
        testTrainingEventContact2.Training_Event__c = testTrainingEvent.Id;
        insert testTrainingEventContact2;
        listTrainingEventContact.add(testTrainingEventContact2);
        
        
        List<Training_Topic__c> testlistTrainingTopics = new List<Training_Topic__c>();
        Training_Topic__c testTrainingTopic = new Training_Topic__c();
        testTrainingTopic.Category__c = 'BIGX';
        testTrainingTopic.Topic__c = 'BIGX:';
        testlistTrainingTopics.add(testTrainingTopic);
        testTrainingTopic = new Training_Topic__c();
        testTrainingTopic.Category__c = 'NAL PRODUCTS';
        testTrainingTopic.Topic__c = 'PROV - PROVIEW';
        testlistTrainingTopics.add(testTrainingTopic);
        testTrainingTopic = new Training_Topic__c();
        testTrainingTopic.Category__c = '1Point Online';
        testTrainingTopic.Topic__c = 'General Functionality';
        testlistTrainingTopics.add(testTrainingTopic);
        insert testlistTrainingTopics;        
        
        Training_Topic__c topc = new Training_Topic__c();
        topc.Topic__c ='1Point Online';
        topc.Category__c ='ANZ';
        insert topc;
        
        Training_Event_Topic__c tTopicCont = new Training_Event_Topic__c();
        tTopicCont.Training_Topic__c = topc.id;
        tTopicCont.Training_Event_Contact__c = testTrainingEventContact.id;
        insert tTopicCont;
        
        List<Training_Event_Contact__c> listTrainingEventContact1 = new List<Training_Event_Contact__c>();        
        
        pageReference pgMassEditTrainingContacts = page.massEditTrainingEventContacts;
        Test.setCurrentPage(pgMassEditTrainingContacts);
        ApexPages.currentPage().getParameters().put('id', testTrainingEvent.Id);
        
        ApexPages.StandardSetController sc1 = new ApexPages.StandardSetController(listTrainingEventContact1);
        sc1.setSelected(listTrainingEventContact1);              
        MassEditTrainingContacts controller1 = new MassEditTrainingContacts(sc1);
        controller1.toggleSort();
        
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(listTrainingEventContact);
        sc.setSelected(listTrainingEventContact);                
        MassEditTrainingContacts controller = new MassEditTrainingContacts(sc); 
        
        list<SelectOption> topicCategory= controller.getlistCategories();
        Test.startTest();
        controller.setBool();
        controller.oPagingContacts.moveNext(); 
        controller.oPagingContacts.movePrev(); 
        String trngId= controller.getTrngEvntId();  
        PageReference pg1= controller.saveTopics();      
        controller.sSearchValue5= 'BIGX';
        controller.selTopics ='PROV - PROVIEW';
        controller.selTopicsList();
        PageReference pg2= controller.findResults();
        controller.listTrainingEventContacts[0].bSelected =false;
        controller.tTopicDel ='BIGX';
        controller.tContactDel =testTrainingEventContact.id;
        controller.RemoveTrainingContactTopic();
        controller.RemoveSelected();       
        Test.stopTest();
    } 
}