objects/Training_Event__c.object
<CustomObject>
    <description>This is the object for Training Event.</description>
    <fields>
        <fullName>SAPAccountNumber__c</fullName>
        <formula>Account__r.SAPAccountNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Completed-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Contacting</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Date__c</fullName>
        <label>Training Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Training_Name__c</fullName>
        <label>Training Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Training Event</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Training Event Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Training_Event_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Event_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Training_Event__c</fullName>
        <label>Training Event</label>
        <referenceTo>Training_Event__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Training_Event_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_trained_Date__c</fullName>
        <label>User Trained Date</label>
        <type>Date</type>
    </fields>
    <label>Training Event Contact</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Identifer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Event Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testupdateTrainedCheckbox.cls
@isTest
public class testupdateTrainedCheckbox
{
    public static testmethod void testupdateTrainedCheckbox()
    {
        List<Account> listAccount = new List<Account>();
        listAccount = [select Name,Customer_Type__c, Customer_Group__c, Industry, SAPAccountNumber__c from Account where SAPAccountNumber__c = '1000550771'];
        Account account = new Account();
        if(listAccount.isEmpty())
        {
            account.Name = 'testAccount';
            account.Customer_Type__c = 'Induvidual';
            account.Customer_Group__c = 'ACADEMIC';
            account.Industry = 'Energy';
            account.SAPAccountNumber__c = '1000550771';
            insert account;
        }
        else
        {
            account = listAccount[0];
        }
        
        Contact contact = new Contact();
        contact.LastName = 'testContact';
        contact.FirstName = 'testContact';
        contact.AccountId = account.Id;
        insert contact;
        
        Training_Event__c testTrainingEvent = new Training_Event__c();
        testTrainingEvent.Training_Name__c = 'testTrainingEvent';
        testTrainingEvent.Training_Date__c = System.Today();
        testTrainingEvent.Status__c = 'Pending';
        insert testTrainingEvent;
        
        Training_Event_Contact__c tec = new Training_Event_Contact__c();
        tec.Training_Event__c = testTrainingEvent.Id;
        tec.Contact_Name__c = contact.Id;
        tec.User_trained_Date__c = date.parse('12/12/2011');
        insert tec;
        
        tec.User_trained_Date__c = null;
        update tec;
        
        tec.User_trained_Date__c = date.parse('12/12/2100');
        update tec;
    }
}