objects/Trial__c.object
<CustomObject>
    <description>As per DLT-5979 - This object is created to capture details of Trial.</description>
    <fields>
        <fullName>Contact_LeadId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Lead ID</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>On-Demand Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Lead_Converted__c</fullName>
        <formula>Contact_LeadId__r.IsConverted</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Lead Converted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ODT_Trial_Product_Category__c</fullName>
        <description>This field captures the product category of Product that is being offered for the Trial</description>
        <label>Trial Product Category</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <label>Trial Id(s)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Source__c</fullName>
        <label>Trial Source</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trial_Status__c</fullName>
        <label>Trial Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Bounceback</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Timed-out</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Entitlement Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trial</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Trial Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ODT_LT_Extend.cls
public class ODT_LT_Extend {
@AuraEnabled
    public static List<String> UserProfileName()
    {
        
        User userDetails =[select id, name,Profile.name, userrole.name from user where id=:UserInfo.getUserId()];
        List<String> userRoleProfile= new List<String>();
        userRoleProfile.add(userDetails.profile.name);
        userRoleProfile.add(userDetails.userrole.name);
        //userRoleProfile.add(userDetails.profile.name);
        return userRoleProfile;
    }
    
   /* 
    @AuraEnabled
    public static Trial__c trialDetails(Id recordId)
    {
        Trial__c trail;
        if (Schema.sObjectType.Trial__c.isQueryable())
            trail = [select id,Name,Contact_LeadId__c,Is_Lead_Converted__c,Trial_Status__c,Trial_Source__c,ODT_Trial_Product_Category__c,Trial_Id__c from Trial__c where id =: recordId];
       
        return trail;
        
    }*/
}