objects/Trial__c.object
<CustomObject>
    <description>As per DLT-5979 - This object is created to capture details of Trial.</description>
    <label>Trial</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Trial Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trial_Contact__c.object
<CustomObject>
    <description>created as part of DPS-21134 for omni enterprise trial</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Trial Contacts</relationshipLabel>
        <relationshipName>Trial_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>One_Pass_ID__c</fullName>
        <label>One Pass ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It is checked if User has selected as a primary on Trial Console page</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Bounceback</fullName>
                </value>
                <value>
                    <fullName>Rep Initiated</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>TimedOut</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Entitlement Error</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                    <isActive>false</isActive>
                    <label>Activated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trials__c</fullName>
        <label>Trial</label>
        <referenceTo>Ent_Trial__c</referenceTo>
        <relationshipLabel>Trial Contacts</relationshipLabel>
        <relationshipName>Trial_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Trial Contact</label>
    <nameField>
        <label>Trial Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Trial_Product__c.object
<CustomObject>
    <description>Created as part of DPS-20526 for omni enterprise trial</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>created as part of ent trial</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Trial Products</relationshipLabel>
        <relationshipName>Trial_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Material_Number__c</fullName>
        <formula>Product_Name__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Trial Products</relationshipLabel>
        <relationshipName>Trial_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial</label>
        <referenceTo>Ent_Trial__c</referenceTo>
        <relationshipLabel>Trial Products</relationshipLabel>
        <relationshipName>Trial_Products1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Trial Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ODTDG_RetrieveAddedUsers.cls
/********************************************************************************************************
*  @description ODTDG_RetrieveAddedUsers : to Retrieve already added users / Invited users in Trial
*********************************************************************************************************/
@RestResource(urlMapping='/ODTDGRetrieveAddedUsers/*')
global with sharing class ODTDG_RetrieveAddedUsers {
   
/********************************************************************************************************
*  @description ValidatecustomersData: This is the main method to validate the customer data with post data 
* @return ODTDG_CustomerData as a service response we will share the customer data along with error messages if any 
*********************************************************************************************************/ 
    @HTTPGet
    global static List<ODTDG_RetrieveAddedUsers.UserDetails> retrieveUsersData(){

            List<UserDetails> userDetails = new List<UserDetails>();
            
            System.debug(LoggingLevel.INFO,'ReqBody...............'+RestContext.request.params.tostring());
            
           // Map<String, Object> m =  (Map<String, Object>) JSON.deserializeUntyped(RestContext.request.requestBody.tostring());
            RestRequest newRequest = RestContext.request;
            Map<String,String> m = newRequest.params;
            
            String onePassId=m.get('onePassId');
            //String productCode=m.get('productCode');

            System.debug(LoggingLevel.INFO,'onePassId...............'+onePassId);
            //System.debug(LoggingLevel.INFO,'productCode...............'+productCode);

/*
        if(Schema.sObjectType.Trial_Product__c.isQueryable()){
            List<ID> trialIds=new List<ID>();
            List<Trial_product__c> products = [SELECT Id, Trial__c, Material_Number__c, Product_Name__c 
                                                FROM Trial_Contact__c 
                                                WHERE Product_Name__r.ProductCode=: productCode];
            
            for(Trial_Product__c p:products){
                trialIds.add(products.Trial__c);
            }
        }

*/

            
        if(Schema.sObjectType.Trial_Contact__c.isQueryable()){
            Trial_Contact__c cm = ODTDG_Helper.getTrialContact(onePassId);
            ID trialId = cm.Trials__c;
            //Boolean isPrimary=contact.Primary__c;

            List<Trial_Contact__c> contacts = [SELECT Id, Trials__c, Name, First_Name__c, Last_Name__c, Email__c, One_Pass_ID__c, Primary__c, lead__c, Status__c 
                                                FROM Trial_Contact__c 
                                                WHERE trials__c=:trialId and Primary__c=false and Id!= :cm.id];

        

            UserDetails user1 = new UserDetails();
            user1.isPrimary=cm.Primary__c;
            user1.emailAddress=cm.Email__c;
            user1.firstName=cm.First_Name__c;
            user1.lastName=cm.Last_Name__c;
            user1.userAuthId=cm.One_Pass_ID__c;
            user1.status=cm.Status__c;
            userDetails.add(user1);

            for(Trial_Contact__c c:contacts){
                UserDetails user = new UserDetails();
                user.isPrimary=c.Primary__c;
                user.emailAddress=c.Email__c;
                user.firstName=c.First_Name__c;
                user.lastName=c.Last_Name__c;
                user.userAuthId=c.One_Pass_ID__c;
                user.status=c.Status__c;
                userDetails.add(user);
            }

        }
        return userDetails;

    }


/********************************************************************************************************
*  @description CustomerDUserDetailsetails is the constructor for users details  
*********************************************************************************************************/ 
    global class UserDetails {
        public Boolean isPrimary;
        public String emailAddress;
        public String firstName;
        public String lastName;
        public String userAuthId;
        public String status;

    } 

}