objects/User.object
<CustomObject>
    <fields>
        <fullName>Infrequent_User_Timeout__c</fullName>
        <label>Infrequent User Timeout (in hrs)</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Infrequent_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Infrequent User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rep_Type_Description__c</fullName>
        <label>Rep Type Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Bu__c</fullName>
        <description>The field has been created to define the sub bu of the user which will be used to populate the Sub bu field on objects Account,Lead,Opportunities,Activity etc. 
Renamed from ‘Sub-BU’ to ‘BU Region’ as part of data segmentation for LOTUS. DPS-2201, DPS-415</description>
        <label>BU Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>USL</fullName>
                </value>
                <value>
                    <fullName>FindLaw</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>AEM</fullName>
                </value>
                <value>
                    <fullName>LatAm</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LTGS_BuRecord_test.cls
/* Class: LTGS_BuRecord_test
* Purpose: Test class for the Controller class LTGS_BuRecord
* Created: 25/3/2019
* Author: Samarpreet

* CHANGE HISTORY
* ==========================================================================================================
*  Date          Name                 Description
*  2019-03-07    Samarpreet            Initial Version
* ==========================================================================================================

*/
@isTest
public class LTGS_BuRecord_test {
    
    static testMethod void testData() {
        Profile p = [SELECT Id FROM profile WHERE name='GLI Helpdesk Agent'];   
        User user1 = new User(alias = 'newfg15', email='news2E1995@mydomain.com', 
                              emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                              localesidkey='en_US', profileid = p.Id, employeenumber='0144020',Infrequent_User__c=true,Infrequent_User_Timeout__c=2
                              , Sub_Bu__c = 'Elite',timezonesidkey='America/Los_Angeles', username='newsS2e195@mydomain.com',Rep_Type_Description__c='test');        
        
        insert user1;
        
        Test.startTest();
        
        System.runAs(user1) {
            LTGS_BuRecord.UserProfileName();
            Boolean isGLI=LTGS_BuRecord.GLIServiceUserCheck(); 
        }
        Test.stopTest();  
        
    }
}